<?php
namespace App\Console\Commands;
use App\Services\Shipping\Estafeta\EstafetaConfigurationValidator;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Storage;
final class EstafetaAuditCommand extends Command {
 protected $signature='zigo:estafeta-audit'; protected $description='Inventario contractual Estafeta sanitizado.';
 public static function contractMap():array{return[
  'auth'=>['endpoint'=>'config(ltd.estafeta.token_uri) + oauth2/v2.0/token','method'=>'POST','headers'=>['Content-Type'=>'application/x-www-form-urlencoded'],'authentication'=>'client_credentials','request'=>['grant_type','client_id','client_secret','scope'],'response'=>['access_token','expires_in'],'provider_codes'=>['error','error_description'],'timeout'=>'not_set_in_legacy','caller'=>'Estafeta::__construct','environment'=>'configured','evidence'=>'app/Singlenton/Estafeta.php::__construct','confidence'=>'confirmed'],
  'coverage'=>['endpoint'=>null,'method'=>null,'headers'=>[],'authentication'=>null,'request'=>['ltd_id','cp'],'response'=>['extendida'],'provider_codes'=>[],'timeout'=>null,'caller'=>'EstafetaCreacion::validaLtdCobertura','environment'=>'local_database','evidence'=>'app/Negocio/Guias/EstafetaCreacion.php::validaLtdCobertura','confidence'=>'unknown','note'=>'Consulta LtdCobertura; no existe llamada Estafeta.'],
  'quote'=>['endpoint'=>null,'method'=>null,'headers'=>[],'authentication'=>null,'request'=>['package','service','coverage'],'response'=>['costo','costo_seguro','costo_extendida','subPrecio','precio'],'provider_codes'=>[],'timeout'=>null,'caller'=>'EstafetaCreacion::cotizacion','environment'=>'local_pricing','evidence'=>'app/Negocio/Guias/EstafetaCreacion.php::cotizacion + Negocio/Guias/Cotizacion.php','confidence'=>'unknown','note'=>'Calcula con tarifas locales; no existe llamada Estafeta.'],
  'label'=>['endpoint'=>'config(ltd.estafeta.base_uri) + /labelrest/v1/wayBills','method'=>'POST','headers'=>['Authorization'=>'Bearer [REDACTED]','Content-Type'=>'application/json','Ocp-Apim-Subscription-Key'=>'[REDACTED]','apikey'=>'[REDACTED]','apiKey'=>'[REDACTED]'],'authentication'=>'OAuth bearer + subscription key','request'=>['labelDefinition'],'response'=>['data','labelPetitionResult.result.description'],'provider_codes'=>[],'timeout'=>'not_set_in_legacy','caller'=>'Estafeta::envio','environment'=>'configured','evidence'=>'app/Singlenton/Estafeta.php::envio','confidence'=>'confirmed','disabled_in_this_phase'=>true]
 ];}
 public function handle(EstafetaConfigurationValidator $validator):int{$map=self::contractMap();$report=['generated_at'=>now()->toIso8601String(),'contract_map'=>$map,'configuration'=>$validator->validate(),'summary'=>['confirmed'=>count(array_filter($map,fn($v)=>$v['confidence']==='confirmed')),'partial'=>count(array_filter($map,fn($v)=>$v['confidence']==='partial')),'unknown'=>count(array_filter($map,fn($v)=>$v['confidence']==='unknown'))],'READY_FOR_B2C_QUOTES'=>false,'blockers'=>['coverage_contract_unknown','quote_contract_unknown','stage_active_checks_not_executed']];$path='private/estafeta-contracts/contracts-'.now()->format('Ymd-His').'.json';Storage::disk('local')->put($path,json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));$this->info('Reporte: storage/app/'.$path);$this->line('READY_FOR_B2C_QUOTES=false');return self::SUCCESS;}
}
