@extends('tenant.admin.layout')
@section('title', $agent->name)
@section('content')
<div class="eyebrow">BORRADOR DE AGENTE</div><h1>{{ $agent->name }}</h1><div class="chips"><span class="chip">Borrador</span><span class="chip">{{ \App\Support\Presentation\AiAgentPresentation::agentType($agent->type) }}</span><span class="chip">Versión {{ $agent->versions->first()?->version_number??1 }}</span></div><p>{{ $agent->description }}</p>
<section class="customer-section"><h2>Canales y pruebas</h2><div class="marketplace-grid"><article class="card"><h3>Simulator</h3><p>Valida escenarios y preparación antes de publicar, sin afectar operaciones reales.</p><a class="z-btn z-btn--primary" href="{{ route('tenant.admin.ai-agents.simulator.show',$agent) }}">Abrir Simulator</a></article><article class="card"><h3>Channels · Webchat</h3><p>Publica este Agent en un widget seguro para sitios autorizados.</p><a class="z-btn z-btn--primary" href="{{ route('tenant.admin.ai-agents.webchat.show',$agent) }}">Configurar Webchat</a></article><article class="card"><h3>Channels · WhatsApp</h3><p>Conecta conversaciones individuales mediante Meta Cloud API.</p><a class="z-btn z-btn--primary" href="{{ route('tenant.admin.ai-agents.whatsapp.show',$agent) }}">Configurar WhatsApp</a></article></div></section>
@php($contract=$agent->contract?->versions?->first())
<article class="card"><h2>Resumen del contrato del agente</h2>@if($contract)<p>{{ $contract->job_to_be_done }}</p><h3>Objetivos</h3><ul>@foreach($contract->objectives as $objective)<li>{{ \App\Support\Presentation\AiAgentPresentation::outcome($objective) }}</li>@endforeach</ul><h3>Canales previstos</h3><p>@foreach($contract->channels as $channel){{ !$loop->first?', ':'' }}{{ \App\Support\Presentation\AiAgentPresentation::channel($channel) }}@endforeach</p>@else<p class="muted">El contrato se está preparando.</p>@endif</article>
@if($contract)<article class="card"><h2>Acciones autorizadas</h2>@forelse($contract->allowed_actions as $key)@php($registry=app(\App\Domain\AI\Actions\ActionRegistry::class))@php($definition=$registry->find($key))@if($definition&&$registry->isAvailable($definition,app(\App\Domain\Network\Tenancy\TenantContext::class)->tenant()))<p><strong>{{ $definition->displayName }}</strong> — {{ $definition->description }}</p>@endif @empty<p class="muted">Este contrato no autoriza acciones.</p>@endforelse</article>@endif
@if($contract&&$contract->status->value==='draft')<article class="card"><h2>Configurar acciones autorizadas</h2><form method="POST" action="{{ route('tenant.admin.ai-agents.contract.actions.update',$agent) }}">@csrf @forelse($availableActionDefinitions as $definition)<label><input type="checkbox" name="allowed_actions[]" value="{{ $definition->key }}" @checked(in_array($definition->key,$contract->allowed_actions,true))> {{ $definition->displayName }}</label><p class="muted">{{ $definition->description }}</p>@empty<p class="muted">Tu plan no incluye acciones disponibles.</p>@endforelse<button class="z-btn" type="submit">Guardar acciones</button></form></article>@endif
<article class="card"><h2>Conocimiento configurado</h2>@forelse($knowledgeLinks as $link)<div><strong>{{ $link->knowledgeVersion->source->name }}</strong> · Versión {{ $link->knowledgeVersion->version_number }} · Aprobado<form method="POST" action="{{ route('tenant.admin.ai-agents.knowledge.detach',[$agent,$link->knowledgeVersion]) }}">@csrf @method('DELETE')<button class="z-btn z-btn--ghost" type="submit">Desvincular</button></form></div>@empty<p class="muted">Todavía no hay conocimiento vinculado.</p>@endforelse @if($draftVersion)<h3>Agregar conocimiento</h3>@forelse($availableKnowledge as $version)@if(!$knowledgeLinks->contains('knowledge_source_version_id',$version->id))<form method="POST" action="{{ route('tenant.admin.ai-agents.knowledge.attach',[$agent,$version]) }}">@csrf<button class="z-btn" type="submit">Vincular {{ $version->source->name }} · Versión {{ $version->version_number }}</button></form>@endif @empty<p>No hay versiones aprobadas. <a href="{{ route('tenant.admin.ai-knowledge.create') }}">Crear fuente</a></p>@endforelse @endif<p>Este conocimiento todavía no se utiliza para conversar; el canal y el motor de IA se configurarán posteriormente.</p></article>
<article class="card"><h2>Probar búsqueda de conocimiento</h2><p>Esta prueba muestra la información que el agente podría utilizar. Todavía no genera una respuesta conversacional.</p>@if($draftVersion)<form method="POST" action="{{ route('tenant.admin.ai-agents.knowledge.search',$agent) }}">@csrf<label>Pregunta<input name="question" maxlength="2000" required value="{{ old('question',$searchQuestion) }}"></label><button class="z-btn" type="submit">Buscar información</button></form>@endif
@if($searched)@forelse($searchMatches as $match)<section><h3>{{ $match->sourceName }}</h3><p>Versión {{ $match->versionNumber }} · {{ $match->locator }}</p><blockquote>{{ $match->excerpt }}</blockquote></section>@empty<p>No encontramos coincidencias en el conocimiento listo y vinculado.</p>@endforelse @elseif(!$knowledgeLinks->contains(fn($link)=>$link->knowledgeVersion->index?->status?->value==='ready'))<p class="muted">Aún no existe conocimiento listo para probar.</p>@endif</article>
<article class="card"><h2>Probar respuesta del agente</h2><p>Esta es una simulación interna. El agente todavía no está publicado.</p><p>Las respuestas se generan únicamente con el conocimiento configurado.</p>@if($runtimeVersion)<form method="POST" action="{{ route('tenant.admin.ai-agents.conversations.store',$agent) }}">@csrf<button class="z-btn" type="submit">Abrir consola de conversación</button></form>@endif @if($runtimeVersion && $providerConfigured && $runtimeKnowledgeReady)<form method="POST" action="{{ route('tenant.admin.ai-agents.runtime.simulate',$agent) }}">@csrf<label>Pregunta<input name="question" maxlength="2000" required value="{{ old('question',$runtimeQuestion) }}"></label><button class="z-btn" type="submit">Generar respuesta propuesta</button></form>@elseif(!$providerConfigured)<p class="muted">La simulación de respuesta todavía no está configurada.</p>@else<p class="muted">Prepara conocimiento vinculado antes de probar una respuesta.</p>@endif
@if($runtimeError)<p>No fue posible generar la respuesta en este momento. Intenta nuevamente.</p>@elseif($runtimeResult)<h3>Respuesta propuesta</h3><p>{{ $runtimeResult->answer }}</p><p><strong>Confianza:</strong> {{ ['high'=>'Alta','medium'=>'Media','low'=>'Baja'][$runtimeResult->confidence] }}</p>@if($runtimeResult->needsHandoff)<p><strong>Requiere revisión humana; todavía no ha sido asignada.</strong></p><p>{{ ['insufficient_knowledge'=>'Información insuficiente','low_confidence'=>'Confianza baja','human_requested'=>'Solicitada por la persona','sensitive_action'=>'Acción sensible','policy_restriction'=>'Restricción de política'][$runtimeResult->handoffReason]??'Revisión humana requerida' }}</p>@else<p><strong>Revisión humana:</strong> No requerida</p>@endif<h3>Fuentes utilizadas</h3>@forelse($runtimeResult->sources as $source)<section><strong>{{ $source['source_name'] }}</strong><p>Versión {{ $source['version'] }} · {{ $source['locator'] }}</p><blockquote>{{ $source['excerpt'] }}</blockquote></section>@empty<p>No encontramos información suficiente para responder. Esta conversación requeriría intervención humana.</p>@endforelse @endif</article>
<article class="card"><h2>Siguientes pasos</h2><p><strong>El borrador fue creado.</strong> Todavía no conversa con clientes y todavía no está publicado.</p><ul><li>Conocimiento: {{ $knowledgeLinks->contains(fn($link)=>$link->knowledgeVersion->index?->status?->value==='ready') ? 'configurado para pruebas' : ($knowledgeLinks->isNotEmpty() ? 'vinculado; preparación pendiente' : 'pendiente') }}.</li><li>Canal Chat web: pendiente de configuración.</li><li>Pruebas: pendientes.</li><li>Contrato: pendiente de revisión y aprobación.</li><li>Publicación: pendiente.</li></ul><p>El equipo ZIGO continuará con la configuración y validación.</p></article><a class="z-btn" href="{{ route('tenant.admin.ai-agents.index') }}">Volver a Mis agentes</a>
@endsection
