@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title','Mi '.($tenant->branding?->brand_name ?: $tenant->name))
@push('head')<style>.dashboard-hero,.dashboard-primary{display:flex;justify-content:space-between;align-items:center;gap:24px}.dashboard-hero{margin:8px 0 24px}.dashboard-hero h1{font-size:clamp(2rem,4vw,3rem);margin:.25rem 0}.dashboard-grid{display:grid;gap:22px}.dashboard-primary{padding:clamp(24px,3vw,38px);border-radius:22px;background:linear-gradient(135deg,var(--z-primary),var(--z-primary-dark));color:#fff;box-shadow:0 18px 38px color-mix(in srgb,var(--z-primary) 24%,transparent)}.dashboard-primary p{color:rgba(255,255,255,.8);margin:.35rem 0 0}.dashboard-primary .z-btn{background:#fff;color:var(--z-primary)}.dashboard-actions{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}.dashboard-action{padding:20px;text-decoration:none;min-height:96px}.dashboard-action strong{display:block;margin-bottom:5px}.dashboard-lower{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,1fr);gap:22px;align-items:start}.dashboard-lower .customer-section{padding:0;min-width:0}.dashboard-pending .shipment-card{margin-top:12px}@media(max-width:1050px){.dashboard-actions{grid-template-columns:repeat(2,1fr)}.dashboard-lower{grid-template-columns:1fr}}@media(max-width:620px){.dashboard-hero,.dashboard-primary{align-items:flex-start;flex-direction:column}.dashboard-actions,.z-metrics{grid-template-columns:1fr}.dashboard-primary .z-btn{width:100%}}</style>@endpush
@section('content')
<header class="dashboard-hero"><div><div class="z-eyebrow">MI {{ mb_strtoupper($tenant->branding?->brand_name ?: $tenant->name) }}</div><h1>Hola, {{ $profile->display_name ?: $profile->user->name }}</h1><p class="z-muted">Consulta tu actividad y continúa lo que requiere atención.</p></div><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.app.shipments',[],false) }}">Ver mis envíos</a></header>
<div class="dashboard-grid"><div class="z-metrics"><article class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="truck" /></span><div><small>Envíos activos</small><strong>{{ $activeCount }}</strong></div></article><article class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="success" /></span><div><small>Entregados</small><strong>{{ $deliveredCount }}</strong></div></article><article class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="warning" /></span><div><small>Pendientes de pago</small><strong>{{ $pendingCheckouts->count() }}</strong></div></article></div>
<section class="dashboard-primary"><div><div class="z-eyebrow">NUEVO ENVÍO</div><h2>Cotiza y prepara tu envío</h2><p>Captura todos los datos una sola vez y compara servicios antes de pagar.</p></div><a class="z-btn" href="{{ route('tenant.customer.app.quote',[],false) }}">Nuevo envío</a></section>
<nav class="dashboard-actions" aria-label="Acciones rápidas">@foreach([[route('tenant.customer.app.quote',[],false),'Cotizar','Prepara un nuevo envío.'],[route('tenant.b2c.tracking.public',[],false),'Rastrear','Consulta el avance de una guía.'],[route('tenant.customer.app.addresses.index',[],false),'Mis direcciones','Reutiliza contactos frecuentes.'],[route('tenant.customer.app.support',[],false),'Ayuda','Recibe soporte.']] as $action)<a class="z-card dashboard-action" href="{{ $action[0] }}"><strong>{{ $action[1] }}</strong><span class="z-muted">{{ $action[2] }}</span></a>@endforeach</nav>
<div class="dashboard-lower"><section class="customer-section"><div class="z-page-header"><div><div class="z-eyebrow">ACTIVIDAD</div><h2>Últimos envíos</h2></div><a href="{{ route('tenant.customer.app.shipments',[],false) }}">Ver todos</a></div><div class="z-data-list">@forelse($shipments as $shipment)<article class="z-data-row"><div><strong>{{ $shipment->tracking_number }}</strong><div class="z-muted z-small">{{ $shipment->created_at->format('d/m/Y') }}</div></div><div class="z-route-inline"><span>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->sender_snapshot,'address')) }}</span><x-zigo.icon name="chevron" /><span>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->recipient_snapshot,'address')) }}</span></div><span>{{ $shipment->service_code }}</span><span class="z-badge">{{ $labels[$shipment->status] ?? 'Actualización' }}</span><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.app.shipments.show',$shipment->uuid,false) }}">Ver detalle</a></article>@empty<div class="z-empty"><h3>Sin envíos todavía</h3><p>Usa “Nuevo envío” para comenzar.</p></div>@endforelse</div></section>
<aside class="customer-section dashboard-pending"><div class="z-eyebrow">PENDIENTES DE PAGO</div><h2>{{ $pendingCheckouts->isEmpty()?'Todo al día':'Continúa tu compra' }}</h2>@forelse($pendingCheckouts as $checkout)<article class="z-card shipment-card"><strong>{{ data_get($checkout->quote_snapshot,'service','Envío cotizado') }}</strong><span class="z-badge z-badge--warning">Pago pendiente</span><strong>${{ number_format((float)$checkout->total_amount,2) }} {{ $checkout->currency }}</strong><a href="{{ route($checkout->status==='DRAFT'?'tenant.customer.app.checkout.summary':'tenant.customer.app.checkout.payment',$checkout->uuid,false) }}">Continuar pago →</a></article>@empty<p class="z-muted">No tienes pagos pendientes.</p>@endforelse</aside></div></div>
@endsection
