@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title','Mi '.($tenant->branding?->brand_name ?: $tenant->name))
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">MI {{ mb_strtoupper($tenant->branding?->brand_name ?: $tenant->name) }}</div><h1>Hola, {{ $profile->display_name ?: $profile->user->name }}</h1><p class="z-muted">Tus cotizaciones, pagos pendientes y envíos reales están separados.</p></div><a class="z-btn" href="/app/cotizar">Cotizar nuevo envío</a></header>
<div class="z-grid"><article class="z-card z-metric"><small>Envíos activos</small><strong>{{ $activeCount }}</strong></article><article class="z-card z-metric"><small>Entregados</small><strong>{{ $deliveredCount }}</strong></article><article class="z-card z-metric"><small>Pendientes de pago</small><strong>{{ $pendingCheckouts->count() }}</strong></article></div>
@if($pendingCheckouts->isNotEmpty())<section class="customer-section"><div class="z-eyebrow">PENDIENTES DE PAGO</div><h2>Continúa cuando estés listo</h2><div class="z-stack">@foreach($pendingCheckouts as $checkout)<article class="z-card shipment-card"><div class="shipment-card__top"><div><strong>{{ $checkout->quote_snapshot['service'] ?? 'Envío cotizado' }}</strong><div class="z-muted">{{ $checkout->quote_snapshot['route']['origin'] ?? '—' }} → {{ $checkout->quote_snapshot['route']['destination'] ?? '—' }}</div></div><span class="z-badge z-badge--warning">Pago pendiente</span></div><strong>${{ number_format((float)$checkout->total_amount,2) }} {{ $checkout->currency }}</strong><a href="/app/checkout/{{ $checkout->uuid }}/{{ $checkout->status==='DRAFT'?'resumen':'pago' }}">Continuar pago →</a></article>@endforeach</div></section>@endif
<section class="customer-section"><div class="z-page-header"><div><div class="z-eyebrow">ENVÍOS REALES</div><h2>Mis envíos recientes</h2></div><a href="/app/envios">Ver todos</a></div>@forelse($shipments as $shipment)<article class="z-card shipment-card" style="margin-bottom:1rem"><div class="shipment-card__top"><div><strong>{{ $shipment->tracking_number }}</strong><div class="z-muted">{{ $shipment->created_at->format('d/m/Y') }}</div></div><span class="z-badge">{{ $labels[$shipment->status] ?? 'Actualización' }}</span></div><a href="/app/envios/{{ $shipment->uuid }}">Ver envío →</a></article>@empty<div class="z-empty"><div class="z-empty__icon">▤</div><h3>Sin envíos todavía</h3><p>Una cotización pendiente de pago aún no es un envío.</p><a class="z-btn" href="/app/cotizar">Cotizar ahora</a></div>@endforelse</section>
@endsection
