@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title','Mi '.($tenant->branding?->brand_name ?: $tenant->name))
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">MI {{ mb_strtoupper($tenant->branding?->brand_name ?: $tenant->name) }}</div><h1>Hola, {{ $profile->display_name ?: $profile->user->name }}</h1><p class="z-muted">Todo lo que necesitas para enviar y dar seguimiento.</p></div><a class="z-btn" href="/app/cotizar"><x-zigo.icon name="quote" />Crear nuevo envío</a></header>
<div class="z-metrics"><article class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="truck" /></span><div><small>Envíos activos</small><strong>{{ $activeCount }}</strong></div></article><article class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="success" /></span><div><small>Entregados</small><strong>{{ $deliveredCount }}</strong></div></article><article class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="warning" /></span><div><small>Pendientes de pago</small><strong>{{ $pendingCheckouts->count() }}</strong></div></article></div>
@if($pendingCheckouts->isNotEmpty())<section class="customer-section"><div class="z-eyebrow">PENDIENTES DE PAGO</div><h2>Continúa cuando estés listo</h2><div class="z-stack">@foreach($pendingCheckouts as $checkout)<article class="z-card shipment-card"><div class="shipment-card__top"><div><strong>{{ $checkout->quote_snapshot['service'] ?? 'Envío cotizado' }}</strong><div class="z-muted">{{ $checkout->quote_snapshot['route']['origin'] ?? '—' }} → {{ $checkout->quote_snapshot['route']['destination'] ?? '—' }}</div></div><span class="z-badge z-badge--warning">Pago pendiente</span></div><strong>${{ number_format((float)$checkout->total_amount,2) }} {{ $checkout->currency }}</strong><a href="/app/checkout/{{ $checkout->uuid }}/{{ $checkout->status==='DRAFT'?'resumen':'pago' }}">Continuar pago →</a></article>@endforeach</div></section>@endif
<section class="customer-section"><div class="z-page-header"><div><div class="z-eyebrow">ACTIVIDAD</div><h2>Últimos envíos</h2></div><a href="/app/envios">Ver todos</a></div><div class="z-data-list">@forelse($shipments as $shipment)<article class="z-data-row"><div><strong>{{ $shipment->tracking_number }}</strong><div class="z-muted z-small">{{ $shipment->created_at->format('d/m/Y') }}</div></div><div class="z-route-inline"><span>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->sender_snapshot,'address')) }}</span><x-zigo.icon name="chevron" /><span>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->recipient_snapshot,'address')) }}</span></div><span>{{ $shipment->service_code }}</span><span class="z-badge">{{ $labels[$shipment->status] ?? 'Actualización' }}</span><a class="z-btn z-btn--outline" href="/app/envios/{{ $shipment->uuid }}">Ver detalle</a></article>@empty<div class="z-empty"><div class="z-empty__icon"><x-zigo.icon name="shipments" /></div><h3>Sin envíos todavía</h3><p>Crea tu primer envío para comenzar.</p><a class="z-btn" href="/app/cotizar">Cotizar ahora</a></div>@endforelse</div></section>
@endsection
