@extends('tenant.layout')
@section('title','Envío '.$shipment->tracking_number)
@push('head')<style>
.shipment-shell{max-width:1180px;margin:0 auto}.shipment-grid{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);gap:1rem;align-items:start}.shipment-summary{padding:1.15rem}.shipment-grid>.tracking-history,.shipment-grid>aside{min-width:0}.shipment-route{display:grid;grid-template-columns:1fr auto 1fr;gap:.8rem;align-items:center;padding-bottom:1rem;border-bottom:1px solid var(--z-border)}.shipment-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin-top:1rem}.shipment-fact{display:grid;gap:.15rem;padding:.75rem;background:var(--z-surface-subtle,#f7f9fc);border-radius:10px}.delivery-card{margin-top:1rem}.shipment-pickup{margin-top:1rem}
@media(max-width:767px){.shipment-grid{grid-template-columns:1fr}.shipment-route{grid-template-columns:1fr}.shipment-route>span{display:none}.shipment-facts{grid-template-columns:1fr}.shipment-shell .z-panel{padding:1rem}}
</style>@endpush
@section('content')
@php($trackingEvents=$shipment->events)
@php($trackingStatus=$shipment->status)
@php($trackingNumber=$shipment->tracking_number)
@php($trackingUpdatedAt=$shipment->updated_at)
@php($trackingEyebrow='DETALLE DE ENVÍO')
@php($trackingActions='<a class="z-btn" href="'.route('tenant.customer.app.shipments.tracking',$shipment->uuid,false).'">Rastrear</a><a class="z-btn z-btn--outline" href="'.route('tenant.customer.app.shipments.guide',$shipment->uuid,false).'">Descargar guía</a><a class="z-btn z-btn--ghost" href="'.route('tenant.customer.app.support.create',['envio'=>$shipment->uuid],false).'">Ayuda</a>')
<div class="shipment-shell">@include('tenant.tracking._header') @include('tenant.tracking._stepper')
<div class="shipment-grid">@include('tenant.tracking._timeline',['trackingTimelineClass'=>'z-card'])<aside>
<section class="z-card shipment-summary"><h2>Resumen del envío</h2><div class="shipment-route">@foreach(['ORIGEN'=>$shipment->sender_snapshot,'DESTINO'=>$shipment->recipient_snapshot] as $heading=>$party)<div><div class="z-eyebrow">{{ $heading }}</div>@foreach(\App\Support\Presentation\AddressPresenter::lines($party) as $line)@if($loop->first)<strong>{{ $line }}</strong>@else<div class="z-muted">{{ $line }}</div>@endif @endforeach</div>@if(!$loop->last)<span>→</span>@endif @endforeach</div>
<div class="shipment-facts"><div class="shipment-fact"><span class="z-muted">Servicio</span><strong>{{ $shipment->service_code }}</strong></div><div class="shipment-fact"><span class="z-muted">Paquete</span><strong>{{ ucfirst($shipment->package_snapshot['type'] ?? 'Paquete') }} · {{ $shipment->package_snapshot['weight'] ?? '—' }} kg</strong></div><div class="shipment-fact"><span class="z-muted">Estado</span><strong>{{ \App\Support\Presentation\ShipmentStatusPresenter::label($shipment->status) }}</strong></div>@if(isset($shipment->pricing_snapshot['final_price']))<div class="shipment-fact"><span class="z-muted">Total</span><strong>${{ number_format($shipment->pricing_snapshot['final_price'],2) }} {{ $shipment->pricing_snapshot['currency'] ?? 'MXN' }}</strong></div>@endif</div></section>
@if($shipment->deliveryRequirement)<section class="z-card delivery-card"><h2>Modalidad de entrega</h2><p>{{ $shipment->deliveryRequirement->proof_option_name_snapshot ?? 'Evidencia de entrega' }}</p><div class="z-cluster">@if($shipment->deliveryRequirement->require_signature)<span class="z-badge">Firma al recibir</span>@endif @if($shipment->deliveryRequirement->require_photo)<span class="z-badge">Foto</span>@endif @if($shipment->deliveryRequirement->require_gps)<span class="z-badge">Ubicación</span>@endif</div></section>@endif
@if(($pickupEnabled ?? false) && $shipment->status==='CREATED')<section class="z-status-panel shipment-pickup"><h2 class="z-section-title">Tu paquete está listo para continuar</h2><p class="z-muted">La guía está creada y el pago fue aprobado. Solicita la recolección cuando el paquete esté preparado.</p><form method="POST" action="{{ route('tenant.customer.app.shipments.pickup',$shipment->uuid,false) }}">@csrf<button class="z-btn">Solicitar recolección</button></form></section>@endif
</aside></div></div>
@endsection
