@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title',$shipment->tracking_number)
@section('content')
<a href="/app/envios">← Mis envíos</a><header class="z-page-header" style="margin-top:1rem"><div><div class="z-eyebrow">DETALLE DEL ENVÍO</div><h1>{{ $shipment->tracking_number }}</h1><div class="z-cluster"><span class="z-badge @if($shipment->status==='DELIVERED') z-badge--success @elseif(in_array($shipment->status,['DELIVERY_FAILED','CANCELED'])) z-badge--danger @endif">{{ $labels[$shipment->status] ?? 'Actualización' }}</span><span class="z-muted">{{ $shipment->service_code }} · {{ $shipment->created_at->format('d/m/Y') }}</span></div></div><div class="z-actions"><a class="z-btn z-btn--outline" href="/rastreo/{{ $shipment->tracking_number }}"><x-zigo.icon name="tracking" />Rastrear</a><a class="z-btn" href="/app/envios/{{ $shipment->uuid }}/guia.pdf"><x-zigo.icon name="download" />Descargar guía</a><a class="z-btn z-btn--ghost" href="{{ route('tenant.customer.app.support.create',['envio'=>$shipment->uuid]) }}"><x-zigo.icon name="help" />Ayuda</a></div></header>
<div class="z-detail-grid"><div class="z-stack"><section class="z-panel"><h2>Ruta del envío</h2><div class="z-route"><div class="z-route__point"><div class="z-eyebrow">ORIGEN</div><div class="z-route__city">{{ \App\Support\Presentation\AddressPresenter::compact($shipment->sender_snapshot['address'] ?? null) }}</div><div class="z-route__address">{{ \App\Support\Presentation\AddressPresenter::full($shipment->sender_snapshot['address'] ?? null) }} · CP {{ $shipment->sender_snapshot['postal_code'] ?? '—' }}</div></div><div class="z-route__line"></div><div class="z-route__point"><div class="z-eyebrow">DESTINO</div><div class="z-route__city">{{ \App\Support\Presentation\AddressPresenter::compact($shipment->recipient_snapshot['address'] ?? null) }}</div><div class="z-route__address">{{ \App\Support\Presentation\AddressPresenter::full($shipment->recipient_snapshot['address'] ?? null) }} · CP {{ $shipment->recipient_snapshot['postal_code'] ?? '—' }}</div></div></div></section><section class="z-panel"><h2>Seguimiento</h2><ol class="z-timeline">@foreach($shipment->events->sortByDesc('occurred_at') as $event)<li><strong>{{ $labels[$event->status] ?? 'Actualización del envío' }}</strong><div class="z-muted">{{ optional($event->occurred_at)->format('d/m/Y H:i') }}</div></li>@endforeach</ol></section></div><aside class="z-stack"><section class="z-panel"><h2>Paquete y servicio</h2><p><strong>{{ ucfirst($shipment->package_snapshot['type'] ?? 'Paquete') }}</strong> · {{ $shipment->package_snapshot['weight'] ?? '—' }} kg</p><p class="z-muted">Servicio {{ $shipment->service_code }}</p>@if(isset($shipment->pricing_snapshot['final_price']))<strong class="z-metric-value">${{ number_format($shipment->pricing_snapshot['final_price'],2) }} <small>{{ $shipment->pricing_snapshot['currency'] ?? 'MXN' }}</small></strong>@endif</section>
@if($shipment->deliveryRequirement)<section class="z-card" style="margin-top:1rem"><h2>Modalidad de entrega</h2><p>{{ $shipment->deliveryRequirement->proof_option_name_snapshot ?? 'Evidencia de entrega' }}</p><div class="z-cluster">@if($shipment->deliveryRequirement->require_signature)<span class="z-badge">Firma al recibir</span>@endif @if($shipment->deliveryRequirement->require_photo)<span class="z-badge">Foto</span>@endif @if($shipment->deliveryRequirement->require_gps)<span class="z-badge">Ubicación</span>@endif</div></section>@endif
@if($shipment->status==='CREATED')<section class="z-status-panel"><h2 class="z-section-title">Tu paquete está listo para continuar</h2><p class="z-muted">Solicita la recolección cuando el paquete esté preparado.</p><form method="POST" action="/app/envios/{{ $shipment->uuid }}/recoleccion">@csrf<button class="z-btn">Solicitar recolección</button></form></section>@endif</aside></div>
@endsection
