@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title','Mis envíos')
@push('head')<style>.customer-shipments{display:grid;gap:14px;margin-top:16px}.customer-shipment-card{display:grid;gap:15px;padding:20px;border:1px solid var(--z-border);border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(15,35,75,.05)}.customer-shipment-card__head,.customer-shipment-card__foot{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.customer-shipment-card__head strong{display:block;font-size:1.05rem}.customer-shipment-card__route{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:12px;padding:13px;border-radius:11px;background:var(--z-surface-subtle)}.customer-shipment-card__route small,.customer-shipment-card__route strong{display:block}.customer-shipment-card__route small{color:var(--z-muted);margin-bottom:3px}.customer-shipment-card__route strong{font-size:.88rem}.customer-shipment-card__service{display:flex;align-items:center;gap:8px;color:var(--z-muted)}@media(max-width:620px){.customer-shipment-card__head,.customer-shipment-card__foot{align-items:stretch;flex-direction:column}.customer-shipment-card__route{grid-template-columns:1fr}.customer-shipment-card__route>.z-icon{transform:rotate(90deg)}.customer-shipment-card__foot .z-actions{width:100%}.customer-shipment-card__foot .z-btn{flex:1}}</style>@endpush
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">MI CUENTA</div><h1>Mis envíos</h1><p class="z-muted">Gestiona y da seguimiento a tus entregas.</p></div><a class="z-btn" href="{{ route('tenant.customer.app.quote',[],false) }}"><x-zigo.icon name="quote" />Nuevo envío</a></header>
<nav class="z-tabs" aria-label="Filtrar envíos"><a href="/app/envios?estado=todos" @if($filter==='todos') aria-current="page" @endif>Todos</a><a href="/app/envios?estado=activos" @if($filter==='activos') aria-current="page" @endif>Activos</a><a href="/app/envios?estado=entregados" @if($filter==='entregados') aria-current="page" @endif>Entregados</a></nav>
<div class="customer-shipments">
@forelse($shipments as $shipment)
<article class="customer-shipment-card"><header class="customer-shipment-card__head"><div><strong>{{ $shipment->tracking_number }}</strong><small class="z-muted">{{ $shipment->created_at->format('d/m/Y') }}</small></div><span class="z-badge @if($shipment->status==='DELIVERED') z-badge--success @elseif(in_array($shipment->status,['DELIVERY_FAILED','CANCELED'])) z-badge--danger @endif">{{ $labels[$shipment->status] ?? 'Actualización' }}</span></header><div class="customer-shipment-card__route"><div><small>Origen</small><strong>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->sender_snapshot,'address')) }}</strong></div><x-zigo.icon name="chevron" /><div><small>Destino</small><strong>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->recipient_snapshot,'address')) }}</strong></div></div><footer class="customer-shipment-card__foot"><div class="customer-shipment-card__service"><strong>{{ $shipment->service_code }}</strong>@if(isset($shipment->pricing_snapshot['final_price']))<span>·</span><strong>${{ number_format($shipment->pricing_snapshot['final_price'],2) }} {{ $shipment->pricing_snapshot['currency'] ?? 'MXN' }}</strong>@endif</div><div class="z-actions"><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.app.shipments.show',$shipment->uuid,false) }}">Ver detalle</a>@if($shipment->tracking_number)<a class="z-btn z-btn--ghost" href="{{ route('tenant.b2c.tracking.legacy.show',$shipment->tracking_number,false) }}">Rastrear</a>@endif</div></footer></article>
@empty<div class="z-empty"><div class="z-empty__icon"><x-zigo.icon name="shipments" /></div><h3>Sin envíos todavía</h3><p>No hay envíos para este filtro.</p></div>@endforelse
</div><div style="margin-top:1.5rem">{{ $shipments->withQueryString()->links() }}</div>
@endsection
