@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title','Mis envíos')
@section('content')<header class="z-page-header"><div><div class="z-eyebrow">MI CUENTA</div><h1>Mis envíos</h1><p class="z-muted">Gestiona y da seguimiento a tus entregas.</p></div><a class="z-btn" href="/app/cotizar"><x-zigo.icon name="quote" />Nuevo envío</a></header>
@php($all=$shipments->getCollection())
@php($active=$all->whereNotIn('status',['DELIVERED','CANCELED'])->count())
@php($transit=$all->whereIn('status',['PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY'])->count())
@php($delivered=$all->where('status','DELIVERED')->count())
<div class="z-metrics" style="margin-bottom:1rem"><div class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="shipments" /></span><div><small>Activos en esta página</small><strong>{{ $active }}</strong></div></div><div class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="truck" /></span><div><small>En tránsito</small><strong>{{ $transit }}</strong></div></div><div class="z-metric-v2"><span class="z-metric-v2__icon"><x-zigo.icon name="success" /></span><div><small>Entregados</small><strong>{{ $delivered }}</strong></div></div></div>
<nav class="z-tabs" aria-label="Filtrar envíos"><a href="/app/envios?estado=todos" @if($filter==='todos') aria-current="page" @endif>Todos</a><a href="/app/envios?estado=activos" @if($filter==='activos') aria-current="page" @endif>Activos</a><a href="/app/envios?estado=entregados" @if($filter==='entregados') aria-current="page" @endif>Entregados</a></nav><div class="z-data-list" style="margin-top:1rem">@forelse($shipments as $shipment)<article class="z-data-row"><div><span class="z-data-row__label">Guía</span><strong>{{ $shipment->tracking_number }}</strong><div class="z-muted z-small">{{ $shipment->created_at->format('d/m/Y') }}</div></div><div class="z-route-inline"><div><span class="z-data-row__label">Origen</span>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->sender_snapshot,'address')) }}</div><x-zigo.icon name="chevron" /><div><span class="z-data-row__label">Destino</span>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->recipient_snapshot,'address')) }}</div></div><div><span class="z-data-row__label">Servicio</span>{{ $shipment->service_code }}</div><div><span class="z-data-row__label">Estado</span><span class="z-badge @if($shipment->status==='DELIVERED') z-badge--success @elseif(in_array($shipment->status,['DELIVERY_FAILED','CANCELED'])) z-badge--danger @endif">{{ $labels[$shipment->status] ?? 'Actualización' }}</span>@if(isset($shipment->pricing_snapshot['final_price']))<div class="z-small" style="margin-top:.35rem">${{ number_format($shipment->pricing_snapshot['final_price'],2) }} {{ $shipment->pricing_snapshot['currency'] ?? 'MXN' }}</div>@endif</div><a class="z-btn z-btn--outline" href="/app/envios/{{ $shipment->uuid }}">Ver detalle</a></article>@empty<div class="z-empty"><div class="z-empty__icon"><x-zigo.icon name="shipments" /></div><h3>Sin envíos todavía</h3><p>No hay envíos para este filtro.</p></div>@endforelse</div><div style="margin-top:1.5rem">{{ $shipments->withQueryString()->links() }}</div>@endsection
