@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title',$shipment->tracking_number)
@section('content')
<a href="/app/envios">← Mis envíos</a><header class="z-page-header" style="margin-top:1rem"><div><div class="z-eyebrow">DETALLE DEL ENVÍO</div><h1>{{ $shipment->tracking_number }}</h1><span class="z-badge">{{ $labels[$shipment->status] ?? 'Actualización' }}</span></div><div class="z-cluster"><a class="z-btn z-btn--outline" href="/rastreo/{{ $shipment->tracking_number }}">Ver tracking</a><a class="z-btn" href="/app/envios/{{ $shipment->uuid }}/guia.pdf">Descargar guía</a></div></header>
<div class="z-grid"><section class="z-card"><h2>Ruta</h2><div class="z-stack"><div><div class="z-eyebrow">ORIGEN</div><strong>{{ $shipment->sender_snapshot['name'] ?? 'Remitente' }}</strong><p>{{ $shipment->sender_snapshot['address'] ?? '—' }} · CP {{ $shipment->sender_snapshot['postal_code'] ?? '—' }}</p></div><div><div class="z-eyebrow">DESTINO</div><strong>{{ $shipment->recipient_snapshot['name'] ?? 'Destinatario' }}</strong><p>{{ $shipment->recipient_snapshot['address'] ?? '—' }} · CP {{ $shipment->recipient_snapshot['postal_code'] ?? '—' }}</p></div></div></section><section class="z-card"><h2>Paquete</h2><p>{{ ucfirst($shipment->package_snapshot['type'] ?? 'Paquete') }} · {{ $shipment->package_snapshot['weight'] ?? '—' }} kg</p><p class="z-muted">Servicio {{ $shipment->service_code }}</p>@if(isset($shipment->pricing_snapshot['final_price']))<strong>${{ number_format($shipment->pricing_snapshot['final_price'],2) }} {{ $shipment->pricing_snapshot['currency'] ?? 'MXN' }}</strong>@endif</section></div>
<section class="z-card" style="margin-top:1rem"><h2>Seguimiento</h2><ol class="z-timeline">@foreach($shipment->events->sortByDesc('occurred_at') as $event)<li><strong>{{ $labels[$event->status] ?? 'Actualización del envío' }}</strong><div class="z-muted">{{ optional($event->occurred_at)->format('d/m/Y H:i') }}</div></li>@endforeach</ol></section>
@if($shipment->deliveryRequirement)<section class="z-card" style="margin-top:1rem"><h2>Modalidad de entrega</h2><p>{{ $shipment->deliveryRequirement->proof_option_name_snapshot ?? 'Evidencia de entrega' }}</p><div class="z-cluster">@if($shipment->deliveryRequirement->require_signature)<span class="z-badge">Firma al recibir</span>@endif @if($shipment->deliveryRequirement->require_photo)<span class="z-badge">Foto</span>@endif @if($shipment->deliveryRequirement->require_gps)<span class="z-badge">Ubicación</span>@endif</div></section>@endif
@if($shipment->status==='CREATED')<section class="z-card" style="margin-top:1rem"><h2>Recolección</h2><p class="z-muted">Solicita la recolección cuando el paquete esté listo. El despacho asignará al conductor.</p><form method="POST" action="/app/envios/{{ $shipment->uuid }}/recoleccion">@csrf<button class="z-btn">Solicitar recolección</button></form></section>@endif
@endsection
