@extends('tenant.layout')
@php($labels=['CREATED'=>'Envío creado','READY_FOR_PICKUP'=>'Recolección solicitada','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERED'=>'Entregado','DELIVERY_FAILED'=>'No entregado','CANCELED'=>'Cancelado'])
@section('title','Mis envíos')
@push('head')<style>
.customer-section{margin-top:28px}.customer-section__head{margin-bottom:14px}.customer-section__head h2{margin:0}.customer-pending-list{display:grid;gap:12px;padding:4px 20px;border:1px solid var(--z-border);border-radius:16px;background:#fff}.pending-checkout-card{display:grid;grid-template-columns:minmax(170px,1fr) minmax(220px,1.3fr) minmax(250px,.9fr) auto;align-items:center;gap:18px;padding:16px 0;border-bottom:1px solid var(--z-border)}.pending-checkout-card:last-child{border-bottom:0}.pending-checkout-card__head strong,.pending-checkout-card__head small{display:block}.pending-checkout-card__head small{color:var(--z-muted);margin-top:3px}.pending-checkout-card__head .z-badge{margin-top:7px}.pending-checkout-card__route{display:flex;align-items:center;gap:8px}.pending-checkout-card__amounts{display:grid;gap:4px;margin:0}.pending-checkout-card__amounts div{display:flex;justify-content:space-between;gap:12px}.pending-checkout-card__amounts dt,.pending-checkout-card__amounts dd{margin:0}.pending-checkout-card__amounts .total{font-weight:900}.customer-shipments{display:grid;gap:14px;margin-top:16px}.customer-shipment-card{display:grid;gap:15px;padding:20px;border:1px solid var(--z-border);border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(15,35,75,.05)}.customer-shipment-card__head,.customer-shipment-card__foot{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.customer-shipment-card__head strong{display:block;font-size:1.05rem}.customer-shipment-card__route{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:center;gap:12px;padding:13px;border-radius:11px;background:var(--z-surface-subtle)}.customer-shipment-card__route small,.customer-shipment-card__route strong{display:block}.customer-shipment-card__route small{color:var(--z-muted);margin-bottom:3px}.customer-shipment-card__route strong{font-size:.88rem}.customer-shipment-card__service{display:flex;align-items:center;gap:8px;color:var(--z-muted)}@media(max-width:1000px){.pending-checkout-card{grid-template-columns:1fr 1fr}.pending-checkout-card>.z-btn{justify-self:start}}@media(max-width:620px){.pending-checkout-card{grid-template-columns:1fr}.customer-pending-list{padding-inline:16px}.customer-shipment-card__head,.customer-shipment-card__foot{align-items:stretch;flex-direction:column}.customer-shipment-card__route{grid-template-columns:1fr}.customer-shipment-card__route>.z-icon{transform:rotate(90deg)}.customer-shipment-card__foot .z-actions{width:100%}.customer-shipment-card__foot .z-btn{flex:1}}
</style>@endpush
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">MI CUENTA</div><h1>Mis envíos</h1><p class="z-muted">Gestiona tus guías generadas y los pagos que aún están pendientes.</p></div><a class="z-btn" href="{{ route('tenant.customer.app.quote',[],false) }}"><x-zigo.icon name="quote" />Nuevo envío</a></header>
<section class="customer-section" aria-labelledby="shipments-title"><header class="customer-section__head"><div class="z-eyebrow">GUÍAS GENERADAS</div><h2 id="shipments-title">Envíos</h2></header>
<nav class="z-tabs" aria-label="Filtrar envíos"><a href="/app/envios?estado=todos" @if($filter==='todos') aria-current="page" @endif>Todos</a><a href="/app/envios?estado=activos" @if($filter==='activos') aria-current="page" @endif>Activos</a><a href="/app/envios?estado=entregados" @if($filter==='entregados') aria-current="page" @endif>Entregados</a></nav>
<div class="customer-shipments">@forelse($shipments as $shipment)
<article class="customer-shipment-card"><header class="customer-shipment-card__head"><div><strong>{{ $shipment->tracking_number }}</strong><small class="z-muted">{{ $shipment->created_at->format('d/m/Y') }}</small></div><span class="z-badge @if($shipment->status==='DELIVERED') z-badge--success @elseif(in_array($shipment->status,['DELIVERY_FAILED','CANCELED'])) z-badge--danger @endif">{{ $labels[$shipment->status] ?? 'Actualización' }}</span></header><div class="customer-shipment-card__route"><div><small>Origen</small><strong>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->sender_snapshot,'address')) }}</strong></div><x-zigo.icon name="chevron" /><div><small>Destino</small><strong>{{ \App\Support\Presentation\AddressPresenter::compact(data_get($shipment->recipient_snapshot,'address')) }}</strong></div></div><footer class="customer-shipment-card__foot"><div class="customer-shipment-card__service"><strong>{{ $shipment->service_code }}</strong>@if(isset($shipment->pricing_snapshot['final_price']))<span>·</span><strong>${{ number_format($shipment->pricing_snapshot['final_price'],2) }} {{ $shipment->pricing_snapshot['currency'] ?? 'MXN' }}</strong>@endif</div><div class="z-actions"><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.app.shipments.show',$shipment->uuid,false) }}">Ver detalle</a>@if($shipment->tracking_number)<a class="z-btn z-btn--ghost" href="{{ route('tenant.b2c.tracking.legacy.show',$shipment->tracking_number,false) }}">Rastrear</a>@endif</div></footer></article>
@empty<div class="z-empty"><div class="z-empty__icon"><x-zigo.icon name="shipments" /></div><h3>Sin envíos todavía</h3><p>No hay envíos para este filtro.</p></div>@endforelse</div>{{ $shipments->withQueryString()->links('tenant.customer.partials.pagination') }}</section>
@if($pendingCheckouts->isNotEmpty())
<section class="customer-section" aria-labelledby="pending-title"><header class="customer-section__head"><div class="z-eyebrow">CHECKOUTS</div><h2 id="pending-title">Pendientes de pago</h2></header><div class="customer-pending-list">@foreach($pendingCheckouts as $checkout)@include('tenant.customer.partials.pending-checkout',['checkout'=>$checkout])@endforeach</div>@if(method_exists($pendingCheckouts,'links')){{ $pendingCheckouts->withQueryString()->links('tenant.customer.partials.pagination') }}@endif</section>
@endif
@endsection
