<?php

namespace App\Domain\AI\Agents\Services;

use App\Domain\AI\Agents\Enums\{AgentContractStatus,AgentContractVersionStatus,AgentLifecycleEventType,AgentStatus,AgentVersionStatus};
use App\Domain\AI\Agents\Exceptions\{AgentContractNotAcceptedException,AiReviewRequiredException,InconsistentAgentPublicationException,InvalidAgentTransitionException,StaleAiContentHashException};
use App\Domain\AI\Agents\Models\{Agent,AgentContract,AgentContractVersion,AgentVersion};
use App\Domain\AI\Agents\Support\AiLifecycleInputGuard;
use App\Domain\AI\Support\CanonicalJsonHasher;
use App\Models\User;
use Illuminate\Support\Facades\DB;

final class AgentVersionLifecycleService
{
    public function __construct(private AiLifecycleAuthorization$auth,private CanonicalJsonHasher$hasher,private AiLifecycleInputGuard$input,private AgentLifecycleAudit$audit){}

    public function startTesting(User$actor,AgentVersion$input):AgentVersion{$authorized=$this->auth->authorize($actor);$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$contractVersion,$version]=$this->lockChain($ids);$this->assertOpen($agent,$contract);$this->expect($version,AgentVersionStatus::Draft);$hash=$this->configurationHash($version);$version->markTesting($authorized,$hash);$this->audit->agentVersionTesting($authorized,$agent,$version);return$version;},3);}
    public function returnToDraft(User$actor,AgentVersion$input,string$reason):AgentVersion{$authorized=$this->auth->authorize($actor);$reason=$this->input->reason($reason);$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids,$reason){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$cv,$version]=$this->lockChain($ids);$this->assertOpen($agent,$contract);$this->expect($version,AgentVersionStatus::Testing);$version->returnToDraftLifecycle($authorized);$this->audit->agentVersionReturnedToDraft($authorized,$agent,$version,$reason);return$version;},3);}
    public function approve(User$actor,AgentVersion$input,array$evidence):AgentVersion{$authorized=$this->auth->authorize($actor);$evidence=$this->input->evidence($evidence);if($evidence===[])throw new AiReviewRequiredException('Explicit manual review evidence is required.');$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids,$evidence){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$cv,$version]=$this->lockChain($ids);$this->assertOpen($agent,$contract);$this->expect($version,AgentVersionStatus::Testing);$hash=$this->configurationHash($version);if(!hash_equals((string)$version->configuration_hash,$hash))throw new StaleAiContentHashException('Agent configuration hash is stale.');$version->markApproved($authorized,$evidence);$this->audit->agentVersionApproved($authorized,$agent,$version);return$version;},3);}
    public function publish(User$actor,AgentVersion$input):AgentVersion{$authorized=$this->auth->authorize($actor);$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$contractVersion]=$this->lockParents($ids);$candidateIds=AgentVersion::query()->where('agent_id',$agent->id)->where(function($q)use($ids){$q->whereKey($ids[3])->orWhere('status',AgentVersionStatus::Published->value);})->pluck('id')->unique()->sort()->values();$locked=AgentVersion::query()->whereIn('id',$candidateIds)->orderBy('id')->lockForUpdate()->get()->keyBy('id');$version=$locked->get($ids[3])??throw new \RuntimeException('Target agent version disappeared while locking.');if($version->agent_contract_version_id!==$contractVersion?->id)throw new InconsistentAgentPublicationException('Agent version contract relationship changed while locking.');$this->assertOpen($agent,$contract);if($version->status===AgentVersionStatus::Published){if($agent->current_published_version_id===$version->id)return$version;throw new InconsistentAgentPublicationException('Published version pointer is inconsistent.');}$this->expect($version,AgentVersionStatus::Approved);$hash=$this->configurationHash($version);if(!hash_equals((string)$version->configuration_hash,$hash))throw new StaleAiContentHashException('Agent configuration hash is stale.');if(!$contractVersion||$contractVersion->agent_contract_id!==$contract->id)throw new InconsistentAgentPublicationException('Contract version belongs to another agent.');if($contractVersion->status!==AgentContractVersionStatus::Accepted||$contract->status!==AgentContractStatus::Active||$contract->current_accepted_version_id!==$contractVersion->id)throw new AgentContractNotAcceptedException('Current accepted active contract is required.');$previous=$locked->first(fn($item)=>$item->id!==$version->id&&$item->status===AgentVersionStatus::Published);if($previous){$reason='Superseded by published version '.$version->version_number;$previous->markRetired($authorized);$this->audit->agentVersionRetired($authorized,$agent,$previous,'published',$reason);}$version->markPublished($authorized);$agent->activateWithPublishedVersion($authorized,$version);$this->audit->agentVersionPublished($authorized,$agent,$version);return$version;},3);}
    public function retire(User$actor,AgentVersion$input,string$reason):AgentVersion{$authorized=$this->auth->authorize($actor);$reason=$this->input->reason($reason);$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids,$reason){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$cv,$version]=$this->lockChain($ids);$this->assertOpen($agent,$contract);if($version->status!==AgentVersionStatus::Published)throw new InvalidAgentTransitionException('Only a published version can be retired.');$version->markRetired($authorized);if($agent->current_published_version_id===$version->id)$agent->pauseAndClearPublishedVersion($authorized);$this->audit->agentVersionRetired($authorized,$agent,$version,'published',$reason);return$version;},3);}

    public function configurationHash(AgentVersion$v):string{return$this->hasher->hash(['schema_version'=>$v->schema_version,'configuration'=>$v->configuration]);}
    private function parentIds(AgentVersion$v):array{$version=AgentVersion::query()->findOrFail($v->id);$contract=AgentContract::query()->where('agent_id',$version->agent_id)->firstOrFail();return[$version->agent_id,$contract->id,$version->agent_contract_version_id,$version->id];}
    private function lockChain(array$ids):array{[$agentId,$contractId,$cvId,$versionId]=$ids;$agent=Agent::query()->lockForUpdate()->findOrFail($agentId);$contract=AgentContract::query()->where('agent_id',$agent->id)->lockForUpdate()->findOrFail($contractId);$cv=$cvId?AgentContractVersion::query()->where('agent_contract_id',$contract->id)->lockForUpdate()->find($cvId):null;if($cvId&& !$cv)throw new InconsistentAgentPublicationException('Contract version belongs to another agent.');$version=AgentVersion::query()->where('agent_id',$agent->id)->lockForUpdate()->findOrFail($versionId);if($version->agent_contract_version_id!==$cv?->id)throw new InconsistentAgentPublicationException('Agent version contract relationship changed while locking.');return[$agent,$contract,$cv,$version];}
    private function lockParents(array$ids):array{[$agentId,$contractId,$cvId]=$ids;$agent=Agent::query()->lockForUpdate()->findOrFail($agentId);$contract=AgentContract::query()->where('agent_id',$agent->id)->lockForUpdate()->findOrFail($contractId);$cv=$cvId?AgentContractVersion::query()->where('agent_contract_id',$contract->id)->lockForUpdate()->find($cvId):null;if($cvId&&!$cv)throw new InconsistentAgentPublicationException('Contract version belongs to another agent.');return[$agent,$contract,$cv];}
    private function assertOpen(Agent$a,AgentContract$c):void{if($a->status===AgentStatus::Retired||$c->status===AgentContractStatus::Ended)throw new InvalidAgentTransitionException('Terminal aggregate cannot transition agent versions.');}
    private function expect(AgentVersion$v,AgentVersionStatus$s):void{if($v->status!==$s)throw new InvalidAgentTransitionException("Agent version cannot transition from {$v->status->value}.");}
}
