<?php

namespace App\Domain\AI\Agents\Services;

use App\Domain\AI\Agents\Data\AuthorizedAiLifecycleActor;
use App\Domain\AI\Agents\Enums\{AgentContractStatus,AgentContractVersionStatus,AgentLifecycleEventType,AgentStatus};
use App\Domain\AI\Agents\Exceptions\{InvalidAgentTransitionException,StaleAiContentHashException};
use App\Domain\AI\Agents\Models\{Agent,AgentContract,AgentContractVersion};
use App\Domain\AI\Agents\Support\AiLifecycleInputGuard;
use App\Domain\AI\Support\CanonicalJsonHasher;
use App\Models\User;
use Illuminate\Support\Facades\DB;

final class AgentContractVersionLifecycleService
{
    public function __construct(private AiLifecycleAuthorization$auth,private CanonicalJsonHasher$hasher,private AiLifecycleInputGuard$input,private AgentLifecycleAudit$audit){}

    public function offer(User$actor,AgentContractVersion$input):AgentContractVersion{$authorized=$this->auth->authorize($actor);$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$version]=$this->lockChain($ids);$this->assertOpen($agent,$contract);$this->expect($version,AgentContractVersionStatus::Draft);$hash=$this->contractHash($version);$version->markOffered($authorized,$hash);$this->audit->contractVersionOffered($authorized,$agent,$version);return$version;},3);}

    public function accept(User$actor,AgentContractVersion$input,string$expectedContentHash,array$evidence):AgentContractVersion{$authorized=$this->auth->authorize($actor);$evidence=$this->input->evidence($evidence);if($evidence===[])throw new \InvalidArgumentException('Acceptance evidence is required.');$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids,$expectedContentHash,$evidence){$authorized=$this->auth->revalidate($authorized);[$agent,$contract]=$this->lockParents($ids);$candidateIds=AgentContractVersion::query()->where('agent_contract_id',$contract->id)->where(function($q)use($ids){$q->whereKey($ids[2])->orWhere('status',AgentContractVersionStatus::Accepted->value);})->pluck('id')->unique()->sort()->values();$locked=AgentContractVersion::query()->whereIn('id',$candidateIds)->orderBy('id')->lockForUpdate()->get()->keyBy('id');$version=$locked->get($ids[2])??throw new \RuntimeException('Target contract version disappeared while locking.');$this->assertOpen($agent,$contract);$this->expect($version,AgentContractVersionStatus::Offered);$hash=$this->contractHash($version);if(!hash_equals((string)$version->content_hash,$hash)||!hash_equals($hash,$expectedContentHash))throw new StaleAiContentHashException('Contract content hash is stale.');$previous=$locked->first(fn($item)=>$item->id!==$version->id&&$item->status===AgentContractVersionStatus::Accepted);$mustPause=$agent->status===AgentStatus::Active&&$agent->currentPublishedVersion&&$agent->currentPublishedVersion->agent_contract_version_id!==$version->id;if($previous)$previous->markSuperseded($authorized,'Superseded by accepted contract version '.$version->version_number);$version->markAccepted($authorized,$hash,$evidence);$contract->activateWithAcceptedVersion($authorized,$version);if($mustPause)$agent->pauseLifecycle($authorized);$this->audit->contractVersionAccepted($authorized,$agent,$version);if($mustPause)$this->audit->agentPaused($authorized,$agent,'Accepted contract changed current operating terms.');return$version;},3);}

    public function reject(User$actor,AgentContractVersion$input,string$reason):AgentContractVersion{return$this->terminal($actor,$input,AgentContractVersionStatus::Rejected,AgentLifecycleEventType::ContractVersionRejected,$reason);}
    public function withdraw(User$actor,AgentContractVersion$input,string$reason):AgentContractVersion{return$this->terminal($actor,$input,AgentContractVersionStatus::Withdrawn,AgentLifecycleEventType::ContractVersionWithdrawn,$reason);}

    private function terminal(User$actor,AgentContractVersion$input,AgentContractVersionStatus$status,AgentLifecycleEventType$event,string$reason):AgentContractVersion{$authorized=$this->auth->authorize($actor);$reason=$this->input->reason($reason);$ids=$this->parentIds($input);return DB::transaction(function()use($authorized,$ids,$status,$event,$reason){$authorized=$this->auth->revalidate($authorized);[$agent,$contract,$version]=$this->lockChain($ids);$this->assertOpen($agent,$contract);$this->expect($version,AgentContractVersionStatus::Offered);if($status===AgentContractVersionStatus::Rejected){$version->markRejected($authorized,$reason);$this->audit->contractVersionRejected($authorized,$agent,$version,$reason);}else{$version->markWithdrawn($authorized,$reason);$this->audit->contractVersionWithdrawn($authorized,$agent,$version,$reason);}return$version;},3);}
    private function parentIds(AgentContractVersion$v):array{$version=AgentContractVersion::query()->findOrFail($v->id);$contract=AgentContract::query()->findOrFail($version->agent_contract_id);return[$contract->agent_id,$contract->id,$version->id];}
    private function lockChain(array$ids):array{[$agentId,$contractId,$versionId]=$ids;$agent=Agent::query()->lockForUpdate()->findOrFail($agentId);$contract=AgentContract::query()->where('agent_id',$agent->id)->lockForUpdate()->findOrFail($contractId);$version=AgentContractVersion::query()->where('agent_contract_id',$contract->id)->lockForUpdate()->findOrFail($versionId);return[$agent,$contract,$version];}
    private function lockParents(array$ids):array{[$agentId,$contractId]=$ids;$agent=Agent::query()->lockForUpdate()->findOrFail($agentId);$contract=AgentContract::query()->where('agent_id',$agent->id)->lockForUpdate()->findOrFail($contractId);return[$agent,$contract];}
    private function assertOpen(Agent$a,AgentContract$c):void{if($a->status===AgentStatus::Retired||$c->status===AgentContractStatus::Ended)throw new InvalidAgentTransitionException('Terminal aggregate cannot transition contract versions.');}
    private function expect(AgentContractVersion$v,AgentContractVersionStatus$s):void{if($v->status!==$s)throw new InvalidAgentTransitionException("Contract version cannot transition from {$v->status->value}.");}
    private function contractHash(AgentContractVersion$v):string{return$this->hasher->hash(['job_to_be_done'=>$v->job_to_be_done,'objectives'=>$v->objectives,'allowed_capabilities'=>$v->allowed_capabilities,'prohibited_capabilities'=>$v->prohibited_capabilities,'channels'=>$v->channels,'knowledge_requirements'=>$v->knowledge_requirements,'allowed_actions'=>$v->allowed_actions,'handoff_policy'=>$v->handoff_policy,'outcome_policy'=>$v->outcome_policy,'capacity_policy'=>$v->capacity_policy,'sla_policy'=>$v->sla_policy,'privacy_policy'=>$v->privacy_policy,'pricing_policy'=>$v->pricing_policy]);}
}
