@extends('tenant.admin.layout')
@section('title','Configuración')
@section('content')
<nav class="z-breadcrumbs" aria-label="Ruta"><span>Configuración</span></nav>
<header class="z-page-header"><div><div class="z-eyebrow">Tenant Admin</div><h1>Configuración</h1><p class="z-muted">Administra la identidad de tu portal y cómo se completan las entregas.</p></div></header>
<div class="z-grid">
<a class="z-card z-card--interactive" href="{{ route('tenant.admin.delivery-proof-options.index') }}"><span class="z-badge z-badge--success">Operativa</span><h2>Entregas y evidencia</h2><p class="z-muted">Define quién puede recibir, evidencia requerida e intentos permitidos.</p><strong>Administrar entregas →</strong></a>
<a class="z-card z-card--interactive" href="{{ route('tenant.admin.payments.index') }}"><span class="z-badge z-badge--info">Checkout</span><h2>Pagos</h2><p class="z-muted">Conecta la cuenta seller de Mercado Pago del tenant.</p><strong>Administrar pagos →</strong></a>
<section class="z-card"><span class="z-badge {{ $domain ? 'z-badge--success' : 'z-badge--warning' }}">{{ $domain ? 'Dominio verificado' : 'Pendiente' }}</span><h2>Portal y dominio</h2>@if($domain)<span class="z-sr-only">{{ strtoupper($domain->environment) }} {{ strtoupper($domain->status) }}</span><p><strong>{{ $domain->domain }}</strong><br><span class="z-muted">{{ $domain->environment === 'production' ? 'Producción' : ucfirst($domain->environment) }} · {{ $domain->status === 'verified' ? 'Verificado' : ucfirst($domain->status) }}</span></p>@else<p class="z-muted">No existe un dominio principal configurado.</p>@endif @if($previewUrl)<a class="z-btn z-btn--outline" href="{{ $previewUrl }}" target="_blank" rel="noopener noreferrer">Vista previa del portal</a>@endif<p class="z-help">Los dominios personalizados, SSL y activación se administran desde ZIGO Network.</p></section>
</div>
<section class="z-card z-form-section" style="margin-top:1rem"><div class="z-form-section__head"><div class="z-eyebrow">White label</div><h2>Identidad y soporte</h2><p class="z-muted">Estos valores alimentan tokens dinámicos; no se genera CSS independiente por tenant.</p></div>
@if($canEdit)<form class="z-stack" method="POST" enctype="multipart/form-data" action="{{ route('tenant.admin.configuration.update') }}">@csrf @method('PATCH')
<div class="z-form-grid"><label class="z-field"><span>Nombre comercial</span><input name="brand_name" value="{{ old('brand_name',$branding?->brand_name) }}" aria-describedby="brand-help">@error('brand_name')<span class="z-field-error">{{ $message }}</span>@enderror<span class="z-help" id="brand-help">Nombre visible para tus clientes.</span></label><label class="z-field"><span>Email de soporte</span><input type="email" name="support_email" value="{{ old('support_email',$branding?->support_email) }}">@error('support_email')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Teléfono de soporte</span><input name="support_phone" value="{{ old('support_phone',$branding?->support_phone) }}">@error('support_phone')<span class="z-field-error">{{ $message }}</span>@enderror</label></div>
<fieldset class="z-card"><legend><strong>Paleta de marca</strong></legend><p class="z-help">Usa colores hexadecimales de seis dígitos y verifica contraste antes de publicar.</p><div class="z-form-grid z-form-grid--3"><label class="z-field"><span>Primario</span><input name="primary_color" placeholder="#1769E0" value="{{ old('primary_color',$branding?->primary_color) }}">@error('primary_color')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Secundario</span><input name="secondary_color" placeholder="#0B2445" value="{{ old('secondary_color',$branding?->secondary_color) }}">@error('secondary_color')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Acento</span><input name="accent_color" placeholder="#168CFF" value="{{ old('accent_color',$branding?->accent_color) }}">@error('accent_color')<span class="z-field-error">{{ $message }}</span>@enderror</label></div></fieldset>
<div class="z-form-grid"><label class="z-field"><span>Logo</span><input class="z-file" type="file" name="logo" accept="image/png,image/jpeg,image/webp"><span class="z-help">PNG, JPG o WEBP. Máximo 2 MB.</span>@error('logo')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Imagen principal de la landing</span><input class="z-file" type="file" name="hero_image" accept="image/png,image/jpeg,image/webp"><span class="z-help">Imagen horizontal JPG, PNG o WEBP. Máximo 4 MB.</span>@error('hero_image')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Favicon</span><input class="z-file" type="file" name="favicon" accept="image/png,image/jpeg,image/webp"><span class="z-help">PNG, JPG o WEBP. Máximo 512 KB.</span>@error('favicon')<span class="z-field-error">{{ $message }}</span>@enderror</label></div>
<div class="z-form-actions"><button class="z-btn">Guardar configuración</button></div></form>@else<div class="z-alert" role="note">Sólo owners y admins activos pueden modificar esta configuración.</div>@endif</section>
@endsection
