@extends('tenant.admin.layout')
@php($hasLogo=$branding?->logo_path && Storage::disk('public')->exists($branding->logo_path))
@php($hasHero=$branding?->hero_image_path && Storage::disk('public')->exists($branding->hero_image_path))
@php($hasStoredFavicon=is_string($branding?->favicon_path) && Storage::disk('public')->exists($branding->favicon_path))
@php($hasFavicon=\App\Support\Presentation\TenantFavicon::isValid($tenant,$branding?->favicon_path))
@php($logoPreviewUrl=\App\Support\Presentation\TenantBrandingAsset::url($tenant,'logo',$branding?->logo_path))
@php($heroPreviewUrl=\App\Support\Presentation\TenantBrandingAsset::url($tenant,'hero',$branding?->hero_image_path))
@php($faviconPreviewUrl=\App\Support\Presentation\TenantBrandingAsset::url($tenant,'favicon',$branding?->favicon_path))
@section('title','Configuración')
@section('content')
<nav class="z-breadcrumbs" aria-label="Ruta"><span>Configuración</span></nav>
<header class="z-page-header"><div><div class="z-eyebrow">Tenant Admin</div><h1>Configuración</h1><p class="z-muted">Administra la identidad de tu portal y cómo se completan las entregas.</p></div></header>
<div class="z-grid">
<a class="z-card z-card--interactive" href="{{ route('tenant.admin.delivery-proof-options.index') }}"><span class="z-badge z-badge--success">Operativa</span><h2>Entregas y evidencia</h2><p class="z-muted">Define quién puede recibir, evidencia requerida e intentos permitidos.</p><strong>Administrar entregas →</strong></a>
<a class="z-card z-card--interactive" href="{{ route('tenant.admin.payments.index') }}"><span class="z-badge z-badge--info">Checkout</span><h2>Pagos</h2><p class="z-muted">Conecta la cuenta seller de Mercado Pago del tenant.</p><strong>Administrar pagos →</strong></a>
<section class="z-card"><span class="z-badge {{ $domain ? 'z-badge--success' : 'z-badge--warning' }}">{{ $domain ? 'Dominio verificado' : 'Pendiente' }}</span><h2>Portal y dominio</h2>@if($domain)<span class="z-sr-only">{{ strtoupper($domain->environment) }} {{ strtoupper($domain->status) }}</span><p><strong>{{ $domain->domain }}</strong><br><span class="z-muted">{{ $domain->environment === 'production' ? 'Producción' : ucfirst($domain->environment) }} · {{ $domain->status === 'verified' ? 'Verificado' : ucfirst($domain->status) }}</span></p>@else<p class="z-muted">No existe un dominio principal configurado.</p>@endif @if($previewUrl)<a class="z-btn z-btn--outline" href="{{ $previewUrl }}" target="_blank" rel="noopener noreferrer">Vista previa del portal</a>@endif<p class="z-help">Los dominios personalizados, SSL y activación se administran desde ZIGO Network.</p></section>
</div>
<section class="z-card z-form-section" style="margin-top:1rem"><div class="z-form-section__head"><div class="z-eyebrow">White label</div><h2>Identidad y soporte</h2><p class="z-muted">Estos valores alimentan tokens dinámicos; no se genera CSS independiente por tenant.</p></div>
@if($canEdit)<form class="z-stack" method="POST" enctype="multipart/form-data" action="{{ route('tenant.admin.configuration.update') }}">@csrf @method('PATCH')
<div class="z-form-grid"><label class="z-field"><span>Nombre comercial</span><input name="brand_name" value="{{ old('brand_name',$branding?->brand_name) }}" aria-describedby="brand-help">@error('brand_name')<span class="z-field-error">{{ $message }}</span>@enderror<span class="z-help" id="brand-help">Nombre visible para tus clientes.</span></label><label class="z-field"><span>Slogan <span class="z-muted">(opcional)</span></span><input name="tagline" maxlength="120" value="{{ old('tagline',$branding?->tagline) }}">@error('tagline')<span class="z-field-error">{{ $message }}</span>@enderror<span class="z-help">Texto plano, máximo 120 caracteres. Si queda vacío no se muestra.</span></label><label class="z-field"><span>Email de soporte</span><input type="email" name="support_email" value="{{ old('support_email',$branding?->support_email) }}">@error('support_email')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Teléfono de soporte</span><input name="support_phone" value="{{ old('support_phone',$branding?->support_phone) }}">@error('support_phone')<span class="z-field-error">{{ $message }}</span>@enderror</label></div>
<fieldset class="z-card"><legend><strong>Paleta de marca</strong></legend><p class="z-help">Usa colores hexadecimales de seis dígitos y verifica contraste antes de publicar.</p><div class="z-form-grid z-form-grid--3"><label class="z-field"><span>Primario</span><input name="primary_color" placeholder="#1769E0" value="{{ old('primary_color',$branding?->primary_color) }}">@error('primary_color')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Secundario</span><input name="secondary_color" placeholder="#0B2445" value="{{ old('secondary_color',$branding?->secondary_color) }}">@error('secondary_color')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field"><span>Acento</span><input name="accent_color" placeholder="#168CFF" value="{{ old('accent_color',$branding?->accent_color) }}">@error('accent_color')<span class="z-field-error">{{ $message }}</span>@enderror</label></div></fieldset>
<div class="z-form-grid">
<label class="z-field"><span>{{ $hasLogo ? 'Cambiar logo' : 'Logo' }}</span>@if($logoPreviewUrl)<img src="{{ $logoPreviewUrl }}" alt="Logo actual" style="max-width:160px;max-height:52px;object-fit:contain;align-self:flex-start">@endif<input class="z-file" type="file" name="logo" accept="image/png,image/jpeg,image/webp"><span class="z-help">PNG, JPG o WEBP. Máximo 2 MB.</span>@error('logo')<span class="z-field-error">{{ $message }}</span>@enderror</label>
<label class="z-field"><span>{{ $hasHero ? 'Cambiar imagen principal de la landing' : 'Imagen principal de la landing' }}</span>@if($heroPreviewUrl)<img src="{{ $heroPreviewUrl }}" alt="Imagen principal actual" style="width:100%;max-width:320px;aspect-ratio:16/9;object-fit:cover;border-radius:12px">@endif<input class="z-file" type="file" name="hero_image" accept="image/png,image/jpeg,image/webp"><span class="z-help"><strong>Recomendado: 1600 × 900 px.</strong><br>JPG, PNG o WEBP. Máximo 4 MB.</span>@error('hero_image')<span class="z-field-error">{{ $message }}</span>@enderror</label>
<label class="z-field"><span>{{ $hasStoredFavicon ? 'Cambiar favicon' : 'Favicon' }}</span>@if($faviconPreviewUrl)<img src="{{ $faviconPreviewUrl }}" alt="Favicon actual" width="48" height="48" style="width:48px;height:48px;object-fit:contain;align-self:flex-start;border:1px solid var(--z-border);border-radius:8px;padding:4px">@elseif($hasStoredFavicon)<span class="z-alert z-alert--warning" role="status">El favicon configurado anteriormente no cumple el formato actual. Carga una imagen cuadrada de hasta 512 × 512 px.</span>@endif<input class="z-file" type="file" name="favicon" accept="image/png,image/jpeg,image/webp"><span class="z-help">PNG, JPG o WEBP cuadrado. Máximo 512 × 512 px y 512 KB.</span>@error('favicon')<span class="z-field-error">{{ $message }}</span>@enderror</label>
</div>
@php($configuredCards=old('landing_cards',$branding?->landing_cards ?? [['title'=>'Cotización clara','description'=>'Consulta opciones y precios disponibles según los datos de tu envío.','action'=>'QUOTE'],['title'=>'Perfil personal','description'=>'Consulta tus envíos, guías y seguimiento desde tu cuenta.','action'=>'REGISTER'],['title'=>'Seguimiento','description'=>'Consulta el estado de una guía desde la superficie pública del tenant.','action'=>'TRACKING']]))
<fieldset class="z-card"><legend><strong>Tarjetas de la landing</strong></legend><p class="z-help">Configura exactamente tres tarjetas. Las acciones sólo pueden dirigir a superficies existentes del tenant.</p><div class="z-grid">@foreach($configuredCards as $index=>$card)<section class="z-stack"><strong>Tarjeta {{ $index+1 }}</strong><label class="z-field"><span>Título</span><input name="landing_cards[{{ $index }}][title]" maxlength="80" value="{{ $card['title']??'' }}" required></label><label class="z-field"><span>Descripción</span><textarea name="landing_cards[{{ $index }}][description]" maxlength="240" required>{{ $card['description']??'' }}</textarea></label><label class="z-field"><span>Acción</span><select name="landing_cards[{{ $index }}][action]" required>@foreach(['QUOTE'=>'Cotizar','REGISTER'=>'Registro','TRACKING'=>'Rastreo','NONE'=>'Sin enlace'] as $value=>$label)<option value="{{ $value }}" @selected(($card['action']??'NONE')===$value)>{{ $label }}</option>@endforeach</select></label></section>@endforeach</div>@error('landing_cards')<span class="z-field-error">{{ $message }}</span>@enderror @error('landing_cards.*.action')<span class="z-field-error">{{ $message }}</span>@enderror</fieldset>
<div class="z-form-actions"><button class="z-btn">Guardar configuración</button></div></form>@else<div class="z-alert" role="note">Sólo owners y admins activos pueden modificar esta configuración.</div>@endif</section>
@endsection
