@extends('tenant.admin.layout')
@section('title','Dashboard')
@section('content')
<div class="eyebrow">TENANT ADMIN</div><h1>{{ $tenant->branding?->brand_name??$tenant->name }}</h1>
<section class="grid"><article class="card metric"><small>PLAN</small><strong>{{ $plan?->name??'Sin plan' }}</strong></article><article class="card metric"><small>SUSCRIPCIÓN</small><strong>{{ strtoupper($subscription?->status??'TRANSICIÓN') }}</strong></article><article class="card metric"><small>OPERACIONES USADAS</small><strong>{{ $usageSummary['used']??'N/A' }}</strong></article><article class="card metric"><small>DISPONIBLES</small><strong>{{ $usageSummary['remaining']??'N/A' }}</strong></article></section>
@if($usesFallback)<p class="notice">Configuración transitoria desde current_plan_id; snapshot de Entitlements pendiente.</p>@endif
<h2>Servicios contratados</h2><div class="chips">@forelse($modules as $module)<span class="chip">{{ $module->name }}</span>@empty<span class="muted">Sin servicios activos.</span>@endforelse</div>
@php($codes=$modules->pluck('code'))<h2>Operación</h2><section class="grid">@if($codes->contains('B2C')&&$codes->contains('SHIPPING'))<a class="card" href="{{ route('tenant.b2c.quote.create') }}"><strong>Cotizaciones</strong><p class="muted">Crear una cotización logística.</p></a><a class="card" href="{{ route('tenant.admin.operations.index') }}"><strong>Operaciones</strong><p class="muted">Consultar operaciones del tenant.</p></a>@endif @if($codes->contains('TRACKING'))<a class="card" href="{{ route('tenant.b2c.tracking') }}"><strong>Tracking</strong><p class="muted">Entrada tenant-aware controlada.</p></a>@endif @if($codes->contains('CRM'))<article class="card"><strong>CRM</strong><p class="muted">Integración tenant-aware pendiente.</p></article>@endif</section>
@endsection
