@extends('tenant.admin.layout')
@section('title','Dashboard')
@section('content')
<div class="eyebrow">TENANT ADMIN</div><h1>{{ $tenant->branding?->brand_name??$tenant->name }}</h1>
@if($workspace===\App\Domain\Network\ProductShell\TenantWorkspace::ZigoAi)
<p class="muted">Workspace Agentes IA de {{ $tenant->name }}</p><section class="grid"><article class="card metric"><small>AGENTES CREADOS</small><strong>{{ $agentSummary['total'] }}</strong></article><article class="card metric"><small>AGENTES EN BORRADOR</small><strong>{{ $agentSummary['drafts'] }}</strong></article><article class="card metric"><small>PRÓXIMA ETAPA</small><strong>Configurar conocimiento</strong></article><article class="card metric"><small>CANALES</small><strong>Configura tus canales</strong></article></section>@if(in_array($membership?->role??null,['owner','admin'],true))<section class="grid"><a class="card" href="{{ route('tenant.admin.ai-agents.index') }}"><strong>Mis agentes</strong><p class="muted">Revisa los agentes existentes.</p></a><a class="card" href="{{ route('tenant.admin.ai-agents.launchpad.create') }}"><strong>Crear agente</strong><p class="muted">Prepara una nueva propuesta configurable.</p></a></section>@endif
@else
<section class="grid"><article class="card metric"><small>PLAN</small><strong>{{ $plan?->name??'Sin plan' }}</strong></article><article class="card metric"><small>SUSCRIPCIÓN</small><strong>{{ strtoupper($subscription?->status??'TRANSICIÓN') }}</strong></article><article class="card metric"><small>OPERACIONES USADAS</small><strong>{{ $usageSummary['used']??'N/A' }}</strong></article><article class="card metric"><small>DISPONIBLES</small><strong>{{ $usageSummary['remaining']??'N/A' }}</strong></article></section>
@if($usesFallback)<p class="notice">Configuración transitoria desde current_plan_id; snapshot de Entitlements pendiente.</p>@endif
<h2>Servicios contratados</h2><div class="chips">@forelse($modules as $module)<span class="chip">{{ $module->name }}</span>@empty<span class="muted">Sin servicios activos.</span>@endforelse</div>
@php($codes=$modules->pluck('code'))<h2>Operación</h2><section class="grid">@if($codes->contains('B2C')&&$codes->contains('SHIPPING'))<a class="card" href="{{ route('tenant.b2c.quote.create') }}"><strong>Cotizaciones</strong><p class="muted">Crear una cotización logística.</p></a><a class="card" href="{{ route('tenant.admin.operations.index') }}"><strong>Operaciones</strong><p class="muted">Consultar operaciones del tenant.</p></a>@endif @if($codes->contains('TRACKING'))<a class="card" href="{{ route('tenant.b2c.tracking') }}"><strong>Tracking</strong><p class="muted">Entrada tenant-aware controlada.</p></a>@endif @if($codes->contains('CRM'))<article class="card"><strong>CRM</strong><p class="muted">Integración tenant-aware pendiente.</p></article>@endif</section>
@if($codes->contains('AI_CORE')&&in_array($membership?->role??null,['owner','admin'],true))<h2>IA para tu negocio</h2><section class="grid"><a class="card" href="{{ route('tenant.admin.ai-agents.launchpad.create') }}"><strong>Agentes IA</strong><p class="muted">Crea un agente para ventas, atención, citas, cotizaciones u operaciones.</p><span class="z-btn z-btn--primary">Configurar agente</span></a></section>@endif
@endif
@if($aiCapacity)<h2>Agentes IA</h2><section class="grid"><article class="card"><h3>Plan / capacidad actual</h3><p>Agentes: {{ $aiCapacity['MAX_AGENTS']->used }} de {{ $aiCapacity['MAX_AGENTS']->limit }}</p><p>Webchat: {{ $aiCapacity['MAX_WEBCHAT_CHANNELS']->used }} de {{ $aiCapacity['MAX_WEBCHAT_CHANNELS']->limit }}</p><p>WhatsApp: {{ $aiCapacity['MAX_WHATSAPP_CHANNELS']->used }} de {{ $aiCapacity['MAX_WHATSAPP_CHANNELS']->limit }}</p>@if($aiCapacity['MAX_AGENTS']->reached()||$aiCapacity['MAX_WEBCHAT_CHANNELS']->reached()||$aiCapacity['MAX_WHATSAPP_CHANNELS']->reached())<p><strong>Límite alcanzado</strong></p>@endif<a class="btn" href="{{ route('tenant.admin.marketplace') }}#ai-addons">Ampliar capacidad</a></article><article class="card"><h3>Uso del período</h3><p>Runtime: {{ $aiCapacity['MONTHLY_RUNTIME_UNITS']->used }} de {{ $aiCapacity['MONTHLY_RUNTIME_UNITS']->limit }}</p><p>Conversaciones: {{ $aiCapacity['MONTHLY_CONVERSATIONS']->used }} de {{ $aiCapacity['MONTHLY_CONVERSATIONS']->limit }}</p><p>Actions: {{ $aiCapacity['MONTHLY_ACTION_RUNS']->used }} de {{ $aiCapacity['MONTHLY_ACTION_RUNS']->limit }}</p></article></section>@endif
@endsection
