@extends('tenant.admin.layout')
@section('title','Opciones de entrega')
@section('content')
@php($policyLabels=['ANY_PERSON_AT_ADDRESS'=>'Cualquier persona en el domicilio','RECIPIENT_ONLY'=>'Sólo la persona destinataria','AUTHORIZED_PERSON'=>'Persona autorizada','ADULT_AT_ADDRESS'=>'Persona adulta en el domicilio'])
<nav class="z-breadcrumbs" aria-label="Ruta"><a href="{{ route('tenant.admin.configuration.edit') }}">Configuración</a><span aria-hidden="true">/</span><span>Evidencia de entrega</span></nav>
<header class="z-page-header"><div><div class="z-eyebrow">Configuración · Entregas</div><h1>Evidencia de entrega</h1><p class="z-muted">Crea opciones claras para el equipo operativo y conserva la evidencia necesaria.</p></div>@if($canManage)<a class="z-btn" href="#new-delivery-option">Nueva opción</a>@endif</header>
<div class="z-alert" role="note"><strong>Historial protegido.</strong> Cada envío conserva una copia inmutable de sus requisitos. Una opción que ya fue utilizada se desactiva, no se elimina.</div>
<div class="z-stack" style="margin-top:1rem">@forelse($options as $option)<section class="z-card z-form-section"><div class="z-page-header"><div><div class="z-eyebrow">{{ $option->code }}</div><h2>{{ $option->name }}</h2><p class="z-muted">{{ $option->description ?: 'Sin descripción.' }}</p></div><div class="z-cluster"><span class="z-badge {{ $option->is_active?'z-badge--success':'z-badge--muted' }}">{{ $option->is_active?'Activa':'Inactiva' }}</span>@if($option->is_default)<span class="z-badge">Predeterminada</span>@endif</div></div>
<form class="z-stack" method="POST" action="{{ route('tenant.admin.delivery-proof-options.update',$option->uuid) }}">@csrf @method('PUT')
<div class="z-form-grid"><label class="z-field"><span>Nombre visible</span><input name="name" value="{{ $option->name }}" @disabled(!$canManage)></label><label class="z-field"><span>Código interno</span><input name="code" value="{{ $option->code }}" @disabled(!$canManage)><span class="z-help">Identificador técnico; no se muestra al cliente.</span></label><label class="z-field"><span>Descripción para el equipo</span><input name="description" value="{{ $option->description }}" @disabled(!$canManage)></label><label class="z-field"><span>¿Quién puede recibir?</span><select name="receiver_policy" @disabled(!$canManage)>@foreach(\App\Domain\Shipping\LastMile\Models\TenantDeliveryProofOption::RECEIVER_POLICIES as $policy)<option value="{{ $policy }}" @selected($option->receiver_policy===$policy)>{{ $policyLabels[$policy]??ucfirst(strtolower(str_replace('_',' ',$policy))) }}</option>@endforeach</select></label></div>
<fieldset><legend><strong>Evidencia requerida</strong></legend><p class="z-help">Selecciona únicamente lo necesario para completar esta modalidad.</p><div class="z-grid">@foreach(['require_receiver_name'=>'Nombre de quien recibe','require_receiver_type'=>'Relación con destinatario','require_signature'=>'Firma','require_photo'=>'Fotografía','require_gps'=>'Ubicación GPS'] as $field=>$label)<label class="z-choice"><input type="checkbox" name="{{ $field }}" value="1" @checked($option->$field) @disabled(!$canManage)><span>{{ $label }}</span></label>@endforeach</div></fieldset>
<div class="z-form-grid z-form-grid--3"><label class="z-field"><span>Máximo de intentos</span><input type="number" min="1" max="10" name="max_delivery_attempts" value="{{ $option->max_delivery_attempts }}" @disabled(!$canManage)></label><label class="z-field"><span>Recargo</span><input type="number" min="0" step=".01" name="surcharge_amount" value="{{ $option->surcharge_amount }}" @disabled(!$canManage)></label><label class="z-field"><span>Moneda</span><input name="currency" value="{{ $option->currency }}" maxlength="3" @disabled(!$canManage)></label><label class="z-field"><span>Orden de aparición</span><input type="number" min="0" name="sort_order" value="{{ $option->sort_order }}" @disabled(!$canManage)></label></div>
<div class="z-cluster"><label class="z-choice"><input type="checkbox" name="is_active" value="1" @checked($option->is_active) @disabled(!$canManage)><span>Opción activa</span></label><label class="z-choice"><input type="checkbox" name="is_default" value="1" @checked($option->is_default) @disabled(!$canManage)><span>Usar como predeterminada</span></label></div>@if($canManage)<div class="z-form-actions"><button class="z-btn">Guardar opción</button></div>@endif</form></section>@empty<div class="z-empty"><div class="z-empty__icon" aria-hidden="true">＋</div><h2>Aún no hay opciones</h2><p class="z-muted">Crea la primera modalidad de evidencia de entrega.</p></div>@endforelse</div>
@if($canManage)<section class="z-card z-form-section" id="new-delivery-option" style="margin-top:1rem"><div class="z-form-section__head"><div class="z-eyebrow">Nueva modalidad</div><h2>Crear opción de entrega</h2><p class="z-muted">Podrás ajustar sus requisitos antes de utilizarla en una operación.</p></div><form class="z-stack" method="POST" action="{{ route('tenant.admin.delivery-proof-options.store') }}">@csrf
<div class="z-form-grid"><label class="z-field"><span>Nombre visible</span><input name="name" required></label><label class="z-field"><span>Código interno</span><input name="code" required></label><label class="z-field"><span>Descripción</span><input name="description"></label><label class="z-field"><span>¿Quién puede recibir?</span><select name="receiver_policy">@foreach(\App\Domain\Shipping\LastMile\Models\TenantDeliveryProofOption::RECEIVER_POLICIES as $policy)<option value="{{ $policy }}">{{ $policyLabels[$policy]??ucfirst(strtolower(str_replace('_',' ',$policy))) }}</option>@endforeach</select></label></div>
<fieldset><legend><strong>Evidencia requerida</strong></legend><div class="z-grid">@foreach(['require_receiver_name'=>'Nombre de quien recibe','require_receiver_type'=>'Relación con destinatario','require_signature'=>'Firma','require_photo'=>'Fotografía','require_gps'=>'Ubicación GPS'] as $field=>$label)<label class="z-choice"><input type="checkbox" name="{{ $field }}" value="1" @checked($field==='require_receiver_name')><span>{{ $label }}</span></label>@endforeach</div></fieldset>
<div class="z-form-grid z-form-grid--3"><label class="z-field"><span>Máximo de intentos</span><input type="number" name="max_delivery_attempts" min="1" max="10" value="2" required></label><label class="z-field"><span>Recargo</span><input type="number" name="surcharge_amount" min="0" step=".01" value="0"></label><label class="z-field"><span>Moneda</span><input name="currency" value="MXN" maxlength="3" required></label><label class="z-field"><span>Orden</span><input type="number" name="sort_order" min="0" value="0" required></label></div><div class="z-cluster"><label class="z-choice"><input type="checkbox" name="is_active" value="1" checked><span>Opción activa</span></label><label class="z-choice"><input type="checkbox" name="is_default" value="1"><span>Usar como predeterminada</span></label></div><div class="z-form-actions"><button class="z-btn">Crear opción</button></div></form></section>@endif
@endsection
