@php($branding=$tenant->branding)
@php($membership=app(\App\Domain\Network\Tenancy\TenantAccessService::class)->membership(auth()->user()))
@php($safeColor=fn($value,$fallback)=>is_string($value)&&preg_match('/^#[0-9A-Fa-f]{6}$/',$value)?$value:$fallback)
@php($logoUrl=\App\Support\Presentation\TenantBrandingAsset::url($tenant,'logo',$branding?->logo_path))
@php($faviconUrl=\App\Support\Presentation\TenantBrandingAsset::url($tenant,'favicon',$branding?->favicon_path) ?? asset('favicon.ico'))
@php($designSystemPath=public_path('css/zigo-design-system.css'))
@php($designSystemVersion=is_file($designSystemPath) ? filemtime($designSystemPath) : '1')
@php($canUseAi=in_array($membership?->role??null,['owner','admin'],true)&&app(\App\Domain\Network\Billing\EntitlementService::class)->has($tenant,'AI_CORE'))
@php($workspace=app(\App\Domain\Network\ProductShell\TenantWorkspaceResolver::class)->resolveForPresentation($tenant))
@php($isAiWorkspace=$workspace===\App\Domain\Network\ProductShell\TenantWorkspace::ZigoAi)
@php($productName=$isAiWorkspace?'Agentes IA':'ZIGO')
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Administración') · {{ $branding?->brand_name??$tenant->name }}</title>
<link rel="icon" href="{{ $faviconUrl }}"><link rel="stylesheet" href="{{ asset('css/zigo-design-system.css') }}?v={{ $designSystemVersion }}"><style>
:root{--tenant-primary:{{ $safeColor($branding?->primary_color,'#1769E0') }};--tenant-secondary:{{ $safeColor($branding?->secondary_color,'#0B2445') }};--tenant-accent:{{ $safeColor($branding?->accent_color,'#168CFF') }}}
.admin-topbar{height:68px;padding:0 1rem;background:var(--z-secondary);color:#fff;display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;z-index:50}.admin-brand{display:flex;align-items:center;gap:.75rem;font-weight:850}.admin-brand img{max-width:130px;max-height:38px;object-fit:contain}.admin-brand small{display:block;color:#c0d0e1;font-size:.65rem;letter-spacing:.08em}.admin-menu-toggle{width:44px;height:44px;border:1px solid #ffffff40;border-radius:10px;background:transparent;color:#fff;font-size:1.2rem}.admin-logout{border:1px solid #ffffff55;border-radius:10px;min-height:44px;padding:.55rem .8rem;background:transparent;color:#fff}.admin-frame{min-height:calc(100vh - 68px)}.admin-nav{background:#fff;border-bottom:1px solid var(--z-border);padding:.5rem;display:flex;gap:.25rem;overflow-x:auto}.admin-nav__group{display:contents}.admin-nav__label{display:none}.admin-nav a{min-height:44px;padding:.65rem .8rem;border-radius:9px;color:#44536a;text-decoration:none;font-weight:700;font-size:.82rem;white-space:nowrap;display:flex;align-items:center}.admin-nav a:hover,.admin-nav a.active{color:var(--z-primary);background:#eef5ff}.admin-content{width:min(100%,1280px);padding:1.25rem 1rem;margin:auto}.admin-content>.card{margin-bottom:1rem}.admin-content h1{font-size:clamp(1.7rem,4vw,2.25rem)}.admin-content h2{line-height:1.25}.admin-content .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,210px),1fr));gap:1rem}.admin-content .metric small{display:block;color:var(--z-muted);font-weight:800;font-size:.7rem;letter-spacing:.08em}.admin-content .metric strong{display:block;font-size:1.35rem;margin-top:.4rem}.admin-content .chips{display:flex;gap:.5rem;flex-wrap:wrap}.admin-content .card+.card{margin-top:1rem}
@media(min-width:900px){.admin-menu-toggle{display:none}.admin-frame{display:grid;grid-template-columns:250px minmax(0,1fr)}.admin-nav{position:sticky;top:68px;height:calc(100vh - 68px);align-self:start;display:block;border-right:1px solid var(--z-border);border-bottom:0;padding:1.25rem .75rem;overflow-y:auto}.admin-nav__group{display:block;margin-bottom:1.1rem}.admin-nav__label{display:block;padding:.35rem .75rem;color:#8895a6;font-size:.65rem;font-weight:850;letter-spacing:.1em;text-transform:uppercase}.admin-nav a{margin:.12rem 0}.admin-content{padding:2rem}}
</style><style>
.admin-topbar{height:64px;background:#fff;color:var(--z-text);border-bottom-color:var(--z-border-subtle)}.admin-brand__avatar{width:36px;height:36px;display:grid;place-items:center;border-radius:10px;background:var(--z-primary);color:#fff}.admin-brand small{color:var(--z-muted)}.admin-menu-toggle,.admin-logout{border-color:var(--z-border);color:var(--z-text);background:#fff}.admin-frame{min-height:calc(100vh - 64px)}.admin-nav{background:var(--z-secondary)}.admin-nav a{color:#cbd7e5;gap:.65rem}.admin-nav a:hover,.admin-nav a.active{color:#fff;background:#ffffff14}.admin-nav a.active{box-shadow:inset 3px 0 var(--z-accent)}.admin-content{width:min(100%,1400px)}
@media(min-width:900px){.admin-frame{grid-template-columns:240px minmax(0,1fr)}.admin-nav{top:64px;height:calc(100vh - 64px);border-right-color:#ffffff12}.admin-nav__label{color:#8295aa}}
</style>@stack('styles')</head><body class="z-app admin-app">
<header class="admin-topbar"><div class="z-cluster"><button class="admin-menu-toggle" type="button" aria-label="Abrir navegación" aria-controls="admin-navigation" aria-expanded="false" onclick="const n=document.getElementById('admin-navigation');n.hidden=!n.hidden;this.setAttribute('aria-expanded',String(!n.hidden))"><x-zigo.icon name="shipments" /></button><div class="admin-brand">@if($logoUrl)<img src="{{ $logoUrl }}" alt="{{ $tenant->name }}">@else<span class="admin-brand__avatar">Z</span>@endif<span>{{ $productName }}<small>{{ $tenant->name }}</small></span></div></div><div class="z-cluster"><a class="z-btn z-btn--ghost" href="{{ route('tenant.admin.support.index') }}"><x-zigo.icon name="help" />Ayuda</a><form method="POST" action="{{ route('tenant.admin.logout') }}">@csrf<button class="admin-logout"><x-zigo.icon name="user" /> Cerrar sesión</button></form></div></header>
<div class="admin-frame"><nav class="admin-nav" id="admin-navigation" aria-label="Navegación de Tenant Admin">
<div class="admin-nav__group"><span class="admin-nav__label">Resumen</span><a class="{{ request()->routeIs('tenant.admin.dashboard')?'active':'' }}" href="{{ route('tenant.admin.dashboard') }}"><x-zigo.icon name="home" />{{ $isAiWorkspace?'Inicio':'Dashboard' }}</a></div>
@if($canUseAi)<div class="admin-nav__group"><span class="admin-nav__label">IA para tu negocio</span><a class="{{ request()->routeIs('tenant.admin.ai-agents.index')||request()->routeIs('tenant.admin.ai-agents.show')?'active':'' }}" href="{{ route('tenant.admin.ai-agents.index') }}">Mis agentes</a><a class="{{ request()->routeIs('tenant.admin.ai-agents.launchpad.*')?'active':'' }}" href="{{ route('tenant.admin.ai-agents.launchpad.create') }}">Crear agente</a><a class="{{ request()->routeIs('tenant.admin.ai-conversations.*')?'active':'' }}" href="{{ route('tenant.admin.ai-conversations.index') }}">Conversaciones</a><a class="{{ request()->routeIs('tenant.admin.ai-handoffs.*')?'active':'' }}" href="{{ route('tenant.admin.ai-handoffs.index') }}">Handoffs</a><a class="{{ request()->routeIs('tenant.admin.ai-leads.*')?'active':'' }}" href="{{ route('tenant.admin.ai-leads.index') }}">Leads</a><a class="{{ request()->routeIs('tenant.admin.ai-knowledge.*')?'active':'' }}" href="{{ route('tenant.admin.ai-knowledge.index') }}">Conocimiento</a></div>@endif
@unless($isAiWorkspace)<div class="admin-nav__group"><span class="admin-nav__label">Operaciones</span><a class="{{ request()->routeIs('tenant.admin.logistics.*')?'active':'' }}" href="{{ route('tenant.admin.logistics.index') }}"><x-zigo.icon name="operation" />Motor logístico</a><a class="{{ request()->routeIs('tenant.admin.operations.*')?'active':'' }}" href="{{ route('tenant.admin.operations.index') }}"><x-zigo.icon name="shipments" />Envíos</a>@if(app(\App\Domain\Network\Billing\EntitlementService::class)->has($tenant,'DRIVER'))<a class="{{ request()->routeIs('tenant.admin.dispatch.*')?'active':'' }}" href="{{ route('tenant.admin.dispatch.pickups') }}"><x-zigo.icon name="truck" />Recolecciones y despacho</a>@endif</div>
@if(app(\App\Domain\Network\Billing\EntitlementService::class)->has($tenant,'DRIVER'))<div class="admin-nav__group"><span class="admin-nav__label">Conductores</span><a class="{{ request()->routeIs('tenant.admin.drivers.*')?'active':'' }}" href="{{ route('tenant.admin.drivers.index') }}">Drivers</a></div>@endif @endunless
@if(in_array($membership?->role??null,['owner','admin'],true))<div class="admin-nav__group"><span class="admin-nav__label">Clientes y usuarios</span><a class="{{ request()->routeIs('tenant.admin.users.*')?'active':'' }}" href="{{ route('tenant.admin.users.index') }}">Usuarios</a></div>@endif
@unless($isAiWorkspace)<div class="admin-nav__group"><span class="admin-nav__label">Integraciones</span><a class="{{ request()->routeIs('tenant.admin.api-hub.*')?'active':'' }}" href="{{ route('tenant.admin.api-hub.index') }}">API Hub</a></div>@endunless<div class="admin-nav__group"><span class="admin-nav__label">Soporte</span><a class="{{ request()->routeIs('tenant.admin.support.*')?'active':'' }}" href="{{ route('tenant.admin.support.index') }}">Centro de soporte</a>@unless($isAiWorkspace)<a href="{{ route('tenant.admin.support.zigo') }}">Soporte ZIGO</a>@endunless</div><div class="admin-nav__group"><span class="admin-nav__label">Cuenta</span><a class="{{ request()->routeIs('tenant.admin.configuration.*')?'active':'' }}" href="{{ route('tenant.admin.configuration.edit') }}">Configuración</a><a class="{{ request()->routeIs('tenant.admin.plan')?'active':'' }}" href="{{ route('tenant.admin.plan') }}">Plan</a><a class="{{ request()->routeIs('tenant.admin.billing.*')?'active':'' }}" href="{{ route('tenant.admin.billing.index') }}">Facturación</a><a class="{{ request()->routeIs('tenant.admin.marketplace*')?'active':'' }}" href="{{ route('tenant.admin.marketplace') }}">Marketplace</a><a class="{{ request()->routeIs('tenant.admin.purchases')?'active':'' }}" href="{{ route('tenant.admin.purchases') }}">Compras</a></div></nav>
<main class="admin-content" id="main-content">@if(session('success'))<div class="z-alert z-alert--success" role="status">{{ session('success') }}</div>@endif @if($errors->any())<div class="z-alert z-alert--danger" role="alert"><strong>Revisa la información.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main></div>
<script>if(matchMedia('(max-width:899px)').matches)document.getElementById('admin-navigation').hidden=true;addEventListener('resize',()=>{if(matchMedia('(min-width:900px)').matches)document.getElementById('admin-navigation').hidden=false})</script></body></html>
