@extends('tenant.admin.layout')
@section('title','Operación logística')
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">OPERACIÓN</div><h1>Motor logístico</h1><p class="z-muted">Configura servicios propios, cobertura contractual por CP, tarifas y paquetes.</p></div></header>
@if(session('success'))<div class="z-alert z-alert--success">{{ session('success') }}</div>@endif @if($errors->any())<div class="z-alert z-alert--danger">{{ $errors->first() }}</div>@endif
<nav class="z-tabs"><a href="#resumen">Resumen</a><a href="#servicios">Servicios</a><a href="#cobertura">Cobertura</a><a href="#tarifas">Tarifas</a><a href="#paquetes">Paquetes</a></nav>
<section id="resumen" class="z-grid customer-section"><article class="z-card"><div class="z-eyebrow">SERVICIOS</div><h2>{{ $services->count() }}</h2></article><article class="z-card"><div class="z-eyebrow">CP EN COBERTURA</div><h2>{{ $coverage->total() }}</h2></article></section>
<section id="servicios" class="customer-section"><h2>Servicios</h2><form method="POST" action="{{ route('tenant.admin.logistics.services.store') }}" class="z-card z-stack">@csrf<div class="z-form-grid"><label class="z-field">Código<input name="code" required></label><label class="z-field">Nombre<input name="name" required></label></div><label class="z-field">Descripción<textarea name="description"></textarea></label><div class="z-form-grid"><label class="z-field">SLA<input name="sla_text"></label><label class="z-field">Modelo tarifario<select name="pricing_strategy"><option value="FLAT">Precio fijo</option><option value="PACKAGE_FLAT">Precio por paquete</option><option value="BASE_PLUS_OVERAGE">Precio base con kilómetros incluidos</option><option value="DISTANCE_TIERS_OVERAGE">Tarifa por rangos de distancia</option></select></label></div><label><input type="checkbox" name="active" value="1" checked> Activo</label><label><input type="checkbox" name="published" value="1"> Publicado</label><button class="z-btn">Crear servicio</button></form><div class="z-stack" style="margin-top:1rem">@foreach($services as $service)<article class="z-card"><form method="POST" action="{{ route('tenant.admin.logistics.services.update',$service) }}" class="z-stack">@csrf @method('PUT')<div class="z-form-grid"><label class="z-field">Nombre<input name="name" value="{{ $service->name }}"></label><label class="z-field">SLA<input name="sla_text" value="{{ $service->sla_text }}"></label></div><input type="hidden" name="pricing_strategy" value="{{ $service->pricing_strategy }}"><input type="hidden" name="sort_order" value="{{ $service->sort_order }}"><textarea name="description">{{ $service->description }}</textarea><label><input type="checkbox" name="active" value="1" @checked($service->status==='active')> Activo</label><label><input type="checkbox" name="published" value="1" @checked($service->published)> Publicado</label><button class="z-btn z-btn--outline">Guardar</button></form></article>@endforeach</div></section>
<section id="cobertura" class="customer-section"><h2>Cobertura por código postal</h2><form method="GET" class="z-card z-form-grid"><label class="z-field">Buscar CP<input name="q" value="{{ request('q') }}"></label><label class="z-field">Estado<input name="state" value="{{ request('state') }}"></label><label class="z-field">Municipio/Alcaldía<input name="municipality" value="{{ request('municipality') }}"></label><button class="z-btn">Buscar</button></form><form method="POST" action="{{ route('tenant.admin.logistics.coverage.store') }}" class="z-card z-stack">@csrf<div style="max-height:260px;overflow:auto">@foreach($postal as $cp)<label style="display:block"><input type="checkbox" name="postal_codes[]" value="{{ $cp->codigo_postal }}"> {{ $cp->codigo_postal }} · {{ $cp->municipio }}, {{ $cp->estado }}</label>@endforeach</div><button class="z-btn">Agregar selección</button></form><form method="POST" enctype="multipart/form-data" action="{{ route('tenant.admin.logistics.coverage.import') }}" class="z-card z-form-grid">@csrf<label class="z-field">Importar CSV<input type="file" name="csv" accept=".csv,text/csv" required></label><button class="z-btn">Importar</button></form></section>
<section id="tarifas" class="customer-section"><h2>Tarifas</h2>@foreach($services as $service)<form method="POST" action="{{ route('tenant.admin.logistics.pricing.store',$service) }}" class="z-card z-stack">@csrf<h3>{{ $service->name }} · {{ ['FLAT'=>'Precio fijo','PACKAGE_FLAT'=>'Precio por paquete','BASE_PLUS_OVERAGE'=>'Precio base con kilómetros incluidos','DISTANCE_TIERS_OVERAGE'=>'Tarifa por rangos de distancia'][$service->pricing_strategy] }}</h3><div class="z-form-grid z-form-grid--3"><label class="z-field">Desde km<input type="number" step=".001" name="from_km"></label><label class="z-field">Hasta km<input type="number" step=".001" name="to_km"></label><label class="z-field">Precio<input type="number" step=".01" name="amount" required></label></div><details><summary>Después del último rango</summary><div class="z-form-grid"><label class="z-field">A partir de / km incluidos<input name="included_distance_km" type="number" step=".001"></label><label class="z-field">Precio por km adicional<input name="overage_price_per_km" type="number" step=".01"></label><label class="z-field">Forma de cálculo<select name="overage_rounding"><option value="PROPORTIONAL">Proporcional</option><option value="CEIL">Redondear al km siguiente</option></select></label></div></details><button class="z-btn">Agregar tarifa</button></form>@endforeach</section>
<section id="paquetes" class="customer-section"><h2>Paquetes</h2>@foreach([['sobre','Sobre','1',null,null,null],['caja','Caja','40','60','50','40']] as $p)<form method="POST" action="{{ route('tenant.admin.logistics.packages.store') }}" class="z-card z-form-grid">@csrf<input type="hidden" name="package_type" value="{{ $p[0] }}"><h3>{{ $p[1] }}</h3><label class="z-field">Peso máximo kg<input name="max_weight_kg" value="{{ $p[2] }}"></label>@if($p[0]==='caja')@foreach([3=>'Dimensión máxima 1',4=>'Dimensión máxima 2',5=>'Dimensión máxima 3'] as $i=>$label)<label class="z-field">{{ $label }} cm<input name="max_dimension_{{ $i-2 }}_cm" value="{{ $p[$i] }}"></label>@endforeach @endif<button class="z-btn">Guardar</button></form>@endforeach</section>
@push('styles')<style>.logistics-panel-hidden{display:none!important}.z-tabs a[aria-current=page]{color:var(--z-primary);border-color:var(--z-primary)}@media(max-width:639px){.z-tabs a{padding:.7rem .8rem}}</style>@endpush
<script>(()=>{const ids=['resumen','servicios','cobertura','tarifas','paquetes'],tabs=[...document.querySelectorAll('.z-tabs a')];const show=id=>{ids.forEach(panelId=>document.getElementById(panelId)?.classList.toggle('logistics-panel-hidden',panelId!==id));tabs.forEach(tab=>tab.toggleAttribute('aria-current',tab.getAttribute('href')==='#'+id))};tabs.forEach(tab=>tab.addEventListener('click',event=>{event.preventDefault();const id=tab.getAttribute('href').slice(1);history.replaceState(null,'','#'+id);show(id)}));show(ids.includes(location.hash.slice(1))?location.hash.slice(1):'resumen')})()</script>
@endsection
