@extends('tenant.admin.layout')
@section('title','Servicios ZIGO')
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">CATÁLOGO COMERCIAL</div><h1>Servicios ZIGO</h1><p class="z-muted">Amplía tu plataforma con planes, módulos y capacidad operativa disponibles.</p></div><a class="z-btn z-btn--outline" href="{{ route('tenant.admin.purchases',[],false) }}">Ver mis compras</a></header>
@php($groups=['PLAN'=>['Planes','La base de capacidades de tu plataforma.'],'MODULE'=>['Módulos','Funciones adicionales para ampliar tu operación.'],'OPERATIONS_PACK'=>['Packs operativos','Capacidad adicional para temporadas o crecimiento.']])
<nav class="z-tabs" aria-label="Tipos de servicio">@foreach($groups as $type=>$copy)@if($products->where('type',$type)->isNotEmpty())<a href="#{{ strtolower($type) }}">{{ $copy[0] }}</a>@endif @endforeach</nav>
@forelse($groups as $type=>$copy)@php($items=$products->where('type',$type))@if($items->isNotEmpty())<section id="{{ strtolower($type) }}" class="customer-section marketplace-section"><div class="z-page-header"><div><h2>{{ $copy[0] }}</h2><p class="z-muted">{{ $copy[1] }}</p></div></div><div class="marketplace-grid">@foreach($items as $product)<article class="z-card marketplace-card"><div><span class="z-badge">{{ $copy[0] }}</span><h3>{{ $product->name }}</h3><p class="z-muted">{{ $product->description }}</p></div>@if($product->included_operations)<strong>+{{ number_format($product->included_operations) }} operaciones</strong>@endif<div class="marketplace-price"><strong>${{ number_format((float)$product->price,2) }} {{ $product->currency }}</strong><small>{{ $product->billing_type==='MONTHLY'?'Mensual':($product->billing_type==='ANNUAL'?'Anual':'Pago único') }}</small></div><form method="POST" action="{{ route('tenant.admin.marketplace.purchase',[],false) }}">@csrf<input type="hidden" name="product_uuid" value="{{ $product->uuid }}"><input type="hidden" name="purchase_key" value="{{ $keys[$product->uuid] }}"><button class="z-btn z-btn--block">Contratar</button></form></article>@endforeach</div></section>@endif @empty<section class="z-empty"><h2>No hay servicios disponibles</h2><p>El catálogo comercial no tiene ofertas activas en este momento.</p></section>@endforelse
@push('styles')<style>.marketplace-section{scroll-margin-top:90px}.marketplace-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:1rem}.marketplace-card{display:flex;flex-direction:column;gap:1rem}.marketplace-card h3{margin:.8rem 0 .25rem}.marketplace-price{margin-top:auto}.marketplace-price strong,.marketplace-price small{display:block}.marketplace-price strong{font-size:1.35rem;color:var(--z-primary)}</style>@endpush
@endsection
