@extends('tenant.admin.layout')
@section('title','Marketplace')
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">CATÁLOGO COMERCIAL</div><h1>Marketplace</h1><p class="z-muted">Contrata productos y amplía las capacidades de tu Tenant.</p></div><a class="z-btn z-btn--outline" href="{{ route('tenant.admin.purchases',[],false) }}">Ver mis compras</a></header>
<section class="customer-section"><div class="z-page-header"><div><h2>Tus productos</h2><p class="z-muted">Capacidades actualmente disponibles para tu cuenta.</p></div></div>
@if($aiActive && $aiCapacity)<article class="z-card marketplace-card contracted-card"><div class="marketplace-card__head"><div><span class="z-badge">ACTIVO</span><h3>Agentes IA</h3><p class="z-muted">{{ $aiEntitlement?->source === 'manual' ? 'Habilitación administrativa' : 'Producto comercial contratado' }}</p></div><span class="z-badge">Agentes IA</span></div><div class="capacity-grid"><span>Agentes <strong>{{ $aiCapacity['MAX_AGENTS']->limit }}</strong></span><span>Webchat <strong>{{ $aiCapacity['MAX_WEBCHAT_CHANNELS']->limit }}</strong></span><span>WhatsApp <strong>{{ $aiCapacity['MAX_WHATSAPP_CHANNELS']->limit }}</strong></span><span>Conversaciones <strong>{{ $aiCapacity['MONTHLY_CONVERSATIONS']->limit }}</strong></span><span>Runtime <strong>{{ $aiCapacity['MONTHLY_RUNTIME_UNITS']->limit }}</strong></span><span>Actions <strong>{{ $aiCapacity['MONTHLY_ACTION_RUNS']->limit }}</strong></span></div>@if($aiOrders->isNotEmpty())<p class="z-muted">{{ ($aiOrders->first()->purchase_snapshot['billing_type'] ?? 'MONTHLY') === 'ANNUAL' ? 'Anual' : 'Mensual' }} · ${{ number_format((float)$aiOrders->first()->total_amount,2) }} {{ $aiOrders->first()->currency }}</p>@endif<div class="inline"><a class="z-btn" href="{{ route('tenant.admin.ai-agents.index',[],false) }}">Administrar</a><a class="z-btn z-btn--outline" href="#ai-addons">Ampliar capacidad</a></div></article>@else<p class="z-muted">Todavía no tienes Agentes IA contratados.</p>@endif</section>
<section id="ai-addons" class="customer-section"><div class="z-page-header"><div><h2>{{ $aiActive ? 'Amplía Agentes IA' : 'Agentes IA' }}</h2><p class="z-muted">Precios provisionales de Stage, configurables desde el catálogo comercial.</p></div></div><div class="marketplace-grid">@forelse($aiProducts as $product)<article class="z-card marketplace-card"><div><span class="z-badge">{{ data_get($product->metadata,'ai_kind') === 'base' ? 'BASE' : 'AMPLIACIÓN' }}</span><h3>{{ $product->name }}</h3><p class="z-muted">{{ $product->description }}</p></div><div class="marketplace-price"><strong>${{ number_format((float)$product->price,2) }} {{ $product->currency }}</strong><small>{{ $product->billing_type==='MONTHLY'?'Mensual':($product->billing_type==='ANNUAL'?'Anual':'Pago único') }}</small></div><form method="POST" action="{{ route('tenant.admin.marketplace.purchase',[],false) }}">@csrf<input type="hidden" name="product_uuid" value="{{ $product->uuid }}"><input type="hidden" name="purchase_key" value="{{ $keys[$product->uuid] }}"><button class="z-btn z-btn--block">Agregar</button></form></article>@empty<p class="z-muted">No hay ampliaciones disponibles.</p>@endforelse</div></section>
<section class="customer-section"><div class="z-page-header"><div><h2>Otros productos</h2><p class="z-muted">Productos adicionales del catálogo multiproducto.</p></div></div><div class="marketplace-grid">@forelse($products as $product)<article class="z-card marketplace-card"><div><span class="z-badge">{{ $product->type }}</span><h3>{{ $product->name }}</h3><p class="z-muted">{{ $product->description }}</p></div>@if($product->included_operations)<strong>+{{ number_format($product->included_operations) }} operaciones</strong>@endif<div class="marketplace-price"><strong>${{ number_format((float)$product->price,2) }} {{ $product->currency }}</strong><small>{{ $product->billing_type==='MONTHLY'?'Mensual':($product->billing_type==='ANNUAL'?'Anual':'Pago único') }}</small></div><form method="POST" action="{{ route('tenant.admin.marketplace.purchase',[],false) }}">@csrf<input type="hidden" name="product_uuid" value="{{ $product->uuid }}"><input type="hidden" name="purchase_key" value="{{ $keys[$product->uuid] }}"><button class="z-btn z-btn--block">Contratar</button></form></article>@empty<p class="z-muted">No hay otros productos disponibles.</p>@endforelse</div></section>
@push('styles')<style>.marketplace-card{display:flex;flex-direction:column;gap:1rem}.marketplace-card__head{display:flex;justify-content:space-between;gap:1rem}.marketplace-card h3{margin:.7rem 0 .25rem}.marketplace-price{margin-top:auto}.marketplace-price strong,.marketplace-price small{display:block}.marketplace-price strong{font-size:1.35rem;color:var(--z-primary)}.capacity-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:.65rem}.capacity-grid span{padding:.6rem;background:#f7f9fc;border-radius:8px}.capacity-grid strong{display:block}.contracted-card{max-width:850px}</style>@endpush
@endsection
