@extends('tenant.admin.layout')
@section('title','Operación local')
@section('content')
<div class="eyebrow">OPERACIÓN</div><h1>{{ $operation->uuid }}</h1>
<div class="card"><p><strong>Provider:</strong> {{ $operation->provider }}</p><p><strong>Servicio:</strong> {{ $operation->service_code }}</p><p><strong>Estado:</strong> {{ strtoupper($operation->status) }}</p></div>
@if($shipment)
<div class="card"><h2>Envío local</h2><p><strong>Tracking:</strong> <code>{{ $shipment->tracking_number }}</code></p><p><strong>Servicio:</strong> {{ $shipment->service_code }}</p><p><strong>Estado:</strong> {{ $shipment->status }}</p>
@if($shipment->status === 'CREATED')<form method="POST" action="{{ route('tenant.admin.operations.pickup-request',$operation->uuid) }}">@csrf<button class="btn">Solicitar recolección</button></form>
@elseif($shipment->status === 'READY_FOR_PICKUP')<p class="notice">Recolección solicitada. Estamos asignando un repartidor.</p>@endif
<a class="btn" href="{{ route('tenant.admin.operations.guide',$operation->uuid) }}">Descargar guía PDF</a><a class="btn" href="{{ route('tenant.b2c.tracking.show',$shipment->tracking_number) }}">Ver tracking</a>
@if($canManageDrivers && app(\App\Domain\Network\Billing\EntitlementService::class)->has($tenant,'DRIVER'))<h3>Despacho Last Mile</h3>
@if($shipment->status === 'READY_FOR_PICKUP')<p><strong>Driver:</strong> {{ $shipment->activeDriverAssignment?->driverProfile?->user?->name ?? 'Sin asignar' }}</p><form method="POST" action="{{ route('tenant.admin.drivers.assign',$shipment->uuid) }}">@csrf<select class="input" name="driver_uuid" required><option value="">Seleccionar conductor</option>@foreach($drivers as $driver)<option value="{{ $driver->uuid }}">{{ $driver->code }} · {{ $driver->user->name }}</option>@endforeach</select><button class="btn">Asignar / reasignar</button></form>
@else<p class="muted">La asignación estará disponible cuando se solicite la recolección.</p>@endif
@if(in_array($shipment->status,['CREATED','READY_FOR_PICKUP','DELIVERY_FAILED'],true))<form method="POST" action="{{ route('tenant.admin.drivers.transition',$shipment->uuid) }}">@csrf<input type="hidden" name="status" value="CANCELED"><button class="btn">Cancelar envío</button></form>@endif @endif</div>
@elseif($operation->status==='confirmed' && strtoupper((string)$operation->provider)==='ZIGO_LOCAL')
<div class="card"><h2>Generar envío</h2><form method="POST" action="{{ route('tenant.admin.operations.shipment',$operation->uuid) }}">@csrf<h3>Remitente</h3><input name="sender[name]" placeholder="Nombre" required><input name="sender[address]" placeholder="Dirección" required><input name="sender[postal_code]" placeholder="CP" required><input name="sender[phone]" placeholder="Teléfono"><h3>Destinatario</h3><input name="recipient[name]" placeholder="Nombre" required><input name="recipient[address]" placeholder="Dirección" required><input name="recipient[postal_code]" placeholder="CP" required><input name="recipient[phone]" placeholder="Teléfono"><h3>Paquete</h3><input name="package[type]" value="caja" required><input name="package[weight]" type="number" step=".01" placeholder="Peso" required><input name="package[length]" type="number" step=".01" placeholder="Largo"><input name="package[width]" type="number" step=".01" placeholder="Ancho"><input name="package[height]" type="number" step=".01" placeholder="Alto"><input name="reference" placeholder="Referencia"><button class="btn">Generar guía</button></form></div>@endif
@endsection
