@extends('tenant.admin.layout')
@section('title','Operaciones')
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">OPERACIÓN</div><h1>Envíos y operaciones</h1><p class="z-muted">Consulta el estado comercial, pago y avance operativo de cada solicitud.</p></div></header>
@if($errors->any())<div class="z-alert z-alert--danger">{{ $errors->first() }}</div>@endif
<form method="GET" class="z-card z-form-grid operations-filters"><label class="z-field">Buscar<input name="search" value="{{ request('search') }}" placeholder="UUID o referencia"></label><label class="z-field">Estado<select name="status"><option value="">Todos</option>@foreach(['draft'=>'Borrador','quoted'=>'Cotizada','confirmed'=>'Confirmada','canceled'=>'Cancelada'] as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select></label><label class="z-field">Pago<select name="payment"><option value="">Todos</option>@foreach(['PENDING'=>'Pendiente','APPROVED'=>'Aprobado','REJECTED'=>'Rechazado','CANCELED'=>'Cancelado'] as $value=>$label)<option value="{{ $value }}" @selected(request('payment')===$value)>{{ $label }}</option>@endforeach</select></label><div class="z-form-actions"><button class="z-btn">Filtrar</button><a class="z-btn z-btn--outline" href="{{ route('tenant.admin.operations.index',[],false) }}">Limpiar</a></div></form>
<section class="z-card"><div class="z-table-wrap"><table class="z-table"><thead><tr><th>Operación</th><th>Fecha</th><th>Estado</th><th>Pago</th><th>Servicio</th><th>Acciones</th></tr></thead><tbody>@forelse($operations as $operation)@php($checkout=$operation->relationLoaded('customerCheckout')?$operation->customerCheckout:null)@php($canConfirm=$operation->status==='quoted'&&(!$checkout||$checkout->payment_status==='APPROVED'))<tr><td><strong>{{ Illuminate\Support\Str::limit($operation->uuid,18) }}</strong><small class="z-muted">{{ $operation->external_reference ?: 'Sin referencia' }}</small></td><td>{{ $operation->created_at->format('d/m/Y H:i') }}</td><td><span class="z-badge">{{ strtoupper($operation->status) }}</span></td><td><span class="z-badge {{ $checkout?->payment_status==='APPROVED'?'z-badge--success':($checkout?'z-badge--warning':'z-badge--muted') }}">{{ $checkout?->payment_status ?? 'Operación manual' }}</span></td><td>{{ $operation->service_code ?? 'Por seleccionar' }}</td><td><div class="z-cluster"><a class="z-btn z-btn--outline" href="{{ route('tenant.admin.operations.show',$operation->uuid,false) }}">Ver detalle</a>@if($canConfirm)<form method="POST" action="{{ route('tenant.admin.operations.confirm',$operation->uuid,false) }}">@csrf<button class="z-btn">Confirmar</button></form>@elseif($operation->status==='quoted'&&$checkout)<span class="z-muted z-small">Espera pago aprobado</span>@endif</div></td></tr>@empty<tr><td colspan="6"><div class="z-empty"><h3>Sin operaciones</h3><p>Las cotizaciones y envíos aparecerán aquí.</p></div></td></tr>@endforelse</tbody></table></div></section>{{ $operations->links() }}
@push('styles')<style>.operations-filters{grid-template-columns:2fr 1fr 1fr auto;margin-bottom:1rem}.z-table td:first-child small{display:block}@media(max-width:900px){.operations-filters{grid-template-columns:1fr 1fr}}@media(max-width:620px){.operations-filters{grid-template-columns:1fr}}</style>@endpush
@endsection
