@extends('tenant.admin.layout')
@section('title','Operación local')
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">OPERACIÓN</div><h1>Detalle operativo</h1><p class="z-muted"><code>{{ $operation->uuid }}</code></p></div><a class="z-btn z-btn--outline" href="{{ route('tenant.admin.operations.index',[],false) }}">Volver a operaciones</a></header>
@if($errors->any())<div class="z-alert z-alert--danger">{{ $errors->first() }}</div>@endif
@if($canConfirm)<div class="z-status-panel"><h2>Operación manual pendiente de confirmación</h2><p>Al confirmar la operación quedará habilitada para continuar con la generación del envío.</p><form method="POST" action="{{ route('tenant.admin.operations.confirm',$operation->uuid,false) }}">@csrf<button class="z-btn">Confirmar operación</button></form></div>@elseif($operation->status==='quoted' && $operation->customerCheckout)<div class="z-alert z-alert--warning">Pago pendiente: la operación todavía no puede confirmarse.</div>@endif
<div class="card"><p><strong>Provider:</strong> {{ $operation->provider }}</p><p><strong>Servicio:</strong> {{ $operation->service_code }}</p><p><strong>Estado:</strong> {{ strtoupper($operation->status) }}</p></div>
@if($operation->customerCheckout)<div class="card"><h2>Checkout customer</h2><p><strong>Customer:</strong> {{ $operation->customerProfile?->display_name ?: $operation->customerProfile?->user?->email }}</p><p><strong>Checkout:</strong> {{ $operation->customerCheckout->uuid }}</p><p><strong>Estado:</strong> {{ $operation->customerCheckout->status }}</p><p><strong>Pago:</strong> {{ $operation->customerCheckout->payment_status }}</p><p><strong>Total:</strong> ${{ number_format((float)$operation->customerCheckout->total_amount,2) }} {{ $operation->customerCheckout->currency }}</p></div>@endif
@if($shipment)
<div class="card"><h2>Envío local</h2><p><strong>Tracking:</strong> <code>{{ $shipment->tracking_number }}</code></p><p><strong>Servicio:</strong> {{ $shipment->service_code }}</p><p><strong>Estado:</strong> {{ $shipment->status }}</p>
@if($shipment->status === 'CREATED')<form method="POST" action="{{ route('tenant.admin.operations.pickup-request',$operation->uuid) }}">@csrf<button class="btn">Solicitar recolección</button></form>
@elseif($shipment->status === 'READY_FOR_PICKUP')<p class="notice">Recolección solicitada. Estamos asignando un repartidor.</p>@endif
<div class="z-actions"><a class="z-btn" href="{{ route('tenant.admin.operations.guide',$operation->uuid,false) }}">Descargar guía PDF</a><a class="z-btn z-btn--outline" href="{{ route('tenant.admin.operations.tracking',$operation->uuid,false) }}">Ver tracking</a></div>
@if($canManageDrivers && app(\App\Domain\Network\Billing\EntitlementService::class)->has($tenant,'DRIVER'))<h3>Despacho Last Mile</h3>
@php($activeAssignment=$shipment->activeDriverAssignment)
@php($lastMileCopy=['CREATED'=>'Recolección aún no solicitada.','PICKED_UP'=>'Paquete recolectado. Envío en curso.','IN_TRANSIT'=>'Envío en tránsito.','OUT_FOR_DELIVERY'=>'Envío en reparto.','DELIVERED'=>'Entrega completada.','DELIVERY_FAILED'=>'No fue posible completar la entrega. Revisa los intentos registrados.','CANCELED'=>'Envío cancelado.'])
@if(isset($lastMileCopy[$shipment->status]))<p class="notice">{{ $lastMileCopy[$shipment->status] }}</p>@endif
@if($activeAssignment)<div class="notice assignment-current"><strong>Conductor asignado</strong><p><strong>Nombre:</strong> {{ $activeAssignment->driverProfile->user->name }}</p><p><strong>Código:</strong> {{ $activeAssignment->driverProfile->code }}</p>@if($activeAssignment->driverProfile->availability_status)<p><strong>Disponibilidad:</strong> {{ $activeAssignment->driverProfile->availability_status }}</p>@endif</div>@endif
@if($shipment->status === 'READY_FOR_PICKUP')
@if($activeAssignment)
<details><summary class="btn">Reasignar conductor</summary><form method="POST" action="{{ route('tenant.admin.drivers.assign',$shipment->uuid) }}">@csrf<select class="input" name="driver_uuid" required><option value="">Seleccionar nuevo conductor</option>@foreach($drivers as $driver)<option value="{{ $driver->uuid }}">{{ $driver->code }} · {{ $driver->user->name }}</option>@endforeach</select><button class="btn">Confirmar reasignación</button></form></details>
@else
<p class="notice"><strong>Sin conductor asignado.</strong> Selecciona un conductor para continuar.</p><form method="POST" action="{{ route('tenant.admin.drivers.assign',$shipment->uuid) }}">@csrf<select class="input" name="driver_uuid" required><option value="">Seleccionar conductor</option>@foreach($drivers as $driver)<option value="{{ $driver->uuid }}">{{ $driver->code }} · {{ $driver->user->name }}</option>@endforeach</select><button class="btn">Asignar conductor</button></form>
@endif
@endif
@if(in_array($shipment->status,['CREATED','READY_FOR_PICKUP','DELIVERY_FAILED'],true))<form method="POST" action="{{ route('tenant.admin.drivers.transition',$shipment->uuid) }}">@csrf<input type="hidden" name="status" value="CANCELED"><button class="btn">Cancelar envío</button></form>@endif @endif</div>
@if($podEnabled && $shipment->deliveryProof)<div class="card"><h2>PRUEBA DE ENTREGA</h2><p><strong>Receptor:</strong> {{ $shipment->deliveryProof->received_by_name }}</p><p><strong>Tipo:</strong> {{ $shipment->deliveryProof->receiver_type }}</p><p><strong>Capturada:</strong> {{ $shipment->deliveryProof->captured_at }}</p><p><strong>Ubicación:</strong> {{ $shipment->deliveryProof->latitude }}, {{ $shipment->deliveryProof->longitude }} (±{{ $shipment->deliveryProof->accuracy_meters }} m)</p><a class="btn" href="{{ route('tenant.admin.delivery-proofs.evidence',[$shipment->deliveryProof->uuid,'photo']) }}">Ver fotografía</a><a class="btn" href="{{ route('tenant.admin.delivery-proofs.evidence',[$shipment->deliveryProof->uuid,'signature']) }}">Ver firma</a></div>@endif
@if($podEnabled && $shipment->failedDeliveryAttempts->isNotEmpty())<div class="card"><h2>INTENTOS DE ENTREGA</h2>@foreach($shipment->failedDeliveryAttempts->sortBy('attempt_number') as $attempt)<article><h3>Intento #{{ $attempt->attempt_number }}</h3><p><strong>Fecha/hora:</strong> {{ $attempt->occurred_at }}</p><p><strong>Motivo:</strong> {{ \App\Domain\Shipping\LastMile\Models\LocalDeliveryFailedAttempt::REASON_LABELS[$attempt->reason] ?? $attempt->reason }}</p>@if($attempt->notes)<p><strong>Nota:</strong> {{ $attempt->notes }}</p>@endif @if($attempt->photo_path)<p><a href="{{ route('tenant.admin.delivery-failures.photo',$attempt->uuid) }}">Ver fotografía protegida</a></p>@endif @if($attempt->latitude!==null)<p><strong>GPS:</strong> {{ $attempt->latitude }}, {{ $attempt->longitude }} (±{{ $attempt->accuracy_meters }} m)</p>@endif</article>@endforeach @if($shipment->status==='DELIVERY_FAILED' && $shipment->deliveryRequirement && $shipment->failedDeliveryAttempts->count()>=$shipment->deliveryRequirement->max_delivery_attempts)<p class="notice"><strong>Límite de intentos alcanzado.</strong> Pendiente de resolución.</p>@endif</div>@endif
@elseif($canGenerateShipment)
<div class="card"><h2>Generar envío</h2><form method="POST" action="{{ route('tenant.admin.operations.shipment',$operation->uuid) }}">@csrf<h3>Remitente</h3><input name="sender[name]" placeholder="Nombre" required><input name="sender[address]" placeholder="Dirección" required><input name="sender[postal_code]" placeholder="CP" required><input name="sender[phone]" placeholder="Teléfono"><h3>Destinatario</h3><input name="recipient[name]" placeholder="Nombre" required><input name="recipient[address]" placeholder="Dirección" required><input name="recipient[postal_code]" placeholder="CP" required><input name="recipient[phone]" placeholder="Teléfono"><h3>Paquete</h3><input name="package[type]" value="caja" required><input name="package[weight]" type="number" step=".01" placeholder="Peso" required><input name="package[length]" type="number" step=".01" placeholder="Largo"><input name="package[width]" type="number" step=".01" placeholder="Ancho"><input name="package[height]" type="number" step=".01" placeholder="Alto"><input name="reference" placeholder="Referencia"><h3>Tipo de evidencia de entrega</h3><select class="input" name="delivery_proof_option_uuid"><option value="">Opción predeterminada</option>@foreach($proofOptions as $proofOption)<option value="{{ $proofOption->uuid }}" @selected(old('delivery_proof_option_uuid')===$proofOption->uuid)>{{ $proofOption->name }}@if($proofOption->surcharge_amount) · +{{ number_format((float)$proofOption->surcharge_amount,2) }} {{ $proofOption->currency }}@endif</option>@endforeach</select><p class="muted">La modalidad elegida quedará congelada en la guía. Esta selección se moverá al checkout del comprador en ZN-UX.</p><button class="btn">Generar guía</button></form></div>@endif
@endsection
