<?php
namespace App\Http\Requests\Tenant;
use App\Domain\AI\Launchpad\Data\LaunchpadIntakeData;use App\Domain\Network\Tenancy\TenantAccessService;use Illuminate\Foundation\Http\FormRequest;use Illuminate\Validation\Rule;use Illuminate\Validation\Validator;
final class StoreAgentLaunchpadRequest extends FormRequest
{
 private const FRAMEWORK_FIELDS=['_token'];
 public function authorize():bool{return app(TenantAccessService::class)->canManageTenant($this->user());}
 protected function prepareForValidation():void{$clean=function($v)use(&$clean){if(is_array($v))return array_map($clean,$v);return is_string($v)?trim($v):$v;};$this->replace($clean($this->all()));}
 public function rules():array{return['problem_description'=>['required','string','max:2000'],'objective_code'=>['required',Rule::in(LaunchpadIntakeData::OBJECTIVES)],'business_description'=>['nullable','string','max:1500'],'customer_description'=>['nullable','string','max:1000'],'desired_outcomes'=>['nullable','string','max:1000'],'requested_channels'=>['array','max:3'],'requested_channels.*'=>[Rule::in(LaunchpadIntakeData::CHANNELS)],'business_hours'=>['nullable','string','max:300'],'handoff_preference'=>['nullable',Rule::in(LaunchpadIntakeData::HANDOFF)],'knowledge_source_types'=>['array','max:8'],'knowledge_source_types.*'=>[Rule::in(LaunchpadIntakeData::KNOWLEDGE)],'integration_needs'=>['nullable','string','max:1000'],'preferred_language'=>['nullable','string','max:12','regex:/^[a-z]{2}(?:-[A-Z]{2})?$/'],'desired_agent_name'=>['nullable','string','max:160']];}
 public function withValidator(Validator$v):void{$v->after(function(Validator$v){$allowed=array_merge(array_keys($this->rules()),self::FRAMEWORK_FIELDS);$forbidden=['tenant_id','actor_id','agent_id','version_number','prompt','system_prompt','token','api_key','password','credentials'];foreach(array_keys($this->all())as$key)if(!in_array($key,$allowed,true)||in_array(strtolower($key),$forbidden,true))$v->errors()->add($key,'Este campo no está permitido.');foreach($this->all()as$key=>$value){$strings=is_array($value)?$value:[$value];foreach($strings as$item)if(is_string($item)&&(preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u',$item)||preg_match('/<[^>]+>/u',$item)||preg_match('/\b(password|api[_ -]?key|(?:access[_ -]?)?token|bearer|client[_ -]?secret)\s*[:=]/i',$item)))$v->errors()->add($key,'No incluyas código activo, contraseñas, tokens ni credenciales.');}});}
 public function data():LaunchpadIntakeData{return LaunchpadIntakeData::fromArray($this->validated());}
}
