@extends('tenant.admin.layout')
@section('title','Conductor')
@section('content')
<div class="eyebrow">LAST MILE</div><h1>{{ $driver->user->name }}</h1>
<section class="card"><p><strong>Código:</strong> {{ $driver->code }}</p><p><strong>Perfil:</strong> {{ $driver->status }}</p><p><strong>Presencia:</strong> {{ $driver->isOnline() ? 'ONLINE' : 'OFFLINE' }}</p><p><strong>Disponibilidad:</strong> {{ $driver->availability_status }}</p><p><strong>Vehículo:</strong> {{ $driver->vehicle_label??'—' }}</p></section>
<section class="card"><h2>Liquidación / actividad</h2><p><strong>Periodo:</strong> {{ $report['period'] }}</p><p>Entregas: {{ $report['deliveries'] }}</p><p>Delivery failed: {{ $report['failed'] }}</p><p>Earnings generated: {{ number_format($report['generated'],2) }} {{ $policy?->currency ?? 'MXN' }}</p><p>Paid: {{ number_format($report['paid'],2) }} {{ $policy?->currency ?? 'MXN' }}</p><p>Pendiente de liquidación: <strong>{{ number_format($report['pending'],2) }} {{ $policy?->currency ?? 'MXN' }}</strong></p></section>
<section class="card"><h2>Política de compensación del conductor</h2><p>{{ $policy?->compensation_type ?? 'Sin configurar' }}@if($policy) · {{ $policy->settlement_frequency }}@if($policy->amount_per_delivery !== null) · {{ number_format((float)$policy->amount_per_delivery,2) }} {{ $policy->currency }} por entrega @endif @endif</p>
@if($canManage)<form method="POST" action="{{ route('tenant.admin.drivers.compensation.update', $driver->uuid) }}">@csrf @method('PUT')<select class="input" name="compensation_type" required>@foreach(\App\Domain\Shipping\LastMile\Models\DriverCompensationPolicy::TYPES as $type)<option value="{{ $type }}" @selected($policy?->compensation_type===$type)>{{ $type }}</option>@endforeach</select><select class="input" name="settlement_frequency" required>@foreach(\App\Domain\Shipping\LastMile\Models\DriverCompensationPolicy::FREQUENCIES as $frequency)<option value="{{ $frequency }}" @selected($policy?->settlement_frequency===$frequency)>{{ $frequency }}</option>@endforeach</select><input class="input" type="number" min="0" step="0.01" name="amount_per_delivery" value="{{ $policy?->amount_per_delivery }}" placeholder="Monto por entrega"><input class="input" name="currency" value="{{ $policy?->currency ?? 'MXN' }}" maxlength="3" required><button class="btn">Guardar política</button></form>@endif</section>
<section class="card"><h2>Historial de asignaciones</h2>@forelse($driver->assignments->sortByDesc('assigned_at') as $assignment)<p><code>{{ $assignment->shipment->tracking_number }}</code> · {{ $assignment->status }} · {{ $assignment->assigned_at }}</p>@empty<p>Sin asignaciones.</p>@endforelse</section>
@endsection
