<?php
namespace App\Domain\AI\Actions\Services;
use App\Domain\AI\Usage\AiCapacityService;
use App\Domain\AI\Actions\ActionRegistry;use App\Domain\AI\Actions\Data\{ActionDefinition,ActionExecutionContext,ActionRequestData};use App\Domain\AI\Actions\Enums\{ActionConfirmationPolicy,ActionRunStatus};use App\Domain\AI\Actions\Exceptions\ActionConflictException;use App\Domain\AI\Actions\Models\ActionRun;use App\Domain\AI\Actions\Support\ActionSchemaValidator;use App\Domain\AI\Agents\Models\{AgentContractVersion,AgentVersion};use App\Domain\AI\Conversations\Exceptions\ConversationTurnSupersededException;use App\Domain\AI\Conversations\Models\{Conversation,ConversationMessage};use App\Domain\AI\Runtime\Models\RuntimeRun;use App\Domain\Network\Tenancy\Models\Tenant;use Illuminate\Database\QueryException;use Illuminate\Support\Facades\{DB,Schema};
final class ActionExecutor
{
 public function __construct(private ActionRegistry$registry,private ActionSchemaValidator$schemas,private ActionAggregateGuard$guard,private AiCapacityService$capacity){}
 public function reserve(Conversation$c,ConversationMessage$m,RuntimeRun$r,ActionRequestData$request):ActionRun
 {
  return DB::transaction(function()use($c,$m,$r,$request){$conversation=Conversation::query()->lockForUpdate()->findOrFail($c->id);$message=ConversationMessage::query()->whereKey($m->id)->lockForUpdate()->firstOrFail();$run=RuntimeRun::query()->whereKey($r->id)->lockForUpdate()->firstOrFail();$version=AgentVersion::query()->whereKey($conversation->agent_version_id)->firstOrFail();$contract=AgentContractVersion::query()->whereKey($version->agent_contract_version_id)->firstOrFail();$this->guard->assert($conversation,$message,$run,$version,$contract);$definition=$this->registry->find($request->actionKey);if(!$definition)throw new \DomainException('Action is not registered.');$this->assertAvailable($definition,(int)$conversation->tenant_id);if(!in_array($request->actionKey,$contract->allowed_actions??[],true))throw new \DomainException('Action is not allowed by the pinned Contract.');$this->schemas->validate($request->arguments,$definition->inputSchema,(int)config('ai.actions.max_input_bytes',16384));$key=hash('sha256',implode(':',[$conversation->tenant_id,$conversation->id,$message->id,$run->id,$request->actionKey]));$existing=ActionRun::query()->where('idempotency_key',$key)->first();if($existing)return$existing;$action=new ActionRun;$action->agent_id=$conversation->agent_id;$action->agent_version_id=$version->id;$action->contract_version_id=$contract->id;$action->conversation_id=$conversation->id;$action->source_message_id=$message->id;$action->runtime_run_id=$run->id;$action->action_key=$definition->key;$action->effect=$definition->effect;$action->status=$definition->confirmation===ActionConfirmationPolicy::Required?ActionRunStatus::AwaitingConfirmation:ActionRunStatus::Requested;$action->idempotency_key=$key;$action->input=$request->arguments;$action->requested_at=now();try{$action->save();}catch(QueryException$e){$existing=ActionRun::query()->where('idempotency_key',$key)->first();if(!$existing)throw$e;$action=$existing;}return$action;});
 }
 public function execute(ActionRun$action,?string$tokenHash=null,?\DateTimeInterface$expiresAt=null,?callable$beforeClaim=null):ActionRun
 {
  if(!Schema::hasColumn('ai_action_runs','conversation_turn_token_hash'))return$this->legacyClaimAndPerform($action,null,$beforeClaim);
  if($tokenHash===null||$expiresAt===null)throw new \LogicException('Action execution requires durable turn ownership.');
  $claimed=DB::transaction(function()use($action,$tokenHash,$expiresAt,$beforeClaim){$tenant=Tenant::query()->findOrFail($action->tenant_id);$this->capacity->lockAuthority($tenant);$locked=ActionRun::query()->lockForUpdate()->findOrFail($action->id);if($locked->status!==ActionRunStatus::Requested)throw new ActionConflictException('Action is not available for execution.');if($beforeClaim)$beforeClaim($locked);$locked->bindTurn($tokenHash,$expiresAt);$this->capacity->consume($tenant,AiCapacityService::MONTHLY_ACTION_RUNS,'action_run:'.$locked->id);$locked->beginAutomatic();return$locked->fresh();});return$this->perform($claimed,$tokenHash);
 }
 public function confirm(ActionRun$action,int$userId,?string$tokenHash=null,?\DateTimeInterface$expiresAt=null):ActionRun
 {
  if(!Schema::hasColumn('ai_action_runs','conversation_turn_token_hash'))return$this->legacyClaimAndPerform($action,$userId);
  if($tokenHash===null||$expiresAt===null)throw new \LogicException('Action execution requires durable turn ownership.');
  return$this->performClaimed($this->claimConfirmation($action,$userId,$tokenHash,$expiresAt),$tokenHash);
 }
 public function claimConfirmation(ActionRun$action,int$userId,string$tokenHash,\DateTimeInterface$expiresAt):ActionRun{return DB::transaction(function()use($action,$userId,$tokenHash,$expiresAt){$tenant=Tenant::query()->findOrFail($action->tenant_id);$this->capacity->lockAuthority($tenant);$locked=ActionRun::query()->lockForUpdate()->findOrFail($action->id);if($locked->status!==ActionRunStatus::AwaitingConfirmation)throw new ActionConflictException('Action is no longer awaiting confirmation.');$definition=$this->registry->find($locked->action_key);if(!$definition||$definition->effect!==$locked->effect||$definition->confirmation!==ActionConfirmationPolicy::Required)throw new ActionConflictException('Action is no longer registered consistently.');$contract=AgentContractVersion::query()->findOrFail($locked->contract_version_id);if(!in_array($locked->action_key,$contract->allowed_actions??[],true))throw new ActionConflictException('Action is no longer allowed.');$locked->bindTurn($tokenHash,$expiresAt);$this->capacity->consume($tenant,AiCapacityService::MONTHLY_ACTION_RUNS,'action_run:'.$locked->id);$locked->begin($userId);return$locked->fresh();});}
 public function performClaimed(ActionRun$action,string$tokenHash):ActionRun{if($action->status!==ActionRunStatus::Executing)throw new ActionConflictException('Action confirmation was not claimed.');return$this->perform($action,$tokenHash);}
 private function perform(ActionRun$run,string$tokenHash):ActionRun
 {
  $this->assertOwned($run,$tokenHash);$definition=$this->registry->find($run->action_key);if(!$definition)return$this->fail($run,'action_not_registered',$tokenHash);$contract=AgentContractVersion::query()->findOrFail($run->contract_version_id);try{$this->assertAvailable($definition,(int)$run->tenant_id);}catch(\Throwable){return$this->fail($run,'action_not_allowed',$tokenHash);}if($definition->effect!==$run->effect||!in_array($run->action_key,$contract->allowed_actions??[],true))return$this->fail($run,'action_not_allowed',$tokenHash);if(DB::transactionLevel()!==0)throw new \LogicException('Action handlers must execute outside database transactions.');try{$result=$definition->handler->execute($this->context($run),$run->input);}catch(\Throwable){return$this->uncertain($run,$tokenHash);}try{$this->schemas->validate($result->data,$definition->outputSchema,(int)config('ai.actions.max_output_bytes',32768));}catch(\Throwable){return$this->uncertain($run,$tokenHash);}return DB::transaction(function()use($run,$result,$tokenHash){$conversation=Conversation::query()->lockForUpdate()->findOrFail($run->conversation_id);$locked=ActionRun::query()->lockForUpdate()->findOrFail($run->id);if($locked->status!==ActionRunStatus::Executing)return$locked;if(!$this->owned($conversation,$locked,$tokenHash)||$locked->execution_expires_at?->isPast()){$locked->requireReconciliation($tokenHash);return$locked->fresh();}$locked->succeed($result->data,$tokenHash);return$locked->fresh();});
 }
 private function fail(ActionRun$run,string$code,?string$tokenHash=null):ActionRun{return DB::transaction(function()use($run,$code,$tokenHash){$conversation=Conversation::query()->lockForUpdate()->findOrFail($run->conversation_id);$locked=ActionRun::query()->lockForUpdate()->findOrFail($run->id);if($locked->status===ActionRunStatus::Executing){if($tokenHash!==null&&!$this->owned($conversation,$locked,$tokenHash))throw new ConversationTurnSupersededException;$locked->fail($code,$tokenHash);}return$locked->fresh();});}
 private function uncertain(ActionRun$run,string$tokenHash):ActionRun{return DB::transaction(function()use($run,$tokenHash){$conversation=Conversation::query()->lockForUpdate()->findOrFail($run->conversation_id);$locked=ActionRun::query()->lockForUpdate()->findOrFail($run->id);if($locked->status===ActionRunStatus::Executing&&$this->owned($conversation,$locked,$tokenHash))$locked->requireReconciliation($tokenHash);return$locked->fresh();});}
 private function assertOwned(ActionRun$run,string$tokenHash):void{$conversation=Conversation::query()->findOrFail($run->conversation_id);if(!$this->owned($conversation,$run,$tokenHash)||$run->execution_expires_at?->isPast())throw new ConversationTurnSupersededException;}
 private function owned(Conversation$c,ActionRun$r,string$tokenHash):bool{return$c->turn_in_progress&&is_string($c->active_turn_token_hash)&&hash_equals($c->active_turn_token_hash,$tokenHash)&&is_string($r->conversation_turn_token_hash)&&hash_equals($r->conversation_turn_token_hash,$tokenHash);}
 private function legacyClaimAndPerform(ActionRun$action,?int$userId,?callable$beforeClaim=null):ActionRun{$claimed=DB::transaction(function()use($action,$userId,$beforeClaim){$locked=ActionRun::query()->lockForUpdate()->findOrFail($action->id);if($beforeClaim)$beforeClaim($locked);$userId===null?$locked->beginAutomatic():$locked->begin($userId);return$locked->fresh();});$definition=$this->registry->find($claimed->action_key);if(!$definition)return$this->fail($claimed,'action_not_registered');try{$result=$definition->handler->execute($this->context($claimed),$claimed->input);$this->schemas->validate($result->data,$definition->outputSchema,(int)config('ai.actions.max_output_bytes',32768));return DB::transaction(function()use($claimed,$result){$locked=ActionRun::query()->lockForUpdate()->findOrFail($claimed->id);$locked->succeed($result->data);return$locked->fresh();});}catch(\Throwable){return$this->fail($claimed,'action_output_invalid');}}
 private function context(ActionRun$r):ActionExecutionContext{return new ActionExecutionContext($r,$r->conversation()->firstOrFail(),$r->sourceMessage()->firstOrFail(),$r->runtimeRun()->firstOrFail(),$r->agent()->firstOrFail(),$r->agentVersion()->firstOrFail(),$r->contractVersion()->firstOrFail());}
 private function assertAvailable(ActionDefinition$d,int$tenantId):void{$tenant=Tenant::query()->findOrFail($tenantId);if(!$this->registry->isAvailable($d,$tenant))throw new \DomainException('Action is unavailable for this tenant.');}
}
