<?php
namespace App\Domain\AI\Actions\Services;
use App\Domain\AI\Actions\Enums\ActionRunStatus;use App\Domain\AI\Actions\Exceptions\ActionConflictException;use App\Domain\AI\Actions\Models\ActionRun;use App\Domain\AI\Agents\Services\AiLifecycleAuthorization;use App\Domain\AI\Conversations\Enums\{ConversationMessageRole,ConversationMessageStatus};use App\Domain\AI\Conversations\Models\{Conversation,ConversationMessage};use App\Domain\AI\Handoff\Services\RequestHumanHandoffService;use App\Domain\AI\Leads\Services\RecordLeadOutcomeCandidatesService;use App\Domain\AI\Runtime\Models\RuntimeRun;use App\Domain\AI\Tenancy\AiTenantBoundary;use App\Models\User;use Illuminate\Support\Facades\DB;
final class ConfirmActionRunService
{
 public function __construct(private AiLifecycleAuthorization$auth,private AiTenantBoundary$tenants,private ActionExecutor$actions,private GeneratePostActionResponseService$postAction,private RecordLeadOutcomeCandidatesService$outcomes,private RequestHumanHandoffService$handoffs){}
 public function confirm(User$actor,ActionRun$action):ConversationMessage
 {
  $authorized=$this->auth->authorize($actor);$this->tenants->assertResourceBelongsToCurrentTenant($action);
  [$conversation,$message,$agent,$version]=DB::transaction(function()use($action,$authorized){$c=Conversation::query()->lockForUpdate()->findOrFail($action->conversation_id);$a=ActionRun::query()->where('conversation_id',$c->id)->whereKey($action->id)->lockForUpdate()->firstOrFail();if($a->status!==ActionRunStatus::AwaitingConfirmation)throw new ActionConflictException('Action is no longer awaiting confirmation.');$fresh=$this->auth->revalidate($authorized);$sequence=$c->reserveActionCompletion($fresh);$m=new ConversationMessage;$m->conversation_id=$c->id;$m->sequence=$sequence;$m->role=ConversationMessageRole::Assistant;$m->status=ConversationMessageStatus::Pending;$m->content=null;$m->needs_handoff=false;$m->save();return[$c,$m,$c->agent()->firstOrFail(),$c->agentVersion()->firstOrFail()];});
  try{$executed=$this->actions->confirm($action,$actor->id);$result=$this->postAction->generate($actor,$agent,$version,$executed);return DB::transaction(function()use($conversation,$message,$result,$authorized){$c=Conversation::query()->lockForUpdate()->findOrFail($conversation->id);$m=ConversationMessage::query()->lockForUpdate()->findOrFail($message->id);$fresh=$this->auth->revalidate($authorized);$m->complete($fresh,$result->answer,(int)$result->runtimeRunId,$result->confidence,$result->needsHandoff,$result->handoffReason);$c->finishTurn($fresh,$result->needsHandoff);$run=RuntimeRun::query()->findOrFail((int)$result->runtimeRunId);$this->outcomes->record($c,$m,$run,$result->leadCandidate,$result->resolvedCandidate);if($result->needsHandoff)$this->handoffs->request($fresh,$c,$m,$run);return$m->fresh();});}catch(\Throwable$e){DB::transaction(function()use($conversation,$message,$authorized){$c=Conversation::query()->lockForUpdate()->findOrFail($conversation->id);$m=ConversationMessage::query()->lockForUpdate()->findOrFail($message->id);$fresh=$this->auth->revalidate($authorized);$m->fail($fresh,'action_completion_failed');$c->finishTurn($fresh,false);});throw$e;}
 }
}
