<?php
namespace App\Http\Controllers\B2C;use App\Http\Controllers\Controller;use App\Models\B2cFiscalProfile;use App\Models\B2cInvoiceRequest;use App\Models\B2cInvoiceRequestEvent;use App\Services\Notifications\CrmAdminNotificationService;use Illuminate\Http\Request;
final class B2cInvoiceCorrectionController extends Controller{
 private function own(Request $r,B2cInvoiceRequest $i):void{abort_unless((int)$i->user_id===(int)$r->user()->getAuthIdentifier(),403);}
 public function correct(Request $r,B2cInvoiceRequest $invoiceRequest){$this->own($r,$invoiceRequest);abort_unless($invoiceRequest->status===B2cInvoiceRequest::STATUS_RECHAZADA,409);return redirect()->route('b2c.envios.detalle',$invoiceRequest->cotizacion_id)->with('error','Actualiza tus datos fiscales y después selecciona “Reenviar solicitud”.');}
 public function resubmit(Request $r,B2cInvoiceRequest $invoiceRequest,CrmAdminNotificationService $notify){$this->own($r,$invoiceRequest);abort_unless($invoiceRequest->status===B2cInvoiceRequest::STATUS_RECHAZADA,409);$r->validate(['constancia'=>['nullable','file','mimes:pdf,jpg,jpeg,png','max:5120']]);$p=B2cFiscalProfile::where('user_id',$r->user()->getAuthIdentifier())->where('activo',true)->first();if(!$p||!$p->estaCompleto()||!$p->usoCfdiEsCompatible())return redirect()->route('b2c.configuracion')->with('error','Corrige y completa tus datos fiscales antes de reenviar.');$replaced=[];if($r->hasFile('constancia')){$old=$p->constancia_path;$p->update(['constancia_path'=>$r->file('constancia')->store('private/b2c/fiscal/'.$p->user_id,'local')]);$replaced=['constancia'=>['replaced'=>(bool)$old]];}
  $invoiceRequest->forceFill(['fiscal_profile_id'=>$p->id,'razon_social'=>$p->razon_social,'rfc'=>$p->rfc,'codigo_postal_fiscal'=>$p->codigo_postal_fiscal,'direccion_fiscal'=>$p->direccion_fiscal,'regimen_fiscal'=>$p->regimen_fiscal,'uso_cfdi'=>$p->uso_cfdi,'email_facturacion'=>$p->email_facturacion,'status'=>B2cInvoiceRequest::STATUS_SOLICITADA,'solicitada_at'=>now(),'resubmitted_at'=>now(),'rejected_at'=>null,'managed_by_user_id'=>null])->save();
  B2cInvoiceRequestEvent::create(['invoice_request_id'=>$invoiceRequest->id,'user_id'=>$r->user()->getAuthIdentifier(),'event_type'=>'RESUBMITTED','previous_status'=>B2cInvoiceRequest::STATUS_RECHAZADA,'new_status'=>B2cInvoiceRequest::STATUS_SOLICITADA,'public_reason'=>'Información fiscal corregida por el cliente.','replaced_files'=>$replaced]);$notify->invoice($invoiceRequest->fresh());return back()->with('success','Solicitud corregida y reenviada sin crear un duplicado.');}
}
