@extends('network.layout')
@section('title','Detalle onboarding - ZIGO Network')
@section('content')
<div class="eyebrow">ONBOARDING {{ substr($application->uuid,0,8) }}</div><div class="title">{{ $application->company_name }}</div>
@if($payment?->status==='APPROVED' && $application->status==='FAILED')<div class="card" style="border-color:#dc2626"><strong>PAGO CONFIRMADO — PROVISIONING FALLIDO</strong><p>No volver a cobrar. Revisa el código sanitizado y utiliza retry.</p></div>@endif
<div class="grid"><div class="card"><h2>Solicitud</h2><p>Estado: <strong>{{ $application->status }}</strong></p><p>Contacto: {{ $application->contact_name }} {{ $application->contact_last_name }}</p><p>Email: {{ $application->contact_email }}</p><p>Empresa legal: {{ $application->company_legal_name ?? '—' }}</p><p>Subdominio: {{ $application->requested_subdomain }}</p><p>Fallo: {{ $application->failure_code ?? '—' }}</p></div>
<div class="card"><h2>Pago</h2><p>Estado: <strong>{{ $payment?->status ?? 'SIN INTENTO' }}</strong></p><p>Proveedor: {{ $payment?->provider ?? '—' }}</p><p>Monto: {{ $payment ? $payment->currency.' '.$payment->amount : '—' }}</p><p>Aprobado: {{ $payment?->approved_at?->format('Y-m-d H:i') ?? '—' }}</p></div></div>
<div class="card"><h2>Snapshot comercial</h2><p>Plan: {{ data_get($application->commercial_snapshot_json,'plan.name') }}</p><p>Periodo: {{ data_get($application->commercial_snapshot_json,'billing_period') }}</p><p>Operaciones: {{ data_get($application->commercial_snapshot_json,'requested_operations') ?? '—' }}</p><p>Total: {{ $application->currency }} {{ $application->total }}</p><div class="chips">@foreach(data_get($application->commercial_snapshot_json,'modules',[]) as $module)<span class="badge">{{ $module['name'] ?? $module['code'] }}</span>@endforeach</div></div>
<div class="card"><h2>Recursos</h2><p>Tenant: {{ $application->tenant?->name ?? '—' }} / {{ $application->tenant?->uuid ?? '—' }}</p><p>Owner: {{ $application->owner?->name ?? '—' }} — {{ $application->owner?->email ?? '—' }}</p><p>Dominio: {{ $application->tenant?->domains?->firstWhere('is_primary',true)?->domain ?? '—' }}</p><p>Subscription: {{ $application->tenant?->subscriptions?->first()?->status ?? '—' }}</p></div>
@if(in_array($application->status,['PAID','FAILED'],true))<div class="card"><form method="POST" action="{{ route('network.onboarding.retry',$application->uuid) }}">@csrf<button class="btn" type="submit">Retry provisioning</button></form></div>@endif
<div class="card"><h2>Timeline</h2><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Evento</th><th>De</th><th>A</th><th>Actor</th></tr></thead><tbody>@foreach($application->events as $event)<tr><td>{{ $event->created_at?->format('Y-m-d H:i:s') }}</td><td>{{ $event->event }}</td><td>{{ $event->from_status ?? '—' }}</td><td>{{ $event->to_status ?? '—' }}</td><td>{{ $event->actor_type }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
