<?php
namespace App\Domain\Payments;
use App\Domain\Network\Channels\B2C\Models\TenantCustomerCheckout; use App\Domain\Payments\Contracts\PaymentProvider; use App\Domain\Payments\Exceptions\MercadoPagoOAuthException; use App\Domain\Payments\Models\{TenantPaymentAttempt,TenantPaymentConnection}; use Illuminate\Http\Request; use Illuminate\Support\Facades\{DB,Http,Log}; use RuntimeException;
final class MercadoPagoPaymentProvider implements PaymentProvider{
 private function cfg(string $key,mixed $default=null):mixed{return config('zigo_payments.providers.mercado_pago.'.$key,$default);}
 public function authorizationUrl(string $state,string $challenge):string{return $this->cfg('authorization_url').'?'.http_build_query(['response_type'=>'code','client_id'=>$this->cfg('client_id'),'platform_id'=>'mp','redirect_uri'=>$this->cfg('redirect_uri'),'state'=>$state,'code_challenge'=>$challenge,'code_challenge_method'=>'S256']);}
 public function exchangeAuthorizationCode(string $code,string $verifier):array{$environment=(string)$this->cfg('environment','production');$oauthTestToken=$environment==='sandbox'&&(bool)$this->cfg('oauth_test_token',true);$payload=['client_id'=>$this->cfg('client_id'),'client_secret'=>$this->cfg('client_secret'),'grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>$this->cfg('redirect_uri'),'code_verifier'=>$verifier];if($oauthTestToken)$payload['test_token']=true;$tokens=$this->token($payload);Log::info('Mercado Pago OAuth token exchanged',['environment'=>$environment,'oauth_test_token'=>$oauthTestToken,'token_kind'=>MercadoPagoTokenKind::detect($tokens['access_token']??null),'provider_account_id'=>(string)($tokens['user_id']??$tokens['user_id_test']??'')]);return $tokens;}
 public function refreshConnectionIfNeeded(TenantPaymentConnection $connection):TenantPaymentConnection{
  if(!$connection->token_expires_at||$connection->token_expires_at->gt(now()->addMinutes((int)$this->cfg('refresh_before_minutes',30))))return $connection;
  return DB::transaction(function()use($connection){$locked=TenantPaymentConnection::whereKey($connection->id)->lockForUpdate()->firstOrFail();if($locked->token_expires_at?->gt(now()->addMinutes((int)$this->cfg('refresh_before_minutes',30))))return $locked;try{$p=$this->token(['client_id'=>$this->cfg('client_id'),'client_secret'=>$this->cfg('client_secret'),'grant_type'=>'refresh_token','refresh_token'=>$locked->refresh_token]);$this->storeConnectionTokens($locked,$p);return $locked->fresh();}catch(\Throwable $e){$locked->update(['status'=>'EXPIRED']);throw $e;}});
 }
 public function createCheckout(TenantPaymentConnection $connection,TenantPaymentAttempt $attempt,TenantCustomerCheckout $checkout):array{
  $connection=$this->refreshConnectionIfNeeded($connection);$base=rtrim((string)$this->cfg('api_url'),'/');$webhook=(string)$this->cfg('webhook_url');if($webhook==='')throw new RuntimeException('ZIGO_MP_WEBHOOK_URL no está configurado.');
  $return=url('/app/checkout/'.$checkout->uuid.'/pago/retorno');$notification=$webhook.(str_contains($webhook,'?')?'&':'?').'attempt='.rawurlencode($attempt->uuid);if(!app()->environment(['local','testing']))foreach([$return.'/success',$return.'/pending',$return.'/failure',$notification] as $callback){$parts=parse_url($callback);if(($parts['scheme']??'')!=='https'||empty($parts['host'])||in_array($parts['host'],['localhost','127.0.0.1'],true))throw new RuntimeException('MERCADO_PAGO_PUBLIC_HTTPS_URL_REQUIRED');}
  $environment=(string)$this->cfg('environment','production');$payload=['items'=>[['id'=>'zigo-guide','title'=>'Guía de envío','quantity'=>1,'currency_id'=>$checkout->currency,'unit_price'=>(float)$checkout->total_amount]],'external_reference'=>$attempt->external_reference,'back_urls'=>['success'=>$return.'/success','pending'=>$return.'/pending','failure'=>$return.'/failure'],'auto_return'=>'approved','notification_url'=>$notification,'expires'=>true,'expiration_date_to'=>$checkout->expires_at?->toIso8601String()];if($environment==='production'){$email=$checkout->customerProfile?->user?->email;if($email)$payload['payer']=['email'=>$email];}if((float)$attempt->marketplace_fee_amount>0)$payload['marketplace_fee']=(float)$attempt->marketplace_fee_amount;
  Log::info('Mercado Pago preference request',['attempt_uuid'=>$attempt->uuid,'checkout_uuid'=>$checkout->uuid,'environment'=>$environment,'payer_included'=>isset($payload['payer']),'amount'=>(string)$checkout->total_amount,'currency'=>$checkout->currency,'external_reference'=>$attempt->external_reference,'marketplace_fee'=>(string)$attempt->marketplace_fee_amount]);$r=Http::acceptJson()->asJson()->withToken($connection->access_token)->withHeaders(['X-Idempotency-Key'=>$attempt->uuid])->connectTimeout((int)$this->cfg('connect_timeout',5))->timeout((int)$this->cfg('timeout',15))->post($base.'/checkout/preferences',$payload);if(!$r->successful()){Log::warning('Mercado Pago preference rejected',['attempt_uuid'=>$attempt->uuid,'checkout_uuid'=>$checkout->uuid,'status'=>$r->status(),'error'=>data_get($r->json(),'error'),'message'=>data_get($r->json(),'message')]);throw new RuntimeException('Mercado Pago no pudo crear la preferencia.');}$response=$r->json();Log::info('Mercado Pago preference accepted',['attempt_uuid'=>$attempt->uuid,'checkout_uuid'=>$checkout->uuid,'preference_id'=>$response['id']??null,'collector_id'=>$response['collector_id']??null,'sandbox_init_point_present'=>!empty($response['sandbox_init_point']),'init_point_present'=>!empty($response['init_point']),'status'=>'PENDING']);return $response;
 }
 public function retrievePayment(TenantPaymentConnection $connection,string $paymentId):array{$connection=$this->refreshConnectionIfNeeded($connection);$r=Http::acceptJson()->withToken($connection->access_token)->connectTimeout((int)$this->cfg('connect_timeout',5))->timeout((int)$this->cfg('timeout',15))->get(rtrim((string)$this->cfg('api_url'),'/').'/v1/payments/'.rawurlencode($paymentId));if(!$r->successful())throw new RuntimeException('No fue posible verificar el pago con Mercado Pago.');return $r->json();}
 public function validateWebhook(Request $request,string $dataId):bool{$secret=(string)$this->cfg('webhook_secret');$sig=(string)$request->header('x-signature');$rid=(string)$request->header('x-request-id');preg_match('/(?:^|,)\s*ts=([^,]+)/',$sig,$tm);preg_match('/(?:^|,)\s*v1=([^,]+)/',$sig,$vm);if(!$secret||!$rid||!isset($tm[1],$vm[1])||!ctype_digit($tm[1]))return false;$issued=(int)$tm[1];if($issued>99999999999)$issued=(int)floor($issued/1000);if(abs(time()-$issued)>(int)$this->cfg('webhook_tolerance_seconds',300))return false;$manifest='id:'.strtolower(trim($dataId)).';request-id:'.$rid.';ts:'.$tm[1].';';return hash_equals(hash_hmac('sha256',$manifest,$secret),trim($vm[1]));}
 public function storeConnectionTokens(TenantPaymentConnection $c,array $p):void{$c->update(['provider_account_id'=>(string)($p['user_id']??$p['user_id_test']??''),'access_token'=>$p['access_token'],'refresh_token'=>$p['refresh_token']??$c->refresh_token,'token_expires_at'=>now()->addSeconds((int)($p['expires_in']??0)),'scopes'=>isset($p['scope'])?preg_split('/\s+/',trim((string)$p['scope'])):null,'status'=>'CONNECTED','connected_at'=>now(),'disconnected_at'=>null]);}
 private function token(array $payload):array{$r=Http::acceptJson()->asJson()->connectTimeout((int)$this->cfg('connect_timeout',5))->timeout((int)$this->cfg('timeout',15))->post(rtrim((string)$this->cfg('api_url'),'/').'/oauth/token',$payload);$body=$r->json();if(!$r->successful()||!is_array($body)||empty($body['access_token'])){Log::warning('Mercado Pago OAuth token exchange failed',['status'=>$r->status(),'error'=>is_array($body)&&is_scalar($body['error']??null)?(string)$body['error']:null,'message'=>is_array($body)&&is_scalar($body['message']??null)?(string)$body['message']:null,'cause_code'=>is_array($body)&&is_scalar(data_get($body,'cause.0.code'))?(string)data_get($body,'cause.0.code'):null]);throw new MercadoPagoOAuthException('Mercado Pago rechazó el intercambio OAuth.');}return $body;}
}
