<?php
namespace App\Domain\Payments;
use App\Domain\Network\Channels\B2C\Models\TenantCustomerCheckout; use App\Domain\Payments\Contracts\PaymentProvider; use App\Domain\Payments\Models\{TenantPaymentAttempt,TenantPaymentConnection}; use Illuminate\Http\Request; use Illuminate\Support\Facades\{DB,Http}; use RuntimeException;
final class MercadoPagoPaymentProvider implements PaymentProvider{
 private function cfg(string $key,mixed $default=null):mixed{return config('zigo_payments.providers.mercado_pago.'.$key,$default);}
 public function authorizationUrl(string $state,string $challenge):string{return $this->cfg('authorization_url').'?'.http_build_query(['response_type'=>'code','client_id'=>$this->cfg('client_id'),'redirect_uri'=>$this->cfg('redirect_uri'),'state'=>$state,'code_challenge'=>$challenge,'code_challenge_method'=>'S256']);}
 public function exchangeAuthorizationCode(string $code,string $verifier):array{return $this->token(['client_id'=>$this->cfg('client_id'),'client_secret'=>$this->cfg('client_secret'),'grant_type'=>'authorization_code','code'=>$code,'redirect_uri'=>$this->cfg('redirect_uri'),'code_verifier'=>$verifier]);}
 public function refreshConnectionIfNeeded(TenantPaymentConnection $connection):TenantPaymentConnection{
  if(!$connection->token_expires_at||$connection->token_expires_at->gt(now()->addMinutes((int)$this->cfg('refresh_before_minutes',30))))return $connection;
  return DB::transaction(function()use($connection){$locked=TenantPaymentConnection::whereKey($connection->id)->lockForUpdate()->firstOrFail();if($locked->token_expires_at?->gt(now()->addMinutes((int)$this->cfg('refresh_before_minutes',30))))return $locked;try{$p=$this->token(['client_id'=>$this->cfg('client_id'),'client_secret'=>$this->cfg('client_secret'),'grant_type'=>'refresh_token','refresh_token'=>$locked->refresh_token]);$this->storeConnectionTokens($locked,$p);return $locked->fresh();}catch(\Throwable $e){$locked->update(['status'=>'EXPIRED']);throw $e;}});
 }
 public function createCheckout(TenantPaymentConnection $connection,TenantPaymentAttempt $attempt,TenantCustomerCheckout $checkout):array{
  $connection=$this->refreshConnectionIfNeeded($connection);$base=rtrim((string)$this->cfg('api_url'),'/');$webhook=(string)$this->cfg('webhook_url');if($webhook==='')throw new RuntimeException('ZIGO_MP_WEBHOOK_URL no está configurado.');
  $return=url('/app/checkout/'.$checkout->uuid.'/pago/retorno');$payload=['items'=>[['id'=>'zigo-guide','title'=>'Guía de envío','quantity'=>1,'currency_id'=>$checkout->currency,'unit_price'=>(float)$checkout->total_amount]],'external_reference'=>$attempt->external_reference,'back_urls'=>['success'=>$return.'/success','pending'=>$return.'/pending','failure'=>$return.'/failure'],'auto_return'=>'approved','notification_url'=>$webhook.'?attempt='.rawurlencode($attempt->uuid),'expires'=>true,'expiration_date_to'=>$checkout->expires_at?->toIso8601String()];if((float)$attempt->marketplace_fee_amount>0)$payload['marketplace_fee']=(float)$attempt->marketplace_fee_amount;
  $r=Http::acceptJson()->asJson()->withToken($connection->access_token)->withHeaders(['X-Idempotency-Key'=>$attempt->uuid])->connectTimeout((int)$this->cfg('connect_timeout',5))->timeout((int)$this->cfg('timeout',15))->post($base.'/checkout/preferences',$payload);if(!$r->successful())throw new RuntimeException('Mercado Pago no pudo crear la preferencia.');return $r->json();
 }
 public function retrievePayment(TenantPaymentConnection $connection,string $paymentId):array{$connection=$this->refreshConnectionIfNeeded($connection);$r=Http::acceptJson()->withToken($connection->access_token)->connectTimeout((int)$this->cfg('connect_timeout',5))->timeout((int)$this->cfg('timeout',15))->get(rtrim((string)$this->cfg('api_url'),'/').'/v1/payments/'.rawurlencode($paymentId));if(!$r->successful())throw new RuntimeException('No fue posible verificar el pago con Mercado Pago.');return $r->json();}
 public function validateWebhook(Request $request,string $dataId):bool{$secret=(string)$this->cfg('webhook_secret');$sig=(string)$request->header('x-signature');$rid=(string)$request->header('x-request-id');preg_match('/(?:^|,)\s*ts=([^,]+)/',$sig,$tm);preg_match('/(?:^|,)\s*v1=([^,]+)/',$sig,$vm);if(!$secret||!$rid||!isset($tm[1],$vm[1])||!ctype_digit($tm[1]))return false;$issued=(int)$tm[1];if($issued>99999999999)$issued=(int)floor($issued/1000);if(abs(time()-$issued)>(int)$this->cfg('webhook_tolerance_seconds',300))return false;$manifest='id:'.strtolower(trim($dataId)).';request-id:'.$rid.';ts:'.$tm[1].';';return hash_equals(hash_hmac('sha256',$manifest,$secret),trim($vm[1]));}
 public function storeConnectionTokens(TenantPaymentConnection $c,array $p):void{$c->update(['provider_account_id'=>(string)($p['user_id']??$p['user_id_test']??''),'access_token'=>$p['access_token'],'refresh_token'=>$p['refresh_token']??$c->refresh_token,'token_expires_at'=>now()->addSeconds((int)($p['expires_in']??0)),'scopes'=>isset($p['scope'])?preg_split('/\s+/',trim((string)$p['scope'])):null,'status'=>'CONNECTED','connected_at'=>now(),'disconnected_at'=>null]);}
 private function token(array $payload):array{$r=Http::acceptJson()->asJson()->connectTimeout((int)$this->cfg('connect_timeout',5))->timeout((int)$this->cfg('timeout',15))->post(rtrim((string)$this->cfg('api_url'),'/').'/oauth/token',$payload);if(!$r->successful()||!is_array($r->json())||empty($r->json('access_token')))throw new RuntimeException('Mercado Pago rechazó el intercambio OAuth.');return $r->json();}
}
