<?php
namespace App\Domain\Payments;
use App\Domain\Network\Channels\B2C\CustomerCheckoutFulfillmentService; use App\Domain\Network\Channels\B2C\Models\TenantCustomerCheckout; use App\Domain\Payments\Contracts\PaymentProvider; use App\Domain\Payments\Models\{TenantPaymentAttempt,TenantPaymentConnection,TenantPaymentEvent}; use Illuminate\Http\Request; use Illuminate\Support\Facades\{DB,Log}; use Illuminate\Support\Str; use RuntimeException;
final class TenantPaymentService{
 public function __construct(private PaymentProvider $provider,private CustomerCheckoutFulfillmentService $fulfillment){}
 public function createAttempt(TenantCustomerCheckout $checkout,TenantPaymentConnection $connection):TenantPaymentAttempt{
  return DB::transaction(function()use($checkout,$connection){$locked=TenantCustomerCheckout::whereKey($checkout->id)->lockForUpdate()->firstOrFail();abort_unless($locked->status==='PENDING_PAYMENT'&&!$locked->expires_at?->isPast(),409);$existing=TenantPaymentAttempt::where('checkout_id',$locked->id)->whereIn('status',['CREATED','PENDING'])->latest('id')->first();if($existing&&$existing->init_point)return $existing;$fee=config('zigo_payments.providers.mercado_pago.marketplace_fee_enabled')?(string)config('zigo_payments.providers.mercado_pago.marketplace_fee_amount','0.00'):'0.00';abort_if(bccomp($fee,'0.00',2)<0||bccomp($fee,(string)$locked->total_amount,2)>0,500);return TenantPaymentAttempt::create(['tenant_id'=>$locked->tenant_id,'customer_profile_id'=>$locked->customer_profile_id,'checkout_id'=>$locked->id,'payment_connection_id'=>$connection->id,'provider'=>'MERCADO_PAGO','status'=>'CREATED','external_reference'=>'zg_'.Str::lower(Str::random(48)),'amount'=>$locked->total_amount,'currency'=>$locked->currency,'marketplace_fee_amount'=>$fee]);});
 }
 public function initialize(TenantPaymentAttempt $attempt):TenantPaymentAttempt{$data=$this->provider->createCheckout($attempt->connection,$attempt,$attempt->checkout);$id=(string)($data['id']??'');$url=(string)($data[config('zigo_payments.providers.mercado_pago.environment')==='production'?'init_point':'sandbox_init_point']??$data['init_point']??'');abort_unless($id&&$this->safeProviderUrl($url),502);$attempt->update(['provider_preference_id'=>$id,'init_point'=>$url,'status'=>'PENDING']);Log::info('Payment preference created',['attempt_uuid'=>$attempt->uuid,'tenant_id'=>$attempt->tenant_id,'checkout_uuid'=>$attempt->checkout->uuid,'status'=>'PENDING']);return $attempt->fresh();}
 public function webhook(Request $request):void{$dataId=(string)$request->query('data.id',$request->input('data.id',''));abort_unless($this->provider->validateWebhook($request,$dataId),401);$attempt=TenantPaymentAttempt::with(['connection','checkout'])->where('uuid',(string)$request->query('attempt'))->first();if(!$attempt)return;$eventKey=(string)$request->header('x-request-id').':'.$dataId;$event=TenantPaymentEvent::firstOrCreate(['provider'=>'MERCADO_PAGO','event_key'=>$eventKey],['payment_attempt_id'=>$attempt->id,'event_type'=>(string)$request->input('type',$request->query('type')),'provider_payment_id'=>$dataId,'status'=>'RECEIVED','received_at'=>now()]);if(!$event->wasRecentlyCreated||$event->status==='PROCESSED')return;
  try{$payment=$this->provider->retrievePayment($attempt->connection,$dataId);$this->validatePayment($attempt,$payment);$status=strtolower((string)($payment['status']??''));DB::transaction(function()use($attempt,$event,$payment,$status){$locked=TenantPaymentAttempt::whereKey($attempt->id)->lockForUpdate()->firstOrFail();$pid=(string)$payment['id'];$conflict=TenantPaymentAttempt::where('provider_payment_id',$pid)->whereKeyNot($locked->id)->exists();if($conflict)throw new RuntimeException('PAYMENT_ID_CONFLICT');if($status==='approved'){$locked->update(['provider_payment_id'=>$pid,'status'=>'APPROVED','approved_at'=>now()]);$this->fulfillment->approve($locked->checkout,'MERCADO_PAGO',$pid);}elseif(in_array($status,['rejected','cancelled','canceled'],true)){$locked->update(['provider_payment_id'=>$pid,'status'=>strtoupper($status==='cancelled'?'CANCELED':$status),'rejected_at'=>now()]);}else{$locked->update(['provider_payment_id'=>$pid,'status'=>'PENDING']);}$event->update(['status'=>'PROCESSED','processed_at'=>now()]);});}catch(\Throwable $e){$event->update(['status'=>'INCONSISTENT','error_code'=>Str::limit($e->getMessage(),80,''),'processed_at'=>now()]);Log::warning('Payment webhook rejected',['attempt_uuid'=>$attempt->uuid,'tenant_id'=>$attempt->tenant_id,'event_key'=>$eventKey,'reason'=>$event->error_code]);}
 }
 private function validatePayment(TenantPaymentAttempt $a,array $p):void{if((string)($p['id']??'')===''||(string)($p['external_reference']??'')!==$a->external_reference)throw new RuntimeException('REFERENCE_MISMATCH');if(bccomp((string)($p['transaction_amount']??''),(string)$a->amount,2)!==0)throw new RuntimeException('AMOUNT_MISMATCH');if((string)($p['currency_id']??'')!==$a->currency)throw new RuntimeException('CURRENCY_MISMATCH');if((string)($p['collector_id']??'')!==(string)$a->connection->provider_account_id)throw new RuntimeException('SELLER_MISMATCH');}
 private function safeProviderUrl(string $url):bool{$p=parse_url($url);return ($p['scheme']??'')==='https'&&preg_match('/(^|\.)mercadopago\.com(\.mx)?$/i',(string)($p['host']??''));}
}
