<?php
namespace App\Domain\AI\Knowledge\Models;use App\Domain\AI\Agents\Data\AuthorizedAiLifecycleActor;use App\Domain\AI\Knowledge\Data\KnowledgeChunkData;use App\Domain\AI\Knowledge\Enums\KnowledgeIndexStatus;use App\Domain\AI\Tenancy\AiTenantModel;use App\Models\User;use Illuminate\Database\Eloquent\Relations\{BelongsTo,HasMany};use Illuminate\Support\Str;
final class KnowledgeIndex extends AiTenantModel
{
 protected$table='ai_knowledge_indexes';protected$guarded=['*'];protected$casts=['status'=>KnowledgeIndexStatus::class,'chunk_count'=>'integer','requested_at'=>'datetime','started_at'=>'datetime','completed_at'=>'datetime','failed_at'=>'datetime'];public function getRouteKeyName():string{return'uuid';}public function isAiAppendOnly():bool{return true;}protected function immutableIdentityAttributes():array{return['uuid','knowledge_source_id','knowledge_source_version_id','status','schema_version','content_checksum','chunk_count','requested_by_user_id','requested_at','started_at','completed_at','failed_at','safe_error_code'];}protected static function booted():void{parent::booted();static::creating(fn(self$m)=>$m->uuid??=(string)Str::uuid());}
 public function source():BelongsTo{return$this->belongsTo(KnowledgeSource::class,'knowledge_source_id');}public function knowledgeVersion():BelongsTo{return$this->belongsTo(KnowledgeSourceVersion::class,'knowledge_source_version_id');}public function requester():BelongsTo{return$this->belongsTo(User::class,'requested_by_user_id');}public function chunks():HasMany{return$this->hasMany(KnowledgeChunk::class,'knowledge_index_id');}
 public function markProcessing(AuthorizedAiLifecycleActor$a):void{$this->assertLifecycleActor($a);if(!in_array($this->status,[KnowledgeIndexStatus::Pending,KnowledgeIndexStatus::Failed],true))throw new \DomainException('Knowledge index cannot start.');$this->persistNamedLifecycle(['status','started_at','completed_at','failed_at','safe_error_code','chunk_count'],function(){$this->status=KnowledgeIndexStatus::Processing;$this->started_at=now();$this->completed_at=null;$this->failed_at=null;$this->safe_error_code=null;$this->chunk_count=0;});}
 public function markReady(AuthorizedAiLifecycleActor$a,int$count):void{$this->assertLifecycleActor($a);if($this->status!==KnowledgeIndexStatus::Processing)throw new \DomainException('Knowledge index cannot complete.');$this->persistNamedLifecycle(['status','chunk_count','completed_at'],function()use($count){$this->status=KnowledgeIndexStatus::Ready;$this->chunk_count=$count;$this->completed_at=now();});}
 public function markFailed(AuthorizedAiLifecycleActor$a,string$code):void{$this->assertLifecycleActor($a);if(!in_array($code,['invalid_content','checksum_mismatch','source_archived','indexing_failed'],true))throw new \InvalidArgumentException('Invalid safe indexing error code.');if(!in_array($this->status,[KnowledgeIndexStatus::Pending,KnowledgeIndexStatus::Processing,KnowledgeIndexStatus::Failed],true))throw new \DomainException('Knowledge index cannot fail.');$this->persistNamedLifecycle(['status','failed_at','safe_error_code','chunk_count'],function()use($code){$this->status=KnowledgeIndexStatus::Failed;$this->failed_at=now();$this->safe_error_code=$code;$this->chunk_count=0;});}
 public function createChunk(AuthorizedAiLifecycleActor$a,KnowledgeChunkData$data):KnowledgeChunk{$this->assertLifecycleActor($a);if($this->status!==KnowledgeIndexStatus::Processing)throw new \DomainException('Chunks require a processing index.');$chunk=new KnowledgeChunk();$chunk->knowledge_index_id=$this->id;$chunk->knowledge_source_id=$this->knowledge_source_id;$chunk->knowledge_source_version_id=$this->knowledge_source_version_id;$chunk->sequence=$data->sequence;$chunk->content=$data->content;$chunk->locator=$data->locator;$chunk->content_checksum=$data->checksum;$chunk->character_count=$data->characterCount;$chunk->save();return$chunk;}
 public function clearChunks(AuthorizedAiLifecycleActor$a):void{$this->assertLifecycleActor($a);if($this->status!==KnowledgeIndexStatus::Processing)throw new \DomainException('Chunks can only be cleared while processing.');(new KnowledgeChunk())->newModelQuery()->toBase()->where('knowledge_index_id',$this->id)->delete();}
}
