<?php
namespace Tests\Feature;
use App\Mail\CrmAdminEventMail;use App\Models\CrmClient;use App\Services\Exports\SimpleXlsxWriter;use App\Services\Notifications\CrmAdminNotificationService;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Mail;use Illuminate\Support\Facades\Schema;use Tests\TestCase;use ZipArchive;
final class AdminNotificationsGuidesExportInvoiceRejectionClosureTest extends TestCase{
 protected function setUp():void{parent::setUp();config(['database.default'=>'sqlite','database.connections.sqlite'=>['driver'=>'sqlite','database'=>':memory:','prefix'=>'','foreign_key_constraints'=>false]]);DB::purge('sqlite');DB::reconnect('sqlite');Schema::create('crm_clients',function(Blueprint $t){$t->id();$t->string('name')->nullable();$t->string('company_name')->nullable();$t->string('contact_name')->nullable();$t->string('email')->nullable();$t->string('phone')->nullable();$t->text('notes')->nullable();$t->timestamps();});Schema::create('zigo_notification_deliveries',function(Blueprint $t){$t->id();$t->string('event_key')->unique();$t->string('event_type');$t->string('notifiable_type');$t->unsignedBigInteger('notifiable_id');$t->json('recipients')->nullable();$t->string('status')->default('PENDING');$t->unsignedSmallInteger('attempts')->default(0);$t->timestamp('sent_at')->nullable();$t->timestamp('failed_at')->nullable();$t->string('last_error')->nullable();$t->timestamps();});}
 public function test_prospect_notification_multiple_recipients_and_idempotency():void{Mail::fake();config(['zigo_notifications.enabled'=>true,'zigo_notifications.prospect'=>true,'zigo_notifications.emails'=>['one@example.test','two@example.test']]);$p=CrmClient::create(['name'=>'Ana','company_name'=>'ACME','email'=>'ana@example.test']);$s=app(CrmAdminNotificationService::class);$s->prospect($p);$s->prospect($p);Mail::assertSent(CrmAdminEventMail::class,1);$this->assertSame(1,DB::table('zigo_notification_deliveries')->count());$this->assertSame('SENT',DB::table('zigo_notification_deliveries')->value('status'));}
 public function test_disabled_flag_sends_nothing():void{Mail::fake();config(['zigo_notifications.enabled'=>true,'zigo_notifications.prospect'=>false,'zigo_notifications.emails'=>['one@example.test']]);app(CrmAdminNotificationService::class)->prospect(CrmClient::create(['name'=>'Ana','email'=>'ana@example.test']));Mail::assertNothingSent();}
 public function test_xlsx_is_valid_and_uses_dash_for_null():void{$path=sys_get_temp_dir().DIRECTORY_SEPARATOR.'zigo-'.uniqid().'.xlsx';$count=app(SimpleXlsxWriter::class)->write($path,['Cotización','Tracking'],function($append){$append([1,null]);});$this->assertSame(1,$count);$zip=new ZipArchive();$this->assertTrue($zip->open($path)===true);$sheet=$zip->getFromName('xl/worksheets/sheet1.xml');$zip->close();unlink($path);$this->assertStringContainsString('Cotización',$sheet);$this->assertStringContainsString('—',$sheet);}
 public function test_export_and_invoice_templates_hide_internal_fields():void{$files=[resource_path('views/email/crm-admin-event.blade.php'),resource_path('views/email/invoice-request-rejected.blade.php'),app_path('Http/Controllers/CRM/CrmGuideExportController.php')];foreach($files as $f){$v=file_get_contents($f);foreach(['provider_base_price','provider_total','guia_response_snapshot','internal_notes'] as $secret)$this->assertStringNotContainsString($secret,$v);}}
}
