<?php
namespace Tests\Feature;
use Illuminate\Support\Facades\Route;
use Tests\TestCase;
final class AiWebchatHttpTest extends TestCase
{
 public function test_public_route_inventory_is_minimal_and_rate_limited():void{$routes=collect(Route::getRoutes())->filter(fn($r)=>str_starts_with((string)$r->getName(),'ai.webchat.'));$names=$routes->pluck('action.as')->filter()->values()->all();foreach(['ai.webchat.sessions.start','ai.webchat.messages.store','ai.webchat.messages.index','ai.webchat.actions.confirm','ai.webchat.widget','ai.webchat.hosted']as$name)$this->assertContains($name,$names);foreach(['ai.webchat.sessions.start','ai.webchat.messages.store','ai.webchat.messages.index','ai.webchat.actions.confirm']as$name)$this->assertStringContainsString('throttle:ai-webchat',implode(',',Route::getRoutes()->getByName($name)->gatherMiddleware()));}
 public function test_widget_uses_shadow_dom_text_content_session_storage_and_no_unsafe_dom_execution():void{$js=file_get_contents(public_path('ai/webchat/widget.js'));foreach(['attachShadow','textContent','sessionStorage','crypto.randomUUID']as$required)$this->assertStringContainsString($required,$js);foreach(['innerHTML','document.write','eval(','new Function(']as$forbidden)$this->assertStringNotContainsString($forbidden,$js);}
 public function test_public_controller_allowlists_payload_and_hides_internal_identity():void{$php=file_get_contents(app_path('Http/Controllers/Webchat/PublicWebchatController.php'));foreach(['tenant_id','agent_id','agent_version_id','contract_version_id','execution_mode','provider']as$field)$this->assertStringNotContainsString("'$field'=>",$php);$this->assertStringContainsString('unsupported_parameter',$php);$this->assertStringContainsString('session_token',$php);}
 public function test_admin_routes_are_inside_existing_tenant_ai_shell():void{foreach(['tenant.admin.ai-agents.webchat.show','tenant.admin.ai-agents.webchat.update','tenant.admin.ai-agents.webchat.rotate']as$name){$route=Route::getRoutes()->getByName($name);$this->assertNotNull($route);$middleware=$route->gatherMiddleware();$this->assertContains('tenant.auth',$middleware);$this->assertContains('tenant.entitlement:AI_CORE',$middleware);}}
 public function test_webchat_cors_boundary_precedes_legacy_handler_and_is_noop_elsewhere():void{$kernel=file_get_contents(app_path('Http/Kernel.php'));$this->assertLessThan(strpos($kernel,'HandleCors::class'),strpos($kernel,'IsolateWebchatCors::class'));$response=$this->call('OPTIONS','/api/non-webchat-cors-probe',[],[],[],['HTTP_ORIGIN'=>'https://legacy.test','HTTP_ACCESS_CONTROL_REQUEST_METHOD'=>'POST']);$this->assertNotNull($response->headers->get('Access-Control-Allow-Origin'));}
}
