<?php
namespace Tests\Feature;
use App\Domain\AI\Channels\Webchat\Models\{WebchatChannel,WebchatSession};
use App\Domain\AI\Channels\Webchat\Support\WebchatOriginPolicy;
use App\Domain\Network\Tenancy\Models\Tenant;
use App\Domain\Network\Tenancy\TenantContext;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\{DB,Schema};
use Tests\TestCase;
final class AiWebchatFoundationTest extends TestCase
{
 protected function setUp():void{parent::setUp();config(['database.default'=>'sqlite','database.connections.sqlite.database'=>':memory:','app.key'=>'base64:'.base64_encode(str_repeat('w',32))]);DB::statement('PRAGMA foreign_keys=ON');$this->base();}
 public function test_migration_up_down_up_and_restrict_foreign_keys():void{$m=$this->migration();$m->up();$this->assertTrue(Schema::hasTable('ai_webchat_channels'));$this->assertNotEmpty(DB::select("PRAGMA foreign_key_list('ai_webchat_sessions')"));$m->down();$this->assertFalse(Schema::hasTable('ai_webchat_channels'));$m->up();$this->assertSame(1,(int)DB::selectOne('PRAGMA foreign_keys')->foreign_keys);}
 public function test_public_keys_and_session_tokens_are_opaque_unique_and_hashed():void{$this->migration()->up();[$tenant,$channel,$conversation]=$this->records();$plain=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$session=new WebchatSession;$session->tenant_id=$tenant->id;$session->webchat_channel_id=$channel->id;$session->conversation_id=$conversation;$session->token_hash=hash('sha256',$plain);$session->expires_at=now()->addDay();$session->last_seen_at=now();$session->save();$this->assertStringStartsWith('wc_',$channel->public_key);$this->assertSame(46,strlen($channel->public_key));$this->assertNotSame($plain,$session->token_hash);$this->assertSame(hash('sha256',$plain),DB::table('ai_webchat_sessions')->value('token_hash'));}
 public function test_session_expiry_and_same_agent_guard():void{$this->migration()->up();[$tenant,$channel,$conversation]=$this->records();$session=new WebchatSession;$session->tenant_id=$tenant->id;$session->webchat_channel_id=$channel->id;$session->conversation_id=$conversation;$session->token_hash=hash('sha256','expired');$session->expires_at=now()->subSecond();$session->last_seen_at=now();$session->save();$this->assertFalse($session->isAvailable());DB::table('ai_agents')->insert(['id'=>2,'tenant_id'=>$tenant->id]);$other=DB::table('ai_conversations')->insertGetId(['tenant_id'=>$tenant->id,'agent_id'=>2]);$this->expectException(\DomainException::class);$bad=new WebchatSession;$bad->tenant_id=$tenant->id;$bad->webchat_channel_id=$channel->id;$bad->conversation_id=$other;$bad->token_hash=hash('sha256','bad');$bad->expires_at=now()->addDay();$bad->last_seen_at=now();$bad->save();}
 public function test_origin_policy_canonicalizes_and_rejects_spoofing_and_unsafe_schemes():void{$p=app(WebchatOriginPolicy::class);$this->assertSame('https://cliente.test',$p->canonicalize('https://CLIENTE.test'));$this->assertTrue($p->permits(['https://cliente.test'],'https://cliente.test'));$this->assertFalse($p->permits(['https://cliente.test'],'https://cliente.test.evil.com'));foreach(['javascript:alert(1)','https://u:p@cliente.test/path','file://cliente.test']as$bad)try{$p->canonicalize($bad);$this->fail('Unsafe origin accepted.');}catch(\InvalidArgumentException){$this->addToAssertionCount(1);}}
 private function records():array{$tenant=Tenant::query()->create(['name'=>'Webchat','slug'=>'webchat','status'=>'active']);app(TenantContext::class)->set($tenant);DB::table('users')->insert(['id'=>1]);DB::table('ai_agents')->insert(['id'=>1,'tenant_id'=>$tenant->id]);$channel=new WebchatChannel;$channel->tenant_id=$tenant->id;$channel->agent_id=1;$channel->enabled=true;$channel->display_name='Demo';$channel->primary_color='#2563EB';$channel->launcher_label='Chat';$channel->allowed_origins=['https://cliente.test'];$channel->created_by_user_id=1;$channel->save();$conversation=DB::table('ai_conversations')->insertGetId(['tenant_id'=>$tenant->id,'agent_id'=>1]);return[$tenant,$channel,$conversation];}
 private function migration(){return require base_path('database/migrations/2026_09_01_100000_create_ai_webchat.php');}
 private function base():void{Schema::create('users',fn(Blueprint$t)=>$t->id());Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid');$t->string('name')->nullable();$t->string('slug')->nullable();$t->string('status')->nullable();$t->timestamps();$t->unique(['id']);});Schema::create('ai_agents',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unique(['tenant_id','id']);});Schema::create('ai_conversations',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('agent_id');$t->unique(['tenant_id','id']);});}
}
