<?php
namespace Tests\Feature;
use App\Domain\AI\Channels\WhatsApp\Jobs\ProcessWhatsAppInboundJob;use App\Domain\AI\Channels\WhatsApp\Models\WhatsAppChannel;use App\Domain\AI\Channels\WhatsApp\Services\ResolveWhatsAppChannelService;use App\Http\Controllers\WhatsApp\WhatsAppWebhookController;use App\Domain\Network\Tenancy\Models\Tenant;use Illuminate\Database\Schema\Blueprint;use Illuminate\Http\Request;use Illuminate\Support\Facades\{DB,Http,Queue,Route,Schema};use Tests\TestCase;
final class AiWhatsAppWebhookTest extends TestCase{
 protected function setUp():void{parent::setUp();Http::preventStrayRequests();}
 public function test_public_surface_is_webhook_only_and_rate_limited():void{$r=Route::getRoutes()->getByName('ai.whatsapp.webhook');$this->assertNotNull($r);$this->assertSame(['GET','POST'],array_values(array_diff($r->methods(),['HEAD'])));$this->assertStringContainsString('throttle:ai-whatsapp-webhook',implode(',',$r->gatherMiddleware()));foreach(Route::getRoutes()as$route)$this->assertFalse(str_contains($route->uri(),'whatsapp/send'));}
 public function test_valid_raw_signature_fast_acks_queues_once_and_changed_body_rejects():void{$this->database();[$channel,$resolver]=$this->channel();Queue::fake();$body=json_encode(['entry'=>[['changes'=>[['value'=>['metadata'=>['phone_number_id'=>'pn_1'],'contacts'=>[['profile'=>['name'=>'Persona']]],'messages'=>[['id'=>'wamid.1','from'=>'5218111111111','type'=>'text','text'=>['body'=>'Hola']]]]]]]]],JSON_THROW_ON_ERROR);$signature='sha256='.hash_hmac('sha256',$body,'app-secret');$controller=app(WhatsAppWebhookController::class);$request=Request::create('/','POST',[],[],[],['HTTP_X_HUB_SIGNATURE_256'=>$signature],$body);$response=$controller->receive($request,$channel->webhook_key,$resolver);$this->assertSame(200,$response->getStatusCode());$this->app->terminate();$this->assertSame(1,DB::table('ai_whatsapp_inbound_receipts')->count());Queue::assertPushed(ProcessWhatsAppInboundJob::class,1);$controller->receive($request,$channel->webhook_key,$resolver);$this->assertSame(1,DB::table('ai_whatsapp_inbound_receipts')->count());try{$bad=Request::create('/','POST',[],[],[],['HTTP_X_HUB_SIGNATURE_256'=>$signature],$body.' ');$controller->receive($bad,$channel->webhook_key,$resolver);$this->fail('Changed raw body accepted.');}catch(\Symfony\Component\HttpKernel\Exception\HttpException$e){$this->assertSame(403,$e->getStatusCode());}}
 public function test_verification_is_timing_safe_and_wrong_token_rejects():void{$this->database();[$channel,$resolver]=$this->channel();$c=app(WhatsAppWebhookController::class);$ok=Request::create('/','GET',['hub_mode'=>'subscribe','hub_verify_token'=>'verify-secret','hub_challenge'=>'12345']);$this->assertSame('12345',$c->verify($ok,$channel->webhook_key,$resolver)->getContent());try{$bad=Request::create('/','GET',['hub_mode'=>'subscribe','hub_verify_token'=>'wrong','hub_challenge'=>'12345']);$c->verify($bad,$channel->webhook_key,$resolver);$this->fail('Wrong verify token accepted.');}catch(\Symfony\Component\HttpKernel\Exception\HttpException$e){$this->assertSame(403,$e->getStatusCode());}}
 public function test_received_redelivery_restores_a_lost_after_response_dispatch():void{$this->database();[$channel,$resolver]=$this->channel();Queue::fake();$body=json_encode(['entry'=>[['changes'=>[['value'=>['metadata'=>['phone_number_id'=>'pn_1'],'messages'=>[['id'=>'wamid.recover','from'=>'5218111111111','type'=>'text','text'=>['body'=>'Hola']]]]]]]]],JSON_THROW_ON_ERROR);$request=Request::create('/','POST',[],[],[],['HTTP_X_HUB_SIGNATURE_256'=>'sha256='.hash_hmac('sha256',$body,'app-secret')],$body);$controller=app(WhatsAppWebhookController::class);$controller->receive($request,$channel->webhook_key,$resolver);$property=new \ReflectionProperty($this->app,'terminatingCallbacks');$property->setValue($this->app,[]);Queue::assertNothingPushed();$controller->receive($request,$channel->webhook_key,$resolver);$this->app->terminate();Queue::assertPushed(ProcessWhatsAppInboundJob::class,1);$this->assertSame('received',DB::table('ai_whatsapp_inbound_receipts')->value('status'));}
 public function test_webhook_authenticates_before_parsing_and_adapter_is_server_controlled():void{$s=file_get_contents(app_path('Http/Controllers/WhatsApp/WhatsAppWebhookController.php'));$this->assertLessThan(strpos($s,'json_decode($raw'),strpos($s,"hash_hmac('sha256',\$raw"));$this->assertStringNotContainsString('ModelGateway',$s);$adapter=file_get_contents(app_path('Infrastructure/WhatsApp/MetaCloudWhatsAppProvider.php'));foreach(['graph_base_url','graph_version','MetaCloudWhatsAppCredentialsResolver','withToken','connectTimeout','timeout','messaging_product','interactive']as$x)$this->assertStringContainsString($x,$adapter);foreach(['WhatsAppChannel','request->url','tenant_url','custom_endpoint','retry(']as$x)$this->assertStringNotContainsString($x,$adapter);}
 private function channel():array{$tenant=Tenant::create(['name'=>'WA','slug'=>'wa','status'=>'active']);DB::table('users')->insert(['id'=>1]);DB::table('ai_agents')->insert(['id'=>1,'tenant_id'=>$tenant->id]);$c=new WhatsAppChannel;$c->tenant_id=$tenant->id;$c->agent_id=1;$c->enabled=true;$c->phone_number_id='pn_1';$c->created_by_user_id=1;$c->setAccessToken('access');$c->setAppSecret('app-secret');$c->setVerifyToken('verify-secret');$c->save();$resolver=$this->mock(ResolveWhatsAppChannelService::class);$resolver->shouldReceive('resolve')->andReturn($c);return[$c,$resolver];}
 private function database():void{config(['database.default'=>'sqlite','database.connections.sqlite.database'=>':memory:','app.key'=>'base64:'.base64_encode(str_repeat('r',32))]);DB::purge();DB::reconnect();DB::statement('PRAGMA foreign_keys=ON');Schema::create('users',fn(Blueprint$t)=>$t->id());Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid');$t->string('name')->nullable();$t->string('slug')->nullable();$t->string('status')->nullable();$t->timestamps();$t->unique(['id']);});Schema::create('ai_agents',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unique(['tenant_id','id']);});Schema::create('ai_conversations',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('agent_id');$t->unique(['tenant_id','id']);});Schema::create('ai_conversation_messages',fn(Blueprint$t)=>$t->id());Schema::create('ai_action_runs',fn(Blueprint$t)=>$t->id());(require database_path('migrations/2026_09_02_100000_create_ai_whatsapp_channel.php'))->up();}
}
