<?php
namespace Tests\Feature;
use App\Domain\AI\Channels\WhatsApp\Contracts\WhatsAppProvider;use App\Domain\AI\Channels\WhatsApp\Data\{WhatsAppOutboundConfirmationRequest,WhatsAppOutboundTextRequest};use App\Domain\AI\Channels\WhatsApp\Support\WhatsAppDeliveryStatusPolicy;use App\Domain\AI\Conversations\Enums\ConversationChannel;use App\Domain\AI\Runtime\Enums\AiExecutionMode;use Tests\TestCase;
final class AiWhatsAppRuntimeTest extends TestCase{
 public function test_channel_reuses_live_conversation_core_and_published_version():void{$this->assertSame('whatsapp',ConversationChannel::WhatsApp->value);$this->assertSame(['live','simulation'],array_map(fn($x)=>$x->value,AiExecutionMode::cases()));$s=file_get_contents(app_path('Domain/AI/Channels/WhatsApp/Services/ProcessWhatsAppInboundService.php'));foreach(['current_published_version_id','AgentVersionStatus::Published','SendInternalConversationMessageService','ConversationChannel::WhatsApp','AwaitingConfirmation','authorizeTurn','lockAuthority','turn_waiting']as$x)$this->assertStringContainsString($x,$s);$core=file_get_contents(app_path('Domain/AI/Conversations/Services/SendInternalConversationMessageService.php'));$this->assertStringContainsString('beforeReserve',$core);foreach(['WhatsAppRuntime','WhatsAppConversationEngine','SimulationRunner']as$x)$this->assertStringNotContainsString($x,$s);}
 public function test_receipts_confirmation_delivery_and_window_are_idempotent_boundaries():void{$migration=file_get_contents(database_path('migrations/2026_09_02_100000_create_ai_whatsapp_channel.php'));foreach(["unique(['whatsapp_channel_id','provider_message_id'],'ai_wa_receipts_provider_msg_uq')","foreign(['tenant_id','whatsapp_channel_id'],'ai_wa_receipts_channel_fk')","idempotency_key',64)->unique()",'confirmation_token_hash','service_window_ends_at']as$x)$this->assertStringContainsString($x,$migration);foreach(['ai_wa_receipts_provider_msg_uq','ai_wa_receipts_channel_fk']as$identifier)$this->assertLessThanOrEqual(64,strlen($identifier));$confirm=file_get_contents(app_path('Domain/AI/Channels/WhatsApp/Services/ConfirmWhatsAppActionService.php'));foreach(['lockForUpdate','insideWindow','conversation_id','agent_id','confirmed_at','ConfirmActionRunService']as$x)$this->assertStringContainsString($x,$confirm);}
 public function test_core_is_horizontal_and_marketing_features_are_absent():void{$files=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator(app_path('Domain/AI/Channels/WhatsApp'),\FilesystemIterator::SKIP_DOTS));foreach($files as$f){if($f->getExtension()!=='php')continue;$s=file_get_contents($f->getPathname());foreach(['zigo.','campaign','broadcast','segment','newsletter','bulk send','WhatsAppActionEngine']as$x)$this->assertStringNotContainsString($x,$s);}}
 public function test_delivery_status_policy_is_monotonic():void{$p=new WhatsAppDeliveryStatusPolicy;foreach([['sent','delivered',true],['sent','read',true],['delivered','read',true],['read','delivered',false],['read','sent',false],['read','failed',false],['delivered','sent',false],['delivered','failed',false],['read','read',true]]as[$from,$to,$allowed])$this->assertSame($allowed,$p->permits($from,$to));}
 public function test_provider_contract_is_bounded_dto_and_http_has_explicit_timeouts():void{$methods=(new \ReflectionClass(WhatsAppProvider::class))->getMethods();$this->assertSame(WhatsAppOutboundTextRequest::class,$methods[0]->getParameters()[0]->getType()->getName());$this->assertSame(WhatsAppOutboundConfirmationRequest::class,$methods[1]->getParameters()[0]->getType()->getName());$adapter=file_get_contents(app_path('Infrastructure/WhatsApp/MetaCloudWhatsAppProvider.php'));foreach(['connectTimeout','timeout','MetaCloudWhatsAppCredentialsResolver']as$x)$this->assertStringContainsString($x,$adapter);$this->assertStringNotContainsString('WhatsAppChannel',$adapter);$this->assertStringNotContainsString('retry(',$adapter);}
}
