<?php
namespace Tests\Feature;
use App\Domain\AI\Channels\WhatsApp\Models\{WhatsAppChannel,WhatsAppDelivery,WhatsAppSession};use App\Domain\AI\Channels\WhatsApp\Services\ProcessWhatsAppInboundService;use App\Domain\Network\Tenancy\Models\Tenant;use App\Domain\Network\Tenancy\TenantContext;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Schema};use Tests\TestCase;
final class AiWhatsAppFoundationTest extends TestCase{
 protected function setUp():void{parent::setUp();config(['database.default'=>'sqlite','database.connections.sqlite.database'=>':memory:','app.key'=>'base64:'.base64_encode(str_repeat('q',32))]);DB::statement('PRAGMA foreign_keys=ON');$this->base();}
 public function test_migration_up_down_up_and_restrict_constraints():void{$m=$this->migration();$m->up();foreach(['ai_whatsapp_channels','ai_whatsapp_sessions','ai_whatsapp_inbound_receipts','ai_whatsapp_deliveries']as$t)$this->assertTrue(Schema::hasTable($t));$this->assertNotEmpty(DB::select("PRAGMA foreign_key_list('ai_whatsapp_sessions')"));$m->down();$this->assertFalse(Schema::hasTable('ai_whatsapp_channels'));$m->up();$this->assertSame(1,(int)DB::selectOne('PRAGMA foreign_keys')->foreign_keys);}
 public function test_credentials_and_contact_are_encrypted_and_aggregates_are_coherent():void{$this->migration()->up();$tenant=Tenant::create(['name'=>'Tenant','slug'=>'tenant','status'=>'active']);app(TenantContext::class)->set($tenant);DB::table('users')->insert(['id'=>1]);DB::table('ai_agents')->insert(['id'=>1,'tenant_id'=>$tenant->id]);DB::table('ai_conversations')->insert(['id'=>1,'tenant_id'=>$tenant->id,'agent_id'=>1]);$c=new WhatsAppChannel;$c->tenant_id=$tenant->id;$c->agent_id=1;$c->phone_number_id='123';$c->created_by_user_id=1;$c->setAccessToken('token-secret');$c->setAppSecret('app-secret');$c->setVerifyToken('verify-secret');$c->save();$s=new WhatsAppSession;$s->tenant_id=$tenant->id;$s->whatsapp_channel_id=$c->id;$s->conversation_id=1;$s->setContact('5218111111111');$s->setProfileName('Persona');$s->service_window_ends_at=now()->addDay();$s->save();$raw=(array)DB::table('ai_whatsapp_channels')->first();$this->assertStringNotContainsString('token-secret',$raw['access_token_encrypted']);$this->assertStringNotContainsString('app-secret',$raw['app_secret_encrypted']);$this->assertStringNotContainsString('verify-secret',$raw['verify_token_encrypted']);$this->assertNotSame('5218111111111',DB::table('ai_whatsapp_sessions')->value('contact_encrypted'));$this->assertSame(hash('sha256','5218111111111'),$s->contact_hash);$this->assertSame('token-secret',$c->accessToken());$serialized=$c->toArray();$json=$c->toJson();foreach(['access_token_encrypted','app_secret_encrypted','verify_token_encrypted','token-secret','app-secret','verify-secret']as$secret){$this->assertArrayNotHasKey($secret,$serialized);$this->assertStringNotContainsString($secret,$json);}}
 public function test_delivery_status_is_channel_scoped_and_monotonic():void{$this->migration()->up();$tenant=Tenant::create(['name'=>'Status','slug'=>'status','status'=>'active']);app(TenantContext::class)->set($tenant);DB::table('users')->insert(['id'=>1]);DB::table('ai_agents')->insert([['id'=>1,'tenant_id'=>$tenant->id],['id'=>2,'tenant_id'=>$tenant->id]]);DB::table('ai_conversations')->insert([['id'=>1,'tenant_id'=>$tenant->id,'agent_id'=>1],['id'=>2,'tenant_id'=>$tenant->id,'agent_id'=>2]]);$channels=[];$sessions=[];foreach([1,2]as$id){$c=new WhatsAppChannel;$c->tenant_id=$tenant->id;$c->agent_id=$id;$c->enabled=true;$c->phone_number_id='pn_'.$id;$c->created_by_user_id=1;$c->setAccessToken('token_'.$id);$c->setAppSecret('secret_'.$id);$c->setVerifyToken('verify_'.$id);$c->save();$s=new WhatsAppSession;$s->tenant_id=$tenant->id;$s->whatsapp_channel_id=$c->id;$s->conversation_id=$id;$s->setContact('521800000000'.$id);$s->service_window_ends_at=now()->addDay();$s->save();$channels[]=$c;$sessions[]=$s;}$d=new WhatsAppDelivery;$d->tenant_id=$tenant->id;$d->whatsapp_session_id=$sessions[0]->id;$d->kind='text';$d->status='sent';$d->idempotency_key=hash('sha256','status-delivery');$d->provider_message_id='wamid.status';$d->save();$method=new \ReflectionMethod(ProcessWhatsAppInboundService::class,'status');$service=app(ProcessWhatsAppInboundService::class);$method->invoke($service,$channels[1],['provider_delivery_id'=>'wamid.status','status'=>'read']);$this->assertSame('sent',$d->fresh()->status);foreach(['delivered','read','failed','delivered','sent']as$status)$method->invoke($service,$channels[0],['provider_delivery_id'=>'wamid.status','status'=>$status]);$this->assertSame('read',$d->fresh()->status);}
 private function migration(){return require base_path('database/migrations/2026_09_02_100000_create_ai_whatsapp_channel.php');}
 private function base():void{Schema::create('users',fn(Blueprint$t)=>$t->id());Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid');$t->string('name')->nullable();$t->string('slug')->nullable();$t->string('status')->nullable();$t->timestamps();$t->unique(['id']);});Schema::create('ai_agents',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unique(['tenant_id','id']);});Schema::create('ai_conversations',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('agent_id');$t->unique(['tenant_id','id']);});Schema::create('ai_conversation_messages',fn(Blueprint$t)=>$t->id());Schema::create('ai_action_runs',fn(Blueprint$t)=>$t->id());}
}
