<?php
namespace Tests\Feature;
use App\Services\Shipping\Estafeta\{EstafetaConfigurationValidator,EstafetaHttpClient};
use App\Services\Shipping\Estafeta\Exceptions\EstafetaConfigurationException;
use App\Services\Shipping\Estafeta\Support\EstafetaSanitizer;
use Illuminate\Support\Facades\Http;
use Tests\TestCase;
class EstafetaIntegrationTest extends TestCase {
 private function validConfig():array{return['enabled'=>true,'environment'=>'stage','auth_url'=>'https://stage.example.test','auth_path'=>'oauth2/v2.0/token','client_id'=>'client','client_secret'=>'secret','scope'=>'execute','quote_url'=>'https://stage.example.test/quote','coverage_url'=>'https://stage.example.test/coverage','contracts'=>['auth'=>'confirmed','coverage'=>'unknown','quote'=>'unknown'],'timeout'=>2,'connect_timeout'=>1,'retry_times'=>2,'retry_sleep_ms'=>0,'token_cache_seconds'=>300,'token_expiry_skew_seconds'=>60,'verify_ssl'=>true,'mock_enabled'=>false,'log_channel'=>'null'];}
 public function test_configuration_is_sanitized_and_validated():void{$r=app(EstafetaConfigurationValidator::class)->validate($this->validConfig());$this->assertTrue($r['valid']);$this->assertTrue($r['credentials_present']['client_secret']);$this->assertArrayNotHasKey('client_secret',$r);}
 public function test_sanitizer_redacts_secrets():void{$r=EstafetaSanitizer::sanitize(['password'=>'abc','nested'=>['api_key'=>'def'],'message'=>'Bearer token-value']);$this->assertSame('[REDACTED]',$r['password']);$this->assertSame('[REDACTED]',$r['nested']['api_key']);$this->assertStringNotContainsString('token-value',$r['message']);}
 public function test_retries_transient_but_not_functional_errors():void{config(['zigo_estafeta'=>$this->validConfig()]);$transient=0;$functional=0;Http::fake(function($request)use(&$transient,&$functional){if(str_contains($request->url(),'validation')){$functional++;return Http::response([],422);}$transient++;return Http::response($transient===1?[]:['ok'=>true],$transient===1?500:200);});$this->assertSame(1,app(EstafetaHttpClient::class)->request('quote','POST','https://stage.example.test/quote')->retryCount);$this->assertSame(2,$transient);$this->assertSame('validation_error',app(EstafetaHttpClient::class)->request('quote','POST','https://stage.example.test/validation')->classification);$this->assertSame(1,$functional);}
 public function test_mock_is_blocked_in_production():void{config(['app.env'=>'production','zigo_estafeta'=>array_merge($this->validConfig(),['mock_enabled'=>true])]);$this->expectException(EstafetaConfigurationException::class);app(EstafetaHttpClient::class)->request('auth','POST','https://example.test/auth');}
 public function test_audit_reports_unknown_contracts_without_http():void{config(['zigo_estafeta'=>$this->validConfig()]);$this->artisan('zigo:estafeta-audit')->expectsOutputToContain('READY_FOR_B2C_QUOTES=false')->assertExitCode(0);Http::assertNothingSent();}
 public function test_auth_uses_confirmed_form_contract():void{config(['zigo_estafeta'=>$this->validConfig()]);Http::fake(['*'=>Http::response(['access_token'=>'sanitized-token','expires_in'=>3600,'token_type'=>'Bearer'],200)]);$result=app(\App\Services\Shipping\Estafeta\EstafetaAuthClient::class)->authenticate();$this->assertTrue($result->success);Http::assertSent(fn($r)=>$r->isForm()&&$r['grant_type']==='client_credentials'&&$r['client_id']==='client'&&$r['client_secret']==='secret'&&$r['scope']==='execute');}
 public function test_unknown_coverage_and_quote_contracts_never_send_http():void{config(['zigo_estafeta'=>$this->validConfig()]);$request=\App\Services\Shipping\Estafeta\Data\EstafetaOperationRequest::fromArray(['origin_postal_code'=>'64000','destination_postal_code'=>'64000']);$this->assertSame('contract_unknown',app(\App\Services\Shipping\Estafeta\EstafetaCoverageClient::class)->check($request,'token')->classification);$this->assertSame('contract_unknown',app(\App\Services\Shipping\Estafeta\EstafetaQuoteClient::class)->quote($request,'token')->classification);Http::assertNothingSent();}
 public function test_volumetric_weight_and_provider_price_are_separate():void{$dimensions=new \App\Services\Shipping\Estafeta\Data\EstafetaDimensions(20,20,20);$package=new \App\Services\Shipping\Estafeta\Data\EstafetaPackage(1,$dimensions);$option=new \App\Services\Shipping\Estafeta\Data\EstafetaQuoteOption('DIA_SIGUIENTE',123.45);$this->assertSame(1.6,$package->volumetricWeight());$this->assertSame(123.45,$option->providerBasePrice);}
}
