<?php
namespace Tests\Feature;
use App\Domain\Network\Catalog\Models\{Module,Plan};use App\Domain\Network\Tenancy\Models\{Tenant,TenantBranding,TenantDomain};use App\Domain\Network\Tenancy\{TenantContext,TenantDomainResolver};use App\Models\Roles\Roles;use App\Models\User;use App\Services\ZigoDomainResolver;use Illuminate\Database\QueryException;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Schema};use Tests\Support\WhiteLabelTestSchema;use Tests\TestCase;
final class NetworkWhiteLabelTest extends TestCase
{
 protected function setUp():void{parent::setUp();if(DB::connection()->getDriverName()!=='sqlite'||DB::connection()->getDatabaseName()!==':memory:')$this->markTestSkipped('Requires SQLite :memory:.');$this->schema();WhiteLabelTestSchema::create();}
 public function test_domain_belongs_to_tenant_and_is_unique():void{$tenant=$this->tenant();$domain=$tenant->domains()->create($this->domainData());$this->assertTrue($domain->tenant->is($tenant));$this->expectException(QueryException::class);$tenant->domains()->create($this->domainData());}
 public function test_invalid_hostnames_and_urls_are_rejected():void{$tenant=$this->tenant();$this->actingAs($this->user('sysadmin'));foreach(['https://cliente.com/ruta','cliente.com/path','bad_host.com']as$domain)$this->post("/network/tenants/{$tenant->id}/domains",array_merge($this->domainData(),['domain'=>$domain]))->assertSessionHasErrors('domain');}
 public function test_only_verified_domain_for_active_tenant_resolves_context():void{$tenant=$this->tenant();$resolver=app(TenantDomainResolver::class);foreach(['pending','disabled']as$status){$domain=$tenant->domains()->create(array_merge($this->domainData(),['domain'=>$status.'.zigo.local','status'=>$status]));$this->assertNull($resolver->resolve($domain->domain));}$verified=$tenant->domains()->create($this->domainData());$this->assertTrue($resolver->resolve('PILOT.ZIGO.LOCAL:8000')->is($verified));$this->assertTrue(app(TenantContext::class)->tenant()->is($tenant));$this->assertNull($resolver->resolve('unknown.zigo-envios.com'));}
 public function test_inactive_and_suspended_tenants_do_not_resolve():void{foreach(['inactive','suspended']as$status){$tenant=$this->tenant($status);$domain=$tenant->domains()->create(array_merge($this->domainData(),['domain'=>$status.'.zigo.local']));$this->assertNull(app(TenantDomainResolver::class)->resolve($domain->domain));}}
 public function test_branding_is_has_one_and_invalid_colors_are_rejected():void{$tenant=$this->tenant();$this->actingAs($this->user('sysadmin'))->put("/network/tenants/{$tenant->id}/branding",['brand_name'=>'Pilot','primary_color'=>'javascript:red'])->assertSessionHasErrors('primary_color');$this->put("/network/tenants/{$tenant->id}/branding",['brand_name'=>'Pilot','primary_color'=>'#3B66F6'])->assertRedirect();$this->assertInstanceOf(TenantBranding::class,$tenant->fresh()->branding);$this->assertSame('Pilot',$tenant->fresh()->branding->brand_name);}
 public function test_preview_uses_fallback_and_only_included_modules():void{$tenant=$this->tenant();$plan=$this->plan();$included=$this->module('TRACKING');$excluded=$this->module('COMMERCE');$plan->modules()->attach($included,['is_included'=>true,'limit_value'=>null]);$plan->modules()->attach($excluded,['is_included'=>false,'limit_value'=>null]);$tenant->update(['current_plan_id'=>$plan->id]);$this->actingAs($this->user('sysadmin'))->get("/network/tenants/{$tenant->id}/preview")->assertOk()->assertSee($tenant->name)->assertSee('#185FA8',false)->assertSee('Tracking')->assertDontSee('Commerce');}
 public function test_crud_is_network_protected_and_legacy_portal_resolver_still_works():void{$tenant=$this->tenant();$this->get("/network/tenants/{$tenant->id}/domains")->assertRedirect('/network/login');$this->actingAs($this->user('admin'))->get("/network/tenants/{$tenant->id}/branding")->assertForbidden();$legacy=app(ZigoDomainResolver::class);$this->assertSame('support',$legacy->portalForHost(config('zigo_domains.portals.support.host')));$this->assertSame('crm',$legacy->portalForHost(config('zigo_domains.portals.crm.host')));$this->assertSame('b2b',$legacy->portalForHost(config('zigo_domains.portals.b2b.host')));}
 public function test_only_one_primary_domain_is_kept_per_tenant_environment():void{$tenant=$this->tenant();$first=$tenant->domains()->create(array_merge($this->domainData(),['domain'=>'first.zigo.local']));$this->actingAs($this->user('sysadmin'))->post("/network/tenants/{$tenant->id}/domains",array_merge($this->domainData(),['domain'=>'second.zigo.local']))->assertRedirect();$this->assertFalse((bool)$first->fresh()->is_primary);$this->assertTrue((bool)$tenant->domains()->where('domain','second.zigo.local')->first()->is_primary);}
 private function domainData():array{return['domain'=>'pilot.zigo.local','type'=>'subdomain','environment'=>'production','is_primary'=>true,'status'=>'verified','verified_at'=>now()];}
 private function tenant(string$status='active'):Tenant{return Tenant::create(['name'=>'Pilot '.$status,'slug'=>'pilot-'.$status.'-'.uniqid(),'status'=>$status]);}
 private function plan():Plan{return Plan::create(['code'=>'LOCAL300','name'=>'Local 300','status'=>'active','currency'=>'MXN','included_operations'=>300]);}
 private function module(string$code):Module{return Module::create(['code'=>$code,'name'=>ucfirst(strtolower($code)),'type'=>'addon','is_active'=>true,'sort_order'=>1]);}
 private function user(string$slug):User{$u=User::forceCreate(['name'=>'Test','email'=>uniqid().'@test.local','password'=>'secret','empresa_id'=>1]);$r=Roles::create(['name'=>$slug,'slug'=>$slug]);$u->roles()->attach($r->id);return$u;}
 private function schema():void{foreach(['network_plan_modules','network_tenant_brandings','network_tenant_domains','network_tenants','network_plans','network_modules','users_roles','roles','users']as$t)Schema::dropIfExists($t);Schema::create('users',function(Blueprint$t){$t->id();$t->string('name');$t->string('email');$t->string('password');$t->unsignedBigInteger('empresa_id');$t->rememberToken();$t->timestamps();});Schema::create('roles',function(Blueprint$t){$t->id();$t->string('name');$t->string('slug');$t->timestamps();});Schema::create('users_roles',function(Blueprint$t){$t->unsignedBigInteger('user_id');$t->unsignedBigInteger('roles_id');});Schema::create('network_modules',function(Blueprint$t){$t->id();$t->string('code')->unique();$t->string('name');$t->text('description')->nullable();$t->string('type');$t->boolean('is_active');$t->unsignedSmallInteger('sort_order');$t->timestamps();});Schema::create('network_plans',function(Blueprint$t){$t->id();$t->string('code')->unique();$t->string('name');$t->text('description')->nullable();$t->string('status');$t->decimal('monthly_price',12,2)->nullable();$t->decimal('annual_price',12,2)->nullable();$t->char('currency',3);$t->unsignedInteger('included_operations')->nullable();$t->timestamps();});Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->string('status');$t->unsignedBigInteger('current_plan_id')->nullable();$t->timestamps();});Schema::create('network_plan_modules',function(Blueprint$t){$t->id();$t->unsignedBigInteger('plan_id');$t->unsignedBigInteger('module_id');$t->boolean('is_included');$t->unsignedInteger('limit_value')->nullable();$t->timestamps();$t->unique(['plan_id','module_id']);});}
}
