<?php
namespace Tests\Feature;
use App\Domain\Network\Catalog\Models\{Module,Plan};use App\Domain\Network\Tenancy\Models\Tenant;use App\Models\Roles\Roles;use App\Models\User;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Schema};use Tests\TestCase;
final class NetworkBuildYourZigoTest extends TestCase
{
 protected function setUp():void{parent::setUp();if(DB::connection()->getDriverName()!== 'sqlite'||DB::connection()->getDatabaseName()!==':memory:')$this->markTestSkipped('Requires SQLite :memory:.');$this->schema();\Tests\Support\WhiteLabelTestSchema::create();}
 public function test_sysadmin_assigns_changes_and_removes_plan_without_changing_uuid():void{$user=$this->user('sysadmin');$tenant=Tenant::create(['name'=>'Rapidex','slug'=>'rapidex','status'=>'active']);$uuid=$tenant->uuid;$a=$this->plan('A');$b=$this->plan('B');$this->actingAs($user)->put("/network/tenants/{$tenant->id}",$this->tenantData($tenant,$a))->assertRedirect();$this->assertSame($a->id,$tenant->fresh()->current_plan_id);$this->put("/network/tenants/{$tenant->id}",$this->tenantData($tenant,$b))->assertRedirect();$this->assertSame($b->id,$tenant->fresh()->current_plan_id);$data=$this->tenantData($tenant,null);$data['uuid']='changed';$this->put("/network/tenants/{$tenant->id}",$data)->assertRedirect();$tenant->refresh();$this->assertNull($tenant->current_plan_id);$this->assertSame($uuid,$tenant->uuid);}
 public function test_non_sysadmin_cannot_edit_tenant():void{$tenant=Tenant::create(['name'=>'T','slug'=>'t','status'=>'active']);$this->actingAs($this->user('admin'))->get("/network/tenants/{$tenant->id}/edit")->assertForbidden();}
 public function test_plan_syncs_multiple_modules_without_duplicates_and_preserves_limits():void{$plan=$this->plan('LOCAL300');$b2c=$this->module('B2C','channel');$shipping=$this->module('SHIPPING','core');$this->actingAs($this->user('sysadmin'))->put("/network/plans/{$plan->id}",$this->planData([[$b2c,1,300],[$shipping,1,null]]))->assertRedirect();$this->assertDatabaseCount('network_plan_modules',2);$this->assertCount(2,$plan->fresh()->modules()->wherePivot('is_included',true)->get());$this->get("/network/plans/{$plan->id}/edit")->assertOk()->assertSee('B2C')->assertSee('value="300"',false);$this->put("/network/plans/{$plan->id}",$this->planData([[$b2c,1,300],[$shipping,0,null]]))->assertRedirect();$this->assertDatabaseCount('network_plan_modules',2);$this->assertCount(1,$plan->fresh()->modules()->wherePivot('is_included',true)->get());$this->assertSame(300,$plan->fresh()->modules->firstWhere('code','B2C')->pivot->limit_value);$this->assertFalse((bool)$plan->fresh()->modules->firstWhere('code','SHIPPING')->pivot->is_included);}
 public function test_dashboard_and_tenant_detail_show_only_effective_modules_without_blade_directives():void{$plan=$this->plan('LOCAL300');$included=$this->module('CRM','addon');$excluded=$this->module('GPS','addon');$plan->modules()->attach($included,['is_included'=>true,'limit_value'=>null]);$plan->modules()->attach($excluded,['is_included'=>false,'limit_value'=>null]);$tenant=Tenant::create(['name'=>'Rapidex','slug'=>'rapidex','status'=>'active','current_plan_id'=>$plan->id]);$this->actingAs($this->user('sysadmin'))->get('/network/dashboard')->assertOk()->assertSee('LOCAL300')->assertSee('1');$response=$this->get("/network/tenants/{$tenant->id}")->assertOk()->assertSee('LOCAL300')->assertSee('CRM')->assertDontSee('GPS')->assertSee('Entitlements pendientes ZN-04');foreach(['@if','@else','@endif']as$directive)$response->assertDontSee($directive,false);}
 public function test_tenant_without_plan_shows_no_catalog_modules_as_contracted():void{$this->module('B2C','channel');$this->module('SHIPPING','core');$tenant=Tenant::create(['name'=>'Nuevo','slug'=>'nuevo','status'=>'active']);$this->actingAs($this->user('sysadmin'))->get("/network/tenants/{$tenant->id}")->assertOk()->assertSee('Sin plan comercial asignado')->assertDontSee('B2C')->assertDontSee('SHIPPING');}
 public function test_invalid_commercial_states_and_plan_are_rejected():void{$tenant=Tenant::create(['name'=>'T','slug'=>'t','status'=>'active']);$this->actingAs($this->user('sysadmin'))->put("/network/tenants/{$tenant->id}",['name'=>'T','slug'=>'t','status'=>'deleted','current_plan_id'=>999])->assertSessionHasErrors(['status','current_plan_id']);}
 private function tenantData(Tenant$t,?Plan$p):array{return['name'=>$t->name,'slug'=>$t->slug,'status'=>'active','current_plan_id'=>$p?->id];}
 private function plan(string$code):Plan{return Plan::create(['code'=>$code,'name'=>$code,'status'=>'active','currency'=>'MXN','included_operations'=>$code==='LOCAL300'?300:null]);}
 private function module(string$code,string$type):Module{return Module::create(['code'=>$code,'name'=>$code,'type'=>$type,'is_active'=>true,'sort_order'=>1]);}
 private function planData(array$rows):array{return['name'=>'Local 300','description'=>'Plan test','status'=>'active','monthly_price'=>0,'annual_price'=>0,'currency'=>'MXN','included_operations'=>300,'modules'=>array_map(fn($r)=>['id'=>$r[0]->id,'included'=>$r[1],'limit_value'=>$r[2]],$rows)];}
 private function user(string$slug):User{$u=User::forceCreate(['name'=>'Test','email'=>uniqid().'@test.local','password'=>'secret','empresa_id'=>1]);$r=Roles::create(['name'=>$slug,'slug'=>$slug]);$u->roles()->attach($r->id);return$u;}
 private function schema():void{foreach(['network_tenant_memberships','network_plan_modules','network_tenants','network_plans','network_modules','users_roles','roles','users']as$t)Schema::dropIfExists($t);Schema::create('users',function(Blueprint$t){$t->id();$t->string('name');$t->string('email');$t->string('password');$t->unsignedBigInteger('empresa_id');$t->rememberToken();$t->timestamps();});Schema::create('roles',function(Blueprint$t){$t->id();$t->string('name');$t->string('slug');$t->timestamps();});Schema::create('users_roles',function(Blueprint$t){$t->unsignedBigInteger('user_id');$t->unsignedBigInteger('roles_id');});Schema::create('network_modules',function(Blueprint$t){$t->id();$t->string('code')->unique();$t->string('name');$t->text('description')->nullable();$t->string('type');$t->boolean('is_active');$t->unsignedSmallInteger('sort_order');$t->timestamps();});Schema::create('network_plans',function(Blueprint$t){$t->id();$t->string('code')->unique();$t->string('name');$t->text('description')->nullable();$t->string('status');$t->decimal('monthly_price',12,2)->nullable();$t->decimal('annual_price',12,2)->nullable();$t->char('currency',3);$t->unsignedInteger('included_operations')->nullable();$t->timestamps();});Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->string('status');$t->unsignedBigInteger('current_plan_id')->nullable();$t->timestamps();});Schema::create('network_plan_modules',function(Blueprint$t){$t->id();$t->unsignedBigInteger('plan_id');$t->unsignedBigInteger('module_id');$t->boolean('is_included');$t->unsignedInteger('limit_value')->nullable();$t->timestamps();$t->unique(['plan_id','module_id']);});Schema::create('network_tenant_memberships',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('user_id');$t->string('role');$t->string('status');$t->timestamps();$t->unique(['tenant_id','user_id']);});}
}
