<?php
namespace Tests\Feature;
use App\Models\Roles\Roles;use App\Models\User;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{DB,Hash,Route,Schema};use Tests\TestCase;
final class NetworkAuthTest extends TestCase
{
 protected function setUp():void{parent::setUp();if(DB::connection()->getDriverName()!=='sqlite'||DB::connection()->getDatabaseName()!==':memory:')$this->markTestSkipped('Requires SQLite :memory:.');foreach(['network_plan_modules','network_plans','network_modules','network_tenants','users_roles','roles','users']as$t)Schema::dropIfExists($t);Schema::create('users',function(Blueprint$t){$t->id();$t->string('name');$t->string('email')->unique();$t->string('password');$t->unsignedBigInteger('empresa_id');$t->rememberToken();$t->timestamps();});Schema::create('roles',function(Blueprint$t){$t->id();$t->string('name');$t->string('slug');$t->timestamps();});Schema::create('users_roles',function(Blueprint$t){$t->unsignedBigInteger('user_id');$t->unsignedBigInteger('roles_id');});Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->string('name');$t->string('slug')->unique();$t->string('status');$t->timestamps();});Schema::create('network_modules',function(Blueprint$t){$t->id();$t->string('code');$t->string('name');$t->string('type');$t->boolean('is_active');$t->unsignedSmallInteger('sort_order');$t->timestamps();});Schema::create('network_plans',function(Blueprint$t){$t->id();$t->string('code');$t->string('name');$t->string('status');$t->char('currency',3);$t->timestamps();});}
 public function test_guests_are_redirected_to_dedicated_login():void{foreach(['/network','/network/topology','/network/dashboard','/network/tenants']as$uri)$this->get($uri)->assertRedirect('/network/login');$this->get('/network/login')->assertOk()->assertSee('ENTRAR A NETWORK');}
 public function test_sysadmin_can_login_navigate_and_logout():void{$u=$this->user('sysadmin');$this->post('/network/login',['email'=>$u->email,'password'=>'network-secret'])->assertRedirect('/network');$this->assertAuthenticatedAs($u);$this->get('/network/topology')->assertOk();$this->post('/network/logout')->assertRedirect('/network/login');$this->assertGuest();}
 public function test_non_sysadmin_is_rejected_and_session_is_closed():void{$u=$this->user('admin');$this->post('/network/login',['email'=>$u->email,'password'=>'network-secret'])->assertSessionHasErrors('email');$this->assertGuest();}
 public function test_general_login_route_remains_available():void{$this->assertTrue(Route::has('login'));$this->get('/login')->assertOk();}
 private function user(string$slug):User{$u=User::forceCreate(['name'=>'Network Test','email'=>$slug.'@network.test','password'=>Hash::make('network-secret'),'empresa_id'=>1]);$r=Roles::create(['name'=>$slug,'slug'=>$slug]);$u->roles()->attach($r->id);return$u;}
}
