<?php
namespace Tests\Feature;
use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\{Cache,DB,Http,Schema,Storage};use Tests\TestCase;
final class ShippingProductionQuoteProbeTest extends TestCase {
 protected function setUp():void{parent::setUp();config(['database.default'=>'sqlite','database.connections.sqlite'=>['driver'=>'sqlite','database'=>':memory:','prefix'=>'','foreign_key_constraints'=>false]]);DB::purge('sqlite');DB::reconnect('sqlite');Schema::create('b2c_cotizaciones',fn(Blueprint$t)=>$t->id());Schema::create('zigo_provider_api_events',function(Blueprint$t){$t->id();$t->string('provider');$t->string('operation');$t->string('environment');$t->string('correlation_id');$t->string('status');$t->integer('http_status')->nullable();$t->string('provider_code')->nullable();$t->integer('duration_ms');$t->integer('retry_count');$t->integer('requested_by_user_id')->nullable();$t->json('metadata')->nullable();$t->timestamps();});Storage::fake('local');Cache::flush();$this->configureXperta();}
 private function configureXperta():void{config(['services.shipping.prd_quote_probe_enabled'=>true,'services.shipping.prd_quote_probe_timeout'=>2,'services.shipping.unified_quote_enabled'=>false,'services.xperta.enabled'=>true,'services.xperta.base_url'=>'https://prd-xperta.test','services.xperta.empresa'=>'empresa','services.xperta.ltd'=>'estafeta','services.xperta.corporativo'=>'corp','services.xperta.email'=>'private@example.test','services.xperta.password'=>'private-password','services.xperta.api_key'=>'private-api-key','services.xperta.token_path'=>'/api/v1/{empresa}/login','services.xperta.quote_path'=>'/api/v1/empresas/{empresa}/ltds/{ltd}/servicios/{service}/cotizaciones','services.xperta.quote_method'=>'POST','services.xperta.services'=>['terrestre','diasig'],'services.xperta.include_declared_value_in_quote'=>false,'services.xperta.connect_timeout'=>1,'services.xperta.timeout'=>2,'zigo_provider_rates.engine_v2_enabled'=>false]);}
 private function args(array $extra=[]):array{return array_merge(['--environment'=>'production','--carrier'=>'estafeta','--operation'=>'quote','--cp-origin'=>'64000','--cp-destination'=>'64000','--weight'=>'1','--length'=>'20','--width'=>'20','--height'=>'20','--package-type'=>'box','--confirm'=>'SHIPPING-PRD'],$extra);}
 public function test_prd_is_blocked_when_flag_is_false():void{config(['services.shipping.prd_quote_probe_enabled'=>false]);$this->artisan('zigo:shipping-probe',$this->args())->expectsOutputToContain('PRD_PROBE_DISABLED')->assertExitCode(1);Http::assertNothingSent();}
 public function test_prd_rejects_confirmation_operation_carrier_all_and_recorder():void{foreach([['--confirm'=>'wrong','code'=>'CONFIRMATION_INVALID'],['--operation'=>'coverage','code'=>'OPERATION_NOT_ALLOWED'],['--carrier'=>'fedex','code'=>'CARRIER_NOT_ALLOWED'],['--operation'=>'all','code'=>'OPERATION_NOT_ALLOWED'],['--record-contract'=>true,'code'=>'CONTRACT_RECORDING_FORBIDDEN']] as $case){$code=$case['code'];unset($case['code']);$this->artisan('zigo:shipping-probe',$this->args($case))->expectsOutputToContain($code)->assertExitCode(1);}Http::assertNothingSent();}
 public function test_prd_rejects_any_non_canonical_parameter():void{foreach([['--cp-origin'=>'64001'],['--cp-destination'=>'64001'],['--weight'=>'2'],['--length'=>'21'],['--width'=>'21'],['--height'=>'21'],['--package-type'=>'envelope']] as $change)$this->artisan('zigo:shipping-probe',$this->args($change))->expectsOutputToContain('NON_CANONICAL_INPUT')->assertExitCode(1);Http::assertNothingSent();}
 public function test_prd_rejects_strategy_other_than_xperta():void{config(['services.xperta.enabled'=>false]);$this->artisan('zigo:shipping-probe',$this->args())->expectsOutputToContain('STRATEGY_NOT_ALLOWED')->assertExitCode(1);Http::assertNothingSent();}
 public function test_valid_prd_quote_executes_one_functional_request_and_writes_sanitized_report():void{$quoteCalls=0;Http::fake(function($request)use(&$quoteCalls){if(str_contains($request->url(),'/login'))return Http::response(['message'=>['token'=>'raw-private-token']],200);$quoteCalls++;return Http::response(['success'=>true,'data'=>[['costo'=>100,'costo_ae'=>20,'sub_total'=>120,'total'=>139.2]]],200);});$before=DB::table('b2c_cotizaciones')->count();$this->artisan('zigo:shipping-probe',$this->args())->expectsOutputToContain('READY_FOR_B2C_QUOTE_ADAPTER=true')->assertExitCode(0);$this->assertSame(1,$quoteCalls);$this->assertSame($before,DB::table('b2c_cotizaciones')->count());$this->assertFalse(config('services.shipping.unified_quote_enabled'));$file=collect(Storage::disk('local')->allFiles('private/shipping-probes'))->last();$json=Storage::disk('local')->get($file);$report=json_decode($json,true);$this->assertSame(['generated_at','environment','strategy','http_provider','success','external_call_executed','services','costo','costo_ae','sub_total','total','currency','correlation_id','provider_status','READY_FOR_B2C_QUOTE_ADAPTER'],array_keys($report));foreach(['raw-private-token','private@example.test','private-password','private-api-key','Authorization','headers','request','response'] as $secret)$this->assertStringNotContainsString($secret,$json);$this->assertSame(1,DB::table('zigo_provider_api_events')->count());}
 public function test_stage_dry_run_continues_unchanged():void{Http::fake();$this->artisan('zigo:shipping-probe',['--environment'=>'stage','--dry-run'=>true])->expectsOutputToContain('READY_FOR_B2C_QUOTE_ADAPTER=false')->assertExitCode(0);Http::assertNothingSent();$this->assertFalse(config('services.shipping.unified_quote_enabled'));}
 public function test_prd_403_corporate_rejection_is_persisted_as_sanitized_diagnostic():void{Http::fake(function($request){if(str_contains($request->url(),'/login'))return Http::response(['message'=>['token'=>'private-token']],200);return Http::response(['message'=>'Corporativo no Autorizado','token'=>'must-not-persist'],403,['X-Correlation-ID'=>'provider-correlation']);});$this->artisan('zigo:shipping-probe',$this->args())->expectsOutputToContain('READY_FOR_B2C_QUOTE_ADAPTER=false')->assertExitCode(1);$event=DB::table('zigo_provider_api_events')->first();$this->assertSame('XPERTA_CORPORATE_UNAUTHORIZED',$event->provider_code);$metadata=json_decode($event->metadata,true);$this->assertSame('corporate_unauthorized',$metadata['provider_message_code']);$json=json_encode([$event,$metadata]);foreach(['private-token','must-not-persist','private-password','private-api-key','private@example.test'] as $secret)$this->assertStringNotContainsString($secret,$json);$file=collect(Storage::disk('local')->allFiles('private/shipping-probes'))->last();$report=json_decode(Storage::disk('local')->get($file),true);$this->assertSame('XPERTA_CORPORATE_UNAUTHORIZED',$report['error_code']);}
}
