<?php
namespace Tests\Feature;
use App\Services\Shipping\{ProviderStrategyResolver,UnifiedShippingQuoteService};use App\Services\Shipping\Data\UnifiedQuoteRequest;use App\Services\Shipping\Diagnostics\ShippingContractRecorder;use Illuminate\Support\Facades\{Http,Storage};use RuntimeException;use Tests\TestCase;
final class ShippingStrategyIntegrationTest extends TestCase {
 private function xpertaConfig():void{config(['services.xperta.enabled'=>true,'services.xperta.environment'=>'sandbox','services.xperta.base_url'=>'https://stage-xperta.test','services.xperta.empresa'=>'empresa','services.xperta.ltd'=>'estafeta','services.xperta.corporativo'=>'corp','services.xperta.email'=>'stage@example.test','services.xperta.password'=>'secret','services.xperta.api_key'=>'key','services.xperta.quote_method'=>'POST','services.xperta.quote_path'=>'/api/v1/empresas/{empresa}/ltds/{ltd}/servicios/{service}/cotizaciones','services.xperta.services'=>['terrestre'],'zigo_provider_rates.engine_v2_enabled'=>false]);}
 public function test_selects_xperta_estafeta_only_with_confirmed_contract_and_config():void{$this->xpertaConfig();$r=app(ProviderStrategyResolver::class)->resolve('quote','estafeta','stage');$this->assertSame('xperta_estafeta',$r['strategy']);$this->assertSame('xperta',$r['http_provider']);}
 public function test_rejects_unknown_contract():void{$this->xpertaConfig();$r=app(ProviderStrategyResolver::class)->resolve('cancellation','estafeta','stage');$this->assertSame('unavailable',$r['strategy']);$this->assertContains('cancellation_contract_unknown',$r['reasons']);}
 public function test_recorder_sanitizes_structure():void{config(['services.shipping.contract_recorder_enabled'=>true]);Storage::fake('local');$recorder=app(ShippingContractRecorder::class);$recorder->record(['provider'=>'xperta','operation'=>'quote','method'=>'POST','url'=>'https://stage.test/quote?token=x','headers'=>['Authorization'=>'Bearer secret','x-api-key'=>'secret','Accept'=>'application/json'],'request'=>['cp'=>'64000','password'=>'secret','nested'=>['weight'=>1]]],fn()=>['data'=>['token'=>'secret'],'total'=>100]);$file=collect(Storage::disk('local')->allFiles('private/shipping-contract-recordings'))->first();$text=Storage::disk('local')->get($file);$this->assertStringNotContainsString('Bearer secret',$text);$this->assertStringNotContainsString('64000',$text);$this->assertStringNotContainsString('x-api-key',$text);}
 public function test_recorder_is_blocked_in_production():void{config(['app.env'=>'production','services.shipping.contract_recorder_allow_production'=>false]);$this->expectException(RuntimeException::class);app(ShippingContractRecorder::class)->record([],fn()=>[]);}
 public function test_unified_quote_is_experimental_and_has_no_silent_fallback():void{config(['services.shipping.unified_quote_enabled'=>false]);$this->expectException(RuntimeException::class);app(UnifiedShippingQuoteService::class)->quote(new UnifiedQuoteRequest('estafeta','64000','64000',1));}
 public function test_probe_dry_run_and_missing_confirmation_make_no_request():void{$this->xpertaConfig();Http::fake();$this->artisan('zigo:shipping-probe',['--environment'=>'stage','--dry-run'=>true])->expectsOutputToContain('READY_FOR_B2C_QUOTE_ADAPTER=false')->assertExitCode(0);$this->artisan('zigo:shipping-probe',['--environment'=>'stage'])->expectsOutputToContain('READY_FOR_B2C_QUOTE_ADAPTER=false')->assertExitCode(0);Http::assertNothingSent();}
 public function test_audit_and_flow_map_are_static():void{Http::fake();$this->artisan('zigo:shipping-contract-audit',['--provider'=>'all','--environment'=>'stage'])->assertExitCode(0);$this->artisan('zigo:b2c-quote-flow-map',['--no-external-call'=>true])->assertExitCode(0);Http::assertNothingSent();}
 public function test_internal_probe_routes_are_strictly_protected():void{$routes=collect(app('router')->getRoutes()->getRoutes())->filter(fn($r)=>str_contains($r->uri(),'internal/shipping/quote-probe'));$this->assertCount(2,$routes);foreach($routes as $route){$middleware=$route->gatherMiddleware();$this->assertContains('auth',$middleware);$this->assertContains('roles:sysadmin',$middleware);$this->assertContains('throttle:3,1',$middleware);}}
}
