<?php
namespace Tests\Feature;
use App\Services\Shipping\Xperta\{XpertaApiClient,XpertaProviderException};use Illuminate\Support\Facades\{Artisan,Http};use Tests\TestCase;
final class XpertaForbiddenDiagnosticTest extends TestCase {
 protected function setUp():void{parent::setUp();config(['services.xperta.enabled'=>true,'services.xperta.environment'=>'production','services.xperta.base_url'=>'https://api.xperta.test','services.xperta.empresa'=>'empresa-publica','services.xperta.corporativo'=>'corp-publico','services.xperta.ltd'=>'estafeta','services.xperta.email'=>'private@example.test','services.xperta.password'=>'private-password','services.xperta.api_key'=>'private-key','services.xperta.services'=>['terrestre'],'services.xperta.quote_path'=>'/api/v1/empresas/{empresa}/ltds/{ltd}/servicios/{service}/cotizaciones','services.xperta.token_path'=>'/api/v1/{empresa}/login','services.xperta.frequency_path'=>'/frequency','services.xperta.guide_path'=>'/guide']);}
 /** @dataProvider forbiddenMessages */
 public function test_403_is_classified_without_retaining_provider_message(string $message,string $expected,string $messageCode):void{Http::fake(['*'=>Http::response(['message'=>$message],403,['X-Correlation-ID'=>'safe-correlation'])]);try{app(XpertaApiClient::class)->send('POST','/api/v1/empresas/empresa/ltds/estafeta/servicios/terrestre/cotizaciones',[],['Corporativo'=>'corp-publico']);$this->fail('Expected exception');}catch(XpertaProviderException $e){$this->assertSame($expected,$e->errorCode);$this->assertSame($expected,$e->getMessage());$this->assertSame($messageCode,$e->diagnosticMetadata['provider_message_code']);$this->assertSame('api.xperta.test',$e->diagnosticMetadata['host']);$this->assertSame('terrestre',$e->diagnosticMetadata['service']);$json=json_encode($e->diagnosticMetadata);$this->assertStringNotContainsString('private-password',$json);$this->assertStringNotContainsString('private-key',$json);$this->assertStringNotContainsString('private@example.test',$json);}}
 public static function forbiddenMessages():array{return[['Corporativo no Autorizado','XPERTA_CORPORATE_UNAUTHORIZED','corporate_unauthorized'],['API Key no autorizada','XPERTA_API_KEY_UNAUTHORIZED','api_key_unauthorized'],['Credenciales no autorizadas','XPERTA_CREDENTIALS_UNAUTHORIZED','credentials_unauthorized'],['Acceso denegado','XPERTA_HTTP_403','http_403']];}
 public function test_config_check_is_read_only_and_never_prints_secrets():void{config(['services.xperta.base_url'=>'https://qa-xperta.test']);Http::fake();Artisan::call('zigo:xperta-config-check');$output=Artisan::output();$this->assertStringContainsString('empresa-publica',$output);$this->assertStringContainsString('corp-publico',$output);$this->assertStringContainsString('hostname parece no productivo',$output);foreach(['private-password','private-key','private@example.test'] as $secret)$this->assertStringNotContainsString($secret,$output);Http::assertNothingSent();}
}
