<?php
namespace Tests\Feature;
use App\Domain\Network\Channels\B2C\Models\TenantCustomerCheckout; use App\Domain\Payments\MercadoPagoPaymentProvider; use App\Domain\Payments\Models\{TenantPaymentAttempt,TenantPaymentConnection}; use Illuminate\Database\Schema\Blueprint; use Illuminate\Http\Request; use Illuminate\Support\Facades\{DB,Http,Schema}; use Tests\TestCase;
final class ZigoMercadoPagoProviderTest extends TestCase{
 protected function setUp():void{parent::setUp();config()->set('zigo_payments.providers.mercado_pago',['enabled'=>true,'environment'=>'sandbox','client_id'=>'public-client-id','client_secret'=>'server-secret','redirect_uri'=>'https://payments.example.test/payments/mercado-pago/oauth/callback','webhook_secret'=>'signed-secret','api_url'=>'https://api.mercadopago.com','authorization_url'=>'https://auth.mercadopago.com/authorization','webhook_url'=>'https://payments.example.test/api/payments/mercado-pago/webhook','marketplace_fee_enabled'=>true,'marketplace_fee_amount'=>'5.00','connect_timeout'=>1,'timeout'=>2,'refresh_before_minutes'=>30,'webhook_tolerance_seconds'=>300]);}
 public function test_oauth_authorization_uses_state_and_pkce_without_client_secret():void{$url=(new MercadoPagoPaymentProvider)->authorizationUrl('opaque-state','s256-challenge');parse_str(parse_url($url,PHP_URL_QUERY),$q);$this->assertSame('code',$q['response_type']);$this->assertSame('opaque-state',$q['state']);$this->assertSame('s256-challenge',$q['code_challenge']);$this->assertSame('S256',$q['code_challenge_method']);$this->assertArrayNotHasKey('client_secret',$q);}
 public function test_preference_uses_frozen_server_values_and_seller_token():void{
  Http::fake(['api.mercadopago.com/checkout/preferences'=>Http::response(['id'=>'pref-1','sandbox_init_point'=>'https://www.mercadopago.com.mx/checkout/v1/redirect?pref_id=pref-1'],201)]);
  $connection=new TenantPaymentConnection(['status'=>'CONNECTED','access_token'=>'seller-oauth-token']);$checkout=new TenantCustomerCheckout(['uuid'=>'b5b637ae-84cc-42f1-a3ec-e611003f77b7','status'=>'PENDING_PAYMENT','currency'=>'MXN','total_amount'=>'120.00','expires_at'=>now()->addHour()]);$attempt=new TenantPaymentAttempt(['uuid'=>'48b6df10-6954-419c-bb29-09527efffd52','external_reference'=>'zg_opaque_reference','marketplace_fee_amount'=>'5.00']);
  (new MercadoPagoPaymentProvider)->createCheckout($connection,$attempt,$checkout);
  Http::assertSent(function($r){$body=$r->data();return $r->url()==='https://api.mercadopago.com/checkout/preferences'&&$r->hasHeader('Authorization','Bearer seller-oauth-token')&&$body['items'][0]['unit_price']===120.0&&$body['items'][0]['currency_id']==='MXN'&&$body['marketplace_fee']===5.0&&$body['external_reference']==='zg_opaque_reference'&&!isset($body['tenant_id']);});
 }
 public function test_webhook_signature_requires_documented_manifest_and_fresh_timestamp():void{$provider=new MercadoPagoPaymentProvider;$ts=(string)(time()*1000);$id='123456';$rid='request-abc';$manifest="id:{$id};request-id:{$rid};ts:{$ts};";$signature=hash_hmac('sha256',$manifest,'signed-secret');$request=Request::create('/api/payments/mercado-pago/webhook','POST',['data'=>['id'=>$id]],[],[],['HTTP_X_REQUEST_ID'=>$rid,'HTTP_X_SIGNATURE'=>"ts={$ts},v1={$signature}"]);$this->assertTrue($provider->validateWebhook($request,$id));$request->headers->set('x-signature',"ts={$ts},v1=bad");$this->assertFalse($provider->validateWebhook($request,$id));}
 public function test_browser_return_routes_are_get_only_and_no_manual_paid_route_exists():void{$routes=collect(app('router')->getRoutes()->getRoutes());$names=$routes->map(fn($r)=>$r->getName())->filter();$this->assertFalse($names->contains(fn($n)=>str_contains((string)$n,'manual')||str_contains((string)$n,'force-paid')));$return=$routes->first(fn($r)=>$r->getName()==='tenant.customer.app.checkout.mercado-pago.return');$this->assertSame(['GET','HEAD'],$return->methods());}
 public function test_payment_migration_is_reversible_and_tokens_are_encrypted_at_rest():void{
  if(DB::connection()->getDriverName()!=='sqlite'||DB::connection()->getDatabaseName()!==':memory:')$this->markTestSkipped('Requires SQLite :memory:.');
  Schema::create('network_tenants',fn(Blueprint $t)=>$t->id());Schema::create('tenant_customer_profiles',fn(Blueprint $t)=>$t->id());Schema::create('tenant_customer_checkouts',fn(Blueprint $t)=>$t->id());DB::table('network_tenants')->insert(['id'=>1]);DB::table('tenant_customer_profiles')->insert(['id'=>1]);DB::table('tenant_customer_checkouts')->insert(['id'=>1]);
  $migration=require database_path('migrations/2026_08_14_100000_create_tenant_payment_foundation.php');$migration->up();
  $connection=TenantPaymentConnection::create(['tenant_id'=>1,'provider'=>'MERCADO_PAGO','status'=>'CONNECTED','access_token'=>'access-secret','refresh_token'=>'refresh-secret']);$raw=DB::table('tenant_payment_connections')->where('id',$connection->id)->first();$this->assertNotSame('access-secret',$raw->access_token);$this->assertNotSame('refresh-secret',$raw->refresh_token);$this->assertSame('access-secret',$connection->fresh()->access_token);
  $migration->down();$this->assertFalse(Schema::hasTable('tenant_payment_connections'));Schema::dropIfExists('tenant_customer_checkouts');Schema::dropIfExists('tenant_customer_profiles');Schema::dropIfExists('network_tenants');
 }
}
