<?php
namespace Tests\Feature;
use App\Domain\Network\Tenancy\Models\{Tenant,TenantMembership}; use App\Domain\Support\Models\{SupportTicket,SupportTicketEvent}; use App\Domain\Support\SupportTicketService; use App\Models\User; use Illuminate\Database\Schema\Blueprint; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\{DB,Event,Schema,Storage}; use Illuminate\Validation\ValidationException; use Tests\TestCase;
final class ZigoSupportCenterTest extends TestCase{
 private Tenant$tenant;private User$requester;private SupportTicketService$service;
 protected function setUp():void{parent::setUp();if(DB::connection()->getDriverName()!=='sqlite'||DB::connection()->getDatabaseName()!==':memory:')$this->markTestSkipped('Requires SQLite :memory:.');$this->schema();$this->tenant=Tenant::create(['name'=>'RapidGo','slug'=>'rapidgo','status'=>'active']);$this->requester=User::create(['name'=>'Customer','email'=>'customer@test','password'=>'x']);$this->service=app(SupportTicketService::class);}
 public function test_customer_ticket_has_opaque_reference_fixed_scope_and_created_audit():void{Event::fake([\App\Domain\Support\Events\SupportTicketCreated::class]);$ticket=$this->ticket();$this->assertMatchesRegularExpression('/^SUP-[A-Z0-9]{10}$/',$ticket->public_reference);$this->assertSame('TENANT_OPERATIONAL',$ticket->scope);$this->assertDatabaseHas('support_ticket_events',['ticket_id'=>$ticket->id,'type'=>'CREATED']);Event::assertDispatched(\App\Domain\Support\Events\SupportTicketCreated::class);}
 public function test_public_and_internal_messages_are_append_only_and_first_response_is_recorded():void{$ticket=$this->ticket();$staff=User::create(['name'=>'Staff','email'=>'staff@test','password'=>'x']);$this->service->reply($ticket,$staff,'Respuesta pública');$this->service->reply($ticket,$staff,'Nota secreta','INTERNAL');$this->assertSame(2,$ticket->messages()->count());$this->assertSame(1,$ticket->messages()->where('visibility','PUBLIC')->count());$this->assertNotNull($ticket->fresh()->first_response_at);$routes=collect(app('router')->getRoutes()->getRoutes());$this->assertFalse($routes->contains(fn($r)=>in_array('DELETE',$r->methods(),true)&&str_contains($r->uri(),'support')));}
 public function test_status_assignment_and_resolution_are_audited_and_idempotent_data_is_derivable():void{$ticket=$this->ticket();$staff=User::create(['name'=>'Staff','email'=>'staff2@test','password'=>'x']);$this->service->assign($ticket,$staff,$staff->id);$this->service->priority($ticket,$staff,'HIGH');$this->service->status($ticket,$staff,'RESOLVED');$this->assertNotNull($ticket->fresh()->resolved_at);$this->assertSame(['ASSIGNED','PRIORITY_CHANGED','RESOLVED'],SupportTicketEvent::where('ticket_id',$ticket->id)->where('type','!=','CREATED')->pluck('type')->all());}
 public function test_attachments_are_private_allowlisted_and_randomly_named():void{Storage::fake('local');$ticket=$this->ticket();$attachment=$this->service->attach($ticket,null,$this->requester,UploadedFile::fake()->create('proof.pdf',10,'application/pdf'));$this->assertStringStartsWith('support/'.$ticket->uuid.'/',$attachment->stored_path);$this->assertStringNotContainsString('proof.pdf',$attachment->stored_path);Storage::disk('local')->assertExists($attachment->stored_path);try{$this->service->attach($ticket,null,$this->requester,UploadedFile::fake()->create('evil.html',2,'text/html'));$this->fail('HTML must be rejected');}catch(ValidationException){$this->assertTrue(true);}}
 public function test_route_contract_enforces_surface_middleware_and_network_scope_controller():void{$routes=collect(app('router')->getRoutes()->getRoutes());foreach(['tenant.customer.app.support.store','tenant.driver.support.store','driver.support.store','tenant.admin.support.index','network.support.index','network.support.store']as$name)$this->assertNotNull($routes->first(fn($r)=>$r->getName()===$name));$network=$routes->first(fn($r)=>$r->getName()==='network.support.index');$this->assertContains('network.superadmin',$network->gatherMiddleware());$this->assertSame(['GET','HEAD'],$network->methods());$tenant=$routes->first(fn($r)=>$r->getName()==='tenant.admin.support.index');$this->assertContains('tenant.support.staff',$tenant->gatherMiddleware());}
 public function test_migration_is_reversible():void{$m=require database_path('migrations/2026_08_16_100000_create_zigo_support_center.php');$m->down();$this->assertFalse(Schema::hasTable('support_tickets'));}
 private function ticket():SupportTicket{return$this->service->create($this->requester,['tenant_id'=>$this->tenant->id,'requester_type'=>'CUSTOMER','scope'=>'TENANT_OPERATIONAL','category'=>'DELIVERY','priority'=>'NORMAL','subject'=>'Mi envío','description'=>'Necesito ayuda']);}
 private function schema():void{Schema::create('users',function(Blueprint$t){$t->id();$t->string('name');$t->string('email');$t->string('password');$t->timestamps();});Schema::create('network_tenants',function(Blueprint$t){$t->id();$t->uuid('uuid')->nullable();$t->string('name');$t->string('slug');$t->string('status');$t->timestamps();});Schema::create('network_tenant_operations',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->timestamps();});Schema::create('local_shipments',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('tenant_operation_id')->nullable();$t->timestamps();});Schema::create('tenant_customer_checkouts',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->timestamps();});Schema::create('tenant_driver_profiles',function(Blueprint$t){$t->id();$t->unsignedBigInteger('tenant_id');$t->unsignedBigInteger('user_id');$t->timestamps();});$m=require database_path('migrations/2026_08_16_100000_create_zigo_support_center.php');$m->up();}
}
