@extends('network.layout')
@section('title','ZIGO Local')
@section('content')
<div class="eyebrow">SHIPPING</div><h1>ZIGO Local</h1><p>Cobertura, servicios y operación propia. Los costos sólo son visibles en Network.</p>
@if(session('success'))<div class="notice">{{ session('success') }}</div>@endif @if($errors->any())<div class="notice">{{ $errors->first() }}</div>@endif
<div class="grid-2"><section class="card"><h2>Nueva zona</h2><form method="POST" action="{{ route('network.local-shipping.zones.store') }}">@csrf<label>Código<input name="code" required></label><label>Nombre<input name="name" required></label><input type="hidden" name="status" value="active"><button class="btn">Crear zona</button></form></section>
<section class="card"><h2>Zonas y CP</h2>@forelse($zones as $zone)<article><strong>{{ $zone->name }}</strong> <small>{{ strtoupper($zone->status) }}</small><div>{{ $zone->postalCodes->pluck('postal_code')->join(', ') ?: 'Sin CP' }}</div><form method="POST" action="{{ route('network.local-shipping.postal-codes.store',$zone) }}">@csrf<input name="postal_code" placeholder="64000" maxlength="5" required><button class="btn">Asignar CP</button></form><form method="POST" action="{{ route('network.local-shipping.zones.toggle',$zone) }}">@csrf @method('PATCH')<button>Activar/desactivar</button></form></article>@empty<p>Sin zonas configuradas.</p>@endforelse</section></div>
<section class="card"><h2>Nuevo servicio</h2><form method="POST" action="{{ route('network.local-shipping.services.store') }}" class="grid-form">@csrf<input name="code" placeholder="Código" required><input name="name" placeholder="Nombre" required><select name="origin_zone_id" required><option value="">Origen</option>@foreach($zones as $zone)<option value="{{ $zone->id }}">{{ $zone->name }}</option>@endforeach</select><select name="destination_zone_id" required><option value="">Destino</option>@foreach($zones as $zone)<option value="{{ $zone->id }}">{{ $zone->name }}</option>@endforeach</select><select name="service_level"><option value="same_day">Same Day</option><option value="next_day">Next Day</option><option value="scheduled">Scheduled</option></select><input name="base_cost" type="number" step=".01" min="0" placeholder="Costo operativo" required><input name="base_price" type="number" step=".01" min="0" placeholder="Precio venta" required><input name="currency" value="MXN" maxlength="3" required><input name="max_weight" type="number" step=".01" placeholder="Peso máximo"><input name="max_length" type="number" step=".01" placeholder="Largo máximo"><input name="max_width" type="number" step=".01" placeholder="Ancho máximo"><input name="max_height" type="number" step=".01" placeholder="Alto máximo"><input name="estimated_min_hours" type="number" placeholder="Horas mín."><input name="estimated_max_hours" type="number" placeholder="Horas máx."><input type="hidden" name="status" value="active"><button class="btn">Crear servicio</button></form></section>
<section class="card table-wrap"><h2>Servicios</h2><table><thead><tr><th>Servicio</th><th>Ruta</th><th>Nivel</th><th>Costo</th><th>Precio</th><th>Estado</th></tr></thead><tbody>@forelse($services as $service)<tr><td>{{ $service->name }}<br><code>{{ $service->code }}</code></td><td>{{ $service->originZone->name }} → {{ $service->destinationZone->name }}</td><td>{{ $service->service_level }}</td><td>${{ number_format($service->base_cost,2) }}</td><td>${{ number_format($service->base_price,2) }}</td><td><form method="POST" action="{{ route('network.local-shipping.services.toggle',$service) }}">@csrf @method('PATCH')<button>{{ strtoupper($service->status) }}</button></form></td></tr>@empty<tr><td colspan="6">Sin servicios.</td></tr>@endforelse</tbody></table></section>
<section class="card table-wrap"><h2>Envíos locales</h2><table><thead><tr><th>Tracking</th><th>Tenant</th><th>Servicio</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>@forelse($shipments as $shipment)<tr><td><code>{{ $shipment->tracking_number }}</code></td><td>{{ $shipment->tenant->name }}</td><td>{{ $shipment->service_code }}</td><td>{{ $shipment->status }}</td><td>{{ $shipment->created_at }}</td></tr>@empty<tr><td colspan="5">Sin envíos.</td></tr>@endforelse</tbody></table>{{ $shipments->links() }}</section>
@endsection
<style>.grid-2{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:18px}.grid-form{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.card{margin-bottom:18px}.card input,.card select{padding:9px;max-width:100%}.card article{padding:10px 0;border-bottom:1px solid #ddd}.card form{margin-top:8px}</style>
