@push('head')<style>
.tenant-package-dims[hidden]{display:none!important}
.tenant-quote-form{width:100%}.tenant-route-grid{align-items:start}.tenant-route-side{display:grid;gap:.85rem;min-width:0}.tenant-postal{position:relative}.tenant-postal-options{position:absolute;z-index:100;top:calc(100% - 1.2rem);left:0;right:0;max-height:250px;overflow:auto;background:#fff;border:1px solid var(--z-border);border-radius:0 0 12px 12px;box-shadow:0 18px 38px rgba(15,35,75,.18)}.tenant-postal-option{display:block;width:100%;padding:11px 13px;border:0;border-bottom:1px solid var(--z-border);background:#fff;text-align:left;cursor:pointer}.tenant-postal-option strong,.tenant-postal-option small{display:block}.tenant-postal-option small,.tenant-location{color:var(--z-muted)}.tenant-postal-status{padding:12px}.tenant-location{display:block;min-height:1.3rem;margin-top:.35rem;font-size:.8rem}.tenant-package-main{display:grid;grid-template-columns:minmax(220px,260px) minmax(140px,180px);gap:16px;justify-content:start}.tenant-package-dims{display:grid;grid-template-columns:repeat(3,minmax(120px,150px));gap:16px;justify-content:start}.field-error{display:block;min-height:18px;color:var(--z-danger);font-size:.78rem;font-weight:700}@media(max-width:639px){.tenant-route-grid,.tenant-package-main,.tenant-package-dims{grid-template-columns:1fr}}
</style>@endpush
@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $customerPortal ?? false ? route('tenant.customer.app.quote.store',[],false) : route('tenant.b2c.quote.store',[],false) }}" class="z-card z-stack tenant-quote-form" data-public-quote>@csrf
<section class="z-form-section"><div class="z-form-section__head"><h2>Ruta</h2><p class="z-help">La cobertura se valida por código postal.</p></div><div class="z-form-grid tenant-route-grid">
@foreach(['origin'=>['origen','cp_origen'],'destination'=>['destino','cp_destino']] as $side=>$route)
<div class="tenant-route-side"><div class="tenant-postal"><label class="z-field">Código postal de {{ $route[0] }}<input data-postal-display="{{ $side }}" inputmode="numeric" autocomplete="off" role="combobox" aria-expanded="false" value="{{ old($route[1]) && old($side.'_settlement') ? old($route[1]).' - '.old($side.'_settlement') : old($route[1]) }}" required></label><input type="hidden" name="{{ $route[1] }}" data-postal="{{ $side }}" value="{{ old($route[1]) }}"><input type="hidden" name="{{ $side }}_settlement" data-settlement="{{ $side }}" value="{{ old($side.'_settlement') }}"><input type="hidden" name="{{ $side }}_city" data-city="{{ $side }}" value="{{ old($side.'_city') }}"><input type="hidden" name="{{ $side }}_state" data-state="{{ $side }}" value="{{ old($side.'_state') }}"><div class="tenant-postal-options" data-options="{{ $side }}" hidden></div><span data-location="{{ $side }}" hidden></span></div><label class="z-field">Calle y número<input name="{{ $side }}_address" value="{{ old($side.'_address') }}" autocomplete="street-address"></label></div>
@endforeach
</div></section>
<section class="z-form-section"><div class="z-form-section__head"><h2>Paquete</h2><p class="z-help">Sobre: 1 kg fijo. Caja: máximo 40 kg y 60 × 50 × 40 cm.</p></div><div class="tenant-package-main"><label class="z-field">Tipo<select name="tipo_envio" data-package-type><option value="sobre" @selected(old('tipo_envio','sobre')==='sobre')>Sobre</option><option value="caja" @selected(old('tipo_envio')==='caja')>Caja</option></select></label><label class="z-field"><span data-weight-label>Peso</span><input data-weight type="number" step="0.01" min="0.1" max="40" name="peso" value="{{ old('peso',1) }}" required><small class="field-error" data-error="weight"></small></label></div><div class="tenant-package-dims" data-dimensions><label class="z-field">Largo (cm)<input data-dimension="length" type="number" min="1" max="60" name="length" value="{{ old('length') }}"><small class="field-error" data-error="length"></small></label><label class="z-field">Ancho (cm)<input data-dimension="width" type="number" min="1" max="50" name="width" value="{{ old('width') }}"><small class="field-error" data-error="width"></small></label><label class="z-field">Alto (cm)<input data-dimension="height" type="number" min="1" max="40" name="height" value="{{ old('height') }}"><small class="field-error" data-error="height"></small></label></div><div class="z-help" data-billable>Sobre: peso facturable fijo de 1 kg.</div><div class="z-alert z-alert--danger" data-package-error role="alert" hidden>El paquete excede los límites permitidos. Para caja se admite un máximo de 40 kg y dimensiones de hasta 60 × 50 × 40 cm.</div></section>
<div class="z-form-actions"><button class="z-btn" type="submit">Cotizar envío</button></div></form>
@push('scripts')<script>
(()=>{const form=document.querySelector('[data-public-quote]');if(!form)return;const requests=new Map(),close=side=>{const list=form.querySelector(`[data-options="${side}"]`);list.hidden=true;form.querySelector(`[data-postal-display="${side}"]`).setAttribute('aria-expanded','false')},choose=(side,postal,name,city,state)=>{form.querySelector(`[data-postal-display="${side}"]`).value=`${postal} - ${name}`;form.querySelector(`[data-postal="${side}"]`).value=postal;form.querySelector(`[data-settlement="${side}"]`).value=name;form.querySelector(`[data-city="${side}"]`).value=city;form.querySelector(`[data-state="${side}"]`).value=state;form.querySelector(`[data-location="${side}"]`).textContent=[city,state].filter(Boolean).join(', ');close(side)};
const lookup=async(input,preferred='')=>{const side=input.dataset.postalDisplay,postal=(input.value.match(/^\s*(\d{0,5})/)?.[1]||''),list=form.querySelector(`[data-options="${side}"]`),settlement=form.querySelector(`[data-settlement="${side}"]`);input.value=postal;form.querySelector(`[data-postal="${side}"]`).value=postal;settlement.value='';form.querySelector(`[data-city="${side}"]`).value='';form.querySelector(`[data-state="${side}"]`).value='';requests.get(side)?.abort();list.replaceChildren();close(side);if(postal.length!==5)return;const controller=new AbortController();requests.set(side,controller);list.hidden=false;input.setAttribute('aria-expanded','true');const loading=document.createElement('div');loading.className='tenant-postal-status';loading.textContent='Consultando colonias…';list.append(loading);try{const response=await fetch(`/codigos-postales/${postal}`,{headers:{Accept:'application/json'},signal:controller.signal}),data=await response.json();if(!response.ok)throw new Error(data.message);const colonies=Array.isArray(data.colonias)?data.colonias:[];list.replaceChildren();colonies.forEach(colony=>{const button=document.createElement('button'),title=document.createElement('strong'),detail=document.createElement('small');button.type='button';button.className='tenant-postal-option';title.textContent=[postal,colony.nombre,data.municipio,data.estado].filter(Boolean).join(' - ');detail.textContent=[data.municipio,data.estado].filter(Boolean).join(', ');button.append(title,detail);button.addEventListener('click',()=>choose(side,postal,colony.nombre,data.municipio||'',data.estado||''));list.append(button)});if(colonies.length===1)choose(side,postal,colonies[0].nombre,data.municipio||'',data.estado||'');else if(preferred&&colonies.some(c=>c.nombre===preferred))choose(side,postal,preferred,data.municipio||'',data.estado||'');else form.querySelector(`[data-location="${side}"]`).textContent=[data.municipio,data.estado].filter(Boolean).join(', ')}catch(error){if(error.name==='AbortError')return;list.textContent=error.message||'No fue posible consultar el código postal.'}};
form.querySelectorAll('[data-postal-display]').forEach(input=>{const side=input.dataset.postalDisplay,postal=form.querySelector(`[data-postal="${side}"]`).value,preferred=form.querySelector(`[data-settlement="${side}"]`).value;input.addEventListener('input',()=>lookup(input));if(/^\d{5}$/.test(postal)){input.value=postal;lookup(input,preferred)}});const type=form.querySelector('[data-package-type]'),weight=form.querySelector('[data-weight]'),dims=form.querySelector('[data-dimensions]'),fields=[...dims.querySelectorAll('input')],submit=form.querySelector('button[type=submit]');const sync=()=>{const box=type.value==='caja',values=Object.fromEntries(fields.map(i=>[i.dataset.dimension,Number(i.value||0)])),failures={weight:box&&Number(weight.value)>40?'El peso máximo permitido es 40 kg.':'',length:box&&values.length>60?'El largo máximo permitido es 60 cm.':'',width:box&&values.width>50?'El ancho máximo permitido es 50 cm.':'',height:box&&values.height>40?'El alto máximo permitido es 40 cm.':''};dims.hidden=!box;weight.readOnly=!box;form.querySelector('[data-weight-label]').textContent=box?'Peso real (kg)':'Peso';if(!box)weight.value=1;fields.forEach(i=>i.required=box);Object.entries(failures).forEach(([key,value])=>form.querySelector(`[data-error="${key}"]`).textContent=value);const invalid=Object.values(failures).some(Boolean);form.querySelector('[data-package-error]').hidden=!invalid;submit.disabled=invalid;const vol=box?values.length*values.width*values.height/5000:0;form.querySelector('[data-billable]').textContent=box?`Peso volumétrico: ${vol.toFixed(2)} kg · Peso facturable: ${Math.ceil(Math.max(Number(weight.value||0),vol))} kg`:'Sobre: peso facturable fijo de 1 kg.'};[type,weight,...fields].forEach(i=>i.addEventListener('input',sync));sync()})();
(()=>{const form=document.querySelector('[data-public-quote]'),type=form?.querySelector('[data-package-type]'),dims=form?.querySelector('[data-dimensions]'),fields=[...(dims?.querySelectorAll('input')||[])];if(!type)return;const clearEnvelope=()=>{if(type.value==='sobre')fields.forEach(field=>field.value='')};type.addEventListener('change',clearEnvelope);clearEnvelope()})();
</script>@endpush
