@extends('network.layout')
@section('title',$tenant->name.' - ZIGO Network')
@section('content')
@php($renewal=$orders->first(fn($order)=>str_starts_with($order->purchase_key,'renewal:')))
<header class="tenant-head"><div><div class="eyebrow">EMPRESA 360</div><div class="title">{{ $tenant->name }}</div><div class="subtitle">{{ $tenant->slug }} · {{ $tenant->uuid }}</div></div><a class="btn" href="{{ route('network.tenants.edit',$tenant) }}">Editar empresa</a></header>
<nav class="tenant-tabs"><a href="#resumen">Resumen</a><a href="#usuarios">Usuarios</a><a href="#facturacion">Facturación</a><a href="#operacion">Operación</a><a href="#soporte">Soporte</a></nav>
<section id="resumen" class="section-anchor"><h2>Resumen</h2><div class="summary-grid"><div><small>Estado</small><strong>{{ ucfirst($tenant->status) }}</strong></div><div><small>Plan</small><strong>{{ $subscription?->plan?->name??$tenant->currentPlan?->name??'Sin plan' }}</strong></div><div><small>Módulos</small><strong>{{ $modules->count() }}</strong></div><div><small>Consumo</small><strong>{{ $usageSummary?$usageSummary['used'].' / '.($usageSummary['limit']??'∞'):'N/A' }}</strong></div><div><small>Vencimiento</small><strong>{{ $subscription?->current_period_end?->format('d/m/Y')??'N/A' }}</strong></div><div><small>Dominio</small><strong>{{ $tenant->primaryDomain?->domain??'Pendiente' }}</strong></div><div><small>Último pago</small><strong>{{ $attempts->where('status','APPROVED')->first()?->approved_at?->format('d/m/Y')??'Sin pago' }}</strong></div></div>
<div class="card"><h3>Plataforma</h3><p>@forelse($modules as $module)<span class="module-chip">{{ $module->name }}</span>@empty<span class="muted">Sin módulos habilitados.</span>@endforelse</p><p>@forelse($tenant->domains as $domain)<span class="module-chip">{{ $domain->domain }} · {{ strtoupper($domain->status) }}</span>@empty<span class="muted">Sin dominios.</span>@endforelse</p><div class="actions"><a class="btn btn-secondary" href="{{ route('network.tenants.domains.index',$tenant) }}">Dominios</a><a class="btn btn-secondary" href="{{ route('network.tenants.branding.edit',$tenant) }}">Branding</a><a class="btn btn-secondary" href="{{ route('network.tenants.preview',$tenant) }}">Preview</a></div></div></section>
<section id="usuarios" class="section-anchor card"><div class="section-head"><div><h2>Usuarios</h2><p class="muted">{{ $tenant->memberships_count }} memberships · {{ $tenant->owners_count }} owner · {{ $tenant->active_memberships_count }} activos</p></div><a class="btn" href="{{ route('network.users.index',['tenant_id'=>$tenant->id]) }}">Administrar usuarios</a></div><div class="table-wrap"><table><thead><tr><th>Usuario</th><th>Email</th><th>Rol</th><th>Estado</th></tr></thead><tbody>@forelse($tenant->memberships as $membership)<tr><td>{{ $membership->user->name }}</td><td>{{ $membership->user->email }}</td><td>{{ $membership->role }}</td><td><span class="badge badge-{{ $membership->status }}">{{ strtoupper($membership->status) }}</span></td></tr>@empty<tr><td colspan="4">Sin memberships.</td></tr>@endforelse</tbody></table></div></section>
<section id="facturacion" class="section-anchor"><h2>Facturación</h2><div class="billing-grid"><div class="card"><h3>Suscripción</h3>@if($subscription)<p><strong>{{ $subscription->plan->name }} · {{ strtoupper($subscription->status) }}</strong></p><p>{{ $subscription->current_period_start->format('d/m/Y') }} — {{ $subscription->current_period_end->format('d/m/Y') }}</p><p>{{ now()->startOfDay()->diffInDays($subscription->current_period_end->copy()->startOfDay(),false) }} días restantes</p>@if($renewal)<p>{{ $subscription->current_period_end->isPast()?'Saldo pendiente':'Renovación' }}: <strong>${{ number_format((float)$renewal->total_amount,2) }} {{ $renewal->currency }}</strong><br><small>Orden {{ $renewal->status }} · Pago {{ $renewal->payment_status }}</small></p>@endif<a class="btn" href="{{ route('network.subscriptions.show',$subscription) }}">Gestionar ciclo</a>@else<p class="muted">Sin suscripción.</p>@endif</div><div class="card"><h3>Consumo y avisos</h3><p>{{ $usageSummary?$usageSummary['used'].' / '.($usageSummary['limit']??'∞').' operaciones':'Sin consumo disponible' }}</p><p class="muted">El historial de avisos está disponible en el detalle de suscripción.</p></div></div>
<div class="card table-wrap"><h3>Pagos</h3><table><thead><tr><th>Provider</th><th>Importe</th><th>Estado</th><th>Fecha</th><th></th></tr></thead><tbody>@forelse($attempts as $attempt)<tr><td>{{ $attempt->provider }}</td><td>${{ $attempt->amount }} {{ $attempt->currency }}</td><td>{{ $attempt->status }}</td><td>{{ $attempt->approved_at?->format('d/m/Y H:i')??$attempt->created_at->format('d/m/Y H:i') }}</td><td><a class="btn btn-secondary" href="{{ route('network.payments.show',$attempt) }}">Ver</a></td></tr>@empty<tr><td colspan="5">Sin pagos SaaS.</td></tr>@endforelse</tbody></table></div></section>
<section id="operacion" class="section-anchor card"><h2>Operación</h2><p>Consumo: <strong>{{ $usageSummary?$usageSummary['used'].' / '.($usageSummary['limit']??'∞'):'N/A' }}</strong></p><div class="table-wrap"><table><thead><tr><th>UUID</th><th>Estado</th><th>Servicio</th><th>Provider</th><th>Fecha</th></tr></thead><tbody>@forelse($operations as $operation)<tr><td><code>{{ $operation->uuid }}</code></td><td>{{ strtoupper($operation->status) }}</td><td>{{ $operation->service_code??'—' }}</td><td>{{ $operation->provider??'—' }}</td><td>{{ $operation->created_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="5">Sin operaciones tenant.</td></tr>@endforelse</tbody></table></div></section>
<section id="soporte" class="section-anchor card"><div class="section-head"><div><h2>Soporte</h2><p>{{ $tickets->count() }} tickets relacionados.</p>@if($onboarding)<p class="muted">Origen onboarding {{ $onboarding->status }} · <a href="{{ route('network.onboarding.show',$onboarding->uuid) }}">Ver timeline</a></p>@endif</div><a class="btn" href="{{ route('network.support.index',['tenant_id'=>$tenant->id]) }}">Support Center</a></div></section>
<section class="card danger-zone"><h2>Zona de peligro</h2><p class="muted">Estas acciones conservan las validaciones de historial y requieren motivo.</p>@if(in_array($tenant->status,['inactive','suspended','archived'],true))<form method="POST" action="{{ route('network.tenants.archive',$tenant) }}">@csrf<label>Motivo para archivar</label><input name="reason" required maxlength="500"><button class="btn btn-danger">Archivar empresa</button></form>@endif<form method="POST" action="{{ route('network.tenants.destroy',$tenant) }}">@csrf @method('DELETE')<label>Motivo de eliminación definitiva</label><input name="reason" required maxlength="500"><button class="btn btn-danger">Eliminar definitivamente</button></form></section>
@endsection
@push('styles')<style>.tenant-head,.section-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.tenant-tabs{position:sticky;top:0;z-index:4;display:flex;gap:7px;padding:10px;margin:15px 0;background:#f4f7fb;border-bottom:1px solid #dbe4ef}.tenant-tabs a{padding:8px 11px;color:#475569;text-decoration:none;font-weight:800}.section-anchor{scroll-margin-top:65px}.summary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));background:#fff;border-radius:14px;margin-bottom:14px}.summary-grid div{padding:14px;border-right:1px solid #e5e7eb}.summary-grid small,.summary-grid strong{display:block}.summary-grid small{color:#64748b;font-size:10px;text-transform:uppercase;font-weight:900;margin-bottom:5px}.billing-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.module-chip{display:inline-block;margin:3px;padding:5px 8px;border-radius:8px;background:#e7f0ff;color:#174f91;font-weight:800;font-size:11px}.actions{display:flex;gap:7px;flex-wrap:wrap}.btn-secondary{background:#e2e8f0;color:#334155}.btn-danger{background:#b91c1c}.danger-zone{margin-top:34px;border:1px solid #fecaca;background:#fff7f7}.danger-zone form{max-width:640px;margin:12px 0}.danger-zone input{margin:6px 0}.danger-zone label{display:block;font-weight:800}@media(max-width:700px){.tenant-head,.section-head{align-items:flex-start;flex-direction:column}.billing-grid{grid-template-columns:1fr}.tenant-tabs{overflow:auto}}</style>@endpush
