<?php
namespace App\Domain\Support;
use App\Domain\Support\Events\{SupportTicketAssigned,SupportTicketCreated,SupportTicketReplied,SupportTicketResolved}; use App\Domain\Support\Models\{SupportTicket,SupportTicketAttachment,SupportTicketEvent,SupportTicketMessage}; use App\Models\User; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\{DB,Storage}; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
final class SupportTicketService{
 public function create(User$user,array$data,?UploadedFile$file=null):SupportTicket{return DB::transaction(function()use($user,$data,$file){$ticket=SupportTicket::create($data+['requester_user_id'=>$user->id,'channel'=>'WEB','status'=>'OPEN']);$this->audit($ticket,$user,'CREATED',['scope'=>$ticket->scope]);if($file)$this->attach($ticket,null,$user,$file);SupportTicketCreated::dispatch($ticket);return$ticket;});}
 public function reply(SupportTicket$ticket,User$user,string$message,string$visibility='PUBLIC',?UploadedFile$file=null):SupportTicketMessage{return DB::transaction(function()use($ticket,$user,$message,$visibility,$file){$entry=$ticket->messages()->create(['author_user_id'=>$user->id,'visibility'=>$visibility,'message'=>$message]);if($file)$this->attach($ticket,$entry,$user,$file);if($user->id!==$ticket->requester_user_id&&$visibility==='PUBLIC'&&!$ticket->first_response_at)$ticket->update(['first_response_at'=>now()]);SupportTicketReplied::dispatch($ticket,$entry);return$entry;});}
 public function assign(SupportTicket$ticket,User$actor,?int$userId):void{$before=$ticket->assigned_user_id;$ticket->update(['assigned_user_id'=>$userId]);$this->audit($ticket,$actor,'ASSIGNED',['from'=>$before,'to'=>$userId]);SupportTicketAssigned::dispatch($ticket);}
 public function status(SupportTicket$ticket,User$actor,string$status):void{$before=$ticket->status;$values=['status'=>$status];if($status==='RESOLVED')$values['resolved_at']=now();if($status==='CLOSED')$values['closed_at']=now();$ticket->update($values);$this->audit($ticket,$actor,in_array($status,['RESOLVED','CLOSED'],true)?$status:'STATUS_CHANGED',['from'=>$before,'to'=>$status]);if($status==='RESOLVED')SupportTicketResolved::dispatch($ticket);}
 public function priority(SupportTicket$ticket,User$actor,string$priority):void{$before=$ticket->priority;$ticket->update(['priority'=>$priority]);$this->audit($ticket,$actor,'PRIORITY_CHANGED',['from'=>$before,'to'=>$priority]);}
 public function attach(SupportTicket$ticket,?SupportTicketMessage$message,User$user,UploadedFile$file):SupportTicketAttachment{$max=(int)config('zigo_support.attachment_max_kb',5120);if(!$file->isValid()||$file->getSize()>$max*1024||!in_array($file->getMimeType(),config('zigo_support.allowed_mimes',[]),true))throw ValidationException::withMessages(['attachment'=>'El archivo debe ser JPEG, PNG, WEBP o PDF y respetar el límite configurado.']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','application/pdf'=>'pdf'][$file->getMimeType()];$path=$file->storeAs('support/'.$ticket->uuid,Str::uuid().'.'.$ext,config('zigo_support.attachment_disk','local'));$original=Str::limit(preg_replace('~[\x00-\x1F\x7F\\\\/]+~u',' ',basename($file->getClientOriginalName()))?:'adjunto.'.$ext,255,'');return$ticket->attachments()->create(['message_id'=>$message?->id,'uploaded_by_user_id'=>$user->id,'original_name'=>$original,'stored_path'=>$path,'mime'=>$file->getMimeType(),'size'=>$file->getSize()]);}
 public function download(SupportTicketAttachment$attachment){abort_if(str_contains($attachment->stored_path,'..'),404);$disk=Storage::disk(config('zigo_support.attachment_disk','local'));abort_unless($disk->exists($attachment->stored_path),404);return$disk->download($attachment->stored_path,$attachment->original_name,['Content-Type'=>$attachment->mime,'X-Content-Type-Options'=>'nosniff']);}
 private function audit(SupportTicket$ticket,?User$actor,string$type,array$metadata=[]):void{SupportTicketEvent::create(['ticket_id'=>$ticket->id,'actor_user_id'=>$actor?->id,'type'=>$type,'metadata'=>$metadata,'created_at'=>now()]);}
}
