<?php
namespace App\Services\Exports;use App\Models\B2cCotizacion;use App\Models\B2cMovimientoSaldo;use App\Models\B2cRecarga;use Illuminate\Database\Eloquent\Builder;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
final class PaymentExportQuery{
 public function filters(Request $r,string $tab):array{$keys=$tab==='recharges'?['recarga_estado','acreditada','recarga_desde','recarga_hasta','recarga_usuario','recarga_referencia']:['pago_estado','metodo','pago_desde','pago_hasta','pago_cliente','pago_referencia'];return array_filter($r->only($keys),fn($v)=>$v!==null&&$v!=='');}
 public function shipments(array $f=[]):Builder{$q=B2cCotizacion::query()->with('user:id,name,email')->whereNotNull('user_id')->where(function(Builder $q){$q->whereNotNull('payment_id')->orWhereNotNull('payment_status')->orWhereNotNull('payment_verified_at')->orWhereIn('estatus',['PAGO_INICIADO','PAGO_PENDIENTE','PAGO_RECHAZADO','PAGADA','GUIA_GENERADA','ERROR_GENERACION_GUIA']);});
  if(filled($f['pago_estado']??null))$q->where('payment_status',strtolower(trim($f['pago_estado'])));if(($f['metodo']??null)==='saldo')$q->where('payment_status','saldo_prepago');elseif(($f['metodo']??null)==='mercadopago')$q->where(fn(Builder $x)=>$x->whereNull('payment_status')->orWhere('payment_status','<>','saldo_prepago'));$this->dates($q,$f,'pago_desde','pago_hasta','updated_at');
  if(filled($f['pago_cliente']??null)){$v=trim($f['pago_cliente']);$q->whereHas('user',fn(Builder $u)=>$u->where('name','like',"%{$v}%")->orWhere('email','like',"%{$v}%"));}if(filled($f['pago_referencia']??null)){$v=trim($f['pago_referencia']);$q->where(fn(Builder $x)=>$x->where('payment_id','like',"%{$v}%")->orWhere('payment_external_reference','like',"%{$v}%")->orWhere('referencia','like',"%{$v}%"));}return $q;}
 public function recharges(array $f=[]):Builder{$q=B2cRecarga::query()->with('user:id,name,email');if(filled($f['recarga_estado']??null))$q->where('estatus',strtoupper(trim($f['recarga_estado'])));if(($f['acreditada']??null)==='si')$this->credited($q,true);elseif(($f['acreditada']??null)==='no')$this->credited($q,false);$this->dates($q,$f,'recarga_desde','recarga_hasta','created_at');if(filled($f['recarga_usuario']??null)){$v=trim($f['recarga_usuario']);$q->whereHas('user',fn(Builder $u)=>$u->where('name','like',"%{$v}%")->orWhere('email','like',"%{$v}%"));}if(filled($f['recarga_referencia']??null)){$v=trim($f['recarga_referencia']);$q->where(fn(Builder $x)=>$x->where('mp_payment_id','like',"%{$v}%")->orWhere('referencia','like',"%{$v}%"));}return $q;}
 public function movements($items):void{if($items->isEmpty())return;$refs=$items->map(fn(B2cRecarga $r)=>'RECARGA-'.$r->id);$m=B2cMovimientoSaldo::where('tipo','RECARGA')->whereIn('referencia',$refs)->latest('id')->get()->keyBy('referencia');$items->each(fn(B2cRecarga $r)=>$r->setRelation('movimiento',$m->get('RECARGA-'.$r->id)));}
 private function dates(Builder $q,array $f,string $from,string $to,string $column):void{if(filled($f[$from]??null))$q->whereDate($column,'>=',$f[$from]);if(filled($f[$to]??null))$q->whereDate($column,'<=',$f[$to]);}
 private function credited(Builder $q,bool $yes):void{$ref=DB::connection()->getDriverName()==='sqlite'?"'RECARGA-' || b2c_recargas.id":"CONCAT('RECARGA-', b2c_recargas.id)";$method=$yes?'whereExists':'whereNotExists';$q->{$method}(fn($m)=>$m->selectRaw('1')->from('b2c_movimientos_saldo')->whereColumn('b2c_movimientos_saldo.user_id','b2c_recargas.user_id')->where('tipo','RECARGA')->where('estatus','APLICADO')->whereColumn('saldo_nuevo','>','saldo_anterior')->whereRaw('b2c_movimientos_saldo.referencia = '.$ref));}
}
