<?php
namespace App\Services\Exports;use RuntimeException;use ZipArchive;
final class SimpleXlsxWriter{
 public function write(string $target,array $headers,callable $rows):int{$dir=dirname($target);if(!is_dir($dir))mkdir($dir,0775,true);$sheet=tempnam($dir,'sheet-');$h=fopen($sheet,'wb');fwrite($h,'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>');$n=1;$this->row($h,$n++,$headers);$count=0;$rows(function(array $values)use($h,&$n,&$count){$this->row($h,$n++,$values);$count++;});fwrite($h,'</sheetData></worksheet>');fclose($h);
  $z=new ZipArchive();if($z->open($target,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)throw new RuntimeException('No fue posible crear XLSX.');
  $z->addFromString('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');
  $z->addFromString('_rels/.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
  $z->addFromString('xl/workbook.xml','<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Guías" sheetId="1" r:id="rId1"/></sheets></workbook>');
  $z->addFromString('xl/_rels/workbook.xml.rels','<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');$z->addFile($sheet,'xl/worksheets/sheet1.xml');$z->close();unlink($sheet);return $count;}
 private function row($h,int $number,array $values):void{fwrite($h,'<row r="'.$number.'">');foreach(array_values($values) as $i=>$v){$ref=$this->column($i+1).$number;$text=$v===null||$v===''?'—':(string)$v;fwrite($h,'<c r="'.$ref.'" t="inlineStr"><is><t xml:space="preserve">'.htmlspecialchars($text,ENT_XML1|ENT_QUOTES,'UTF-8').'</t></is></c>');}fwrite($h,'</row>');}
 private function column(int $n):string{$s='';while($n>0){$n--; $s=chr(65+$n%26).$s;$n=intdiv($n,26);}return $s;}
}
