@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ route('tenant.customer.app.quote.store',[],false) }}" class="z-stack customer-complete-quote" data-complete-quote>@csrf
<div class="customer-address-grid">
@foreach(['sender'=>['ORIGEN','origen','cp_origen',$originAddresses,'origin_settlement'],'recipient'=>['DESTINO','destino','cp_destino',$destinationAddresses,'destination_settlement']] as $key=>$section)
<section class="z-card z-form-section" data-address-section="{{ $key }}"><div class="z-form-section__head"><div class="z-eyebrow">{{ $section[0] }}</div><h2>Datos de {{ $section[1] }}</h2></div>
@if($section[3]->isNotEmpty())<label class="z-field">Usar dirección guardada<select name="{{ $key }}_address_uuid" data-saved-address><option value="">Capturar dirección nueva</option>@foreach($section[3] as $saved)@php($savedAddress=$saved->only(['contact_name','phone','email','street','exterior','interior','postal_code','settlement','municipality','state','references']))<option value="{{ $saved->uuid }}" data-address="{{ json_encode($savedAddress,JSON_HEX_APOS|JSON_HEX_QUOT) }}">{{ $saved->alias }} · {{ $saved->settlement }}, CP {{ $saved->postal_code }}</option>@endforeach</select></label>@endif
<div class="z-form-grid"><label class="z-field">Nombre<input name="{{ $key }}[name]" data-address-field="contact_name" value="{{ old($key.'.name') }}" required></label><label class="z-field">Teléfono<input name="{{ $key }}[phone]" data-address-field="phone" value="{{ old($key.'.phone') }}" required></label></div>
<label class="z-field">Correo <span class="z-muted">(opcional)</span><input type="email" name="{{ $key }}[email]" data-address-field="email" value="{{ old($key.'.email') }}"></label>
<div class="postal-combobox" data-postal-combobox><label class="z-field" for="postal-{{ $key }}">Código postal<input id="postal-{{ $key }}" name="{{ $section[2] }}" data-postal="{{ $key }}" data-address-field="postal_code" inputmode="numeric" maxlength="5" autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="postal-options-{{ $key }}" value="{{ old($section[2]) }}" required></label><input type="hidden" name="{{ $section[4] }}" data-settlement="{{ $key }}" data-address-field="settlement" value="{{ old($section[4]) }}"><input type="hidden" name="{{ $key==='sender'?'origin_city':'destination_city' }}" data-municipality="{{ $key }}" value="{{ old($key==='sender'?'origin_city':'destination_city') }}"><input type="hidden" name="{{ $key==='sender'?'origin_state':'destination_state' }}" data-state="{{ $key }}" value="{{ old($key==='sender'?'origin_state':'destination_state') }}"><div id="postal-options-{{ $key }}" class="postal-options" data-postal-options="{{ $key }}" role="listbox" hidden></div><small class="postal-support z-muted" data-location="{{ $key }}" aria-live="polite">Municipio y estado</small></div>
<div class="z-form-grid"><label class="z-field">Calle o avenida<input name="{{ $key }}[street]" data-address-field="street" value="{{ old($key.'.street') }}" required></label><label class="z-field">Número exterior<input name="{{ $key }}[exterior]" data-address-field="exterior" value="{{ old($key.'.exterior') }}" required></label></div>
<label class="z-field">Número interior <span class="z-muted">(opcional)</span><input name="{{ $key }}[interior]" data-address-field="interior" value="{{ old($key.'.interior') }}"></label><label class="z-field">Referencias<textarea name="{{ $key }}[references]" data-address-field="references">{{ old($key.'.references') }}</textarea></label><label class="z-choice"><input type="checkbox" name="save_{{ $key }}_address" value="1"><span>Guardar esta dirección</span></label>
</section>
@endforeach
</div>
<section class="z-card z-form-section"><div class="z-form-section__head"><div class="z-eyebrow">PAQUETE</div><h2>¿Qué vas a enviar?</h2></div><div class="z-form-grid"><label class="z-field">Tipo<select name="tipo_envio" data-package-type><option value="sobre" @selected(old('tipo_envio','sobre')==='sobre')>Sobre</option><option value="caja" @selected(old('tipo_envio')==='caja')>Caja</option></select></label><label class="z-field"><span data-weight-label>Peso</span><input name="peso" data-weight type="number" step="0.01" min="0.1" max="40" value="{{ old('peso',1) }}" required><small class="field-error" data-error="weight"></small></label></div><p class="package-help z-muted" data-envelope-help>Sobre: peso facturable fijo de 1 kg.</p><div class="z-form-grid z-form-grid--3" data-dimensions><label class="z-field">Largo (cm)<input name="length" data-dimension="length" type="number" min="1" max="60" value="{{ old('length') }}"><small class="field-error" data-error="length"></small></label><label class="z-field">Ancho (cm)<input name="width" data-dimension="width" type="number" min="1" max="50" value="{{ old('width') }}"><small class="field-error" data-error="width"></small></label><label class="z-field">Alto (cm)<input name="height" data-dimension="height" type="number" min="1" max="40" value="{{ old('height') }}"><small class="field-error" data-error="height"></small></label></div><div class="package-summary" data-package-summary><div><span>Peso real</span><strong data-real>1.00 kg</strong></div><div><span>Peso volumétrico</span><strong data-volumetric>—</strong></div><div><span>Peso facturable</span><strong data-billable>1 kg</strong></div></div><div class="z-alert z-alert--danger" data-package-error hidden>El paquete excede los límites permitidos. Para caja se admite un máximo de 40 kg y dimensiones de hasta 60 × 50 × 40 cm.</div></section>
<div class="z-form-actions"><button class="z-btn" type="submit">Ver servicios disponibles</button></div></form>
@push('head')<style>
.customer-address-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.postal-combobox{position:relative;margin-bottom:16px}.postal-combobox .z-field{margin:0}.postal-options{position:absolute;z-index:100;top:calc(100% - 20px);left:0;right:0;max-height:260px;overflow:auto;background:#fff;border:1px solid var(--z-border);border-radius:0 0 12px 12px;box-shadow:0 18px 38px rgba(15,35,75,.18)}.postal-option{display:block;width:100%;padding:12px 14px;border:0;border-bottom:1px solid var(--z-border);background:#fff;color:var(--z-text);text-align:left;cursor:pointer}.postal-option:last-child{border-bottom:0}.postal-option:hover,.postal-option:focus{background:var(--z-surface-subtle);outline:0}.postal-option strong,.postal-option small{display:block}.postal-option strong{font-size:.9rem}.postal-option small{margin-top:2px;color:var(--z-muted)}.postal-status{padding:13px 14px;color:var(--z-muted);font-size:.9rem}.postal-support{display:block;min-height:20px;margin-top:6px;font-size:.8rem}.package-help{margin:-4px 0 16px}.field-error{display:block;min-height:18px;margin-top:5px;color:var(--z-danger);font-size:.78rem;font-weight:700}.package-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;border:1px solid var(--z-border);border-radius:14px;overflow:hidden}.package-summary div{padding:16px;background:var(--z-surface-subtle)}.package-summary span,.package-summary strong{display:block}.package-summary span{font-size:.78rem;color:var(--z-muted);margin-bottom:4px}@media(max-width:850px){.customer-address-grid{grid-template-columns:1fr}}@media(max-width:620px){.package-summary{grid-template-columns:1fr}.postal-options{max-height:220px}}
</style>@endpush
@push('scripts')<script>
(()=>{const form=document.querySelector('[data-complete-quote]');if(!form)return;const requests=new Map();
const close=side=>{const input=form.querySelector(`[data-postal="${side}"]`),options=form.querySelector(`[data-postal-options="${side}"]`);options.hidden=true;input.setAttribute('aria-expanded','false')};
const choose=(side,postal,colony,municipality,state)=>{form.querySelector(`[data-postal="${side}"]`).value=postal;form.querySelector(`[data-settlement="${side}"]`).value=colony;form.querySelector(`[data-municipality="${side}"]`).value=municipality;form.querySelector(`[data-state="${side}"]`).value=state;form.querySelector(`[data-location="${side}"]`).textContent=[municipality,state].filter(Boolean).join(', ');close(side)};
const lookup=async(input,preferred='')=>{const side=input.dataset.postal,options=form.querySelector(`[data-postal-options="${side}"]`),settlement=form.querySelector(`[data-settlement="${side}"]`),municipalityField=form.querySelector(`[data-municipality="${side}"]`),stateField=form.querySelector(`[data-state="${side}"]`),location=form.querySelector(`[data-location="${side}"]`),postal=input.value.replace(/\D/g,'').slice(0,5);input.value=postal;requests.get(side)?.abort();settlement.value='';municipalityField.value='';stateField.value='';location.textContent=postal.length===5?'Consultando municipio y estado…':'Municipio y estado';options.replaceChildren();close(side);if(postal.length!==5)return;const controller=new AbortController();requests.set(side,controller);options.hidden=false;input.setAttribute('aria-expanded','true');const loading=document.createElement('div');loading.className='postal-status';loading.textContent='Consultando colonias…';options.append(loading);try{const response=await fetch(`/codigos-postales/${postal}`,{headers:{Accept:'application/json'},signal:controller.signal}),data=await response.json();if(!response.ok)throw new Error(data.message);const colonies=Array.isArray(data.colonias)?data.colonias:[];options.replaceChildren();if(!colonies.length)throw new Error('No encontramos colonias para este código postal.');colonies.forEach(colony=>{const name=colony.nombre||'',municipality=data.municipio||'',state=data.estado||'',button=document.createElement('button'),title=document.createElement('strong'),detail=document.createElement('small');button.type='button';button.className='postal-option';button.setAttribute('role','option');title.textContent=[postal,name,municipality,state].filter(Boolean).join(' - ');detail.textContent=[municipality,state].filter(Boolean).join(', ');button.append(title,detail);button.addEventListener('click',()=>choose(side,postal,name,municipality,state));options.append(button)});if(colonies.length===1||preferred){const selected=colonies.find(item=>item.nombre===preferred)||colonies[0];choose(side,postal,selected.nombre,data.municipio||'',data.estado||'')}else{location.textContent=[data.municipio,data.estado].filter(Boolean).join(', ')}}catch(error){if(error.name==='AbortError')return;options.replaceChildren();const status=document.createElement('div');status.className='postal-status';status.textContent=error.message||'No fue posible consultar el código postal.';options.append(status);options.hidden=false;input.setAttribute('aria-expanded','true');location.textContent='Verifica el código postal'}};
form.querySelectorAll('[data-postal]').forEach(input=>{input.addEventListener('input',()=>lookup(input));input.addEventListener('focus',()=>{if(input.value.length===5&&!form.querySelector(`[data-settlement="${input.dataset.postal}"]`).value)lookup(input)});const preferred=form.querySelector(`[data-settlement="${input.dataset.postal}"]`).value;if(/^\d{5}$/.test(input.value))lookup(input,preferred)});
form.querySelectorAll('[data-saved-address]').forEach(select=>select.addEventListener('change',()=>{const raw=select.selectedOptions[0]?.dataset.address;if(!raw)return;const section=select.closest('[data-address-section]'),address=JSON.parse(raw);Object.entries(address).forEach(([key,value])=>{const field=section.querySelector(`[data-address-field="${key}"]`);if(field)field.value=value??''});lookup(section.querySelector('[data-postal]'),address.settlement||'')}));document.addEventListener('click',event=>{if(!event.target.closest('[data-postal-combobox]'))form.querySelectorAll('[data-postal]').forEach(input=>close(input.dataset.postal))});
const type=form.querySelector('[data-package-type]'),weight=form.querySelector('[data-weight]'),dims=form.querySelector('[data-dimensions]'),inputs=[...dims.querySelectorAll('input')],error=form.querySelector('[data-package-error]'),submit=form.querySelector('button[type=submit]'),weightLabel=form.querySelector('[data-weight-label]'),envelopeHelp=form.querySelector('[data-envelope-help]');const sync=()=>{const box=type.value==='caja';dims.hidden=!box;weight.readOnly=!box;weightLabel.textContent=box?'Peso real (kg)':'Peso';envelopeHelp.hidden=box;if(!box)weight.value=1;inputs.forEach(i=>i.required=box);const values=Object.fromEntries(inputs.map(i=>[i.dataset.dimension,Number(i.value||0)])),real=Number(weight.value||0),vol=box?values.length*values.width*values.height/5000:0,billable=box?Math.ceil(Math.max(real,vol)):1,failures={weight:box&&real>40?'El peso máximo permitido es 40 kg.':'',length:box&&values.length>60?'El largo máximo permitido es 60 cm.':'',width:box&&values.width>50?'El ancho máximo permitido es 50 cm.':'',height:box&&values.height>40?'El alto máximo permitido es 40 cm.':''},invalid=Object.values(failures).some(Boolean);Object.entries(failures).forEach(([key,message])=>form.querySelector(`[data-error="${key}"]`).textContent=message);form.querySelector('[data-real]').textContent=`${real.toFixed(2)} kg`;form.querySelector('[data-volumetric]').textContent=box?`${vol.toFixed(2)} kg`:'—';form.querySelector('[data-billable]').textContent=`${billable} kg`;error.hidden=!invalid;submit.disabled=invalid};[type,weight,...inputs].forEach(i=>i.addEventListener('input',sync));form.addEventListener('submit',event=>{const missing=[...form.querySelectorAll('[data-settlement]')].some(field=>!field.value);if(missing){event.preventDefault();form.querySelectorAll('[data-postal]').forEach(input=>{if(!form.querySelector(`[data-settlement="${input.dataset.postal}"]`).value)form.querySelector(`[data-location="${input.dataset.postal}"]`).textContent='Selecciona una colonia del listado.'})}});sync()})();
</script>@endpush
