<?php
namespace App\Http\Controllers\Tenant;
use App\Domain\AI\Agents\Enums\AgentVersionStatus;use App\Domain\AI\Agents\Models\Agent;use App\Domain\AI\Knowledge\Contracts\KnowledgeRetriever;use App\Domain\AI\Knowledge\Enums\{KnowledgeSourceStatus,KnowledgeVersionStatus};use App\Domain\AI\Knowledge\Models\{AgentVersionKnowledgeSource,KnowledgeSourceVersion};use App\Domain\AI\Tenancy\AiTenantBoundary;use App\Http\Controllers\Controller;use App\Http\Requests\Tenant\SearchKnowledgeRequest;use App\Http\Support\AiLaunchpadHttpGate;
final class AiAgentController extends Controller
{
 public function index(AiLaunchpadHttpGate$gate,AiTenantBoundary$tenants){$gate->ensure(auth()->user());return view('tenant.admin.ai-agents.index',['tenant'=>$tenants->requireTenant(),'agents'=>Agent::query()->latest()->paginate(20)]);}
 public function show(Agent$agent,AiLaunchpadHttpGate$gate,AiTenantBoundary$tenants){$gate->ensure(auth()->user());$gate->assertCurrentTenant($agent);return view('tenant.admin.ai-agents.show',$this->detail($agent,$tenants));}
 public function search(SearchKnowledgeRequest$request,Agent$agent,AiLaunchpadHttpGate$gate,AiTenantBoundary$tenants,KnowledgeRetriever$retriever){$gate->ensure($request->user());$gate->assertCurrentTenant($agent);$data=$this->detail($agent,$tenants);abort_unless($data['draftVersion'],404);$data['searchMatches']=$retriever->retrieve($data['draftVersion'],$request->queryData());$data['searched']=true;$data['searchQuestion']=$request->validated('question');return view('tenant.admin.ai-agents.show',$data);}
 private function detail(Agent$agent,AiTenantBoundary$tenants):array{$agent->load(['contract','versions'=>fn($q)=>$q->orderByDesc('version_number')]);if($agent->contract)$agent->contract->load(['versions'=>fn($q)=>$q->orderByDesc('version_number')]);$draft=$agent->versions->first(fn($v)=>$v->status===AgentVersionStatus::Draft);$links=$draft?AgentVersionKnowledgeSource::query()->where('agent_version_id',$draft->id)->with(['knowledgeVersion.source','knowledgeVersion.index'])->get():collect();$available=KnowledgeSourceVersion::query()->where('status',KnowledgeVersionStatus::Approved->value)->whereHas('source',fn($q)=>$q->where('status',KnowledgeSourceStatus::Active->value))->with(['source','index'])->get();return['tenant'=>$tenants->requireTenant(),'agent'=>$agent,'draftVersion'=>$draft,'knowledgeLinks'=>$links,'availableKnowledge'=>$available,'searchMatches'=>[],'searched'=>false,'searchQuestion'=>''];}
}
