<?php
namespace App\Http\Controllers\Tenant;
use App\Domain\AI\Launchpad\Data\LaunchpadRecommendationData;use App\Domain\AI\Launchpad\Models\AgentLaunchpadSession;use App\Domain\AI\Launchpad\Services\{ConvertLaunchpadSessionToAgentDraftService,GenerateLaunchpadRecommendationService};use App\Domain\AI\Tenancy\AiTenantBoundary;use App\Http\Controllers\Controller;use App\Http\Requests\Tenant\StoreAgentLaunchpadRequest;use App\Http\Support\AiLaunchpadHttpGate;use Illuminate\Http\RedirectResponse;use Illuminate\Validation\ValidationException;
final class AiAgentLaunchpadController extends Controller
{
 public function create(AiLaunchpadHttpGate$gate,AiTenantBoundary$t){$gate->ensure(auth()->user());return view('tenant.admin.ai-agents.launchpad.create',['tenant'=>$t->requireTenant()]);}
 public function store(StoreAgentLaunchpadRequest$r,AiLaunchpadHttpGate$gate,GenerateLaunchpadRecommendationService$s):RedirectResponse{$gate->ensure($r->user());try{$session=$s->generate($r->user(),$r->data());}catch(\InvalidArgumentException){throw ValidationException::withMessages(['problem_description'=>'No fue posible generar una propuesta con esta información.']);}return redirect()->route('tenant.admin.ai-agents.launchpad.show',$session);}
 public function show(AgentLaunchpadSession$launchpadSession,AiLaunchpadHttpGate$gate,AiTenantBoundary$t){$gate->ensure(auth()->user());$gate->assertCurrentTenant($launchpadSession);try{$recommendation=LaunchpadRecommendationData::fromArray($launchpadSession->recommendation??[]);}catch(\Throwable){abort(422,'La propuesta no está disponible.');}return view('tenant.admin.ai-agents.launchpad.show',['tenant'=>$t->requireTenant(),'launchpadSession'=>$launchpadSession,'recommendation'=>$recommendation]);}
 public function convert(AgentLaunchpadSession$launchpadSession,AiLaunchpadHttpGate$gate,ConvertLaunchpadSessionToAgentDraftService$s):RedirectResponse{$gate->ensure(auth()->user());$gate->assertCurrentTenant($launchpadSession);$agent=$s->convert(auth()->user(),$launchpadSession);return redirect()->route('tenant.admin.ai-agents.show',$agent)->with('success','El borrador del agente fue creado.');}
}
