<?php
namespace App\Http\Controllers\Tenant;
use App\Domain\AI\Knowledge\Models\{KnowledgeSource,KnowledgeSourceVersion};use App\Domain\AI\Knowledge\Services\{ApproveKnowledgeVersionService,CreateKnowledgeRevisionService,CreateKnowledgeSourceService};use App\Domain\AI\Tenancy\AiTenantBoundary;use App\Http\Controllers\Controller;use App\Http\Requests\Tenant\{EmptyKnowledgeMutationRequest,StoreKnowledgeRevisionRequest,StoreKnowledgeSourceRequest};use App\Http\Support\AiLaunchpadHttpGate;use Illuminate\Validation\ValidationException;
final class AiKnowledgeController extends Controller
{
 public function index(AiLaunchpadHttpGate$g,AiTenantBoundary$t){$g->ensure(auth()->user());return view('tenant.admin.ai-knowledge.index',['tenant'=>$t->requireTenant(),'sources'=>KnowledgeSource::query()->with('versions.index')->latest()->paginate(20)]);}
 public function create(AiLaunchpadHttpGate$g,AiTenantBoundary$t){$g->ensure(auth()->user());return view('tenant.admin.ai-knowledge.create',['tenant'=>$t->requireTenant()]);}
 public function store(StoreKnowledgeSourceRequest$r,AiLaunchpadHttpGate$g,CreateKnowledgeSourceService$s){$g->ensure($r->user());$source=$s->create($r->user(),$r->sourceName(),$r->knowledgeData());return redirect()->route('tenant.admin.ai-knowledge.show',$source)->with('success','La fuente fue creada como borrador.');}
 public function show(KnowledgeSource$knowledgeSource,AiLaunchpadHttpGate$g,AiTenantBoundary$t){$g->ensure(auth()->user());$g->assertCurrentTenant($knowledgeSource);$knowledgeSource->load(['versions'=>fn($q)=>$q->with('index')->orderByDesc('version_number')]);return view('tenant.admin.ai-knowledge.show',['tenant'=>$t->requireTenant(),'source'=>$knowledgeSource]);}
 public function revision(KnowledgeSource$knowledgeSource,AiLaunchpadHttpGate$g,AiTenantBoundary$t){$g->ensure(auth()->user());$g->assertCurrentTenant($knowledgeSource);return view('tenant.admin.ai-knowledge.revision',['tenant'=>$t->requireTenant(),'source'=>$knowledgeSource]);}
 public function storeRevision(StoreKnowledgeRevisionRequest$r,KnowledgeSource$knowledgeSource,AiLaunchpadHttpGate$g,CreateKnowledgeRevisionService$s){$g->ensure($r->user());$g->assertCurrentTenant($knowledgeSource);$s->create($r->user(),$knowledgeSource,$r->knowledgeData());return redirect()->route('tenant.admin.ai-knowledge.show',$knowledgeSource)->with('success','La nueva revisión fue creada.');}
 public function approve(EmptyKnowledgeMutationRequest$r,KnowledgeSource$knowledgeSource,KnowledgeSourceVersion$knowledgeVersion,AiLaunchpadHttpGate$g,ApproveKnowledgeVersionService$s){$g->ensure($r->user());$g->assertCurrentTenant($knowledgeSource);$g->assertCurrentTenant($knowledgeVersion);abort_unless($knowledgeVersion->knowledge_source_id===$knowledgeSource->id,404);try{$s->approve($r->user(),$knowledgeVersion);}catch(\DomainException){throw ValidationException::withMessages(['version'=>'Esta versión no puede aprobarse.']);}return back()->with('success','La versión fue aprobada.');}
}
