<?php
namespace App\Http\Controllers\Tenant;
use App\Domain\Network\Commerce\{PlatformPaymentService,TenantSaasOrderService};use App\Domain\Network\Commerce\Models\{NetworkCommercialProduct,TenantSaasOrder};use App\Domain\Network\Tenancy\{TenantAccessService,TenantContext};use App\Http\Controllers\Controller;use Illuminate\Http\Request;
final class TenantSaasController extends Controller{
 public function marketplace(Request$r,TenantContext$c){$products=NetworkCommercialProduct::with(['plan','module'])->where('is_active',true)->orderBy('sort_order')->get();$keys=[];foreach($products as$p)$keys[$p->uuid]=(string)\Illuminate\Support\Str::uuid();$r->session()->put('saas_purchase_keys',$keys);return view('tenant.admin.marketplace',['tenant'=>$c->tenant()->load('branding'),'products'=>$products,'keys'=>$keys]);}
 public function purchase(Request$r,TenantContext$c,TenantAccessService$a,TenantSaasOrderService$s){abort_unless($a->canManageTenant($r->user()),403);$d=$r->validate(['product_uuid'=>['required','uuid'],'purchase_key'=>['required','uuid']]);abort_unless(hash_equals((string)$r->session()->get('saas_purchase_keys.'.$d['product_uuid']),$d['purchase_key']),419);$p=NetworkCommercialProduct::where('uuid',$d['product_uuid'])->where('is_active',true)->firstOrFail();$o=$s->create($c->tenant(),$r->user(),$p,$d['purchase_key']);return redirect()->route('tenant.admin.saas.payment',$o->uuid);}
 public function purchases(TenantContext$c){return view('tenant.admin.purchases',['tenant'=>$c->tenant()->load('branding'),'orders'=>TenantSaasOrder::where('tenant_id',$c->id())->latest()->paginate(30)]);}
 public function payment(string$order,TenantContext$c){$o=$this->order($order,$c);return view('tenant.admin.saas-payment',['tenant'=>$c->tenant()->load('branding'),'order'=>$o]);}
 public function checkout(string$order,TenantContext$c,TenantAccessService$a,PlatformPaymentService$s){abort_unless($a->canManageTenant(auth()->user()),403);abort_unless(config('zigo_payments.platform.enabled'),503);$attempt=$s->initialize($this->order($order,$c));$url=$attempt->getRawOriginal('init_point');$host=(string)parse_url($url,PHP_URL_HOST);abort_unless(parse_url($url,PHP_URL_SCHEME)==='https'&&preg_match('/(^|\.)mercadopago\.com(\.mx)?$/i',$host),502);return redirect()->away($url);}
 public function returned(string$order,string$result,TenantContext$c){abort_unless(in_array($result,['success','pending','failure'],true),404);return view('tenant.admin.saas-return',['tenant'=>$c->tenant()->load('branding'),'order'=>$this->order($order,$c)->fresh(),'result'=>$result]);}
 private function order(string$uuid,TenantContext$c):TenantSaasOrder{return TenantSaasOrder::where('tenant_id',$c->id())->where('uuid',$uuid)->firstOrFail();}
}
