<?php
namespace App\Http\Controllers\Tenant;use App\Domain\ApiHub\Models\{TenantApiClient,TenantApiKey,TenantApiQuotaPolicy,TenantApiUsageEvent,TenantApiWebhookDelivery,TenantApiWebhookEndpoint};use App\Domain\Network\Billing\EntitlementService;use App\Domain\Network\Tenancy\{TenantAccessService,TenantContext};use App\Services\ApiHub\Webhooks\{WebhookSigner,WebhookUrlGuard};use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Support\Facades\{Crypt,DB};use Illuminate\Support\Str;use Illuminate\Validation\Rule;
final class TenantApiHubController extends Controller{public function index(Request$r,TenantContext$c,TenantAccessService$access){$tenant=$c->tenant()->load('branding');$policy=TenantApiQuotaPolicy::current($tenant->id);$used=TenantApiUsageEvent::where('tenant_id',$tenant->id)->where('occurred_at','>=',now()->startOfMonth())->sum('units');return view('tenant.admin.api-hub',['tenant'=>$tenant,'enabled'=>app(EntitlementService::class)->has($tenant,'API'),'policy'=>$policy,'used'=>$used,'clients'=>TenantApiClient::with(['keys','webhooks'])->where('tenant_id',$tenant->id)->get(),'deliveries'=>TenantApiWebhookDelivery::where('tenant_id',$tenant->id)->latest()->limit(20)->get(),'canManage'=>$access->hasRole(['owner','admin'],$r->user())]);}
 public function client(Request$r,TenantContext$c,TenantAccessService$a){$this->manage($r,$a);$d=$r->validate(['name'=>['required','string','max:160'],'description'=>['nullable','string','max:1000'],'environment'=>['required',Rule::in(['STAGE','PRODUCTION'])]]);TenantApiClient::create($d+['tenant_id'=>$c->id(),'status'=>'ACTIVE','created_by_user_id'=>$r->user()->id]);return back()->with('success','Cliente API creado.');}
 public function key(Request$r,string$client,TenantContext$c,TenantAccessService$a){$this->manage($r,$a);$apiClient=$this->clientOwned($c,$client);$d=$r->validate(['name'=>['required','string','max:160'],'scopes'=>['required','array','min:1'],'scopes.*'=>['required',Rule::in(TenantApiKey::SCOPES)],'expires_at'=>['nullable','date','after:today']]);$prefix=config('zigo_api_hub.key_prefix');$plain=$prefix.'_'.rtrim(strtr(base64_encode(random_bytes(36)),'+/','-_'),'=');$created=TenantApiKey::create(['tenant_id'=>$c->id(),'api_client_id'=>$apiClient->id,'key_prefix'=>$prefix,'key_hash'=>hash('sha256',$plain),'last_four'=>substr($plain,-4),'name'=>$d['name'],'scopes'=>array_values(array_unique($d['scopes'])),'expires_at'=>$d['expires_at']??null]);\App\Domain\ApiHub\Models\TenantApiAuditEvent::create(['tenant_id'=>$c->id(),'api_client_id'=>$apiClient->id,'api_key_id'=>$created->id,'actor_user_id'=>$r->user()->id,'action'=>'KEY_CREATED','metadata'=>['scopes'=>$created->scopes],'created_at'=>now()]);return back()->with('success','API key creada. Cópiala ahora; no podremos volver a mostrarla.')->with('new_tenant_api_key',$plain);}
 public function revoke(Request$r,string$client,string$key,TenantContext$c,TenantAccessService$a){$this->manage($r,$a);$apiClient=$this->clientOwned($c,$client);$revoked=TenantApiKey::where('uuid',$key)->where('tenant_id',$c->id())->where('api_client_id',$apiClient->id)->firstOrFail();$revoked->update(['revoked_at'=>now()]);\App\Domain\ApiHub\Models\TenantApiAuditEvent::create(['tenant_id'=>$c->id(),'api_client_id'=>$apiClient->id,'api_key_id'=>$revoked->id,'actor_user_id'=>$r->user()->id,'action'=>'KEY_REVOKED','created_at'=>now()]);return back()->with('success','API key revocada.');}
 public function webhook(Request$r,string$client,TenantContext$c,TenantAccessService$a,WebhookSigner$signer,WebhookUrlGuard$guard){$this->manage($r,$a);$apiClient=$this->clientOwned($c,$client);$d=$r->validate(['name'=>['required','string','max:160'],'url'=>['required','url','max:2048'],'events'=>['required','array','min:1'],'events.*'=>['required',Rule::in(TenantApiWebhookEndpoint::EVENTS)]]);$guard->assertAllowed($d['url'],app()->environment(['local','testing'])?'sandbox':'production');$plain=$signer->generateSecret();TenantApiWebhookEndpoint::create(['tenant_id'=>$c->id(),'api_client_id'=>$apiClient->id,'name'=>$d['name'],'url'=>$d['url'],'events'=>array_values(array_unique($d['events'])),'status'=>'ACTIVE','secret_encrypted'=>Crypt::encryptString($plain),'secret_prefix'=>substr($plain,0,22)]);return back()->with('success','Webhook creado. Copia el secreto ahora.')->with('new_tenant_webhook_secret',$plain);}
 public function rotateWebhook(Request$r,string$webhook,TenantContext$c,TenantAccessService$a,WebhookSigner$signer){$this->manage($r,$a);$endpoint=TenantApiWebhookEndpoint::where('uuid',$webhook)->where('tenant_id',$c->id())->firstOrFail();$plain=$signer->generateSecret();$endpoint->update(['secret_encrypted'=>Crypt::encryptString($plain),'secret_prefix'=>substr($plain,0,22)]);\App\Domain\ApiHub\Models\TenantApiAuditEvent::create(['tenant_id'=>$c->id(),'api_client_id'=>$endpoint->api_client_id,'actor_user_id'=>$r->user()->id,'action'=>'WEBHOOK_SECRET_ROTATED','metadata'=>['webhook_uuid'=>$endpoint->uuid],'created_at'=>now()]);return back()->with('success','Secreto rotado.')->with('new_tenant_webhook_secret',$plain);}
 public function webhookStatus(Request$r,string$webhook,TenantContext$c,TenantAccessService$a){$this->manage($r,$a);$d=$r->validate(['status'=>['required',Rule::in(['ACTIVE','PAUSED','DISABLED'])]]);TenantApiWebhookEndpoint::where('uuid',$webhook)->where('tenant_id',$c->id())->firstOrFail()->update($d);return back()->with('success','Estado webhook actualizado.');}
 private function manage(Request$r,TenantAccessService$a):void{abort_unless($a->hasRole(['owner','admin'],$r->user()),403);}private function clientOwned(TenantContext$c,string$uuid){return TenantApiClient::where('uuid',$uuid)->where('tenant_id',$c->id())->firstOrFail();}}

