<?php

namespace App\Http\Controllers\Tenant;

use App\Domain\Network\Tenancy\TenantContext;
use App\Domain\Shipping\Local\LocalCoverageService;
use App\Domain\Shipping\Local\Models\{LocalShippingPackageRule,LocalShippingPricingRule,LocalShippingService,LocalShippingZone,LocalShippingZonePostalCode};
use App\Http\Controllers\Controller;
use App\Models\ZigoPostalCode;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

final class TenantLogisticsController extends Controller
{
    public function index(Request $request,TenantContext $context){$tenant=$context->tenant()->load('branding');$services=LocalShippingService::with(['pricingRules','packageRules'])->where('tenant_id',$context->id())->orderBy('sort_order')->get();$coverage=LocalShippingZonePostalCode::where('tenant_id',$context->id())->latest()->paginate(30);$postal=ZigoPostalCode::query()->where('activo',true)->when($request->q,fn($q,$v)=>$q->where(fn($x)=>$x->where('codigo_postal','like',$v.'%')->orWhere('asentamiento','like','%'.$v.'%')))->when($request->state,fn($q,$v)=>$q->where('estado',$v))->when($request->municipality,fn($q,$v)=>$q->where('municipio',$v))->select('codigo_postal','estado','municipio')->distinct()->limit(100)->get();return view('tenant.admin.logistics',compact('tenant','services','coverage','postal'));}
    public function service(Request $request,TenantContext $context){$data=$request->validate(['code'=>['required','max:50',Rule::unique('local_shipping_services')->where('tenant_id',$context->id())],'name'=>'required|max:160','description'=>'nullable|max:1000','sla_text'=>'nullable|max:160','pricing_strategy'=>['required',Rule::in(LocalShippingService::PRICING_STRATEGIES)],'sort_order'=>'nullable|integer|min:0','active'=>'nullable|boolean','published'=>'nullable|boolean']);$zone=LocalShippingZone::firstOrCreate(['tenant_id'=>$context->id(),'code'=>'postal-pool'],['name'=>'Cobertura por CP','coverage_mode'=>'POSTAL_POOL','status'=>'active']);LocalShippingService::create($data+['tenant_id'=>$context->id(),'origin_zone_id'=>$zone->id,'destination_zone_id'=>$zone->id,'service_level'=>'scheduled','base_cost'=>'0.00','base_price'=>'0.00','currency'=>'MXN','status'=>$request->boolean('active')?'active':'inactive','published'=>$request->boolean('published')]);return back()->with('success','Servicio guardado.');}
    public function updateService(Request $request,string $service,TenantContext $context){$item=$this->serviceFor($service,$context);$data=$request->validate(['name'=>'required|max:160','description'=>'nullable|max:1000','sla_text'=>'nullable|max:160','pricing_strategy'=>['required',Rule::in(LocalShippingService::PRICING_STRATEGIES)],'sort_order'=>'nullable|integer|min:0']);$item->update($data+['status'=>$request->boolean('active')?'active':'inactive','published'=>$request->boolean('published')]);return back()->with('success','Servicio actualizado.');}
    public function coverage(Request $request,TenantContext $context,LocalCoverageService $coverage){$data=$request->validate(['postal_codes'=>'required']);$zone=LocalShippingZone::firstOrCreate(['tenant_id'=>$context->id(),'code'=>'postal-pool'],['name'=>'Cobertura por CP','coverage_mode'=>'POSTAL_POOL','status'=>'active']);foreach((array)$data['postal_codes'] as $cp)$coverage->assignForTenant($context->id(),$zone,(string)$cp);return back()->with('success','Cobertura actualizada.');}
    public function toggleCoverage(string $coverage,TenantContext $context){$item=LocalShippingZonePostalCode::where('tenant_id',$context->id())->findOrFail($coverage);$item->update(['active'=>!$item->active]);return back();}
    public function removeCoverage(string $coverage,TenantContext $context){LocalShippingZonePostalCode::where('tenant_id',$context->id())->findOrFail($coverage)->delete();return back();}
    public function import(Request $request,TenantContext $context,LocalCoverageService $coverage){$request->validate(['csv'=>'required|file|mimes:csv,txt|max:5120']);$zone=LocalShippingZone::firstOrCreate(['tenant_id'=>$context->id(),'code'=>'postal-pool'],['name'=>'Cobertura por CP','coverage_mode'=>'POSTAL_POOL','status'=>'active']);$handle=fopen($request->file('csv')->getRealPath(),'rb');$header=array_map(fn($v)=>mb_strtolower(trim($v)),fgetcsv($handle)?:[]);while(($row=fgetcsv($handle))!==false){$line=array_combine($header,array_pad($row,count($header),null));$cp=trim((string)($line['cp']??$line['codigo postal']??''));if(preg_match('/^\d{5}$/',$cp))$coverage->assignForTenant($context->id(),$zone,$cp,['notes'=>$line['notas']??null]);}fclose($handle);return back()->with('success','CSV importado.');}
    public function package(Request $request,TenantContext $context){$data=$request->validate(['package_type'=>'required|in:sobre,caja','max_weight_kg'=>'required|numeric|gt:0','max_dimension_1_cm'=>'nullable|numeric|gt:0','max_dimension_2_cm'=>'nullable|numeric|gt:0','max_dimension_3_cm'=>'nullable|numeric|gt:0']);LocalShippingPackageRule::updateOrCreate(['tenant_id'=>$context->id(),'service_id'=>null,'package_type'=>$data['package_type']],$data+['active'=>true]);return back()->with('success','Límites actualizados.');}
    public function pricing(Request $request,string $service,TenantContext $context){$item=$this->serviceFor($service,$context);$data=$request->validate(['package_type'=>'nullable|in:sobre,caja','from_km'=>'nullable|numeric|min:0','to_km'=>'nullable|numeric|gte:from_km','amount'=>'required|numeric|min:0','included_distance_km'=>'nullable|numeric|min:0','overage_price_per_km'=>'nullable|numeric|min:0','overage_rounding'=>'nullable|in:PROPORTIONAL,CEIL','valid_from'=>'nullable|date','valid_to'=>'nullable|date|after_or_equal:valid_from']);LocalShippingPricingRule::create($data+['tenant_id'=>$context->id(),'service_id'=>$item->id,'active'=>true]);return back()->with('success','Tarifa agregada.');}
    private function serviceFor(string $id,TenantContext $context){return LocalShippingService::where('tenant_id',$context->id())->findOrFail($id);}
}
