<?php
namespace App\Http\Controllers\Tenant;
use App\Domain\Network\Tenancy\{TenantAccessService,TenantContext}; use App\Domain\Payments\Contracts\PaymentProvider; use App\Domain\Payments\Models\TenantPaymentConnection; use App\Http\Controllers\Controller; use Illuminate\Http\Request; use Illuminate\Support\Facades\Cache; use Illuminate\Support\Str;
final class TenantPaymentConnectionController extends Controller{
 public function index(TenantContext $c,TenantAccessService $a){return view('tenant.admin.payments',['tenant'=>$c->tenant()->load('branding'),'connection'=>TenantPaymentConnection::where('tenant_id',$c->id())->where('provider','MERCADO_PAGO')->first(),'canManage'=>$a->canManageTenant(auth()->user()),'environment'=>config('zigo_payments.providers.mercado_pago.environment')]);}
 public function connect(Request $r,TenantContext $c,TenantAccessService $a,PaymentProvider $p){abort_unless($a->canManageTenant($r->user()),403);abort_unless(config('zigo_payments.providers.mercado_pago.enabled'),503);$state=Str::random(64);$verifier=Str::random(96);Cache::put('zigo_mp_oauth:'.hash('sha256',$state),['verifier'=>$verifier,'tenant_id'=>$c->id(),'user_id'=>$r->user()->id,'return_url'=>$r->getSchemeAndHttpHost().'/admin/configuracion/pagos'],now()->addMinutes(10));$challenge=rtrim(strtr(base64_encode(hash('sha256',$verifier,true)),'+/','-_'),'=');return redirect()->away($p->authorizationUrl($state,$challenge));}
 public function callback(Request $r,PaymentProvider $p){$state=(string)$r->query('state');$s=Cache::pull('zigo_mp_oauth:'.hash('sha256',$state));abort_unless(is_array($s)&&filled($r->query('code')),403);$membership=\App\Domain\Network\Tenancy\Models\TenantMembership::where('tenant_id',$s['tenant_id'])->where('user_id',$s['user_id'])->where('status','active')->whereIn('role',['owner','admin'])->firstOrFail();$payload=$p->exchangeAuthorizationCode((string)$r->query('code'),$s['verifier']);$connection=TenantPaymentConnection::firstOrCreate(['tenant_id'=>$membership->tenant_id,'provider'=>'MERCADO_PAGO'],['status'=>'PENDING']);$p->storeConnectionTokens($connection,$payload);return redirect($s['return_url'])->with('success','Mercado Pago quedó conectado.');}
 public function disconnect(Request $r,TenantContext $c,TenantAccessService $a){abort_unless($a->canManageTenant($r->user()),403);TenantPaymentConnection::where('tenant_id',$c->id())->where('provider','MERCADO_PAGO')->update(['status'=>'DISCONNECTED','access_token'=>null,'refresh_token'=>null,'token_expires_at'=>null,'disconnected_at'=>now()]);return back()->with('success','Mercado Pago fue desconectado.');}
}
