@extends('network.layout')
@section('title','Mapa - ZIGO Network')
@section('content')
<header class="hero"><div><div class="eyebrow">ARQUITECTURA VIVA</div><div class="title">Network Topology</div><div class="subtitle">Cómo se conecta hoy el ecosistema y hacia dónde evoluciona.</div></div><div class="legend"><span class="edge">CURRENT</span><span class="edge future">FUTURE</span><span class="edge experimental">EXPERIMENTAL</span></div></header>
<section id="topology-canvas" class="card topology-canvas"><svg id="topology-svg" class="topology-svg" aria-hidden="true"></svg><div class="topology-zones"><section class="topology-zone core-zone"><button data-node="NETWORK_CORE" data-node-code="NETWORK_CORE" class="core-node topology-node"><i class="fa fa-network-wired"></i><b>ZIGO NETWORK CORE</b><small>Centro de control</small></button></section>@foreach($groups as $group=>$groupNodes)<section class="topology-zone"><h2>{{ str_replace('_',' ',$group) }}</h2>@foreach($groupNodes as $node)@if($node['code'] !== 'NETWORK_CORE')<button data-node="{{ $node['code'] }}" data-node-code="{{ $node['code'] }}" class="topology-node"><i class="fa {{ $node['icon'] }}"></i><span>{{ $node['short_label'] }}</span><x-network.status-badge :status="$node['implementation_status']" /></button>@endif @endforeach</section>@endforeach</div></section>
<script type="application/json" id="topology-edges">{!! json_encode($connections, JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) !!}</script>
<x-network.node-detail :nodes="$nodes" />
@endsection
@push('scripts')<script>(()=>{const canvas=document.getElementById('topology-canvas'),svg=document.getElementById('topology-svg'),edges=JSON.parse(document.getElementById('topology-edges').textContent);function draw(){const box=canvas.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);svg.innerHTML='';edges.forEach((edge,index)=>{const a=canvas.querySelector(`[data-node-code="${edge.from}"]`),b=canvas.querySelector(`[data-node-code="${edge.to}"]`);if(!a||!b)return;const ar=a.getBoundingClientRect(),br=b.getBoundingClientRect(),line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',ar.left-box.left+ar.width/2);line.setAttribute('y1',ar.top-box.top+ar.height/2);line.setAttribute('x2',br.left-box.left+br.width/2);line.setAttribute('y2',br.top-box.top+br.height/2);line.setAttribute('class',`topology-line ${edge.status}`);line.dataset.edge=index;svg.appendChild(line)})}function focus(code){canvas.classList.add('focused');canvas.querySelectorAll('[data-node-code]').forEach(n=>n.classList.remove('related','selected'));const related=new Set([code]);edges.forEach((e,i)=>{if(e.from===code||e.to===code){related.add(e.from);related.add(e.to);svg.querySelector(`[data-edge="${i}"]`)?.classList.add('related')}});related.forEach(c=>canvas.querySelector(`[data-node-code="${c}"]`)?.classList.add('related'));canvas.querySelector(`[data-node-code="${code}"]`)?.classList.add('selected')}canvas.addEventListener('mouseover',e=>{const n=e.target.closest('[data-node-code]');if(n)focus(n.dataset.nodeCode)});canvas.addEventListener('mouseleave',()=>{canvas.classList.remove('focused');canvas.querySelectorAll('.related,.selected').forEach(n=>n.classList.remove('related','selected'));svg.querySelectorAll('.related').forEach(n=>n.classList.remove('related'))});window.addEventListener('resize',draw);requestAnimationFrame(draw)})();</script>@endpush
