@extends('layouts.zigo-platform')
@section('title','ZIGO Platform | Tu plataforma de envíos')
@section('content')
<div class="shell">
<section class="hero"><div class="hero-copy"><div class="eyebrow">Tu negocio · Tu marca · Tu operación</div><h1>Opera tu propia plataforma de envíos con <strong>ZIGO</strong></h1><p class="lead">Centraliza ventas, clientes y operación logística en una plataforma con tu identidad, respaldada por la tecnología de ZIGO.</p><div class="actions"><a class="btn btn-primary" href="{{ route('zigo-platform.start') }}">Comenzar</a><a class="btn btn-secondary" href="#planes">Ver planes</a></div></div>
<div class="platform-preview" role="img" aria-label="Vista previa del panel operativo ZIGO Platform"><div class="product-browser"><div class="product-browser__bar"><i></i><i></i><i></i></div><div class="product-browser__body"><aside class="product-nav"><span class="product-nav__brand">TU MARCA</span><span class="active">Inicio</span><span>Operaciones</span><span>Clientes</span><span>Tracking</span><span>Servicios</span></aside><div class="product-main"><div class="product-top"><strong>Resumen operativo</strong><span class="product-user"></span></div><div class="product-kpis"><div class="product-kpi"><small>Envíos activos</small><strong>28</strong></div><div class="product-kpi"><small>Entregados</small><strong>146</strong></div><div class="product-kpi"><small>Por recolectar</small><strong>7</strong></div></div><div class="product-table"><div class="product-table__head"><span>Últimos envíos</span><span>Ver todos</span></div><div class="product-row"><b>ZGO-01842</b><span class="product-route">Centro → Polanco</span><span class="product-status">En tránsito</span></div><div class="product-row"><b>ZGO-01841</b><span class="product-route">Roma → Del Valle</span><span class="product-status">Recolectado</span></div><div class="product-row"><b>ZGO-01840</b><span class="product-route">Condesa → Centro</span><span class="product-status">Entregado</span></div></div><div class="product-activity"><div><strong>Actividad de hoy</strong></div><div><strong>Operación lista</strong></div></div></div></div></div></div></section>
<div class="quick-benefits"><div class="quick-benefit"><strong>Marca propia</strong><span>Una experiencia con tu identidad.</span></div><div class="quick-benefit"><strong>Operación centralizada</strong><span>Clientes y envíos en un solo lugar.</span></div><div class="quick-benefit"><strong>Última milla</strong><span>Recolecciones y entregas coordinadas.</span></div><div class="quick-benefit"><strong>Integraciones</strong><span>Conecta tus sistemas con API Hub.</span></div></div>
</div>
<section class="section"><div class="section-inner"><div class="section-heading"><div class="eyebrow">Una plataforma para crecer</div><h2>Tu marca al frente. ZIGO trabajando debajo.</h2><p>Activa una operación profesional sin construir cada pieza desde cero.</p></div><div class="value-grid"><article class="value-card"><span class="value-icon">01</span><h3>Una experiencia propia</h3><p>Presenta tu identidad en el portal donde tus clientes cotizan, compran y consultan sus envíos.</p></article><article class="value-card"><span class="value-icon">02</span><h3>Control operativo</h3><p>Reúne clientes, actividad y envíos en una consola preparada para tu empresa.</p></article><article class="value-card"><span class="value-icon">03</span><h3>Capacidad para escalar</h3><p>Incorpora última milla, conductores e integraciones cuando tu solución los incluya.</p></article></div></div></section>
<section class="section section-soft" id="capacidades"><div class="section-inner"><div class="section-heading"><div class="eyebrow">Capacidades</div><h2>Una operación conectada de principio a fin</h2><p>Herramientas claras para vender, administrar y dar visibilidad a cada envío.</p></div><div class="capability-grid">
@foreach([
['P','Portal y clientes','Tu portal, con tu marca','Ofrece una experiencia de envíos con tu identidad.'],
['C','Cotización y envíos','Cotiza y vende envíos','Compara servicios y administra cada operación desde un solo lugar.'],
['G','CRM','Gestiona a tus clientes','Centraliza cuentas, actividad y atención.'],
['O','Operación','Controla cada envío','Supervisa el ciclo operativo desde la solicitud hasta la entrega.'],
['T','Tracking','Seguimiento para tus clientes','Da visibilidad del avance de cada envío.'],
['U','Última milla','Opera tu última milla','Coordina recolecciones, asignaciones y entregas.'],
['D','ZIGO Driver','App para conductores','Conecta a tus motoristas con la operación cuando forma parte de tu solución.'],
['A','API Hub','Conecta tu negocio','Integra ERP, eCommerce, TMS u otros sistemas mediante API Hub.']
] as $capability)
<article class="capability"><span class="capability-icon">{{ $capability[0] }}</span><small class="muted">{{ $capability[1] }}</small><strong>{{ $capability[2] }}</strong><span class="muted">{{ $capability[3] }}</span></article>
@endforeach
</div></div></section>
<section class="section section-dark" id="como-funciona"><div class="section-inner"><div class="section-heading"><div class="eyebrow" style="color:#8fb0ff">Cómo funciona</div><h2>De la elección al lanzamiento</h2><p>Un recorrido directo para configurar y poner en marcha tu operación.</p></div><div class="journey">@foreach(['Elige tu solución'=>'Selecciona una oferta real del catálogo.','Configura tu operación'=>'Define los datos de tu empresa y plataforma.','Conecta e integra'=>'Habilita las capacidades incluidas.','Lanza tu plataforma'=>'Activa tu tenant y comienza a operar.','Escala tu negocio'=>'Amplía capacidades conforme creces.'] as $step=>$copy)<article class="journey-step"><strong>{{ $step }}</strong><p>{{ $copy }}</p></article>@endforeach</div></div></section>
<section class="section" id="planes"><div class="section-inner"><div class="section-heading"><div class="eyebrow">Planes reales</div><h2>Elige una base para tu operación</h2><p>Importes y capacidades provenientes del catálogo comercial vigente.</p></div>
@php($landingOffers=$offers->groupBy('plan_id')->map(fn($group)=>$group->firstWhere('billing_type','MONTHLY') ?: $group->first())->take(3))
@if($landingOffers->isEmpty())<div class="card empty-state"><h3>Estamos preparando nuestras opciones comerciales</h3><p class="muted">Consulta la página de planes para conocer las opciones disponibles.</p><a class="btn btn-primary" href="{{ route('zigo-platform.pricing') }}">Ver planes</a></div>@else<div class="pricing-grid">@foreach($landingOffers as $offer)<article class="card pricing-card"><div class="eyebrow">{{ $offer->billing_type==='ANNUAL'?'Anual':'Mensual' }}</div><h3>{{ $offer->name }}</h3><p class="muted">{{ $offer->description }}</p><div class="price">${{ number_format((float)$offer->price,2) }} {{ $offer->currency }}</div>@if($offer->plan?->included_operations)<p><strong>{{ $offer->metadata['allowance_label'] ?? (number_format($offer->plan->included_operations).' operaciones incluidas por periodo') }}</strong></p>@endif @if($offer->plan?->modules?->isNotEmpty())<ul class="feature-list">@foreach(array_slice(\App\Support\Network\ModulePresentation::labels($offer->plan->modules->where('pivot.is_included',true)),0,5) as $label)<li>{{ $label }}</li>@endforeach</ul>@endif<a class="btn btn-primary" href="{{ route('zigo-platform.start',['offer'=>$offer->uuid]) }}">Comenzar</a></article>@endforeach</div><div class="actions" style="justify-content:center"><a class="btn btn-secondary" href="{{ route('zigo-platform.pricing') }}">Comparar todos los planes</a></div>@endif
</div></section>
<section class="section section-soft"><div class="section-inner"><div class="cta-band"><div><div class="eyebrow" style="color:#a9c2ff">ZIGO Platform</div><h2>Pon tu operación en marcha</h2><p class="muted">Elige una solución y comienza a construir tu plataforma.</p></div><div class="actions"><a class="btn btn-secondary" href="{{ route('zigo-platform.pricing') }}">Ver planes</a><a class="btn btn-primary" href="{{ route('zigo-platform.start') }}">Comenzar</a></div></div></div></section>
@endsection
