@extends('layouts.zigo-platform')
@section('title', 'ZIGO Platform | Tu plataforma de envíos')
@section('content')
<div class="shell">
<section class="hero"><div class="hero-copy"><div class="eyebrow">Tu negocio · Tu marca · Tu operación</div><h1>Opera tu propia plataforma de envíos con <strong>ZIGO</strong></h1><p class="lead">Ofrece una experiencia logística con tu identidad y reúne clientes, cotizaciones, envíos y seguimiento sobre tecnología ZIGO.</p><div class="actions"><a class="btn btn-primary" href="{{ route('zigo-platform.start') }}">Crear mi plataforma</a><a class="btn btn-secondary" href="#planes">Conocer planes</a></div><p class="muted" style="margin-top:16px">Configura capacidades reales conforme a tu operación.</p></div>
<div class="platform-preview" role="img" aria-label="Representación de un dashboard logístico bajo la marca de una empresa"><div class="preview-window"><aside class="preview-side"><span class="preview-logo"></span>@for($i=0;$i<6;$i++)<span class="preview-link @if($i===0) is-active @endif"></span>@endfor</aside><div class="preview-content"><div class="preview-head"><span class="preview-title"></span><span class="preview-avatar"></span></div><div class="preview-metrics"><span class="preview-metric"></span><span class="preview-metric"></span><span class="preview-metric"></span></div><div class="preview-quote"><span class="preview-field"></span><span class="preview-field"></span><span class="preview-field"></span><span class="preview-field"></span></div><span class="preview-table"></span></div></div></div></section>
<div class="trust-strip"><div class="trust-item"><strong>Tenant aislado</strong><span>Operación separada por empresa.</span></div><div class="trust-item"><strong>Branding propio</strong><span>Nombre, colores e identidad.</span></div><div class="trust-item"><strong>Customer App</strong><span>Portal para tus clientes.</span></div><div class="trust-item"><strong>Administración</strong><span>Control operativo centralizado.</span></div></div>
</div>
<section class="section"><div class="section-inner"><div class="section-heading"><div class="eyebrow">Una plataforma para tu operación</div><h2>Tu marca al frente. ZIGO trabajando debajo.</h2><p>Construye una experiencia propia sin empezar desde cero y habilita sólo las capacidades que tu operación necesita.</p></div><div class="value-grid"><article class="value-card"><span class="value-icon">01</span><h3>Vende bajo tu identidad</h3><p>Presenta un portal con branding propio para que tus clientes coticen, ingresen y consulten sus envíos.</p></article><article class="value-card"><span class="value-icon">02</span><h3>Coordina la operación</h3><p>Administra clientes, envíos y capacidades contratadas desde una superficie separada para tu empresa.</p></article><article class="value-card"><span class="value-icon">03</span><h3>Conecta lo que sigue</h3><p>Amplía con operación local, ZIGO Driver, soporte o integraciones cuando formen parte de tu solución.</p></article></div></div></section>
<section class="section section-soft" id="capacidades"><div class="section-inner"><div class="section-heading"><div class="eyebrow">Capacidades</div><h2>Todo lo necesario para poner tu plataforma en movimiento</h2><p>Capacidades comerciales respaldadas por las superficies actuales de ZIGO Platform.</p></div><div class="capability-grid">@foreach(['Portal y clientes'=>'Landing, registro, acceso y Customer App bajo tu marca.','Cotización y envíos'=>'Cotización y proceso de creación de envíos.','Tracking'=>'Consulta del avance de cada envío.','CRM'=>'Herramientas de gestión comercial.','Envíos locales'=>'Configuración para una operación de última milla.','ZIGO Driver'=>'Administración y aplicación de motoristas cuando se contrata.','Soporte'=>'Canales de atención integrados a la plataforma.','API Hub e integraciones'=>'Conexión con sistemas externos cuando forma parte del plan.'] as $name=>$copy)<article class="capability"><span class="capability-number">●</span><strong>{{ $name }}</strong><span class="muted">{{ $copy }}</span></article>@endforeach</div></div></section>
<section class="section section-dark" id="como-funciona"><div class="section-inner"><div class="section-heading"><div class="eyebrow" style="color:#8fb0ff">Cómo funciona</div><h2>De la elección al lanzamiento</h2><p>Un recorrido claro para configurar y poner en marcha tu nueva superficie de envíos.</p></div><div class="journey">@foreach(['Elige tu solución'=>'Selecciona una oferta real del catálogo.','Configura tu operación'=>'Define los datos de tu empresa y plataforma.','Conecta e integra'=>'Habilita las capacidades incluidas en tu solución.','Lanza tu plataforma'=>'Activa tu tenant y comienza a operar.','Escala tu negocio'=>'Amplía capacidades conforme crece tu operación.'] as $step=>$copy)<article class="journey-step"><strong>{{ $step }}</strong><p>{{ $copy }}</p></article>@endforeach</div></div></section>
<section class="section" id="planes"><div class="section-inner"><div class="section-heading"><div class="eyebrow">Planes reales</div><h2>Elige una base para tu operación</h2><p>Los importes y capacidades mostrados provienen del catálogo comercial vigente.</p></div>
@php($landingOffers=$offers->groupBy('plan_id')->map(fn($group)=>$group->firstWhere('billing_type','MONTHLY') ?: $group->first())->take(3))
@if($landingOffers->isEmpty())<div class="card empty-state"><h3>Estamos preparando nuestras opciones comerciales</h3><p class="muted">Consulta la página de planes para conocer las opciones disponibles.</p><a class="btn btn-primary" href="{{ route('zigo-platform.pricing') }}">Ver planes</a></div>@else<div class="pricing-grid">@foreach($landingOffers as $offer)<article class="card pricing-card"><div class="eyebrow">{{ $offer->billing_type==='ANNUAL'?'Anual':'Mensual' }}</div><h3>{{ $offer->name }}</h3><p class="muted">{{ $offer->description }}</p><div class="price">${{ number_format((float)$offer->price,2) }} {{ $offer->currency }}</div>@if($offer->plan?->included_operations)<p><strong>{{ $offer->metadata['allowance_label'] ?? (number_format($offer->plan->included_operations).' operaciones incluidas por periodo') }}</strong></p>@endif @if($offer->plan?->modules?->isNotEmpty())<ul class="feature-list">@foreach(array_slice(\App\Support\Network\ModulePresentation::labels($offer->plan->modules->where('pivot.is_included',true)),0,5) as $label)<li>{{ $label }}</li>@endforeach</ul>@endif<a class="btn btn-primary" href="{{ route('zigo-platform.start',['offer'=>$offer->uuid]) }}">Comenzar</a></article>@endforeach</div><div class="actions" style="justify-content:center"><a class="btn btn-secondary" href="{{ route('zigo-platform.pricing') }}">Comparar todos los planes</a></div>@endif
</div></section>
<section class="section"><div class="section-inner"><div class="cta-band"><div><div class="eyebrow" style="color:#a9c2ff">ZIGO Platform</div><h2>Pon tu operación en marcha</h2><p class="muted">Elige una solución, configura tu empresa y comienza a construir tu plataforma.</p></div><div class="actions"><a class="btn btn-secondary" href="{{ route('zigo-platform.pricing') }}">Ver planes</a><a class="btn btn-primary" href="{{ route('zigo-platform.start') }}">Comenzar</a></div></div></div></section>
@endsection
