<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('ai_knowledge_indexes',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained('network_tenants')->restrictOnDelete();$t->unsignedBigInteger('knowledge_source_id');$t->unsignedBigInteger('knowledge_source_version_id');$t->string('status',20)->default('pending');$t->string('schema_version',20);$t->char('content_checksum',64);$t->unsignedInteger('chunk_count')->default(0);$t->foreignId('requested_by_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('requested_at');$t->timestamp('started_at')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamp('failed_at')->nullable();$t->string('safe_error_code',40)->nullable();$t->timestamps();$t->unique(['tenant_id','id'],'ai_knowledge_indexes_tenant_id_uq');$t->unique(['tenant_id','knowledge_source_id','knowledge_source_version_id'],'ai_knowledge_indexes_version_uq');$t->unique(['tenant_id','id','knowledge_source_id','knowledge_source_version_id'],'ai_knowledge_indexes_identity_uq');$t->index(['tenant_id','status'],'ai_knowledge_indexes_status_ix');$t->foreign(['tenant_id','knowledge_source_id'],'ai_knowledge_indexes_source_fk')->references(['tenant_id','id'])->on('ai_knowledge_sources')->restrictOnDelete();$t->foreign(['tenant_id','knowledge_source_id','knowledge_source_version_id'],'ai_knowledge_indexes_version_fk')->references(['tenant_id','knowledge_source_id','id'])->on('ai_knowledge_source_versions')->restrictOnDelete();});
  Schema::create('ai_knowledge_chunks',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained('network_tenants')->restrictOnDelete();$t->unsignedBigInteger('knowledge_index_id');$t->unsignedBigInteger('knowledge_source_id');$t->unsignedBigInteger('knowledge_source_version_id');$t->unsignedInteger('sequence');$t->text('content');$t->json('locator');$t->char('content_checksum',64);$t->unsignedInteger('character_count');$t->timestamps();$t->unique(['tenant_id','knowledge_index_id','sequence'],'ai_knowledge_chunks_sequence_uq');$t->index(['tenant_id','knowledge_source_version_id'],'ai_knowledge_chunks_version_ix');$t->foreign(['tenant_id','knowledge_index_id','knowledge_source_id','knowledge_source_version_id'],'ai_knowledge_chunks_index_fk')->references(['tenant_id','id','knowledge_source_id','knowledge_source_version_id'])->on('ai_knowledge_indexes')->restrictOnDelete();});
 }
 public function down():void{Schema::dropIfExists('ai_knowledge_chunks');Schema::dropIfExists('ai_knowledge_indexes');}
};
