<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('ai_knowledge_sources',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained('network_tenants')->restrictOnDelete();$t->string('name',160);$t->string('type',30);$t->string('status',20)->default('active');$t->foreignId('created_by_user_id')->constrained('users')->restrictOnDelete();$t->timestamp('archived_at')->nullable();$t->unsignedBigInteger('archived_by_user_id')->nullable();$t->timestamps();$t->unique(['tenant_id','id'],'ai_knowledge_sources_tenant_id_uq');$t->index(['tenant_id','status'],'ai_knowledge_sources_tenant_status_ix');$t->foreign('archived_by_user_id','ai_knowledge_sources_archived_by_fk')->references('id')->on('users')->restrictOnDelete();});
  Schema::create('ai_knowledge_source_versions',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique();$t->foreignId('tenant_id')->constrained('network_tenants')->restrictOnDelete();$t->unsignedBigInteger('knowledge_source_id');$t->unsignedInteger('version_number');$t->string('status',20)->default('draft');$t->json('content');$t->char('checksum',64);$t->foreignId('created_by_user_id')->constrained('users')->restrictOnDelete();$t->unsignedBigInteger('approved_by_user_id')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamps();$t->unique(['tenant_id','id'],'ai_knowledge_versions_tenant_id_uq');$t->unique(['tenant_id','knowledge_source_id','id'],'ai_knowledge_versions_source_id_uq');$t->unique(['tenant_id','knowledge_source_id','version_number'],'ai_knowledge_versions_number_uq');$t->index(['tenant_id','status'],'ai_knowledge_versions_tenant_status_ix');$t->foreign(['tenant_id','knowledge_source_id'],'ai_knowledge_versions_source_fk')->references(['tenant_id','id'])->on('ai_knowledge_sources')->restrictOnDelete();$t->foreign('approved_by_user_id','ai_knowledge_versions_approved_by_fk')->references('id')->on('users')->restrictOnDelete();});
  Schema::create('ai_agent_version_knowledge_sources',function(Blueprint$t){$t->id();$t->foreignId('tenant_id')->constrained('network_tenants')->restrictOnDelete();$t->unsignedBigInteger('agent_version_id');$t->unsignedBigInteger('knowledge_source_id');$t->unsignedBigInteger('knowledge_source_version_id');$t->foreignId('attached_by_user_id')->constrained('users')->restrictOnDelete();$t->timestamps();$t->unique(['tenant_id','agent_version_id','knowledge_source_id'],'ai_agent_knowledge_source_uq');$t->index(['tenant_id','agent_version_id'],'ai_agent_knowledge_agent_ix');$t->foreign(['tenant_id','agent_version_id'],'ai_agent_knowledge_agent_version_fk')->references(['tenant_id','id'])->on('ai_agent_versions')->restrictOnDelete();$t->foreign(['tenant_id','knowledge_source_id'],'ai_agent_knowledge_source_fk')->references(['tenant_id','id'])->on('ai_knowledge_sources')->restrictOnDelete();$t->foreign(['tenant_id','knowledge_source_id','knowledge_source_version_id'],'ai_agent_knowledge_version_fk')->references(['tenant_id','knowledge_source_id','id'])->on('ai_knowledge_source_versions')->restrictOnDelete();});
 }
 public function down():void{Schema::dropIfExists('ai_agent_version_knowledge_sources');Schema::dropIfExists('ai_knowledge_source_versions');Schema::dropIfExists('ai_knowledge_sources');}
};
