<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 Schema::create('tenant_api_clients',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique('tap_client_uuid_uq');$t->foreignId('tenant_id');$t->string('name',160);$t->text('description')->nullable();$t->string('environment',16);$t->string('status',16);$t->foreignId('created_by_user_id');$t->timestamp('last_used_at')->nullable();$t->timestamps();$t->foreign('tenant_id','tap_client_tenant_fk')->references('id')->on('network_tenants');$t->foreign('created_by_user_id','tap_client_creator_fk')->references('id')->on('users');$t->index(['tenant_id','status'],'tap_client_tenant_status_ix');});
 Schema::create('tenant_api_keys',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique('tap_key_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('api_client_id');$t->string('key_prefix',24);$t->char('key_hash',64)->unique('tap_key_hash_uq');$t->string('last_four',4);$t->string('name',160);$t->json('scopes');$t->timestamp('expires_at')->nullable();$t->timestamp('last_used_at')->nullable();$t->timestamp('revoked_at')->nullable();$t->timestamps();$t->foreign('tenant_id','tap_key_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_key_client_fk')->references('id')->on('tenant_api_clients');$t->index(['tenant_id','api_client_id'],'tap_key_tenant_client_ix');});
 Schema::create('tenant_api_audit_events',function(Blueprint$t){$t->id();$t->foreignId('tenant_id');$t->foreignId('api_client_id')->nullable();$t->foreignId('api_key_id')->nullable();$t->foreignId('actor_user_id');$t->string('action',48);$t->json('metadata')->nullable();$t->timestamp('created_at')->useCurrent();$t->foreign('tenant_id','tap_audit_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_audit_client_fk')->references('id')->on('tenant_api_clients');$t->foreign('api_key_id','tap_audit_key_fk')->references('id')->on('tenant_api_keys');$t->foreign('actor_user_id','tap_audit_actor_fk')->references('id')->on('users');$t->index(['tenant_id','created_at'],'tap_audit_tenant_date_ix');});
 Schema::create('tenant_api_operation_links',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique('tap_link_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('api_client_id');$t->foreignId('tenant_operation_id');$t->foreignId('local_shipment_id')->nullable();$t->string('external_reference',160)->nullable();$t->json('quote_snapshot');$t->timestamp('expires_at');$t->timestamps();$t->foreign('tenant_id','tap_link_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_link_client_fk')->references('id')->on('tenant_api_clients');$t->foreign('tenant_operation_id','tap_link_operation_fk')->references('id')->on('network_tenant_operations');$t->foreign('local_shipment_id','tap_link_shipment_fk')->references('id')->on('local_shipments');$t->unique(['api_client_id','tenant_operation_id'],'tap_link_client_operation_uq');});
 Schema::create('tenant_api_usage_events',function(Blueprint$t){$t->id();$t->foreignId('tenant_id');$t->foreignId('api_client_id');$t->foreignId('api_key_id');$t->uuid('request_id');$t->string('endpoint_code',60);$t->unsignedInteger('units')->default(1);$t->unsignedSmallInteger('http_status');$t->unsignedInteger('duration_ms');$t->timestamp('occurred_at');$t->timestamp('created_at')->useCurrent();$t->foreign('tenant_id','tap_usage_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_usage_client_fk')->references('id')->on('tenant_api_clients');$t->foreign('api_key_id','tap_usage_key_fk')->references('id')->on('tenant_api_keys');$t->unique(['request_id','endpoint_code'],'tap_usage_request_endpoint_uq');$t->index(['tenant_id','occurred_at'],'tap_usage_tenant_date_ix');});
 Schema::create('tenant_api_quota_policies',function(Blueprint$t){$t->id();$t->foreignId('tenant_id');$t->unsignedInteger('monthly_request_limit');$t->unsignedInteger('rate_limit_per_minute');$t->timestamp('valid_from');$t->timestamp('valid_until')->nullable();$t->foreignId('source_saas_order_id')->nullable();$t->timestamps();$t->foreign('tenant_id','tap_quota_tenant_fk')->references('id')->on('network_tenants');$t->foreign('source_saas_order_id','tap_quota_order_fk')->references('id')->on('tenant_saas_orders');$t->index(['tenant_id','valid_from','valid_until'],'tap_quota_tenant_valid_ix');});
 Schema::create('tenant_api_idempotency_records',function(Blueprint$t){$t->id();$t->foreignId('tenant_id');$t->foreignId('api_client_id');$t->string('endpoint_code',60);$t->string('idempotency_key',160);$t->char('request_fingerprint',64);$t->unsignedSmallInteger('response_status')->nullable();$t->json('response_body')->nullable();$t->timestamp('expires_at');$t->timestamps();$t->foreign('tenant_id','tap_idem_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_idem_client_fk')->references('id')->on('tenant_api_clients');$t->unique(['api_client_id','endpoint_code','idempotency_key'],'tap_idem_client_endpoint_key_uq');});
 Schema::create('tenant_api_webhook_endpoints',function(Blueprint$t){$t->id();$t->uuid('uuid')->unique('tap_hook_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('api_client_id');$t->string('name',160);$t->string('url',2048);$t->json('events');$t->string('status',16);$t->text('secret_encrypted');$t->string('secret_prefix',24);$t->timestamp('last_delivery_at')->nullable();$t->timestamps();$t->foreign('tenant_id','tap_hook_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_hook_client_fk')->references('id')->on('tenant_api_clients');$t->index(['tenant_id','status'],'tap_hook_tenant_status_ix');});
 Schema::create('tenant_api_webhook_deliveries',function(Blueprint$t){$t->id();$t->uuid('event_id');$t->foreignId('tenant_id');$t->foreignId('api_client_id');$t->foreignId('webhook_endpoint_id');$t->string('event_type',80);$t->string('resource_type',40);$t->string('resource_uuid',64);$t->json('payload');$t->unsignedSmallInteger('attempt')->default(0);$t->string('status',16);$t->unsignedSmallInteger('http_status')->nullable();$t->timestamp('next_retry_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->string('last_error_safe',255)->nullable();$t->timestamps();$t->foreign('tenant_id','tap_delivery_tenant_fk')->references('id')->on('network_tenants');$t->foreign('api_client_id','tap_delivery_client_fk')->references('id')->on('tenant_api_clients');$t->foreign('webhook_endpoint_id','tap_delivery_hook_fk')->references('id')->on('tenant_api_webhook_endpoints');$t->unique(['event_id','webhook_endpoint_id'],'tap_delivery_event_hook_uq');$t->index(['status','next_retry_at'],'tap_delivery_retry_ix');});
 }public function down():void{foreach(['tenant_api_webhook_deliveries','tenant_api_webhook_endpoints','tenant_api_idempotency_records','tenant_api_quota_policies','tenant_api_usage_events','tenant_api_operation_links','tenant_api_audit_events','tenant_api_keys','tenant_api_clients']as$table)Schema::dropIfExists($table);}};

