<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\{DB,Schema};
return new class extends Migration{
 public function up():void{
  if(DB::getDriverName()==='sqlite')DB::statement('PRAGMA foreign_keys=ON');
  Schema::create('ai_whatsapp_channels',function(Blueprint$t){$t->id();$t->uuid('uuid');$t->foreignId('tenant_id');$t->unsignedBigInteger('agent_id');$t->string('webhook_key',64)->unique();$t->boolean('enabled')->default(false);$t->string('provider',24)->default('meta_cloud');$t->string('phone_number_id',120);$t->string('business_account_ref',120)->nullable();$t->string('display_phone',40)->nullable();$t->text('access_token_encrypted');$t->text('app_secret_encrypted');$t->text('verify_token_encrypted');$t->foreignId('created_by_user_id');$t->timestamps();$t->unique(['tenant_id','id']);$t->unique(['tenant_id','agent_id']);$t->foreign(['tenant_id','agent_id'])->references(['tenant_id','id'])->on('ai_agents')->restrictOnDelete();$t->foreign('created_by_user_id')->references('id')->on('users')->restrictOnDelete();});
  Schema::create('ai_whatsapp_sessions',function(Blueprint$t){$t->id();$t->uuid('uuid');$t->foreignId('tenant_id');$t->unsignedBigInteger('whatsapp_channel_id');$t->unsignedBigInteger('conversation_id');$t->char('contact_hash',64);$t->text('contact_encrypted');$t->text('profile_name_encrypted')->nullable();$t->timestamp('service_window_ends_at');$t->timestamp('closed_at')->nullable();$t->timestamps();$t->unique(['tenant_id','id']);$t->unique(['whatsapp_channel_id','contact_hash']);$t->unique(['whatsapp_channel_id','conversation_id']);$t->foreign(['tenant_id','whatsapp_channel_id'])->references(['tenant_id','id'])->on('ai_whatsapp_channels')->restrictOnDelete();$t->foreign(['tenant_id','conversation_id'])->references(['tenant_id','id'])->on('ai_conversations')->restrictOnDelete();});
  Schema::create('ai_whatsapp_inbound_receipts',function(Blueprint$t){$t->id();$t->foreignId('tenant_id');$t->unsignedBigInteger('whatsapp_channel_id');$t->string('provider_message_id',191);$t->string('event_type',24);$t->string('status',16);$t->text('payload_encrypted');$t->string('safe_error_code',64)->nullable();$t->timestamps();$t->unique(['whatsapp_channel_id','provider_message_id']);$t->foreign(['tenant_id','whatsapp_channel_id'])->references(['tenant_id','id'])->on('ai_whatsapp_channels')->restrictOnDelete();});
  Schema::create('ai_whatsapp_deliveries',function(Blueprint$t){$t->id();$t->uuid('uuid');$t->foreignId('tenant_id');$t->unsignedBigInteger('whatsapp_session_id');$t->unsignedBigInteger('conversation_message_id')->nullable();$t->unsignedBigInteger('action_run_id')->nullable();$t->string('kind',24);$t->string('status',16);$t->char('idempotency_key',64)->unique();$t->string('provider_message_id',191)->nullable()->unique();$t->char('confirmation_token_hash',64)->nullable()->unique();$t->timestamp('confirmation_expires_at')->nullable();$t->timestamp('confirmed_at')->nullable();$t->string('safe_error_code',64)->nullable();$t->timestamps();$t->foreign(['tenant_id','whatsapp_session_id'])->references(['tenant_id','id'])->on('ai_whatsapp_sessions')->restrictOnDelete();$t->foreign('conversation_message_id')->references('id')->on('ai_conversation_messages')->restrictOnDelete();$t->foreign('action_run_id')->references('id')->on('ai_action_runs')->restrictOnDelete();});
 }
 public function down():void{if(DB::getDriverName()==='sqlite')DB::statement('PRAGMA foreign_keys=ON');Schema::dropIfExists('ai_whatsapp_deliveries');Schema::dropIfExists('ai_whatsapp_inbound_receipts');Schema::dropIfExists('ai_whatsapp_sessions');Schema::dropIfExists('ai_whatsapp_channels');}
};
