<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('tenant_payment_connections',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique('pay_conn_uuid_uq');$t->foreignId('tenant_id');$t->string('provider',40);$t->string('status',24)->default('PENDING');$t->string('provider_account_id',120)->nullable();$t->text('access_token')->nullable();$t->text('refresh_token')->nullable();$t->timestamp('token_expires_at')->nullable();$t->json('scopes')->nullable();$t->timestamp('connected_at')->nullable();$t->timestamp('disconnected_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->foreign('tenant_id','pay_conn_tenant_fk')->references('id')->on('network_tenants');$t->unique(['tenant_id','provider'],'pay_conn_tenant_provider_uq');$t->index(['provider','status'],'pay_conn_provider_status_idx');});
  Schema::create('tenant_payment_attempts',function(Blueprint $t):void{$t->id();$t->uuid('uuid')->unique('pay_attempt_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('customer_profile_id');$t->foreignId('checkout_id');$t->foreignId('payment_connection_id');$t->string('provider',40);$t->string('status',24)->default('CREATED');$t->string('provider_preference_id',160)->nullable();$t->string('provider_payment_id',160)->nullable();$t->string('external_reference',120)->unique('pay_attempt_external_ref_uq');$t->decimal('amount',12,2);$t->char('currency',3);$t->decimal('marketplace_fee_amount',12,2)->default(0);$t->text('init_point')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamp('rejected_at')->nullable();$t->timestamps();$t->foreign('tenant_id','pay_attempt_tenant_fk')->references('id')->on('network_tenants');$t->foreign('customer_profile_id','pay_attempt_profile_fk')->references('id')->on('tenant_customer_profiles');$t->foreign('checkout_id','pay_attempt_checkout_fk')->references('id')->on('tenant_customer_checkouts');$t->foreign('payment_connection_id','pay_attempt_connection_fk')->references('id')->on('tenant_payment_connections');$t->unique(['provider','provider_payment_id'],'pay_attempt_provider_payment_uq');$t->index(['tenant_id','status'],'pay_attempt_tenant_status_idx');$t->index(['checkout_id','created_at'],'pay_attempt_checkout_date_idx');});
  Schema::create('tenant_payment_events',function(Blueprint $t):void{$t->id();$t->string('provider',40);$t->string('event_key',191);$t->foreignId('payment_attempt_id')->nullable();$t->string('event_type',80)->nullable();$t->string('provider_payment_id',160)->nullable();$t->string('status',32)->default('RECEIVED');$t->string('error_code',80)->nullable();$t->timestamp('received_at');$t->timestamp('processed_at')->nullable();$t->timestamps();$t->unique(['provider','event_key'],'pay_event_provider_key_uq');$t->foreign('payment_attempt_id','pay_event_attempt_fk')->references('id')->on('tenant_payment_attempts');});
 }
 public function down():void{Schema::dropIfExists('tenant_payment_events');Schema::dropIfExists('tenant_payment_attempts');Schema::dropIfExists('tenant_payment_connections');}
};
