<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration{
 public function up():void{
  Schema::create('network_commercial_products',function(Blueprint$t):void{$t->id();$t->uuid('uuid')->unique('saas_product_uuid_uq');$t->string('code',80)->unique('saas_product_code_uq');$t->string('name',160);$t->text('description')->nullable();$t->string('type',24);$t->string('billing_type',20);$t->decimal('price',12,2);$t->char('currency',3)->default('MXN');$t->foreignId('module_id')->nullable();$t->foreignId('plan_id')->nullable();$t->unsignedInteger('included_operations')->nullable();$t->boolean('is_active')->default(true);$t->unsignedInteger('sort_order')->default(0);$t->json('metadata')->nullable();$t->timestamps();$t->foreign('module_id','saas_product_module_fk')->references('id')->on('network_modules');$t->foreign('plan_id','saas_product_plan_fk')->references('id')->on('network_plans');$t->index(['is_active','sort_order'],'saas_product_active_sort_idx');});
  Schema::create('tenant_saas_orders',function(Blueprint$t):void{$t->id();$t->uuid('uuid')->unique('saas_order_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('commercial_product_id');$t->foreignId('created_by_user_id');$t->string('purchase_key',100);$t->string('status',24)->default('DRAFT');$t->string('payment_status',24)->default('PENDING');$t->unsignedInteger('quantity')->default(1);$t->decimal('unit_amount',12,2);$t->decimal('subtotal',12,2);$t->decimal('tax_amount',12,2)->default(0);$t->decimal('total_amount',12,2);$t->char('currency',3);$t->json('purchase_snapshot');$t->string('payment_provider',40)->nullable();$t->string('payment_reference',160)->nullable();$t->timestamp('expires_at')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamp('activated_at')->nullable();$t->timestamps();$t->foreign('tenant_id','saas_order_tenant_fk')->references('id')->on('network_tenants');$t->foreign('commercial_product_id','saas_order_product_fk')->references('id')->on('network_commercial_products');$t->foreign('created_by_user_id','saas_order_user_fk')->references('id')->on('users');$t->unique(['tenant_id','purchase_key'],'saas_order_tenant_purchase_uq');$t->unique(['payment_provider','payment_reference'],'saas_order_payment_ref_uq');$t->index(['tenant_id','status'],'saas_order_tenant_status_idx');});
  Schema::create('tenant_operation_allowances',function(Blueprint$t):void{$t->id();$t->uuid('uuid')->unique('saas_allowance_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('subscription_id');$t->foreignId('saas_order_id');$t->unsignedInteger('operations');$t->timestamp('starts_at');$t->timestamp('expires_at');$t->timestamps();$t->foreign('tenant_id','saas_allowance_tenant_fk')->references('id')->on('network_tenants');$t->foreign('subscription_id','saas_allowance_subscription_fk')->references('id')->on('network_subscriptions');$t->foreign('saas_order_id','saas_allowance_order_fk')->references('id')->on('tenant_saas_orders');$t->unique('saas_order_id','saas_allowance_order_uq');$t->index(['tenant_id','expires_at'],'saas_allowance_tenant_exp_idx');});
  Schema::create('platform_payment_attempts',function(Blueprint$t):void{$t->id();$t->uuid('uuid')->unique('platform_attempt_uuid_uq');$t->foreignId('tenant_id');$t->foreignId('saas_order_id');$t->string('provider',40);$t->string('status',24)->default('CREATED');$t->string('provider_preference_id',160)->nullable();$t->string('provider_payment_id',160)->nullable();$t->string('external_reference',120)->unique('platform_attempt_reference_uq');$t->decimal('amount',12,2);$t->char('currency',3);$t->text('init_point')->nullable();$t->timestamp('approved_at')->nullable();$t->timestamp('rejected_at')->nullable();$t->timestamps();$t->foreign('tenant_id','platform_attempt_tenant_fk')->references('id')->on('network_tenants');$t->foreign('saas_order_id','platform_attempt_order_fk')->references('id')->on('tenant_saas_orders');$t->unique(['provider','provider_payment_id'],'platform_attempt_payment_uq');$t->index(['saas_order_id','status'],'platform_attempt_order_status_idx');});
  Schema::create('platform_payment_events',function(Blueprint$t):void{$t->id();$t->string('provider',40);$t->string('event_key',191);$t->foreignId('platform_payment_attempt_id')->nullable();$t->string('provider_payment_id',160)->nullable();$t->string('status',32)->default('RECEIVED');$t->string('error_code',80)->nullable();$t->timestamp('received_at');$t->timestamp('processed_at')->nullable();$t->timestamps();$t->unique(['provider','event_key'],'platform_event_provider_key_uq');$t->foreign('platform_payment_attempt_id','platform_event_attempt_fk')->references('id')->on('platform_payment_attempts');});
 }
 public function down():void{Schema::dropIfExists('platform_payment_events');Schema::dropIfExists('platform_payment_attempts');Schema::dropIfExists('tenant_operation_allowances');Schema::dropIfExists('tenant_saas_orders');Schema::dropIfExists('network_commercial_products');}
};
