@extends('tenant.layout')
@section('title','Cotizar · '.($tenant->branding?->brand_name ?: $tenant->name))
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">NUEVO ENVÍO</div><h1>Cotiza tu envío</h1><p class="z-muted">Conoce los servicios disponibles y su precio antes de continuar.</p></div></header>
<span class="z-sr-only">CP origen</span>
@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $customerPortal ?? false ? route('tenant.customer.app.quote.store') : route('tenant.b2c.quote.store') }}" class="z-card z-stack">@csrf
<section class="z-form-section"><div class="z-form-section__head"><h2>Ruta</h2><p class="z-help">La cobertura se valida por código postal.</p></div><div class="z-form-grid">@foreach(['origin'=>['origen','cp_origen'],'destination'=>['destino','cp_destino']] as $side=>$route)<div class="z-stack"><label class="z-field">Código postal de {{ $route[0] }}<input name="{{ $route[1] }}" data-postal="{{ $side }}" inputmode="numeric" value="{{ old($route[1]) }}" maxlength="5" required></label><label class="z-field">Colonia<select name="{{ $side }}_settlement" data-settlement="{{ $side }}" disabled><option>Captura primero el CP</option></select></label><label class="z-field">Calle y número<input name="{{ $side }}_address" value="{{ old($side.'_address') }}" required></label><small data-location="{{ $side }}" class="z-muted"></small></div>@endforeach</div></section>
<section class="z-form-section"><div class="z-form-section__head"><h2>Paquete</h2></div><div class="z-form-grid"><label class="z-field">Tipo<select name="tipo_envio" data-package-type><option value="sobre" @selected(old('tipo_envio','sobre')==='sobre')>Sobre</option><option value="caja" @selected(old('tipo_envio')==='caja')>Caja</option></select></label><label class="z-field">Peso (kg)<input type="number" step="0.01" min="0.1" max="70" name="peso" value="{{ old('peso',1) }}" required></label></div><div class="z-form-grid z-form-grid--3" data-dimensions><label class="z-field">Largo (cm)<input type="number" min="1" name="length" value="{{ old('length') }}"></label><label class="z-field">Ancho (cm)<input type="number" min="1" name="width" value="{{ old('width') }}"></label><label class="z-field">Alto (cm)<input type="number" min="1" name="height" value="{{ old('height') }}"></label></div></section>
<div class="z-form-actions"><button class="z-btn" type="submit">Cotizar envío</button></div></form>
@if($result)<section class="customer-section"><div class="z-eyebrow">RESULTADOS</div><h2>Elige cómo enviar</h2><div class="z-stack">@forelse($result['options'] as $index=>$option)<article class="z-card shipment-card"><div class="shipment-card__top"><div><strong>{{ $option['service'] }}</strong><div class="z-muted">{{ $option['sla'] ?? '' }}</div>@if($option['distance_meters'] ?? null)<small class="z-muted">Distancia estimada de ruta: {{ number_format($option['distance_meters']/1000,1) }} km</small>@endif</div><strong style="font-size:1.35rem;color:var(--z-primary)">${{ number_format((float)$option['price'],2) }} {{ $option['currency'] }}</strong></div><form method="POST" action="{{ $customerPortal ?? false ? route('tenant.customer.app.quote.select') : route('tenant.b2c.quote.select') }}">@csrf<input type="hidden" name="operation_uuid" value="{{ $result['operation']->uuid }}"><input type="hidden" name="option" value="{{ $index }}"><button class="z-btn z-btn--block">Elegir este servicio</button></form></article>@empty<div class="z-empty"><div class="z-empty__icon">⌕</div><h3>No hay tarifas disponibles</h3><p>Revisa los datos o intenta más tarde.</p></div>@endforelse</div></section>@endif
@endsection
@push('scripts')<script>(()=>{const type=document.querySelector('[data-package-type]'),dims=document.querySelector('[data-dimensions]');const sync=()=>{const box=type?.value==='caja';dims.hidden=!box;dims.querySelectorAll('input').forEach(i=>i.required=box)};type?.addEventListener('change',sync);sync();document.querySelectorAll('[data-postal]').forEach(input=>input.addEventListener('change',async()=>{const side=input.dataset.postal,select=document.querySelector(`[data-settlement="${side}"]`);select.disabled=true;try{const r=await fetch(`/codigos-postales/${input.value}`,{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok)throw new Error(d.message);select.innerHTML='<option value="">Selecciona una colonia</option>'+d.colonias.map(c=>`<option>${c.nombre}</option>`).join('');select.disabled=false;select.required=true;document.querySelector(`[data-location="${side}"]`).textContent=`${d.municipio}, ${d.estado}`}catch(e){select.innerHTML='<option>Catálogo temporalmente no disponible</option>'}}))})()</script>@endpush
