@extends('tenant.layout')
@section('title','Cotizar · '.($tenant->branding?->brand_name ?: $tenant->name))
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">NUEVO ENVÍO</div><h1>Cotiza tu envío</h1><p class="z-muted">Conoce los servicios disponibles y su precio antes de continuar.</p></div></header>
<span class="z-sr-only">CP origen</span>
@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<form method="POST" action="{{ $customerPortal ?? false ? route('tenant.customer.app.quote.store') : route('tenant.b2c.quote.store') }}" class="z-card z-stack">@csrf
<section class="z-form-section"><div class="z-form-section__head"><h2>Ruta</h2><p class="z-help">Usamos los códigos postales para validar cobertura.</p></div><div class="z-form-grid"><label class="z-field">Código postal de origen<input name="cp_origen" inputmode="numeric" value="{{ old('cp_origen') }}" maxlength="5" required>@error('cp_origen')<span class="z-field-error">{{ $message }}</span>@enderror</label><label class="z-field">Código postal de destino<input name="cp_destino" inputmode="numeric" value="{{ old('cp_destino') }}" maxlength="5" required>@error('cp_destino')<span class="z-field-error">{{ $message }}</span>@enderror</label></div></section>
<section class="z-form-section"><div class="z-form-section__head"><h2>Paquete</h2></div><div class="z-form-grid"><label class="z-field">Tipo<select name="tipo_envio" data-package-type><option value="sobre" @selected(old('tipo_envio','sobre')==='sobre')>Sobre</option><option value="caja" @selected(old('tipo_envio')==='caja')>Caja</option></select></label><label class="z-field">Peso (kg)<input type="number" step="0.01" min="0.1" max="70" name="peso" value="{{ old('peso',1) }}" required></label></div><div class="z-form-grid z-form-grid--3" data-dimensions><label class="z-field">Largo (cm)<input type="number" min="1" name="length" value="{{ old('length') }}"></label><label class="z-field">Ancho (cm)<input type="number" min="1" name="width" value="{{ old('width') }}"></label><label class="z-field">Alto (cm)<input type="number" min="1" name="height" value="{{ old('height') }}"></label></div></section>
<div class="z-form-actions"><button class="z-btn" type="submit">Cotizar envío</button></div></form>
@if($result)<section class="customer-section"><div class="z-eyebrow">RESULTADOS</div><h2>Elige cómo enviar</h2><div class="z-stack">@forelse($result['options'] as $index=>$option)<article class="z-card shipment-card"><div class="shipment-card__top"><div><strong>{{ $option['service'] }}</strong><div class="z-muted">{{ $option['carrier'] }} @if($option['delivery']) · {{ $option['delivery'] }}@endif</div></div><strong style="font-size:1.35rem;color:var(--z-primary)">${{ number_format($option['price'],2) }} MXN</strong></div><form method="POST" action="{{ $customerPortal ?? false ? route('tenant.customer.app.quote.select') : route('tenant.customer.quote.select') }}">@csrf<input type="hidden" name="operation_uuid" value="{{ $result['operation']->uuid }}"><input type="hidden" name="option" value="{{ $index }}"><button class="z-btn z-btn--block">Elegir este servicio</button></form></article>@empty<div class="z-empty"><div class="z-empty__icon">⌕</div><h3>No hay tarifas disponibles</h3><p>Revisa los datos o intenta más tarde.</p></div>@endforelse</div></section>@endif
@endsection
@push('scripts')<script>(()=>{const type=document.querySelector('[data-package-type]'),dims=document.querySelector('[data-dimensions]');const sync=()=>{const box=type?.value==='caja';dims.hidden=!box;dims.querySelectorAll('input').forEach(i=>i.required=box)};type?.addEventListener('change',sync);sync()})()</script>@endpush
