<?php

return [
    'enabled' => env('ZIGO_ESTAFETA_ENABLED', false),
    'gateway_enabled' => env('ZIGO_ESTAFETA_GATEWAY_ENABLED', false),
    'fallback_legacy' => env('ZIGO_ESTAFETA_FALLBACK_LEGACY', false),
    'environment' => env('ZIGO_ESTAFETA_ENVIRONMENT', 'stage'),
    'base_url' => env('ZIGO_ESTAFETA_BASE_URL'),
    'auth_url' => env('ZIGO_ESTAFETA_AUTH_URL', env('ESTAFETA_TOKENURI')),
    'auth_path' => env('ZIGO_ESTAFETA_AUTH_PATH', 'oauth2/v2.0/token'),
    'client_id' => env('ZIGO_ESTAFETA_CLIENT_ID', env('ESTAFETA_APIKEY')),
    'client_secret' => env('ZIGO_ESTAFETA_CLIENT_SECRET', env('ESTAFETA_SECRET')),
    'scope' => env('ZIGO_ESTAFETA_SCOPE', env('ESTAFETA_SCOPE', 'https://graph.microsoft.com/.default')),
    'quote_url' => env('ZIGO_ESTAFETA_QUOTE_URL'),
    'coverage_url' => env('ZIGO_ESTAFETA_COVERAGE_URL'),
    'shipment_url' => env('ZIGO_ESTAFETA_SHIPMENT_URL'),
    'tracking_url' => env('ZIGO_ESTAFETA_TRACKING_URL'),
    'cancellation_url' => env('ZIGO_ESTAFETA_CANCELLATION_URL'),
    'username' => env('ZIGO_ESTAFETA_USERNAME'),
    'password' => env('ZIGO_ESTAFETA_PASSWORD'),
    'customer_number' => env('ZIGO_ESTAFETA_CUSTOMER_NUMBER'),
    'contract_number' => env('ZIGO_ESTAFETA_CONTRACT_NUMBER'),
    'api_key' => env('ZIGO_ESTAFETA_API_KEY'),
    'timeout' => (int) env('ZIGO_ESTAFETA_TIMEOUT', 20),
    'connect_timeout' => (int) env('ZIGO_ESTAFETA_CONNECT_TIMEOUT', 5),
    'retry_times' => (int) env('ZIGO_ESTAFETA_RETRY_TIMES', 2),
    'retry_sleep_ms' => (int) env('ZIGO_ESTAFETA_RETRY_SLEEP_MS', 250),
    'token_cache_seconds' => (int) env('ZIGO_ESTAFETA_TOKEN_CACHE_SECONDS', 3300),
    'token_expiry_skew_seconds' => (int) env('ZIGO_ESTAFETA_TOKEN_EXPIRY_SKEW_SECONDS', 300),
    'contracts' => [
        'auth' => 'confirmed',
        'coverage' => env('ZIGO_ESTAFETA_COVERAGE_CONTRACT', 'unknown'),
        'quote' => env('ZIGO_ESTAFETA_QUOTE_CONTRACT', 'unknown'),
    ],
    'verify_ssl' => env('ZIGO_ESTAFETA_VERIFY_SSL', true),
    'mock_enabled' => env('ZIGO_ESTAFETA_MOCK_ENABLED', false),
    'log_channel' => env('ZIGO_ESTAFETA_LOG_CHANNEL', 'estafeta'),
    'log_retention_days' => (int) env('ZIGO_ESTAFETA_LOG_RETENTION_DAYS', 30),
    'devops_prd_active_checks' => env('ZIGO_DEVOPS_ESTAFETA_PRD_ACTIVE_CHECKS', false),
];
