<?php

$node = static fn (string $code, string $label, string $group, string $status, string $icon, string $description, array $extra = []): array => array_merge([
    'code' => $code, 'label' => $label, 'short_label' => $label, 'description' => $description,
    'group' => $group, 'subgroup' => null, 'icon' => $icon, 'implementation_status' => $status,
    'commercial_module_code' => null, 'route_name' => null, 'url' => null, 'dependencies' => [],
    'order' => 100, 'is_clickable' => true, 'notes' => null, 'visibility' => 'internal',
    'current_capabilities' => [], 'future_capabilities' => [],
], $extra);

return [
    'version' => 'ZN-03',
    'statuses' => [
        'live' => ['label' => 'LIVE', 'description' => 'Funcional actualmente.'],
        'partial' => ['label' => 'PARTIAL', 'description' => 'Funcionalidad real, aún incompleta para Network.'],
        'experimental' => ['label' => 'EXPERIMENTAL', 'description' => 'Piloto o prueba controlada; no productiva.'],
        'planned' => ['label' => 'PLANNED', 'description' => 'Planeado sin implementación real.'],
        'external' => ['label' => 'EXTERNAL', 'description' => 'Dependencia o plataforma externa.'],
        'disabled' => ['label' => 'DISABLED', 'description' => 'Existe, actualmente deshabilitada.'],
    ],
    'connection_statuses' => ['current', 'future', 'experimental'],
    'commercial_module_codes' => ['B2C','B2B','SHIPPING','TRACKING','CRM','DRIVER','COMMERCE','MARKETING','GPS','WAREHOUSE','API','INVOICING'],
    'nodes' => [
        $node('NETWORK_CORE','ZIGO Network Core','CONTROL','live','fas fa-network-wired','Núcleo de gobierno de ZIGO Network.', ['order'=>1,'current_capabilities'=>['Bounded context Network','Acceso exclusivo sysadmin'],'future_capabilities'=>['Orquestación tenant-aware']]),
        $node('TENANTS','Tenants','CONTROL','live','fas fa-building','Registro central de organizaciones tenant.', ['order'=>2,'route_name'=>'network.tenants.index','current_capabilities'=>['Catálogo de tenants'],'future_capabilities'=>['Dominios y branding']]),
        $node('PLANS','Planes','CONTROL','live','fas fa-layer-group','Catálogo de planes SaaS.', ['order'=>3,'route_name'=>'network.plans.index','current_capabilities'=>['CRUD y relación con módulos'],'future_capabilities'=>['Construye tu ZIGO']]),
        $node('MODULES','Módulos','CONTROL','live','fas fa-th-large','Catálogo comercial de productos.', ['order'=>4,'route_name'=>'network.modules.index','current_capabilities'=>['12 módulos comerciales'],'future_capabilities'=>['Entitlements efectivos']]),
        $node('TENANT_DOMAIN','Tenant Domain','CONTROL','live','fas fa-globe','Registro explícito de hostnames white-label por tenant.', ['current_capabilities'=>['Dominios subdomain/custom','Estados y ambiente','Resolución verified'],'future_capabilities'=>['DNS y SSL automation']]),
        $node('TENANT_BRANDING','Tenant Branding','CONTROL','live','fas fa-palette','Identidad visual configurable por tenant.', ['current_capabilities'=>['Nombre','Colores','Logo','Favicon','Contacto'],'future_capabilities'=>['CDN de assets']]),
        $node('TENANT_CONTEXT','Tenant Context','CONTROL','live','fas fa-crosshairs','Contexto request-scoped resuelto por host.', ['current_capabilities'=>['Resolución segura por dominio explícito'],'future_capabilities'=>['Canales tenant-aware']]),
        $node('WHITE_LABEL','White Label','CHANNELS','partial','fas fa-paint-brush','Shell visual tenant con preview interno.', ['current_capabilities'=>['Preview de branding, plan y módulos'],'future_capabilities'=>['B2C/B2B tenant-aware']]),
        $node('TENANT_MEMBERSHIPS','Tenant Memberships','CONTROL','live','fas fa-user-shield','Relación multi-tenant entre usuarios globales y roles de tenant.', ['current_capabilities'=>['Roles owner/admin/operator/support/billing/viewer','Suspensión de acceso','Aislamiento por tenant'],'future_capabilities'=>['Invitaciones y permisos granulares']]),
        $node('TENANT_ADMIN','Tenant Admin','CHANNELS','partial','fas fa-user-cog','Consola administrativa resuelta por el host de cada tenant.', ['current_capabilities'=>['Login tenant','Dashboard','Mi plan','Gestión de usuarios'],'future_capabilities'=>['Operación tenant-aware','Usage y billing']]),
        $node('B2C','Canal B2C','CHANNELS','partial','fas fa-user','Cotización, compra y autoservicio para consumidor.', ['commercial_module_code'=>'B2C','route_name'=>'b2c.dashboard','current_capabilities'=>['Cotización','Pagos','Guías','Tracking'],'future_capabilities'=>['Tenant-aware y white label']]),
        $node('B2B','Canal B2B','CHANNELS','partial','fas fa-briefcase','Portal operativo para clientes empresa.', ['commercial_module_code'=>'B2B','route_name'=>'negocios.dashboard','current_capabilities'=>['Portal autenticado'],'future_capabilities'=>['B2B V2 multi-tenant']]),
        $node('CRM','CRM','BUSINESS','live','fas fa-address-book','Operación comercial y administrativa.', ['commercial_module_code'=>'CRM','route_name'=>'crm.dashboard','current_capabilities'=>['Clientes','Empresas','Pricing','Operación'],'future_capabilities'=>['Integración tenant y AI']]),
        $node('SUPPORT','Soporte','BUSINESS','live','fas fa-headset','Gestión de incidencias y seguimiento.', ['route_name'=>'soporte.dashboard','portal'=>'support','current_capabilities'=>['Portal soporte','Incidencias'],'future_capabilities'=>['Omnicanal y AI handoff'],'notes'=>'Portal disponible mediante el host Soporte configurado.']),
        $node('INVOICING','Facturación CFDI','BUSINESS','live','fas fa-file-invoice-dollar','Facturación operativa existente; no es Billing SaaS.', ['commercial_module_code'=>'INVOICING','route_name'=>'crm.facturacion.index','current_capabilities'=>['Solicitudes y documentos fiscales'],'future_capabilities'=>['Autoservicio tenant']]),
        $node('SHIPPING','Shipping','LOGISTICS','live','fas fa-shipping-fast','Cotización y creación de guías.', ['commercial_module_code'=>'SHIPPING','route_name'=>'cotizaciones.index','current_capabilities'=>['Cotización','Guías','Tarifas'],'future_capabilities'=>['Orquestación multi-tenant']]),
        $node('TRACKING','Tracking','LOGISTICS','live','fas fa-route','Consulta y seguimiento de envíos.', ['commercial_module_code'=>'TRACKING','route_name'=>'rastreos.index','current_capabilities'=>['Rastreo público y operativo'],'future_capabilities'=>['Eventos normalizados']]),
        $node('XPERTA','Xperta','PROVIDERS','external','fas fa-external-link-alt','Plataforma externa integrada para servicios logísticos.', ['current_capabilities'=>['Cotización y guía mediante servicios Xperta'],'notes'=>'Dependencia externa con integración real.']),
        $node('ESTAFETA','Estafeta','PROVIDERS','partial','fas fa-truck','Integración real con componentes modernos y legacy.', ['current_capabilities'=>['Autenticación','Guías','Rastreo','Tarifas locales'],'future_capabilities'=>['Contratos completos de coverage/quote'],'notes'=>'No se declara completa: auditorías del repositorio señalan contratos pendientes.']),
        $node('ZIGO_LOCAL','ZIGO Local','PROVIDERS','planned','fas fa-map-marker-alt','Proveedor futuro de última milla ZIGO.', ['future_capabilities'=>['Asignación local','Despacho de motoristas']]),
        $node('DRIVER','Motoristas','LAST_MILE','planned','fas fa-motorcycle','Aplicación futura para motoristas.', ['commercial_module_code'=>'DRIVER','future_capabilities'=>['Asignaciones','Estados de entrega']]),
        $node('POD','Proof of Delivery','LAST_MILE','planned','fas fa-clipboard-check','Evidencia futura de entrega.', ['future_capabilities'=>['Firma','Fotografía','Geolocalización']]),
        $node('COMMERCE','Commerce','COMMERCE','planned','fas fa-box-open','Marketplace interno de insumos logísticos.', ['commercial_module_code'=>'COMMERCE','future_capabilities'=>['Cajas','Cinta','Sobres','Etiquetas','Material de embalaje']]),
        $node('MARKETING','Marketing','GROWTH','partial','fas fa-bullhorn','Crecimiento, campañas y captación.', ['commercial_module_code'=>'MARKETING','route_name'=>'landing.empresas','current_capabilities'=>['Landing de prospectos y waitlist'],'future_capabilities'=>['Campañas','Promociones','Redes sociales']]),
        $node('GPS','GPS','VISIBILITY','external','fas fa-satellite-dish','Rastreo mediante plataforma GPS externa o integración futura.', ['commercial_module_code'=>'GPS','future_capabilities'=>['Telemetría de unidades y mercancías'],'notes'=>'Representa dependencia externa; no hay módulo GPS propio.']),
        $node('WAREHOUSE','Warehouse','FULFILLMENT','planned','fas fa-warehouse','Bodegas, inventario y fulfillment.', ['commercial_module_code'=>'WAREHOUSE','future_capabilities'=>['Recepción','Inventario','Preparación','Despacho','Cross docking']]),
        $node('API','API Hub','INTEGRATIONS','live','fas fa-code','Administración de integraciones API.', ['commercial_module_code'=>'API','route_name'=>'crm.api-hub.index','current_capabilities'=>['Clientes API','Llaves','Productos','Webhooks'],'future_capabilities'=>['Entitlements tenant']]),
        $node('DEVOPS','DevOps','PLATFORM','live','fas fa-server','Consola de releases, salud e integraciones.', ['route_name'=>'devops.index','current_capabilities'=>['Deployments','Releases','Health','Alerts'],'future_capabilities'=>['Observabilidad Network']]),
        $node('PLATFORM_ENVIRONMENTS','Platform Environments','PLATFORM','live','fas fa-sitemap','Ambientes internos controlados por INNOTECH/ZIGO DevOps.', ['current_capabilities'=>['Separación de ambientes'],'future_capabilities'=>['Feature flags','Observabilidad consolidada']]),
        $node('DEVELOPMENT','Development','PLATFORM','live','fas fa-code-branch','Ambiente interno de desarrollo.', ['current_capabilities'=>['Desarrollo local y control de código'],'notes'=>'Ambiente interno; no es producto tenant.']),
        $node('STAGE','Stage','PLATFORM','live','fas fa-vial','Validación interna previa a producción.', ['current_capabilities'=>['Releases y pruebas controladas'],'notes'=>'STAGE es interno ZIGO; nunca debe ofrecerse como sandbox de cliente.']),
        $node('PRODUCTION','Production','PLATFORM','live','fas fa-shield-alt','Ambiente productivo de la plataforma ZIGO.', ['current_capabilities'=>['Releases productivas','Rollback y health'],'notes'=>'Debe aislar datos sensibles respecto de Stage.']),
        $node('TENANT_ENVIRONMENTS','Tenant Environments','PLATFORM','planned','fas fa-building','Ambientes comerciales futuros por tenant.', ['future_capabilities'=>['Producción tenant','Sandbox opcional']]),
        $node('TENANT_PRODUCTION','Tenant Production','PLATFORM','planned','fas fa-globe','Ambiente productivo futuro para cada tenant.', ['future_capabilities'=>['Dominio ZIGO o dominio propio']]),
        $node('TENANT_SANDBOX','Tenant Sandbox','PLATFORM','planned','fas fa-flask','Ambiente de pruebas opcional y comercial para tenants.', ['future_capabilities'=>['Datos de prueba aislados'],'notes'=>'No confundir con STAGE interno.']),
        $node('BILLING_SAAS','Billing SaaS','FINANCE','planned','fas fa-credit-card','Suscripciones y cobros recurrentes SaaS; separado de CFDI.', ['future_capabilities'=>['Suscripciones','Límites','Suspensión','Reactivación']]),
        $node('ZIGO_AI','ZIGO AI','AI','planned','fas fa-brain','Automatización conversacional y visión aplicada a operaciones logísticas.', ['future_capabilities'=>['AI Conversational','AI Vision']]),
        $node('AI_CONVERSATIONAL','AI Conversational','AI','planned','fas fa-comments','Capa futura de atención natural, siempre identificada como asistente virtual.', ['subgroup'=>'CONVERSATIONAL','future_capabilities'=>['Cotizar','Tracking','Soporte','Commerce','Transferencia humana']]),
        $node('WHATSAPP','WhatsApp','AI','planned','fab fa-whatsapp','Canal futuro para el asistente virtual.', ['subgroup'=>'CONVERSATIONAL','future_capabilities'=>['Mensajería conversacional']]),
        $node('WEBCHAT','Webchat','AI','planned','fas fa-comment-dots','Canal web futuro para conversación.', ['subgroup'=>'CONVERSATIONAL','future_capabilities'=>['Chat embebible']]),
        $node('BOT_BUILDER','Bot Builder','AI','planned','fas fa-tools','Configuración SaaS futura de asistentes por tenant.', ['subgroup'=>'CONVERSATIONAL','future_capabilities'=>['Nombre y tono','Horarios','Permisos por módulo','Bienvenida']]),
        $node('HUMAN_HANDOFF','Human Handoff','AI','planned','fas fa-people-arrows','Transferencia a operador por baja confianza o falta de resolución.', ['subgroup'=>'CONVERSATIONAL','future_capabilities'=>['Cola humana','Contexto de conversación']]),
        $node('AI_VISION','AI Vision','AI','planned','fas fa-eye','Lectura y validación futura de imágenes y documentos.', ['subgroup'=>'VISION','future_capabilities'=>['OCR','Document AI','Estimación guiada']]),
        $node('ADDRESS_OCR','Address OCR','AI','planned','fas fa-map-marked-alt','Extracción futura de direcciones, CP y contacto.', ['subgroup'=>'VISION','future_capabilities'=>['Dirección','Código postal','Nombre y teléfono']]),
        $node('DOCUMENT_AI','Document AI','AI','planned','fas fa-file-alt','Extracción futura de datos desde documentos.', ['subgroup'=>'VISION','future_capabilities'=>['Clasificación','Extracción','Validación']]),
        $node('DIMENSION_AI','Dimension AI','AI','experimental','fas fa-cube','Estimación futura y guiada de dimensiones con confirmación humana.', ['subgroup'=>'VISION','future_capabilities'=>['Varias tomas','Referencia de escala','AR/depth','Confidence score'],'notes'=>'Una fotografía arbitraria no garantiza medidas exactas.']),
    ],
    'connections' => [
        ['from'=>'TENANTS','to'=>'PLANS','status'=>'current'],['from'=>'PLANS','to'=>'MODULES','status'=>'current'],['from'=>'MODULES','to'=>'NETWORK_CORE','status'=>'current'],
        ['from'=>'TENANTS','to'=>'TENANT_DOMAIN','status'=>'current'],['from'=>'TENANT_DOMAIN','to'=>'TENANT_CONTEXT','status'=>'current'],['from'=>'TENANT_CONTEXT','to'=>'WHITE_LABEL','status'=>'current'],['from'=>'TENANT_BRANDING','to'=>'WHITE_LABEL','status'=>'current'],['from'=>'MODULES','to'=>'WHITE_LABEL','status'=>'current'],
        ['from'=>'TENANTS','to'=>'TENANT_MEMBERSHIPS','status'=>'current'],['from'=>'TENANT_MEMBERSHIPS','to'=>'TENANT_ADMIN','status'=>'current'],['from'=>'TENANT_CONTEXT','to'=>'TENANT_ADMIN','status'=>'current'],
        ['from'=>'NETWORK_CORE','to'=>'B2C','status'=>'current'],['from'=>'NETWORK_CORE','to'=>'B2B','status'=>'current'],['from'=>'NETWORK_CORE','to'=>'CRM','status'=>'current'],['from'=>'NETWORK_CORE','to'=>'API','status'=>'current'],
        ['from'=>'B2C','to'=>'SHIPPING','status'=>'current'],['from'=>'B2B','to'=>'SHIPPING','status'=>'current'],['from'=>'SHIPPING','to'=>'XPERTA','status'=>'current'],['from'=>'SHIPPING','to'=>'ESTAFETA','status'=>'current'],['from'=>'SHIPPING','to'=>'TRACKING','status'=>'current'],
        ['from'=>'NETWORK_CORE','to'=>'SUPPORT','status'=>'current'],['from'=>'NETWORK_CORE','to'=>'INVOICING','status'=>'current'],['from'=>'NETWORK_CORE','to'=>'DEVOPS','status'=>'current'],
        ['from'=>'DEVOPS','to'=>'PLATFORM_ENVIRONMENTS','status'=>'current'],['from'=>'PLATFORM_ENVIRONMENTS','to'=>'DEVELOPMENT','status'=>'current'],['from'=>'PLATFORM_ENVIRONMENTS','to'=>'STAGE','status'=>'current'],['from'=>'PLATFORM_ENVIRONMENTS','to'=>'PRODUCTION','status'=>'current'],
        ['from'=>'TENANTS','to'=>'TENANT_ENVIRONMENTS','status'=>'future'],['from'=>'TENANT_ENVIRONMENTS','to'=>'TENANT_PRODUCTION','status'=>'future'],['from'=>'TENANT_ENVIRONMENTS','to'=>'TENANT_SANDBOX','status'=>'future'],
        ['from'=>'SHIPPING','to'=>'ZIGO_LOCAL','status'=>'future'],['from'=>'ZIGO_LOCAL','to'=>'DRIVER','status'=>'future'],['from'=>'DRIVER','to'=>'POD','status'=>'future'],['from'=>'DRIVER','to'=>'GPS','status'=>'future'],
        ['from'=>'NETWORK_CORE','to'=>'COMMERCE','status'=>'future'],['from'=>'NETWORK_CORE','to'=>'MARKETING','status'=>'future'],['from'=>'NETWORK_CORE','to'=>'WAREHOUSE','status'=>'future'],['from'=>'NETWORK_CORE','to'=>'BILLING_SAAS','status'=>'future'],
        ['from'=>'NETWORK_CORE','to'=>'ZIGO_AI','status'=>'future'],['from'=>'ZIGO_AI','to'=>'AI_CONVERSATIONAL','status'=>'future'],['from'=>'ZIGO_AI','to'=>'AI_VISION','status'=>'future'],
        ['from'=>'WHATSAPP','to'=>'AI_CONVERSATIONAL','status'=>'future'],['from'=>'WEBCHAT','to'=>'AI_CONVERSATIONAL','status'=>'future'],['from'=>'BOT_BUILDER','to'=>'AI_CONVERSATIONAL','status'=>'future'],
        ['from'=>'AI_CONVERSATIONAL','to'=>'HUMAN_HANDOFF','status'=>'future'],['from'=>'AI_CONVERSATIONAL','to'=>'CRM','status'=>'future'],['from'=>'AI_CONVERSATIONAL','to'=>'SHIPPING','status'=>'future'],['from'=>'AI_CONVERSATIONAL','to'=>'TRACKING','status'=>'future'],['from'=>'AI_CONVERSATIONAL','to'=>'SUPPORT','status'=>'future'],['from'=>'AI_CONVERSATIONAL','to'=>'COMMERCE','status'=>'future'],['from'=>'AI_CONVERSATIONAL','to'=>'INVOICING','status'=>'future'],
        ['from'=>'AI_VISION','to'=>'ADDRESS_OCR','status'=>'future'],['from'=>'AI_VISION','to'=>'DOCUMENT_AI','status'=>'future'],['from'=>'AI_VISION','to'=>'DIMENSION_AI','status'=>'experimental'],['from'=>'ADDRESS_OCR','to'=>'SHIPPING','status'=>'future'],['from'=>'DIMENSION_AI','to'=>'SHIPPING','status'=>'experimental'],
    ],
];
