<?php
namespace App\Http\Controllers\Support;
use App\Domain\Network\Channels\B2C\Models\TenantCustomerCheckout; use App\Domain\Network\Tenancy\TenantContext; use App\Domain\Shipping\Local\Models\LocalShipment; use App\Domain\Support\Models\{SupportTicket,SupportTicketAttachment}; use App\Domain\Support\SupportTicketService; use App\Http\Controllers\Controller; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
final class CustomerSupportController extends Controller{
 public function index(Request$r,TenantContext$c){$p=$r->attributes->get('customer_profile');$ready=\Illuminate\Support\Facades\Schema::hasTable('support_tickets');$own=fn()=>SupportTicket::where('tenant_id',$c->id())->where('customer_profile_id',$p->id)->where('requester_user_id',$p->user_id);$tickets=$ready?$own()->latest()->paginate(20):new \Illuminate\Pagination\LengthAwarePaginator([],0,20);return view('support.customer.index',['tenant'=>$c->tenant()->load('branding'),'tickets'=>$tickets,'openCount'=>$ready?$own()->whereNotIn('status',['RESOLVED','CLOSED'])->count():0,'profile'=>$p]);}
 public function create(Request$r,TenantContext$c){$p=$r->attributes->get('customer_profile');return view('support.customer.create',['tenant'=>$c->tenant()->load('branding'),'shipments'=>$this->shipments($c->id(),$p->id)->latest()->limit(20)->get(),'checkouts'=>TenantCustomerCheckout::where('tenant_id',$c->id())->where('customer_profile_id',$p->id)->latest()->limit(20)->get(),'shipmentHint'=>$r->query('envio')]);}
 public function store(Request$r,TenantContext$c,SupportTicketService$s){$p=$r->attributes->get('customer_profile');$d=$r->validate(['category'=>['required',Rule::in(SupportTicket::TENANT_CATEGORIES)],'subject'=>['required','string','max:180'],'description'=>['required','string','max:10000'],'shipment_uuid'=>['nullable','uuid'],'checkout_uuid'=>['nullable','uuid'],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$shipment=!empty($d['shipment_uuid'])?$this->shipments($c->id(),$p->id)->where('local_shipments.uuid',$d['shipment_uuid'])->firstOrFail():null;$checkout=!empty($d['checkout_uuid'])?TenantCustomerCheckout::where('tenant_id',$c->id())->where('customer_profile_id',$p->id)->where('uuid',$d['checkout_uuid'])->firstOrFail():null;$ticket=$s->create($r->user(),['tenant_id'=>$c->id(),'customer_profile_id'=>$p->id,'requester_type'=>'CUSTOMER','scope'=>'TENANT_OPERATIONAL','category'=>$d['category'],'priority'=>'NORMAL','subject'=>$d['subject'],'description'=>$d['description'],'related_shipment_id'=>$shipment?->id,'related_operation_id'=>$shipment?->tenant_operation_id,'related_checkout_id'=>$checkout?->id],$r->file('attachment'));return redirect()->route('tenant.customer.app.support.show',$ticket->uuid)->with('success','Tu solicitud fue creada.');}
 public function show(Request$r,string$ticket,TenantContext$c){$item=$this->ticket($r,$c,$ticket);return view('support.customer.show',['tenant'=>$c->tenant()->load('branding'),'ticket'=>$item->load(['messages'=>fn($q)=>$q->where('visibility','PUBLIC')->with('author'),'attachments'=>fn($q)=>$q->whereNull('message_id')->orWhereHas('message',fn($m)=>$m->where('visibility','PUBLIC'))])]);}
 public function reply(Request$r,string$ticket,TenantContext$c,SupportTicketService$s){$item=$this->ticket($r,$c,$ticket);abort_if(in_array($item->status,['CLOSED'],true),422);$d=$r->validate(['message'=>['required','string','max:10000'],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$s->reply($item,$r->user(),$d['message'],'PUBLIC',$r->file('attachment'));return back()->with('success','Respuesta enviada.');}
 public function attachment(Request$r,string$ticket,SupportTicketAttachment$attachment,TenantContext$c,SupportTicketService$s){$item=$this->ticket($r,$c,$ticket);abort_unless($attachment->ticket_id===$item->id,404);abort_if($attachment->message_id&&$attachment->message()->where('visibility','!=','PUBLIC')->exists(),404);return$s->download($attachment);}
 private function ticket(Request$r,TenantContext$c,string$uuid):SupportTicket{$p=$r->attributes->get('customer_profile');return SupportTicket::where('uuid',$uuid)->where('tenant_id',$c->id())->where('customer_profile_id',$p->id)->where('requester_user_id',$p->user_id)->firstOrFail();}
 private function shipments(int$tenant,int$profile){return LocalShipment::query()->select('local_shipments.*')->join('network_tenant_operations as sop','sop.id','=','local_shipments.tenant_operation_id')->where('local_shipments.tenant_id',$tenant)->where('sop.tenant_id',$tenant)->where('sop.customer_profile_id',$profile);}
}
