<?php
namespace App\Http\Controllers\Support;
use App\Domain\Shipping\LastMile\Models\DriverAssignment; use App\Domain\Support\Models\{SupportTicket,SupportTicketAttachment}; use App\Domain\Support\SupportTicketService; use App\Http\Controllers\Controller; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
final class DriverSupportController extends Controller{
 public function index(Request$r){$p=$r->attributes->get('driver_profile');$tickets=\Illuminate\Support\Facades\Schema::hasTable('support_tickets')?SupportTicket::where('tenant_id',$p->tenant_id)->where('requester_user_id',$r->user()->id)->latest()->paginate(20):new \Illuminate\Pagination\LengthAwarePaginator([],0,20);return view('support.driver.index',['tenant'=>$p->tenant()->with('branding')->firstOrFail(),'profile'=>$p,'tickets'=>$tickets,'assignments'=>DriverAssignment::with('shipment')->where('tenant_id',$p->tenant_id)->where('driver_profile_id',$p->id)->where('status','ACTIVE')->get()]);}
 public function store(Request$r,SupportTicketService$s){$p=$r->attributes->get('driver_profile');$d=$r->validate(['scope'=>['required',Rule::in(SupportTicket::SCOPES)],'category'=>['required','string'],'subject'=>['required','string','max:180'],'description'=>['required','string','max:10000'],'shipment_uuid'=>['nullable','uuid'],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$allowed=$d['scope']==='TENANT_OPERATIONAL'?SupportTicket::TENANT_CATEGORIES:SupportTicket::ZIGO_CATEGORIES;abort_unless(in_array($d['category'],$allowed,true),422);$assignment=null;if(!empty($d['shipment_uuid']))$assignment=DriverAssignment::with('shipment')->where('tenant_id',$p->tenant_id)->where('driver_profile_id',$p->id)->where('status','ACTIVE')->whereHas('shipment',fn($q)=>$q->where('uuid',$d['shipment_uuid']))->firstOrFail();$ticket=$s->create($r->user(),['tenant_id'=>$p->tenant_id,'requester_type'=>'DRIVER','scope'=>$d['scope'],'category'=>$d['category'],'priority'=>'NORMAL','subject'=>$d['subject'],'description'=>$d['description'],'related_shipment_id'=>$assignment?->local_shipment_id,'related_driver_profile_id'=>$p->id],$r->file('attachment'));return redirect()->route($this->route($r,'show'),$ticket->uuid)->with('success','Solicitud creada.');}
 public function show(Request$r,string$ticket){$item=$this->ticket($r,$ticket);$p=$r->attributes->get('driver_profile');return view('support.driver.show',['tenant'=>$p->tenant()->with('branding')->firstOrFail(),'profile'=>$p,'ticket'=>$item->load(['messages'=>fn($q)=>$q->where('visibility','PUBLIC')->with('author'),'attachments'=>fn($q)=>$q->whereNull('message_id')->orWhereHas('message',fn($m)=>$m->where('visibility','PUBLIC'))])]);}
 public function reply(Request$r,string$ticket,SupportTicketService$s){$item=$this->ticket($r,$ticket);$d=$r->validate(['message'=>['required','string','max:10000'],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$s->reply($item,$r->user(),$d['message'],'PUBLIC',$r->file('attachment'));return back()->with('success','Respuesta enviada.');}
 public function attachment(Request$r,string$ticket,SupportTicketAttachment$a,SupportTicketService$s){$item=$this->ticket($r,$ticket);abort_unless($a->ticket_id===$item->id,404);abort_if($a->message_id&&$a->message()->where('visibility','!=','PUBLIC')->exists(),404);return$s->download($a);}
 private function ticket(Request$r,string$uuid){$p=$r->attributes->get('driver_profile');return SupportTicket::where('uuid',$uuid)->where('tenant_id',$p->tenant_id)->where('requester_user_id',$r->user()->id)->where('related_driver_profile_id',$p->id)->firstOrFail();}
 private function route(Request$r,string$suffix):string{return$r->routeIs('driver.*')?'driver.support.'.$suffix:'tenant.driver.support.'.$suffix;}
}
