<?php
namespace App\Http\Controllers\Support;
use App\Domain\Support\Models\{SupportTicket,SupportTicketAttachment}; use App\Domain\Support\SupportTicketService; use App\Http\Controllers\Controller; use App\Models\User; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
final class NetworkSupportController extends Controller{
 public function index(Request$r){$q=SupportTicket::with(['tenant','requester','assignee'])->where('scope','ZIGO_PLATFORM');foreach(['tenant_id','status','priority','category','assigned_user_id']as$f)if($r->filled($f))$q->where($f,$r->input($f));return view('support.network.index',['tickets'=>$q->latest()->paginate(40)->withQueryString()]);}
 public function store(Request$r,SupportTicketService$s){$d=$r->validate(['tenant_id'=>['nullable','exists:network_tenants,id'],'category'=>['required',Rule::in(SupportTicket::ZIGO_CATEGORIES)],'priority'=>['required',Rule::in(SupportTicket::PRIORITIES)],'subject'=>['required','string','max:180'],'description'=>['required','string','max:10000'],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$ticket=$s->create($r->user(),['tenant_id'=>$d['tenant_id']??null,'requester_type'=>'NETWORK','scope'=>'ZIGO_PLATFORM','category'=>$d['category'],'priority'=>$d['priority'],'subject'=>$d['subject'],'description'=>$d['description']],$r->file('attachment'));return redirect()->route('network.support.show',$ticket->uuid)->with('success','Ticket interno creado.');}
 public function show(string$ticket){return view('support.network.show',['ticket'=>$this->ticket($ticket)->load(['tenant','requester','assignee','messages.author','attachments','events.actor']),'staff'=>$this->staff()]);}
 public function reply(Request$r,string$ticket,SupportTicketService$s){$item=$this->ticket($ticket);$d=$r->validate(['message'=>['required','string','max:10000'],'visibility'=>['required',Rule::in(['PUBLIC','INTERNAL'])],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$s->reply($item,$r->user(),$d['message'],$d['visibility'],$r->file('attachment'));return back()->with('success','Respuesta registrada.');}
 public function update(Request$r,string$ticket,SupportTicketService$s){$item=$this->ticket($ticket);$d=$r->validate(['status'=>['nullable',Rule::in(SupportTicket::STATUSES)],'priority'=>['nullable',Rule::in(SupportTicket::PRIORITIES)],'assigned_user_id'=>['nullable','integer']]);if(array_key_exists('assigned_user_id',$d)){$id=$d['assigned_user_id']?:null;if($id&&!$this->staff()->contains('id',$id))abort(422);$s->assign($item,$r->user(),$id);}if(!empty($d['status']))$s->status($item,$r->user(),$d['status']);if(!empty($d['priority']))$s->priority($item,$r->user(),$d['priority']);return back()->with('success','Ticket actualizado.');}
 public function attachment(string$ticket,SupportTicketAttachment$a,SupportTicketService$s){$item=$this->ticket($ticket);abort_unless($a->ticket_id===$item->id,404);return$s->download($a);}
 private function ticket(string$uuid){return SupportTicket::where('uuid',$uuid)->where('scope','ZIGO_PLATFORM')->firstOrFail();}
 private function staff(){return User::whereHas('roles',fn($q)=>$q->where('slug','sysadmin'))->get();}
}
