<?php
namespace App\Http\Controllers\Support;
use App\Domain\Network\Tenancy\Models\TenantMembership; use App\Domain\Network\Tenancy\TenantContext; use App\Domain\Support\Models\{SupportTicket,SupportTicketAttachment}; use App\Domain\Support\SupportTicketService; use App\Http\Controllers\Controller; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
final class TenantSupportController extends Controller{
 public function index(Request$r,TenantContext$c){$q=SupportTicket::with(['requester','assignee'])->where('tenant_id',$c->id())->where('scope','TENANT_OPERATIONAL');foreach(['status','priority','category']as$f)if($r->filled($f))$q->where($f,$r->string($f));return view('support.tenant.index',['tenant'=>$c->tenant()->load('branding'),'tickets'=>$q->latest()->paginate(30)->withQueryString(),'staff'=>$this->staff($c->id())]);}
 public function zigo(Request$r,TenantContext$c){return view('support.tenant.zigo',['tenant'=>$c->tenant()->load('branding'),'tickets'=>SupportTicket::where('tenant_id',$c->id())->where('scope','ZIGO_PLATFORM')->where('requester_type','TENANT_STAFF')->latest()->paginate(20)]);}
 public function storeZigo(Request$r,TenantContext$c,SupportTicketService$s){$d=$r->validate(['category'=>['required',Rule::in(SupportTicket::ZIGO_CATEGORIES)],'subject'=>['required','string','max:180'],'description'=>['required','string','max:10000'],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$ticket=$s->create($r->user(),['tenant_id'=>$c->id(),'requester_type'=>'TENANT_STAFF','scope'=>'ZIGO_PLATFORM','category'=>$d['category'],'priority'=>'NORMAL','subject'=>$d['subject'],'description'=>$d['description']],$r->file('attachment'));return redirect()->route('tenant.admin.support.show',$ticket->uuid)->with('success','Solicitud enviada a ZIGO.');}
 public function show(Request$r,string$ticket,TenantContext$c){$item=$this->ticket($c,$ticket);$internal=$item->scope==='TENANT_OPERATIONAL';return view('support.tenant.show',['tenant'=>$c->tenant()->load('branding'),'ticket'=>$item->load(['relatedShipment','relatedCheckout','relatedDriverProfile','messages'=>fn($q)=>$internal?$q->with('author'):$q->where('visibility','PUBLIC')->with('author'),'attachments'=>fn($q)=>$internal?$q:$q->whereNull('message_id')->orWhereHas('message',fn($m)=>$m->where('visibility','PUBLIC')),'events']),'staff'=>$this->staff($c->id()),'canManage'=>$internal]);}
 public function reply(Request$r,string$ticket,TenantContext$c,SupportTicketService$s){$item=$this->ticket($c,$ticket);$d=$r->validate(['message'=>['required','string','max:10000'],'visibility'=>['nullable',Rule::in(['PUBLIC','INTERNAL'])],'attachment'=>['nullable','file','max:'.config('zigo_support.attachment_max_kb')]]);$visibility=$item->scope==='TENANT_OPERATIONAL'?($d['visibility']??'PUBLIC'):'PUBLIC';$s->reply($item,$r->user(),$d['message'],$visibility,$r->file('attachment'));return back()->with('success','Respuesta registrada.');}
 public function update(Request$r,string$ticket,TenantContext$c,SupportTicketService$s){$item=SupportTicket::where('uuid',$ticket)->where('tenant_id',$c->id())->where('scope','TENANT_OPERATIONAL')->firstOrFail();$d=$r->validate(['status'=>['nullable',Rule::in(SupportTicket::STATUSES)],'priority'=>['nullable',Rule::in(SupportTicket::PRIORITIES)],'assigned_user_id'=>['nullable','integer']]);if(array_key_exists('assigned_user_id',$d)){$id=$d['assigned_user_id']?:null;if($id&&!$this->staff($c->id())->contains('user_id',$id))abort(422,'La persona asignada no pertenece al equipo de soporte del tenant.');$s->assign($item,$r->user(),$id);}if(!empty($d['status']))$s->status($item,$r->user(),$d['status']);if(!empty($d['priority']))$s->priority($item,$r->user(),$d['priority']);return back()->with('success','Ticket actualizado.');}
 public function attachment(Request$r,string$ticket,SupportTicketAttachment$a,TenantContext$c,SupportTicketService$s){$item=$this->ticket($c,$ticket);abort_unless($a->ticket_id===$item->id,404);abort_if($item->scope==='ZIGO_PLATFORM'&&$a->message_id&&$a->message()->where('visibility','!=','PUBLIC')->exists(),404);return$s->download($a);}
 private function ticket(TenantContext$c,string$uuid){return SupportTicket::where('uuid',$uuid)->where('tenant_id',$c->id())->where(fn($q)=>$q->where('scope','TENANT_OPERATIONAL')->orWhere(fn($p)=>$p->where('scope','ZIGO_PLATFORM')->where('requester_type','TENANT_STAFF')))->firstOrFail();}
 private function staff(int$tenant){return TenantMembership::with('user')->where('tenant_id',$tenant)->where('status','active')->whereIn('role',['owner','admin','operator','support'])->get();}
}
