<?php
namespace App\Infrastructure\WhatsApp;use App\Domain\AI\Channels\WhatsApp\Contracts\WhatsAppProvider;use App\Domain\AI\Channels\WhatsApp\Data\{WhatsAppOutboundConfirmationRequest,WhatsAppOutboundTextRequest};use App\Infrastructure\WhatsApp\Data\MetaCloudWhatsAppCredentials;use Illuminate\Support\Facades\Http;
final class MetaCloudWhatsAppProvider implements WhatsAppProvider{
 public function __construct(private MetaCloudWhatsAppCredentialsResolver$credentials){}
 private function client(MetaCloudWhatsAppCredentials$c){return Http::withToken($c->accessToken)->acceptJson()->connectTimeout((int)config('ai.whatsapp.connect_timeout_seconds',5))->timeout((int)config('ai.whatsapp.request_timeout_seconds',20));}
 private function url(MetaCloudWhatsAppCredentials$c):string{return rtrim((string)config('ai.whatsapp.graph_base_url'),'\/').'/'.(string)config('ai.whatsapp.graph_version').'/'.rawurlencode($c->phoneNumberId).'/messages';}
 public function sendText(WhatsAppOutboundTextRequest$request):string{$c=$this->credentials->resolve($request->channelId);$r=$this->client($c)->post($this->url($c),['messaging_product'=>'whatsapp','to'=>$request->recipient,'type'=>'text','text'=>['body'=>$request->body]])->throw()->json();return(string)($r['messages'][0]['id']??throw new \RuntimeException('provider_response_invalid'));}
 public function sendConfirmation(WhatsAppOutboundConfirmationRequest$request):string{$c=$this->credentials->resolve($request->channelId);$s=$request->summary;$body=$s['title']."\n".implode("\n",array_map(fn($f)=>$f['label'].': '.$f['value'],$s['fields']));$r=$this->client($c)->post($this->url($c),['messaging_product'=>'whatsapp','to'=>$request->recipient,'type'=>'interactive','interactive'=>['type'=>'button','body'=>['text'=>$body],'action'=>['buttons'=>[['type'=>'reply','reply'=>['id'=>$request->confirmToken,'title'=>'Confirmar']],['type'=>'reply','reply'=>['id'=>$request->cancelToken,'title'=>'Cancelar']]]]]])->throw()->json();return(string)($r['messages'][0]['id']??throw new \RuntimeException('provider_response_invalid'));}
}
