@extends('tenant.layout')
@section('title',$address?'Editar dirección':'Nueva dirección')
@section('content')
<div style="max-width:900px"><header class="z-page-header"><div><div class="z-eyebrow">MIS DIRECCIONES</div><h1>{{ $address?'Editar dirección':'Nueva dirección' }}</h1><p class="z-muted">El municipio y estado se obtienen automáticamente desde SEPOMEX.</p></div></header>
@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<form class="z-card z-stack" method="POST" action="{{ $address?route('tenant.customer.app.addresses.update',$address,false):route('tenant.customer.app.addresses.store',[],false) }}">@csrf @if($address)@method('PUT')@endif
<div class="z-form-grid"><label class="z-field">Alias<input name="alias" value="{{ old('alias',$address?->alias) }}" required></label><label class="z-field">Uso<select name="address_type" required>@foreach(['origin'=>'Origen','destination'=>'Destino','both'=>'Origen y destino'] as $value=>$label)<option value="{{ $value }}" @selected(old('address_type',$address?->address_type??'both')===$value)>{{ $label }}</option>@endforeach</select></label></div>
<div class="z-form-grid"><label class="z-field">Contacto<input name="contact_name" value="{{ old('contact_name',$address?->contact_name) }}" required></label><label class="z-field">Empresa <span class="z-muted">(opcional)</span><input name="company" value="{{ old('company',$address?->company) }}"></label><label class="z-field">Teléfono<input name="phone" value="{{ old('phone',$address?->phone) }}" required></label><label class="z-field">Correo <span class="z-muted">(opcional)</span><input type="email" name="email" value="{{ old('email',$address?->email) }}"></label></div>
<div class="z-form-grid"><label class="z-field">Código postal<input name="postal_code" data-address-postal inputmode="numeric" maxlength="5" value="{{ old('postal_code',$address?->postal_code) }}" required></label><label class="z-field">Colonia<select name="settlement" data-address-settlement data-current="{{ old('settlement',$address?->settlement) }}" required><option value="">Captura el CP</option></select></label></div><p class="z-muted" data-address-location>{{ $address?->municipality }}@if($address?->municipality), {{ $address->state }}@endif</p>
<div class="z-form-grid"><label class="z-field">Calle o avenida<input name="street" value="{{ old('street',$address?->street) }}" required></label><label class="z-field">No. exterior<input name="exterior" value="{{ old('exterior',$address?->exterior) }}" required></label><label class="z-field">No. interior <span class="z-muted">(opcional)</span><input name="interior" value="{{ old('interior',$address?->interior) }}"></label></div>
<label class="z-field">Referencias <span class="z-muted">(opcional)</span><textarea name="references">{{ old('references',$address?->references) }}</textarea></label>
<div class="z-cluster"><label class="z-choice"><input type="checkbox" name="is_default_origin" value="1" @checked(old('is_default_origin',$address?->is_default_origin))><span>Predeterminada de origen</span></label><label class="z-choice"><input type="checkbox" name="is_default_destination" value="1" @checked(old('is_default_destination',$address?->is_default_destination))><span>Predeterminada de destino</span></label></div>
<div class="z-form-actions"><a class="z-btn z-btn--ghost" href="{{ route('tenant.customer.app.addresses.index',[],false) }}">Cancelar</a><button class="z-btn">Guardar dirección</button></div></form></div>
@endsection
@push('scripts')<script>(()=>{const postal=document.querySelector('[data-address-postal]'),settlement=document.querySelector('[data-address-settlement]'),location=document.querySelector('[data-address-location]');const lookup=async()=>{if(!/^\d{5}$/.test(postal.value))return;settlement.disabled=true;try{const response=await fetch(`/codigos-postales/${postal.value}`,{headers:{Accept:'application/json'}}),data=await response.json();if(!response.ok)throw new Error(data.message);const current=settlement.dataset.current;settlement.innerHTML='<option value="">Selecciona una colonia</option>'+data.colonias.map(item=>`<option${item.nombre===current?' selected':''}>${item.nombre}</option>`).join('');settlement.disabled=false;location.textContent=`${data.municipio}, ${data.estado}`}catch(error){settlement.innerHTML='<option value="">Código postal no disponible</option>';location.textContent=error.message||'No fue posible consultar SEPOMEX'}};postal.addEventListener('change',()=>{settlement.dataset.current='';lookup()});if(/^\d{5}$/.test(postal.value))lookup()})()</script>@endpush
