@extends('tenant.layout')
@section('title','Mis direcciones')
@push('head')<style>.address-card-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.address-card{display:flex;min-width:0;flex-direction:column;gap:15px;padding:20px;border:1px solid var(--z-border);border-radius:16px;background:#fff;box-shadow:0 8px 24px rgba(15,35,75,.05)}.address-card__head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.address-card__head h2{font-size:1.12rem;margin:0}.address-card__contact strong,.address-card__contact span{display:block}.address-card__contact span{margin-top:3px;color:var(--z-muted);font-size:.88rem}.address-card__location{padding:13px;border-radius:11px;background:var(--z-surface-subtle)}.address-card__location strong,.address-card__location span{display:block}.address-card__location span{margin-top:4px;color:var(--z-muted);font-size:.82rem}.address-card__actions{display:flex;gap:8px;margin-top:auto;padding-top:2px}.address-card__actions form{margin:0}.address-card__actions .z-btn{min-height:40px}@media(max-width:1100px){.address-card-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.address-card-grid{grid-template-columns:1fr}}</style>@endpush
@section('content')
<header class="z-page-header"><div><div class="z-eyebrow">MI CUENTA</div><h1>Mis direcciones</h1><p class="z-muted">Guarda domicilios frecuentes para completar tus envíos más rápido.</p></div><a class="z-btn" href="{{ route('tenant.customer.app.addresses.create',[],false) }}">Nueva dirección</a></header>
<div class="address-card-grid">
@forelse($addresses as $address)
<article class="address-card"><header class="address-card__head"><h2>{{ $address->alias }}</h2><span class="z-badge">{{ ['origin'=>'Origen','destination'=>'Destino','both'=>'Ambos'][$address->address_type] }}</span></header><div class="address-card__contact"><strong>{{ $address->contact_name }}</strong><span>{{ $address->phone }}</span></div><div class="address-card__location"><strong>{{ $address->street }} {{ $address->exterior }}@if($address->interior), Int. {{ $address->interior }}@endif</strong><span>{{ $address->settlement }} · CP {{ $address->postal_code }}</span><span>{{ $address->municipality }}, {{ $address->state }}</span></div>@if($address->is_default_origin || $address->is_default_destination)<div class="z-cluster">@if($address->is_default_origin)<span class="z-badge z-badge--success">Origen predeterminado</span>@endif @if($address->is_default_destination)<span class="z-badge z-badge--success">Destino predeterminado</span>@endif</div>@endif<div class="address-card__actions"><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.app.addresses.edit',$address,false) }}">Editar</a><form method="POST" action="{{ route('tenant.customer.app.addresses.destroy',$address,false) }}">@csrf @method('DELETE')<button class="z-btn z-btn--ghost" type="submit">Eliminar</button></form></div></article>
@empty<div class="z-empty"><h3>Aún no tienes direcciones</h3><p>Agrega una dirección para usarla en tus próximos envíos.</p><a class="z-btn" href="{{ route('tenant.customer.app.addresses.create',[],false) }}">Agregar dirección</a></div>@endforelse
</div>
@endsection
