<?php
namespace App\Domain\Network\Billing;
use App\Domain\Network\Billing\Models\Subscription;use App\Domain\Network\Catalog\Models\Plan;use App\Domain\Network\Tenancy\Models\Tenant;use Illuminate\Support\Carbon;use Illuminate\Support\Facades\{DB,Schema};use Illuminate\Validation\ValidationException;
final class SubscriptionService
{
 public function __construct(private EntitlementService$entitlements){}
 public function currentForTenant(Tenant|int$tenant):?Subscription{if(!Schema::hasTable('network_subscriptions'))return null;$id=$tenant instanceof Tenant?$tenant->id:$tenant;return Subscription::with('plan')->where('tenant_id',$id)->whereIn('status',Subscription::CURRENT_STATUSES)->where('started_at','<=',now())->where('current_period_end','>=',now())->latest('started_at')->first();}
 public function activeForTenant(Tenant|int$tenant):?Subscription{$s=$this->currentForTenant($tenant);return$s&&in_array($s->status,['trial','trialing','active','past_due','grace'],true)?$s:null;}
 public function historyForTenant(Tenant|int$tenant){if(!Schema::hasTable('network_subscriptions'))return collect();$id=$tenant instanceof Tenant?$tenant->id:$tenant;return Subscription::with('plan')->where('tenant_id',$id)->latest('started_at')->get();}
 public function create(Tenant$tenant,array$data,?int$actorId=null):Subscription
 {
  if(!in_array($data['status']??null,Subscription::STATUSES,true))throw ValidationException::withMessages(['status'=>'Estado de suscripción inválido.']);
  $started=Carbon::parse($data['started_at']);$periodStart=Carbon::parse($data['current_period_start']);$periodEnd=Carbon::parse($data['current_period_end']);
  if($periodStart->lt($started)||$periodEnd->lte($periodStart))throw ValidationException::withMessages(['current_period_end'=>'El periodo de suscripción es inconsistente.']);
  return DB::transaction(function()use($tenant,$data,$actorId,$periodStart,$periodEnd){Tenant::whereKey($tenant->id)->lockForUpdate()->first();$overlap=Subscription::where('tenant_id',$tenant->id)->whereIn('status',Subscription::CURRENT_STATUSES)->where('current_period_start','<=',$periodEnd)->where('current_period_end','>=',$periodStart)->exists();if($overlap)throw ValidationException::withMessages(['status'=>'El tenant ya tiene una suscripción vigente o superpuesta.']);$plan=Plan::findOrFail($data['plan_id']);$data['operations_limit']=$plan->included_operations;$subscription=$tenant->subscriptions()->create($data);$this->entitlements->snapshotFromPlan($subscription,$plan);$subscription->events()->create(['tenant_id'=>$tenant->id,'actor_user_id'=>$actorId,'event'=>'created','to_status'=>$subscription->status,'metadata'=>['plan_id'=>$plan->id]]);return$subscription->load(['plan','entitlements.module']);});
 }
 public function changeStatus(Subscription$s,string$status,?int$actorId=null):Subscription
 {return DB::transaction(function()use($s,$status,$actorId){$s=Subscription::whereKey($s->id)->lockForUpdate()->firstOrFail();if(!in_array($status,Subscription::STATUSES,true))throw ValidationException::withMessages(['status'=>'Estado de suscripción inválido.']);if(in_array($status,Subscription::CURRENT_STATUSES,true)&&$status!==$s->status){$conflict=Subscription::where('tenant_id',$s->tenant_id)->whereKeyNot($s->id)->whereIn('status',Subscription::CURRENT_STATUSES)->where('current_period_start','<=',$s->current_period_end)->where('current_period_end','>=',$s->current_period_start)->exists();if($conflict)throw ValidationException::withMessages(['status'=>'Ya existe otra suscripción vigente o superpuesta.']);}$from=$s->status;$updates=['status'=>$status];if($status==='canceled')$updates['canceled_at']=now();if($status==='ended')$updates['ended_at']=now();if(in_array($status,['trial','active'],true)){$updates['canceled_at']=null;$updates['ended_at']=null;}$s->update($updates);$event=match($status){'active'=>$from==='suspended'?'reactivated':'activated','past_due'=>'past_due','grace'=>'grace','suspended'=>'suspended','canceled'=>'canceled','ended'=>'ended',default=>'status_changed'};$s->events()->create(['tenant_id'=>$s->tenant_id,'actor_user_id'=>$actorId,'event'=>$event,'from_status'=>$from,'to_status'=>$status]);return$s->fresh(['plan','entitlements.module']);});}
 public function activatePaidPlan(Tenant$tenant,int$planId,string$billingType,?int$actorId=null):Subscription
 {return DB::transaction(function()use($tenant,$planId,$billingType,$actorId){$plan=Plan::findOrFail($planId);$current=$this->currentForTenant($tenant);$months=$billingType==='ANNUAL'?12:1;if($current&&$current->plan_id===$plan->id){$from=$current->current_period_end->isFuture()?$current->current_period_end:now();$old=$current->status;$current->update(['status'=>'active','current_period_end'=>$from->copy()->addMonthsNoOverflow($months),'operations_limit'=>$plan->included_operations]);$current->events()->create(['tenant_id'=>$tenant->id,'actor_user_id'=>$actorId,'event'=>'renewed','from_status'=>$old,'to_status'=>'active','metadata'=>['months'=>$months]]);return$current->fresh();}if($current)$this->changeStatus($current,'ended',$actorId);$start=now();$subscription=$this->create($tenant,['plan_id'=>$plan->id,'status'=>'active','started_at'=>$start,'current_period_start'=>$start,'current_period_end'=>$start->copy()->addMonthsNoOverflow($months)],$actorId);$tenant->update(['current_plan_id'=>$plan->id]);return$subscription;});}
}
