<?php
namespace App\Domain\Network\Billing;
use App\Domain\Network\Billing\Models\{Subscription,UsageEvent};use App\Domain\Network\Tenancy\Models\Tenant;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
final class UsageService
{
 public function __construct(private SubscriptionService$subscriptions){}
 public function record(Tenant$t,string$metric,int$quantity=1,?string$idempotencyKey=null,array$metadata=[],mixed$occurredAt=null):UsageEvent{if(!in_array($metric,config('zigo_usage.metrics',[]),true))throw ValidationException::withMessages(['metric'=>'Métrica inválida.']);if($quantity<1)throw ValidationException::withMessages(['quantity'=>'La cantidad debe ser al menos 1.']);$s=$this->subscriptions->currentForTenant($t);if(!$s)throw ValidationException::withMessages(['subscription'=>'No existe una suscripción vigente.']);if($idempotencyKey){$existing=UsageEvent::where('tenant_id',$t->id)->where('metric',$metric)->where('idempotency_key',$idempotencyKey)->first();if($existing)return$existing;}return UsageEvent::create(['tenant_id'=>$t->id,'subscription_id'=>$s->id,'metric'=>$metric,'quantity'=>$quantity,'idempotency_key'=>$idempotencyKey,'occurred_at'=>$occurredAt??now(),'metadata'=>$metadata?:null]);}
 public function total(Tenant$t,string$metric='operations',?Subscription$s=null):int{$s??=$this->subscriptions->currentForTenant($t);if(!$s)return 0;return(int)UsageEvent::where('tenant_id',$t->id)->where('subscription_id',$s->id)->where('metric',$metric)->whereBetween('occurred_at',[$s->current_period_start,$s->current_period_end])->sum('quantity');}
 public function limit(Tenant$t,string$metric='operations',?Subscription$s=null):?int{$s??=$this->subscriptions->currentForTenant($t);return$metric==='operations'?$s?->operations_limit:null;}
 public function summary(Tenant$t,string$metric='operations',?Subscription$s=null):array{$s??=$this->subscriptions->currentForTenant($t);$used=$this->total($t,$metric,$s);$limit=$this->limit($t,$metric,$s);$remaining=$limit===null?null:max(0,$limit-$used);return['used'=>$used,'limit'=>$limit,'remaining'=>$remaining,'percentage'=>$limit&&$limit>0?round(($used/$limit)*100,2):null,'over_limit'=>$limit!==null&&$used>$limit];}
 public function remaining(Tenant$t,string$metric='operations'):?int{return$this->summary($t,$metric)['remaining'];}public function percentage(Tenant$t,string$metric='operations'):?float{return$this->summary($t,$metric)['percentage'];}
}
