<?php
namespace App\Domain\AI\Usage;
use App\Domain\AI\Agents\Enums\AgentStatus;use App\Domain\AI\Agents\Models\Agent;use App\Domain\AI\Channels\Webchat\Models\WebchatChannel;use App\Domain\AI\Channels\WhatsApp\Models\WhatsAppChannel;use App\Domain\AI\Core\AiFeatureGate;use App\Domain\AI\Usage\Exceptions\AiCapacityExceededException;use App\Domain\Network\Billing\{EntitlementService,SubscriptionService,UsageService};use App\Domain\Network\Billing\Models\{Entitlement,Subscription,UsageEvent};use App\Domain\Network\Tenancy\Models\Tenant;use Illuminate\Support\Facades\{DB,Schema};
final class AiCapacityService{
 public const MAX_AGENTS='MAX_AGENTS',MAX_WEBCHAT_CHANNELS='MAX_WEBCHAT_CHANNELS',MAX_WHATSAPP_CHANNELS='MAX_WHATSAPP_CHANNELS',MONTHLY_RUNTIME_UNITS='MONTHLY_RUNTIME_UNITS',MONTHLY_ACTION_RUNS='MONTHLY_ACTION_RUNS',MONTHLY_CONVERSATIONS='MONTHLY_CONVERSATIONS';
 public const METRICS=[self::MONTHLY_RUNTIME_UNITS=>'ai_runtime_units',self::MONTHLY_ACTION_RUNS=>'ai_action_runs',self::MONTHLY_CONVERSATIONS=>'ai_conversations'];
 public function __construct(private SubscriptionService$subscriptions,private EntitlementService$entitlements,private UsageService$usage,private AiUsagePeriodResolver$periods,private AiFeatureGate$feature){}
 public function activeSubscription(Tenant$t):?Subscription{if(!$this->feature->enabled()||$t->status!=='active')return null;$s=$this->subscriptions->activeForTenant($t);return$s&&now()->lt($s->current_period_end)?$s:null;}
 private function authority(Tenant$t,?Subscription$s=null):array{if(!$this->feature->enabled()||$t->status!=='active')return[null,null];if($s===null)$s=$this->activeSubscription($t);elseif((int)$s->tenant_id!==(int)$t->id||$s->status!=='active'||now()->lt($s->current_period_start)||now()->gte($s->current_period_end))return[null,null];if(!$s)return[null,null];$e=$s->entitlements()->where('tenant_id',$t->id)->where('code','AI_CORE')->where('is_enabled',true)->first();return[$s,$e];}
 public function limit(Tenant$t,string$c,?Subscription$s=null):int{[$s,$e]=$this->authority($t,$s);if(!$s||!$e)return 0;$base=$this->planBaseline($s,$e,$c)??(int)config('ai.capacity.defaults.'.$c,0);if(!Schema::hasTable('network_entitlement_capacities'))return$base;$rows=DB::table('network_entitlement_capacities')->where('tenant_id',$t->id)->where('subscription_id',$s->id)->where('entitlement_id',$e->id)->where('capability_code',$c)->where('is_enabled',true);$override=(clone$rows)->where('source','override')->where('source_key','override')->value('quantity');$addons=(int)(clone$rows)->where('source','addon')->sum('quantity');return(int)($override??$base)+$addons;}
 private function planBaseline(Subscription$s,Entitlement$e,string$c):?int{if(!Schema::hasTable('network_plan_module_capacities'))return null;$value=DB::table('network_plan_module_capacities')->where('plan_id',$s->plan_id)->where('module_id',$e->module_id)->where('capability_code',$c)->value('quantity');return$value===null?null:(int)$value;}
 public function used(Tenant$t,string$c,?Subscription$s=null):int{$s??=$this->activeSubscription($t);if(!$s)return 0;return match($c){self::MAX_AGENTS=>$this->resourceCount('ai_agents',fn()=>Agent::query()->where('tenant_id',$t->id)->where('status','!=',AgentStatus::Retired->value)->count()),self::MAX_WEBCHAT_CHANNELS=>$this->resourceCount('ai_webchat_channels',fn()=>WebchatChannel::query()->where('tenant_id',$t->id)->count()),self::MAX_WHATSAPP_CHANNELS=>$this->resourceCount('ai_whatsapp_channels',fn()=>WhatsAppChannel::query()->where('tenant_id',$t->id)->count()),default=>isset(self::METRICS[$c])?$this->meteredTotal($t,self::METRICS[$c],$s):0};}
 private function meteredTotal(Tenant$t,string$metric,Subscription$s):int{$period=$this->periods->current($s);if(!$period||!Schema::hasTable('network_usage_events'))return 0;return(int)UsageEvent::query()->where('tenant_id',$t->id)->where('subscription_id',$s->id)->where('metric',$metric)->where('occurred_at','>=',$period->start)->where('occurred_at','<',$period->end)->sum('quantity');}
 public function capacity(Tenant$t,string$c,?Subscription$s=null):AiCapacity{return new AiCapacity($this->used($t,$c,$s),$this->limit($t,$c,$s));}
 public function lockAuthority(Tenant$t):void{if(!Schema::hasTable('network_subscriptions')){if(app()->environment('testing'))return;throw new \LogicException('AI capacity authority is unavailable.');}$this->entitlements->lockCurrentAuthority($t);if(Schema::hasTable('network_entitlement_capacities'))DB::table('network_entitlement_capacities')->where('tenant_id',$t->id)->orderBy('id')->lockForUpdate()->get();}
 public function assertResourceAvailable(Tenant$t,string$c):void{$this->lockAuthority($t);if($this->capacity($t,$c)->reached())throw new AiCapacityExceededException($c);}
 public function consume(Tenant$t,string$c,string$key,array$metadata=[]):void{$metric=self::METRICS[$c]??throw new \InvalidArgumentException('Unknown metered AI capability.');if(!Schema::hasTable('network_usage_events')){if(app()->environment('testing'))return;throw new \LogicException('AI usage authority is unavailable.');}$this->lockAuthority($t);$s=$this->activeSubscription($t);if(!$s)throw new AiCapacityExceededException($c);if(DB::table('network_usage_events')->where('tenant_id',$t->id)->where('metric',$metric)->where('idempotency_key',$key)->exists())return;if($this->used($t,$c,$s)>=$this->limit($t,$c,$s))throw new AiCapacityExceededException($c);try{$this->usage->record($t,$metric,1,$key,$metadata,now());}catch(\Illuminate\Database\QueryException $e){if(DB::table('network_usage_events')->where('tenant_id',$t->id)->where('metric',$metric)->where('idempotency_key',$key)->exists())return;throw$e;}}
 public function summary(Tenant$t):array{return collect([self::MAX_AGENTS,self::MAX_WEBCHAT_CHANNELS,self::MAX_WHATSAPP_CHANNELS,self::MONTHLY_RUNTIME_UNITS,self::MONTHLY_CONVERSATIONS,self::MONTHLY_ACTION_RUNS])->mapWithKeys(fn($c)=>[$c=>$this->capacity($t,$c)])->all();}
 private function resourceCount(string$table,callable$count):int{if(Schema::hasTable($table))return(int)$count();if(app()->environment('testing'))return 0;throw new \LogicException('AI capacity resource authority is unavailable.');}
}
