<?php
namespace App\Http\Controllers\Network;
use App\Domain\Network\Catalog\Models\{Module,Plan};use App\Domain\Network\Commerce\Models\{NetworkCommercialProduct,TenantSaasOrder};use App\Domain\Network\Operations\NetworkAdminAuditService;use App\Http\Controllers\Controller;use Illuminate\Http\Request;use Illuminate\Validation\Rule;
final class CommercialCatalogController extends Controller{
 public function index(){return view('network.catalog',['products'=>NetworkCommercialProduct::with(['plan','module'])->orderByRaw('COALESCE(display_order, sort_order)')->paginate(30),'plans'=>Plan::where('status','active')->get(),'modules'=>Module::where('is_active',true)->get()]);}
 public function store(Request$r,NetworkAdminAuditService$audit){$d=$this->data($r);$product=NetworkCommercialProduct::create($d);$audit->record($r->user()->id,'commercial_product.created',$product,[],$product->only(array_keys($d)));return back()->with('success','Producto comercial creado.');}
 public function update(Request$r,NetworkCommercialProduct$product,NetworkAdminAuditService$audit){$d=$this->data($r,$product);$before=$product->only(array_keys($d));$product->update($d);$audit->record($r->user()->id,'commercial_product.updated',$product,$before,$product->fresh()->only(array_keys($d)));return back()->with('success','Producto actualizado.');}
 public function orders(){return view('network.saas-orders',['orders'=>TenantSaasOrder::with(['tenant','product'])->latest()->paginate(50)]);}
 private function data(Request$r,?NetworkCommercialProduct$p=null):array{$d=$r->validate(['code'=>['required','max:80',Rule::unique('network_commercial_products')->ignore($p)],'name'=>['required','max:160'],'description'=>['nullable','max:2000'],'type'=>['required',Rule::in(NetworkCommercialProduct::TYPES)],'billing_type'=>['required',Rule::in(NetworkCommercialProduct::BILLING_TYPES)],'price'=>['required','numeric','min:0'],'currency'=>['required',Rule::in(['MXN'])],'plan_id'=>['nullable','exists:network_plans,id'],'module_id'=>['nullable','exists:network_modules,id'],'included_operations'=>['nullable','integer','min:1'],'is_active'=>['nullable','boolean'],'is_public'=>['nullable','boolean'],'sort_order'=>['nullable','integer','min:0'],'display_order'=>['nullable','integer','min:0'],'archived'=>['nullable','boolean']]);$d['is_active']=(bool)($d['is_active']??false);$d['is_public']=(bool)($d['is_public']??false);$d['archived_at']=($d['archived']??false)?now():null;unset($d['archived']);if($d['is_public']&&(!$d['is_active']||$d['type']!=='PLAN'||!in_array($d['billing_type'],['MONTHLY','ANNUAL'],true)))throw \Illuminate\Validation\ValidationException::withMessages(['is_public'=>'Sólo una oferta PLAN mensual/anual activa puede publicarse.']);if($d['type']==='PLAN'&&empty($d['plan_id']))throw \Illuminate\Validation\ValidationException::withMessages(['plan_id'=>'Selecciona el plan activable.']);if(in_array($d['type'],['MODULE','ADDON'],true)&&empty($d['module_id']))throw \Illuminate\Validation\ValidationException::withMessages(['module_id'=>'Selecciona el módulo activable.']);if($d['type']==='OPERATION_PACK'&&empty($d['included_operations']))throw \Illuminate\Validation\ValidationException::withMessages(['included_operations'=>'Define las operaciones del paquete.']);return$d;}
}
