<?php
namespace App\Http\Controllers\Network;

use App\Domain\Network\Billing\Models\Subscription;
use App\Domain\Network\Billing\{SaasSubscriptionLifecycleService,SubscriptionService,UsageService};
use App\Domain\Network\Commerce\Models\{PlatformPaymentAttempt,TenantSaasOrder};
use App\Domain\Network\Onboarding\Models\SaasOnboardingApplication;
use App\Domain\Network\Onboarding\Services\OwnerActivationService;
use App\Domain\Network\Operations\Models\NetworkAdminAuditEvent;
use App\Domain\Network\Operations\NetworkAdminAuditService;
use App\Domain\Network\Tenancy\Models\{Tenant,TenantMembership};
use App\Domain\Network\Tenancy\{TenantAccessService,TenantContext,TenantLifecycleService};
use App\Http\Controllers\Controller;
use App\Models\{User,ZigoNotificationDelivery};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{Password,Schema};
use Illuminate\Validation\Rule;

final class NetworkOperationsController extends Controller
{
 public function users(Request$r){$q=TenantMembership::with(['tenant','user'])->when($r->filled('q'),fn($q)=>$q->whereHas('user',fn($u)=>$u->where('email','like','%'.$r->q.'%')->orWhere('name','like','%'.$r->q.'%')))->when($r->filled('tenant_id'),fn($q)=>$q->where('tenant_id',$r->tenant_id))->when($r->filled('status'),fn($q)=>$q->where('status',$r->status));return view('network.operations.users',['memberships'=>$q->latest()->paginate(30)->withQueryString(),'tenants'=>Tenant::orderBy('name')->get()]);}
 public function tenantUsers(Tenant$tenant){return redirect()->route('network.users.index',['tenant_id'=>$tenant->id]);}
 public function membership(Request$r,Tenant$tenant,TenantMembership$membership,TenantContext$context,TenantAccessService$access,NetworkAdminAuditService$audit){abort_unless($membership->tenant_id===$tenant->id,404);$data=$r->validate(['role'=>['required',Rule::in(TenantMembership::ROLES)],'status'=>['required',Rule::in(TenantMembership::STATUSES)]]);$before=$membership->only(['role','status']);$context->set($tenant);$access->updateMembership($membership,$data,$r->user(),true);$audit->record($r->user()->id,'membership.updated',$membership,$before,$membership->fresh()->only(['role','status']));return back()->with('success','Acceso tenant actualizado.');}
 public function reset(Request$r,Tenant$tenant,TenantMembership$membership,NetworkAdminAuditService$audit){abort_unless($membership->tenant_id===$tenant->id,404);Password::broker()->sendResetLink(['email'=>$membership->user->email]);$audit->record($r->user()->id,'membership.password_reset_requested',$membership);return back()->with('success','Flujo estándar de recuperación solicitado.');}
 public function activation(Request$r,Tenant$tenant,TenantMembership$membership,OwnerActivationService$activation,NetworkAdminAuditService$audit){abort_unless($membership->tenant_id===$tenant->id,404);$app=SaasOnboardingApplication::where('tenant_id',$tenant->id)->where('owner_user_id',$membership->user_id)->where('status','ACTIVE')->firstOrFail();if(Schema::hasTable('zigo_notification_deliveries'))ZigoNotificationDelivery::where('event_key','saas-owner-welcome:'.$app->uuid)->whereIn('status',['SENT','FAILED'])->delete();$activation->sendIfNeeded($app);$audit->record($r->user()->id,'membership.activation_resent',$membership);return back()->with('success','Activación reenviada de forma segura.');}
 public function subscriptions(Request$r,UsageService$usage){$q=Subscription::with(['tenant','plan'])->when($r->filled('tenant_id'),fn($q)=>$q->where('tenant_id',$r->tenant_id))->when($r->filled('plan_id'),fn($q)=>$q->where('plan_id',$r->plan_id))->when($r->filled('status'),fn($q)=>$q->where('status',$r->status))->when($r->lifecycle==='upcoming',fn($q)=>$q->whereBetween('current_period_end',[now(),now()->addDays(max(config('zigo_billing.reminder_days',[30])))]))->when($r->lifecycle==='expired',fn($q)=>$q->where('current_period_end','<',now()));if($r->filled('billing')){$annual=$r->billing==='ANNUAL';$driver=$q->getConnection()->getDriverName();$expression=$driver==='sqlite'?'julianday(current_period_end)-julianday(current_period_start)':'DATEDIFF(current_period_end,current_period_start)';$q->whereRaw($expression.($annual?'>=':'<').' 300');}return view('network.operations.subscriptions',['subscriptions'=>$q->latest()->paginate(30)->withQueryString()]);}
 public function subscription(Subscription$subscription,UsageService$usage){$subscription->load(['tenant','plan','entitlements.module','events']);$orders=TenantSaasOrder::with('attempts')->where('tenant_id',$subscription->tenant_id)->where('purchase_key','like','renewal:%')->latest()->get();$notices=Schema::hasTable('zigo_notification_deliveries')?ZigoNotificationDelivery::where('notifiable_type',Subscription::class)->where('notifiable_id',$subscription->id)->latest()->get():collect();return view('network.operations.subscription',compact('subscription','orders','notices')+['usage'=>$usage->summary($subscription->tenant,'operations',$subscription)]);}
 public function subscriptionStatus(Request$r,Subscription$subscription,SubscriptionService$service,NetworkAdminAuditService$audit){$data=$r->validate(['status'=>['required',Rule::in(['suspended'])]]);$before=$subscription->status;$service->changeStatus($subscription,$data['status'],$r->user()->id);$subscription->tenant()->update(['status'=>'suspended']);$audit->record($r->user()->id,'subscription.status_changed',$subscription,['status'=>$before],['status'=>$data['status']]);return back()->with('success','Suscripción suspendida. La reactivación requiere pago verificado.');}
 public function subscriptionReminder(Request$r,Subscription$subscription,SaasSubscriptionLifecycleService$service,NetworkAdminAuditService$audit){$sent=$service->sendReminder($subscription);$audit->record($r->user()->id,'subscription.reminder_requested',$subscription,[],['sent'=>$sent]);return back()->with('success',$sent?'Recordatorio enviado.':'El recordatorio de este periodo ya fue enviado.');}
 public function subscriptionRenewal(Request$r,Subscription$subscription,SaasSubscriptionLifecycleService$service,NetworkAdminAuditService$audit){$order=$service->generateRenewal($subscription,$r->user());$audit->record($r->user()->id,'subscription.renewal_generated',$order,[],['subscription_id'=>$subscription->id,'total_amount'=>$order->total_amount,'currency'=>$order->currency]);return back()->with('success','Renovación generada. El precio queda visible en la orden antes del checkout.');}
 public function subscriptionSuspend(Request$r,Subscription$subscription,SaasSubscriptionLifecycleService$service,NetworkAdminAuditService$audit){$before=$subscription->status;$service->suspendExpired($subscription,$r->user()->id);$audit->record($r->user()->id,'subscription.suspended_for_expiration',$subscription,['status'=>$before],['status'=>$subscription->fresh()->status]);return back()->with('success','Acceso comercial suspendido; el historial permanece intacto.');}
 public function tenantArchive(Request$r,Tenant$tenant,TenantLifecycleService$service,NetworkAdminAuditService$audit){$data=$r->validate(['reason'=>['required','string','max:500']]);$before=$tenant->only(['status','archived_at','archive_reason']);$service->archive($tenant,$data['reason']);$audit->record($r->user()->id,'tenant.archived',$tenant,$before,$tenant->fresh()->only(['status','archived_at','archive_reason']));return back()->with('success','Tenant archivado sin eliminar su historial.');}
 public function tenantDelete(Request$r,Tenant$tenant,TenantLifecycleService$service,NetworkAdminAuditService$audit){$data=$r->validate(['reason'=>['required','string','max:500']]);if(!$service->canPermanentlyDeleteTenant($tenant))throw \Illuminate\Validation\ValidationException::withMessages(['tenant'=>'El tenant conserva historial y sólo puede archivarse.']);$snapshot=$tenant->only(['id','uuid','name','slug','status']);$service->deleteEmpty($tenant,$data['reason']);$audit->record($r->user()->id,'tenant.permanently_deleted',$tenant,$snapshot,['reason'=>$data['reason']]);return redirect()->route('network.tenants.index')->with('success','Tenant vacío eliminado.');}
 public function payments(Request$r){$q=PlatformPaymentAttempt::with(['order.tenant','onboarding.tenant'])->when($r->filled('status'),fn($q)=>$q->where('status',$r->status))->when($r->filled('provider'),fn($q)=>$q->where('provider',$r->provider))->when($r->filled('tenant_id'),fn($q)=>$q->where(function($x)use($r){$x->where('tenant_id',$r->tenant_id)->orWhereHas('onboarding',fn($o)=>$o->where('tenant_id',$r->tenant_id));}));return view('network.operations.payments',['attempts'=>$q->latest()->paginate(40)->withQueryString()]);}
 public function payment(PlatformPaymentAttempt$attempt){$attempt->load(['order.tenant','order.product','onboarding.tenant']);$events=$attempt->hasMany(\App\Domain\Network\Commerce\Models\PlatformPaymentEvent::class,'platform_payment_attempt_id')->latest('received_at')->get();return view('network.operations.payment',compact('attempt','events'));}
 public function audit(){return view('network.operations.audit',['events'=>NetworkAdminAuditEvent::with('actor')->latest('created_at')->paginate(50)]);}
}
