@extends('tenant.layout')
@section('title','Datos del envío')
@section('content')
@include('tenant.customer.journey.steps',['currentStep'=>3])
<header class="z-page-header"><div><div class="z-eyebrow">PASO 3</div><h1>Datos del envío</h1><p class="z-muted">La ruta y el paquete conservan exactamente lo cotizado.</p></div></header>
@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<section class="z-card" style="margin-bottom:1rem"><div class="z-grid"><div><div class="z-eyebrow">RUTA COTIZADA</div><strong>{{ $operation->metadata['origin_postal_code'] }} → {{ $operation->metadata['destination_postal_code'] }}</strong></div><div><div class="z-eyebrow">PAQUETE COTIZADO</div><strong>{{ ucfirst($package['type'] ?? 'Paquete') }} · {{ $package['weight'] ?? '—' }} kg</strong>@if(($package['type']??null)==='caja')<div class="z-muted">{{ $package['length'] }} × {{ $package['width'] }} × {{ $package['height'] }} cm</div>@endif</div></div></section>
<form method="POST" action="/app/envio/nuevo" class="z-stack">@csrf
@foreach(['sender'=>['REMITENTE','origen',$operation->metadata['origin_postal_code']], 'recipient'=>['DESTINATARIO','destino',$operation->metadata['destination_postal_code']]] as $key=>$section)<section class="z-card z-form-section"><div class="z-form-section__head"><div class="z-eyebrow">{{ $section[0] }}</div><h2>Datos de {{ $section[1] }}</h2></div><div class="z-form-grid"><label class="z-field">Nombre<input name="{{ $key }}[name]" value="{{ old($key.'.name') }}" required></label><label class="z-field">Teléfono<input type="tel" name="{{ $key }}[phone]" value="{{ old($key.'.phone') }}" required></label></div><label class="z-field">Dirección<input name="{{ $key }}[address]" value="{{ old($key.'.address') }}" required></label><div class="z-form-grid"><label class="z-field">Código postal<input name="{{ $key }}[postal_code]" value="{{ $section[2] }}" readonly aria-readonly="true" data-postal="{{ $key }}"></label><label class="z-field">Colonia<select name="{{ $key }}[neighborhood]" required data-neighborhood="{{ $key }}"><option value="">Cargando colonias…</option></select></label></div><div class="z-form-grid"><label class="z-field">Municipio<input data-municipality="{{ $key }}" disabled></label><label class="z-field">Estado<input data-state="{{ $key }}" disabled></label></div><label class="z-field">Referencias opcionales<textarea name="{{ $key }}[references]">{{ old($key.'.references') }}</textarea></label></section>@endforeach
<section class="z-card"><label class="z-field">Referencia de tu envío <input name="reference" value="{{ old('reference') }}" maxlength="100"><span class="z-help">Por ejemplo, número de pedido interno.</span></label></section><div class="z-form-actions"><a class="z-btn z-btn--outline" href="/app/cotizar">Volver a cotizar</a><button class="z-btn">Continuar a evidencia</button></div></form>
@endsection
@push('scripts')<script>document.querySelectorAll('[data-postal]').forEach(async input=>{const side=input.dataset.postal,select=document.querySelector(`[data-neighborhood="${side}"]`);try{const response=await fetch('/postal-code/lookup/'+encodeURIComponent(input.value),{headers:{Accept:'application/json'}}),data=await response.json();if(!response.ok)throw new Error();document.querySelector(`[data-municipality="${side}"]`).value=data.municipio||'';document.querySelector(`[data-state="${side}"]`).value=data.estado||'';select.innerHTML='<option value="">Selecciona colonia</option>'+data.colonias.map(c=>`<option value="${String(c.nombre).replaceAll('"','&quot;')}">${c.nombre}</option>`).join('')}catch(e){select.innerHTML='<option value="">Catálogo temporalmente no disponible</option>'}})</script>@endpush
