@extends('tenant.layout')
@section('title','Datos del envío')
@php($snapshot=\App\Domain\Shipping\Local\Models\LocalShippingQuoteSnapshot::where('tenant_id',$operation->tenant_id)->where('uuid',$operation->metadata['selected_quote_snapshot_uuid']??'')->first())
@section('content')
@include('tenant.customer.journey.steps',['currentStep'=>3])
<header class="z-page-header"><div><div class="z-eyebrow">DATOS DEL ENVÍO</div><h1>¿Quién envía y quién recibe?</h1><p class="z-muted">Completa las direcciones para confirmar la ruta y obtener el precio final antes de pagar.</p></div></header>
@if($errors->any())<div class="z-alert z-alert--danger">{{ $errors->first() }}</div>@endif
<section class="z-card" style="margin-bottom:1rem"><div class="z-form-grid"><div><div class="z-eyebrow">ORIGEN</div><strong>{{ $snapshot?->origin['settlement'] }}, {{ $snapshot?->origin['municipality'] }}, {{ $snapshot?->origin['state'] }} · CP {{ $snapshot?->origin['postal_code'] }}</strong></div><div><div class="z-eyebrow">DESTINO</div><strong>{{ $snapshot?->destination['settlement'] }}, {{ $snapshot?->destination['municipality'] }}, {{ $snapshot?->destination['state'] }} · CP {{ $snapshot?->destination['postal_code'] }}</strong></div></div><div style="margin-top:1rem"><a href="/app/cotizar">Cambiar ruta y volver a cotizar</a></div></section>
<form method="POST" action="/app/envio/nuevo" class="z-stack">@csrf<div class="journey-people">
@foreach(['sender'=>['REMITENTE','origen'],'recipient'=>['DESTINATARIO','destino']] as $key=>$section)@php($savedAddresses=$key==='sender'?$originAddresses:$destinationAddresses)@php($routeAddress=$key==='sender' ? ($snapshot?->origin ?? []) : ($snapshot?->destination ?? []))<section class="z-card z-form-section" data-person="{{ $key }}" data-route-postal="{{ $routeAddress['postal_code']??'' }}" data-route-settlement="{{ $routeAddress['settlement']??'' }}"><div class="z-form-section__head"><div class="z-eyebrow">{{ $section[0] }}</div><h2>Datos de {{ $section[1] }}</h2></div>@if($savedAddresses->isNotEmpty())<label class="z-field">Usar dirección guardada<select name="{{ $key }}_address_uuid" data-saved-address><option value="">Capturar una dirección nueva</option>@foreach($savedAddresses as $saved)@php($savedAddressJson=json_encode($saved->only(['contact_name','phone','email','street','exterior','interior','postal_code','settlement','municipality','state','references']), JSON_HEX_APOS | JSON_HEX_QUOT))<option value="{{ $saved->uuid }}" data-address="{{ $savedAddressJson }}">{{ $saved->alias }} · {{ $saved->settlement }}, CP {{ $saved->postal_code }}</option>@endforeach</select><span class="z-help" data-address-message></span></label>@endif<div class="z-form-grid"><label class="z-field">Nombre<input name="{{ $key }}[name]" data-address-field="contact_name" value="{{ old($key.'.name') }}" required></label><label class="z-field">Teléfono<input type="tel" name="{{ $key }}[phone]" data-address-field="phone" value="{{ old($key.'.phone') }}" required></label></div><label class="z-field">Correo <span class="z-muted">(opcional)</span><input type="email" name="{{ $key }}[email]" data-address-field="email" value="{{ old($key.'.email') }}"></label><div class="z-form-grid"><label class="z-field">Calle o avenida<input name="{{ $key }}[street]" data-address-field="street" value="{{ old($key.'.street') }}" required></label><label class="z-field">No. exterior<input name="{{ $key }}[exterior]" data-address-field="exterior" value="{{ old($key.'.exterior') }}" required></label></div><label class="z-field">No. interior <span class="z-muted">(opcional)</span><input name="{{ $key }}[interior]" data-address-field="interior" value="{{ old($key.'.interior') }}"></label><label class="z-field">Referencias<textarea name="{{ $key }}[references]" data-address-field="references">{{ old($key.'.references') }}</textarea></label><label class="z-choice"><input type="checkbox" name="save_{{ $key }}_address" value="1" data-save-address><span>Guardar esta dirección</span></label><label class="z-field" data-address-alias hidden>Alias de la dirección<input name="{{ $key }}_address_alias" value="{{ old($key.'_address_alias') }}" placeholder="Casa, oficina…"></label></section>@endforeach</div>
<section class="z-card"><label class="z-field">Referencia de tu envío<input name="reference" value="{{ old('reference') }}" maxlength="100"></label></section><div class="z-form-actions"><button class="z-btn">Continuar al resumen</button></div></form>
@endsection
@push('scripts')<script>(()=>{document.querySelectorAll('[data-person]').forEach(section=>{const select=section.querySelector('[data-saved-address]'),message=section.querySelector('[data-address-message]'),save=section.querySelector('[data-save-address]'),alias=section.querySelector('[data-address-alias]');select?.addEventListener('change',()=>{const option=select.selectedOptions[0];if(!option?.dataset.address){message.textContent='';return}const address=JSON.parse(option.dataset.address),compatible=address.postal_code===section.dataset.routePostal&&address.settlement===section.dataset.routeSettlement;if(!compatible){message.textContent='Esta dirección pertenece a otra ruta. Vuelve a cotizar para utilizarla.';select.value='';return}message.textContent=`${address.settlement}, ${address.municipality}, ${address.state} · CP ${address.postal_code}`;Object.entries(address).forEach(([key,value])=>{const field=section.querySelector(`[data-address-field="${key}"]`);if(field)field.value=value??''})});save?.addEventListener('change',()=>alias.hidden=!save.checked);if(save)alias.hidden=!save.checked})})()</script>@endpush
