@extends('network.layout')
@section('title',$ticket->public_reference)
@section('content')
<div class="hero"><div><div class="eyebrow">ZIGO PLATFORM</div><h1 class="title">{{ $ticket->public_reference }}</h1><p class="subtitle">{{ $ticket->subject }} · {{ $ticket->tenant?->name??'ZIGO interno' }}</p></div></div>
<section class="card"><p>{{ $ticket->description }}</p></section>
@if($ticket->tenant)<section class="card"><h2>Contexto comercial</h2><p>Tenant: <strong>{{ strtoupper($ticket->tenant->status) }}</strong> · Suscripción: <strong>{{ strtoupper($subscription?->status??'SIN SUSCRIPCIÓN') }}</strong></p><p>Vencimiento: {{ $subscription?->current_period_end?->format('d/m/Y')??'N/A' }} · Último pago: {{ $lastPayment?->status??'N/A' }} · Renovación: {{ $renewal?->status??'NO' }} · Payment: {{ $renewal?->payment_status??'N/A' }}</p>@if($renewal)<p>{{ $subscription?->current_period_end?->isPast()?'Saldo pendiente':'Importe renovación' }}: <strong>${{ number_format((float)$renewal->total_amount,2) }} {{ $renewal->currency }}</strong></p>@endif</section>@endif
<form class="card grid" method="POST" action="{{ route('network.support.update',$ticket->uuid) }}">@csrf @method('PATCH')<div class="field"><label>Asignar</label><select name="assigned_user_id"><option value="">Sin asignar</option>@foreach($staff as $u)<option value="{{ $u->id }}" @selected($ticket->assigned_user_id===$u->id)>{{ $u->name }}</option>@endforeach</select></div><div class="field"><label>Estado</label><select name="status">@foreach(\App\Domain\Support\Models\SupportTicket::STATUSES as $v)<option @selected($ticket->status===$v)>{{ $v }}</option>@endforeach</select></div><div class="field"><label>Prioridad</label><select name="priority">@foreach(\App\Domain\Support\Models\SupportTicket::PRIORITIES as $v)<option @selected($ticket->priority===$v)>{{ $v }}</option>@endforeach</select></div><button class="btn">Actualizar</button></form>
<section class="card"><h2>Conversación</h2>@foreach($ticket->messages as $m)<article class="alert {{ $m->visibility==='INTERNAL'?'error':'' }}"><strong>{{ $m->author->name }} · {{ $m->visibility==='INTERNAL'?'Nota interna':'Público' }}</strong><p>{{ $m->message }}</p></article>@endforeach @foreach($ticket->attachments as $a)<p><a href="{{ route('network.support.attachment',[$ticket->uuid,$a]) }}">Descargar {{ $a->original_name }}</a></p>@endforeach</section>
<form class="card" method="POST" enctype="multipart/form-data" action="{{ route('network.support.reply',$ticket->uuid) }}">@csrf<div class="field"><label>Respuesta</label><textarea name="message" required rows="5"></textarea></div><div class="field"><label>Visibilidad</label><select name="visibility"><option value="PUBLIC">Visible al solicitante</option><option value="INTERNAL">Nota interna ZIGO</option></select></div><input type="file" name="attachment" accept="image/jpeg,image/png,image/webp,application/pdf"><button class="btn">Responder</button></form>
@endsection
