<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'ZIGO Platform')</title>
    <style>
        :root{--blue:#3867f5;--blue-dark:#1d4ed8;--orange:#f97316;--ink:#0b1734;--muted:#60708a;--line:#dfe7f3;--soft:#f5f8ff;--ok:#147d4f}
        *{box-sizing:border-box}body{margin:0;font-family:Inter,Arial,sans-serif;color:var(--ink);background:linear-gradient(180deg,#fff 0,#f5f8ff 100%);line-height:1.5}a{color:inherit}
        .nav{background:rgba(255,255,255,.96);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:20}.nav-inner{max-width:1180px;margin:auto;padding:15px 24px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-size:22px;font-weight:900;text-decoration:none;color:var(--blue)}.nav-links{display:flex;gap:18px;align-items:center}.nav-links a{text-decoration:none;font-weight:800}.home-link{color:var(--muted);font-size:14px}
        main{max-width:1180px;margin:auto;padding:48px 24px 80px}.hero{padding:74px 0;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(300px,.8fr);gap:54px;align-items:center}.hero-copy{max-width:750px}.hero-visual{min-height:340px;border-radius:32px;background:linear-gradient(145deg,#132b66,#3867f5);padding:28px;box-shadow:0 28px 70px rgba(49,92,245,.24);display:grid;gap:14px;align-content:center}.visual-bar{height:14px;border-radius:20px;background:rgba(255,255,255,.22)}.visual-bar:nth-child(2){width:72%;background:#fff}.visual-bar:nth-child(3){width:88%;background:#facc15}.visual-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.visual-tile{height:90px;border-radius:18px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.18)}.eyebrow{color:var(--blue);font-weight:900;letter-spacing:.08em;text-transform:uppercase}.hero h1{font-size:clamp(42px,6vw,68px);line-height:1.03;margin:12px 0 20px;letter-spacing:-.035em}.lead{font-size:21px;color:var(--muted);max-width:680px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}
        .btn{display:inline-block;border:0;border-radius:12px;padding:13px 20px;font-weight:800;text-decoration:none;cursor:pointer;font-size:16px}.btn-primary{background:var(--blue);color:#fff}.btn-secondary{background:#fff;color:var(--blue);border:1px solid var(--line)}
        .card{background:#fff;border:1px solid var(--line);border-radius:20px;padding:26px;box-shadow:0 12px 35px rgba(27,56,112,.07)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px}.price{font-size:30px;font-weight:900}.muted{color:var(--muted)}
        .section{padding:46px 0}.section-heading{max-width:720px;margin-bottom:28px}.section-heading h2{font-size:clamp(30px,4vw,44px);margin:7px 0}.capability-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:14px}.capability{background:#fff;border:1px solid var(--line);border-radius:18px;padding:20px;min-height:132px}.capability strong{display:block;margin-bottom:8px}.journey{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;counter-reset:journey}.journey-step{background:#10245a;color:#fff;border-radius:18px;padding:22px;min-height:160px;counter-increment:journey}.journey-step:before{content:counter(journey);display:flex;width:34px;height:34px;border-radius:50%;background:#facc15;color:#10213b;align-items:center;justify-content:center;font-weight:900;margin-bottom:18px}.cta-band{background:linear-gradient(135deg,#10245a,#3867f5);color:#fff;border-radius:30px;padding:42px;display:flex;align-items:center;justify-content:space-between;gap:24px}.cta-band h2{font-size:36px;margin:0 0 8px}.cta-band .muted{color:#dce6ff}
        .billing-toggle{display:flex;justify-content:center;gap:6px;margin:24px auto 32px;background:#eaf0ff;padding:6px;border-radius:14px;width:max-content}.billing-toggle button{border:0;background:transparent;padding:10px 20px;border-radius:10px;font-weight:900;color:var(--muted);cursor:pointer}.billing-toggle button.active{background:#fff;color:var(--blue);box-shadow:0 6px 18px rgba(20,45,90,.1)}.pricing-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;align-items:stretch}.pricing-card{display:flex;flex-direction:column}.pricing-card .btn{margin-top:auto;text-align:center}.feature-list{list-style:none;padding:0;margin:18px 0 26px}.feature-list li{padding:7px 0;border-bottom:1px solid #edf1f8}.feature-list li:before{content:'✓';color:var(--ok);font-weight:900;margin-right:8px}.empty-state{text-align:center;max-width:680px;margin:60px auto;padding:46px}
        .wizard{max-width:800px;margin:auto}.steps{display:flex;gap:8px;margin-bottom:22px}.step{height:7px;flex:1;background:#dbe3f2;border-radius:9px}.step.active{background:var(--blue)}h1{line-height:1.15}.field{margin:17px 0}.field label,.label{display:block;font-weight:800;margin-bottom:6px}.field input,.field select{width:100%;padding:13px;border:1px solid #cbd6e7;border-radius:11px;font:inherit;background:#fff}.choice{display:block;border:1px solid var(--line);border-radius:14px;padding:16px;margin:10px 0;background:#fff}.choice:has(input:checked){border-color:var(--blue);box-shadow:0 0 0 2px rgba(56,103,245,.1)}.choice input{margin-right:8px}.errors{background:#fff0f0;color:#9c2020;padding:14px;border-radius:10px}.summary{display:grid;grid-template-columns:1fr 1fr;gap:12px}.summary div{padding:11px 0;border-bottom:1px solid var(--line)}.total{font-size:24px;font-weight:900;color:var(--blue)}
        @media(max-width:900px){.hero{grid-template-columns:1fr}.hero-visual{min-height:270px}.capability-grid{grid-template-columns:repeat(2,1fr)}.journey{grid-template-columns:1fr 1fr}.pricing-grid{grid-template-columns:1fr}.cta-band{align-items:flex-start;flex-direction:column}}
        @media(max-width:640px){.nav-inner,main{padding-left:16px;padding-right:16px}.nav-inner{align-items:flex-start;flex-direction:column}.nav-links{width:100%;justify-content:space-between;gap:8px;font-size:13px;flex-wrap:wrap}.hero{padding:45px 0}.summary{grid-template-columns:1fr}.card{padding:20px}.capability-grid,.journey{grid-template-columns:1fr}.cta-band{padding:28px}.cta-band h2{font-size:30px}}
    </style>
</head>
<body>
<header class="nav"><div class="nav-inner"><a class="brand" href="{{ route('zigo-platform.landing') }}">ZIGO Platform</a><nav class="nav-links"><a href="{{ route('zigo-platform.pricing') }}">Precios</a><a class="btn btn-primary" href="{{ route('zigo-platform.start') }}">Comenzar</a><a class="home-link" href="{{ url('/') }}">Volver a ZIGO</a></nav></div></header>
<main>@yield('content')</main>
</body>
</html>
