<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'ZIGO Platform')</title>
    <style>
        :root{--blue:#3867f5;--blue-dark:#173eae;--navy:#071a3d;--orange:#f97316;--yellow:#facc15;--ink:#0b1734;--muted:#5d6c84;--line:#dfe7f3;--soft:#f5f8ff;--ok:#147d4f}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Inter,"Segoe UI",Arial,sans-serif;color:var(--ink);background:#fff;line-height:1.5}a{color:inherit}.shell{width:min(100% - 48px,1220px);margin-inline:auto}
        .nav{background:rgba(255,255,255,.94);border-bottom:1px solid rgba(223,231,243,.9);position:sticky;top:0;z-index:20;backdrop-filter:blur(14px)}.nav-inner{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:11px;font-size:22px;font-weight:950;text-decoration:none;color:var(--navy);letter-spacing:-.02em}.brand-mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(145deg,var(--blue),var(--blue-dark));display:grid;place-items:center;color:#fff;box-shadow:0 10px 24px rgba(56,103,245,.24)}.brand em{font-style:normal;color:var(--orange)}.nav-links{display:flex;gap:22px;align-items:center}.nav-links a{text-decoration:none;font-weight:800;font-size:14px}.nav-links>a:not(.btn):hover{color:var(--blue)}.home-link{color:var(--muted)!important}
        main{overflow:hidden}.page-main{width:min(100% - 48px,1180px);margin:auto;padding:42px 0 80px}.hero{padding:88px 0 82px;display:grid;grid-template-columns:minmax(0,1.05fr) minmax(420px,.95fr);gap:68px;align-items:center}.hero-copy{max-width:720px}.eyebrow{color:var(--blue);font-size:12px;font-weight:950;letter-spacing:.14em;text-transform:uppercase}.hero h1{font-size:clamp(46px,6vw,76px);line-height:1.01;margin:14px 0 22px;letter-spacing:-.05em}.hero h1 strong{color:var(--orange)}.lead{font-size:clamp(18px,2vw,21px);color:var(--muted);max-width:690px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:30px}.btn{display:inline-flex;align-items:center;justify-content:center;min-height:48px;border:0;border-radius:14px;padding:13px 22px;font-weight:900;text-decoration:none;cursor:pointer;font-size:15px}.btn-primary{background:var(--blue);color:#fff;box-shadow:0 14px 30px rgba(56,103,245,.24)}.btn-primary:hover{background:var(--blue-dark)}.btn-secondary{background:#fff;color:var(--blue);border:1px solid var(--line);box-shadow:0 10px 26px rgba(15,35,75,.07)}
        .platform-preview{min-height:470px;border-radius:32px;background:linear-gradient(145deg,#0b2358,#3867f5);padding:24px;box-shadow:0 34px 80px rgba(24,63,158,.28);position:relative;overflow:hidden}.platform-preview:before{content:"";position:absolute;width:260px;height:260px;border-radius:50%;background:rgba(250,204,21,.18);right:-90px;top:-100px}.preview-window{position:relative;height:100%;min-height:422px;border-radius:22px;background:#f7f9fd;display:grid;grid-template-columns:88px 1fr;overflow:hidden;box-shadow:0 18px 45px rgba(0,0,0,.18)}.preview-side{background:#10245a;padding:20px 14px;display:grid;align-content:start;gap:13px}.preview-logo{height:30px;border-radius:9px;background:var(--orange);margin-bottom:12px}.preview-link{height:10px;border-radius:10px;background:rgba(255,255,255,.28)}.preview-link.is-active{background:#fff}.preview-content{padding:24px;display:grid;align-content:start;gap:18px}.preview-head{display:flex;justify-content:space-between;align-items:center}.preview-title{width:46%;height:18px;border-radius:10px;background:#17305e}.preview-avatar{width:34px;height:34px;border-radius:50%;background:#dce6ff}.preview-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.preview-metric{height:72px;border-radius:14px;background:#fff;border:1px solid #e4eaf4;box-shadow:0 8px 20px rgba(15,35,75,.06)}.preview-quote{height:150px;border-radius:18px;background:linear-gradient(135deg,var(--blue),var(--blue-dark));padding:18px;display:grid;grid-template-columns:1fr 1fr;gap:10px}.preview-field{height:42px;border-radius:10px;background:#fff}.preview-table{height:92px;border-radius:15px;background:#fff;border:1px solid #e4eaf4}
        .trust-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--line);border:1px solid var(--line);border-radius:20px;overflow:hidden;box-shadow:0 14px 35px rgba(23,52,104,.06)}.trust-item{background:#fff;padding:22px}.trust-item strong{display:block;margin-bottom:4px}.trust-item span{color:var(--muted);font-size:14px}.section{padding:76px 0}.section-soft{background:var(--soft)}.section-dark{background:var(--navy);color:#fff}.section-inner{width:min(100% - 48px,1180px);margin:auto}.section-heading{max-width:760px;margin-bottom:34px}.section-heading h2{font-size:clamp(34px,4vw,50px);line-height:1.08;margin:8px 0 14px;letter-spacing:-.035em}.section-heading p{color:var(--muted);font-size:18px}.section-dark .section-heading p{color:#c9d5ed}.value-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.value-card,.card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:26px;box-shadow:0 14px 38px rgba(27,56,112,.07)}.value-card:nth-child(2){transform:translateY(18px)}.value-icon{width:44px;height:44px;border-radius:13px;background:#eaf0ff;color:var(--blue);display:grid;place-items:center;font-weight:950;margin-bottom:20px}.value-card h3{font-size:21px;margin:0 0 9px}.value-card p{color:var(--muted);margin:0}.capability-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.capability{background:#fff;border:1px solid var(--line);border-radius:18px;padding:21px;min-height:150px;box-shadow:0 10px 26px rgba(15,35,75,.05)}.capability strong{display:block;margin:13px 0 8px}.capability-number{color:var(--orange);font-weight:950}.muted{color:var(--muted)}
        .journey{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;counter-reset:journey}.journey-step{background:rgba(255,255,255,.08);border:1px solid rgba(255,255,255,.14);border-radius:19px;padding:22px;min-height:178px;counter-increment:journey}.journey-step:before{content:counter(journey);display:flex;width:38px;height:38px;border-radius:50%;background:var(--yellow);color:#10213b;align-items:center;justify-content:center;font-weight:950;margin-bottom:22px}.journey-step strong{font-size:17px}.journey-step p{color:#c9d5ed;font-size:14px;margin:9px 0 0}.pricing-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;align-items:stretch}.pricing-card{display:flex;flex-direction:column;position:relative;overflow:hidden}.pricing-card:before{content:"";height:5px;background:linear-gradient(90deg,var(--blue),var(--orange));position:absolute;inset:0 0 auto}.pricing-card h3{font-size:24px;margin:10px 0}.pricing-card .btn{margin-top:auto}.price{font-size:30px;font-weight:950}.feature-list{list-style:none;padding:0;margin:18px 0 26px}.feature-list li{padding:7px 0;border-bottom:1px solid #edf1f8}.feature-list li:before{content:'✓';color:var(--ok);font-weight:950;margin-right:8px}.empty-state{text-align:center;max-width:680px;margin:40px auto;padding:46px}.cta-band{background:linear-gradient(135deg,#10245a,#3867f5);color:#fff;border-radius:30px;padding:46px;display:flex;align-items:center;justify-content:space-between;gap:24px;box-shadow:0 26px 60px rgba(24,63,158,.22)}.cta-band h2{font-size:clamp(30px,4vw,42px);margin:0 0 8px}.cta-band .muted{color:#dce6ff}
        .site-footer{background:#050d20;color:#fff;padding:46px 0}.footer-grid{display:grid;grid-template-columns:1.7fr 1fr 1fr;gap:34px}.site-footer p,.site-footer a{color:#aebbd1}.site-footer a{display:block;text-decoration:none;margin:7px 0}.site-footer .brand{color:#fff;margin-bottom:12px}.billing-toggle{display:flex;justify-content:center;gap:6px;margin:24px auto 32px;background:#eaf0ff;padding:6px;border-radius:14px;width:max-content}.billing-toggle button{border:0;background:transparent;padding:10px 20px;border-radius:10px;font-weight:900;color:var(--muted);cursor:pointer}.billing-toggle button.active{background:#fff;color:var(--blue)}
        .wizard{max-width:800px;margin:auto}.steps{display:flex;gap:8px;margin-bottom:22px}.step{height:7px;flex:1;background:#dbe3f2;border-radius:9px}.step.active{background:var(--blue)}h1{line-height:1.15}.field{margin:17px 0}.field label,.label{display:block;font-weight:800;margin-bottom:6px}.field input,.field select{width:100%;padding:13px;border:1px solid #cbd6e7;border-radius:11px;font:inherit;background:#fff}.choice{display:block;border:1px solid var(--line);border-radius:14px;padding:16px;margin:10px 0;background:#fff}.choice:has(input:checked){border-color:var(--blue);box-shadow:0 0 0 2px rgba(56,103,245,.1)}.choice input{margin-right:8px}.errors{background:#fff0f0;color:#9c2020;padding:14px;border-radius:10px}.summary{display:grid;grid-template-columns:1fr 1fr;gap:12px}.summary div{padding:11px 0;border-bottom:1px solid var(--line)}.total{font-size:24px;font-weight:900;color:var(--blue)}
        @media(max-width:980px){.hero{grid-template-columns:1fr}.platform-preview{min-height:400px}.preview-window{min-height:350px}.trust-strip,.capability-grid{grid-template-columns:repeat(2,1fr)}.value-grid,.pricing-grid{grid-template-columns:1fr}.value-card:nth-child(2){transform:none}.journey{grid-template-columns:repeat(2,1fr)}.cta-band{align-items:flex-start;flex-direction:column}}
        @media(max-width:720px){.shell,.section-inner,.page-main{width:min(100% - 32px,1180px)}.nav-inner{min-height:68px}.nav-links a:not(.btn):not(.home-link){display:none}.home-link{font-size:12px}.nav-links{gap:8px}.nav-links .btn{min-height:40px;padding:9px 13px}.hero{padding:54px 0;gap:38px}.hero h1{font-size:42px}.platform-preview{min-height:320px;padding:12px}.preview-window{min-height:296px;grid-template-columns:58px 1fr}.preview-content{padding:15px}.preview-metrics{grid-template-columns:1fr}.preview-metric:nth-child(n+2){display:none}.preview-quote{height:120px}.trust-strip,.capability-grid,.journey,.footer-grid{grid-template-columns:1fr}.section{padding:55px 0}.cta-band{padding:28px}.summary{grid-template-columns:1fr}.card{padding:20px}}
    </style>
</head>
<body>
<header class="nav"><div class="shell nav-inner"><a class="brand" href="{{ route('zigo-platform.landing') }}"><span class="brand-mark">Z</span><span>ZIGO <em>Platform</em></span></a><nav class="nav-links" aria-label="Navegación ZIGO Platform">@if(request()->routeIs('zigo-platform.landing'))<a href="#capacidades">Capacidades</a><a href="#planes">Planes</a><a href="#como-funciona">Cómo funciona</a>@else<a href="{{ route('zigo-platform.landing') }}#capacidades">Capacidades</a><a href="{{ route('zigo-platform.pricing') }}">Planes</a>@endif<a class="btn btn-primary" href="{{ route('zigo-platform.start') }}">Comenzar</a><a class="home-link" href="{{ url('/') }}">Volver a ZIGO</a></nav></div></header>
<main class="@unless(request()->routeIs('zigo-platform.landing')) page-main @endunless">@yield('content')</main>
<footer class="site-footer"><div class="shell footer-grid"><div><a class="brand" href="{{ route('zigo-platform.landing') }}"><span class="brand-mark">Z</span><span>ZIGO <em>Platform</em></span></a><p>Tecnología ZIGO para operar una plataforma de envíos bajo tu marca.</p></div><div><strong>Plataforma</strong><a href="{{ route('zigo-platform.landing') }}#capacidades">Capacidades</a><a href="{{ route('zigo-platform.pricing') }}">Planes</a><a href="{{ route('zigo-platform.start') }}">Comenzar</a></div><div><strong>ZIGO</strong><a href="{{ url('/') }}">Volver a ZIGO</a></div></div></footer>
</body></html>
