@extends('network.layout') @section('title','Construir '.$plan->name) @section('content')
<div class="eyebrow">CONSTRUYE TU ZIGO</div><div class="title">Construir plan</div><div class="subtitle">{{ $plan->code }} · Configuración comercial, no entitlements runtime.</div>
<form method="POST" action="{{ route('network.plans.update',$plan) }}">@csrf @method('PUT')
<div class="card"><h2>Datos comerciales</h2><div class="grid"><div class="field"><label>Nombre</label><input name="name" value="{{ old('name',$plan->name) }}" required></div><div class="field"><label>Estado</label><select name="status">@foreach(\App\Domain\Network\Catalog\Models\Plan::STATUSES as $status)<option value="{{ $status }}" @selected(old('status',$plan->status)===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="field"><label>Precio mensual</label><input name="monthly_price" type="number" min="0" step="0.01" value="{{ old('monthly_price',$plan->monthly_price) }}"></div><div class="field"><label>Precio anual</label><input name="annual_price" type="number" min="0" step="0.01" value="{{ old('annual_price',$plan->annual_price) }}"></div><div class="field"><label>Moneda</label><input name="currency" maxlength="3" value="{{ old('currency',$plan->currency) }}" required></div><div class="field"><label>Operaciones incluidas</label><input name="included_operations" type="number" min="0" value="{{ old('included_operations',$plan->included_operations) }}"></div></div><div class="field"><label>Descripción</label><textarea name="description" rows="3">{{ old('description',$plan->description) }}</textarea></div></div>
@php($configured=$plan->modules->keyBy('id'))
<div class="card plan-builder"><h2>Construir plan</h2><p class="muted">Selecciona capacidades y límites comerciales. AI técnico no forma parte de este catálogo.</p>@php($i=0) @foreach($moduleGroups as $label=>$modules)<h3 class="section-title">{{ $label }}</h3><div class="module-picker">@foreach($modules as $module) @php($pivot=$configured->get($module->id)?->pivot) @php($included=(bool)old("modules.$i.included",$pivot?->is_included??false))<article class="module-option {{ $included?'included':'' }}"><input type="hidden" name="modules[{{ $i }}][id]" value="{{ $module->id }}"><input type="hidden" name="modules[{{ $i }}][included]" value="0"><label class="module-toggle" for="module-{{ $module->id }}"><input id="module-{{ $module->id }}" type="checkbox" name="modules[{{ $i }}][included]" value="1" @checked($included)><span class="checkmark" aria-hidden="true">✓</span><span class="module-copy"><b>{{ $module->name }}</b><small>{{ $module->description ?: $module->code.' · '.strtoupper($module->type) }}</small></span><span class="include-state">{{ $included?'INCLUIDO':'NO INCLUIDO' }}</span></label><label class="limit-control">Límite <input name="modules[{{ $i }}][limit_value]" type="number" min="0" placeholder="Sin límite" value="{{ old("modules.$i.limit_value",$pivot?->limit_value) }}"></label></article>@php($i++) @endforeach</div>@endforeach</div>
<button class="btn" type="submit">GUARDAR PLAN Y MÓDULOS</button> <a class="btn disabled" href="{{ route('network.plans.show',$plan) }}">Cancelar</a></form>
@endsection
@push('styles')<style>.plan-builder{padding:18px}.plan-builder .section-title{margin:20px 0 8px}.module-picker{display:grid;grid-template-columns:repeat(auto-fill,minmax(215px,1fr));gap:9px}.module-option{border:1px solid #d9e2ec;border-radius:11px;padding:10px;background:#f8fafc;transition:.15s}.module-option.included{border-color:#4f8bd8;background:#eef6ff;box-shadow:inset 0 0 0 1px #4f8bd8}.module-toggle{display:grid;grid-template-columns:26px minmax(0,1fr);gap:8px;align-items:center;cursor:pointer;position:relative}.module-toggle input{position:absolute;opacity:0}.checkmark{display:grid;place-items:center;width:25px;height:25px;border:2px solid #94a3b8;border-radius:7px;color:transparent;font-weight:900}.module-toggle input:focus-visible+.checkmark{outline:3px solid #bfdbfe}.module-toggle input:checked+.checkmark{background:#2563eb;border-color:#2563eb;color:#fff}.module-copy b,.module-copy small{display:block}.module-copy small{color:#64748b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}.include-state{grid-column:2;font-size:9px;font-weight:900;color:#64748b;letter-spacing:.06em}.included .include-state{color:#1d4ed8}.limit-control{display:flex;align-items:center;justify-content:flex-end;gap:7px;margin-top:8px;font-size:11px;font-weight:800;color:#64748b}.limit-control input{width:105px;padding:7px}.plan-builder .module-option{min-height:112px}@media(min-width:1280px){.module-picker{grid-template-columns:repeat(4,minmax(0,1fr))}}@media(max-width:650px){.module-picker{grid-template-columns:1fr}}</style>@endpush
@push('scripts')<script>document.querySelectorAll('.module-toggle input').forEach(box=>box.addEventListener('change',()=>{const tile=box.closest('.module-option'),state=tile.querySelector('.include-state');tile.classList.toggle('included',box.checked);state.textContent=box.checked?'INCLUIDO':'NO INCLUIDO'}));</script>@endpush
