@extends('network.layout')
@section('title','Planes y precios - ZIGO Network')
@section('content')
<div class="eyebrow">CATÁLOGO COMERCIAL</div><div class="title">Planes y precios</div>
<nav class="catalog-tabs"><a class="active" href="{{ route('network.plans.index') }}">Planes</a><a href="{{ route('network.commercial-products.index') }}">Precios</a><a href="{{ route('network.modules.index') }}">Módulos</a></nav>
<div class="page-actions"><a class="btn" href="{{ route('network.plans.create') }}">Crear plan</a></div>
<div class="card table-wrap"><table><thead><tr><th>Nombre</th><th>Estado</th><th>Mensual</th><th>Anual</th><th>Capacidad</th><th>Módulos</th><th>Visibilidad</th><th>Acciones</th></tr></thead><tbody>@forelse($plans as $plan) @php($monthly=$plan->commercialOffers->firstWhere('billing_type','MONTHLY')) @php($annual=$plan->commercialOffers->firstWhere('billing_type','ANNUAL'))<tr><td><strong>{{ $plan->name }}</strong><br><small class="muted">{{ $plan->code }}</small></td><td><span class="badge badge-{{ $plan->status }}">{{ strtoupper($plan->status) }}</span></td><td>{{ $monthly?'$'.number_format((float)$monthly->price,2).' '.$monthly->currency:'—' }}</td><td>{{ $annual?'$'.number_format((float)$annual->price,2).' '.$annual->currency:'—' }}</td><td>{{ $plan->included_operations ? number_format($plan->included_operations).' envíos':'—' }}</td><td>{{ $plan->included_modules_count }}</td><td>{{ $plan->commercialOffers->where('is_public',true)->count() }} públicas</td><td><a class="btn btn-secondary" href="{{ route('network.plans.show',$plan) }}">Ver</a> <a class="btn" href="{{ route('network.plans.edit',$plan) }}">Editar</a></td></tr>@empty<tr><td colspan="8">No hay planes registrados.</td></tr>@endforelse</tbody></table>{{ $plans->links() }}</div>
@endsection
@push('styles')<style>.catalog-tabs{display:flex;gap:8px;margin:15px 0;border-bottom:1px solid #dbe4ef;padding-bottom:10px}.catalog-tabs a{padding:8px 12px;border-radius:8px;text-decoration:none;color:#475569;font-weight:800}.catalog-tabs a.active{background:#dbeafe;color:#1d4ed8}.page-actions{margin:12px 0}.btn-secondary{background:#e2e8f0;color:#334155}</style>@endpush
