@php
    $branding = $tenant->branding;
    $brand = $branding?->brand_name ?: $tenant->name;
    $safeColor = fn ($value, $fallback) => is_string($value) && preg_match('/^#[0-9A-Fa-f]{6}$/', $value) ? $value : $fallback;
    $logoUrl = $branding?->logo_path && Storage::disk('public')->exists($branding->logo_path) ? route('tenant.branding.logo', [], false) : null;
    $heroUrl = $branding?->hero_image_path && Storage::disk('public')->exists($branding->hero_image_path) ? route('tenant.branding.hero', [], false) : null;
    $faviconUrl = $branding?->favicon_path && Storage::disk('public')->exists($branding->favicon_path) ? route('tenant.branding.favicon', [], false) : null;
    $supportUrl = $branding?->support_email ? 'mailto:'.$branding->support_email : '#faq';
@endphp
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $brand }} | Cotiza y genera tus guías</title>
    @if($faviconUrl)<link rel="icon" href="{{ $faviconUrl }}">@endif
    <link rel="stylesheet" href="{{ asset('css/b2c-responsive.css') }}">
    <style>
        :root{--zigo-blue:{{ $safeColor($branding?->primary_color,'#3867f5') }};--zigo-blue-dark:{{ $safeColor($branding?->secondary_color,'#1d4ed8') }};--zigo-orange:{{ $safeColor($branding?->accent_color,'#f97316') }};--zigo-yellow:#facc15;--zigo-text:#111827;--zigo-muted:#52607a;--zigo-soft:#f7f9ff}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Arial,sans-serif;color:var(--zigo-text);background:#fff}a{text-decoration:none}.page-wrap{min-height:100vh;background:linear-gradient(180deg,#fff 0%,#fff 62%,#f7f9ff 100%)}
        .top-header{background:#fff;border-bottom:1px solid #edf0f7}.nav{max-width:1220px;margin:0 auto;padding:8px 24px;display:flex;justify-content:space-between;align-items:center;gap:20px;flex-wrap:nowrap}.brand{display:flex;flex-direction:column;align-items:flex-start;justify-content:center;text-decoration:none;min-width:330px}.brand-logo-frame{width:330px;max-width:100%;min-height:72px;display:flex;align-items:center;justify-content:flex-start}.brand-logo{width:310px;max-width:100%;max-height:68px;object-fit:contain;display:block;filter:drop-shadow(0 10px 20px color-mix(in srgb,var(--zigo-blue) 20%,transparent));animation:zigoEnter .8s ease-out;transition:transform .35s ease,filter .35s ease}.brand:hover .brand-logo{transform:translateX(8px) scale(1.04)}.brand-name{font-size:28px;font-weight:900;color:var(--zigo-blue-dark)}.brand-tagline{margin-top:-5px;font-size:12px;letter-spacing:3px;text-transform:uppercase;color:var(--zigo-blue-dark);font-weight:900;line-height:1.2;white-space:nowrap}@keyframes zigoEnter{from{opacity:0;transform:translateX(-28px)}to{opacity:1;transform:translateX(0)}}
        .main-nav{display:flex;align-items:center;justify-content:flex-end;gap:16px;flex-wrap:nowrap;white-space:nowrap}.main-nav a{color:#08152f;font-weight:900;font-size:16px}.main-nav a:hover{color:var(--zigo-blue)}.nav-login{padding:14px 22px;border-radius:14px;background:#fff;color:var(--zigo-blue)!important;box-shadow:0 14px 32px rgba(17,24,39,.10)}.nav-register,.nav-account{background:var(--zigo-blue);color:#fff!important;padding:14px 24px;border-radius:14px;font-weight:900;box-shadow:0 14px 32px color-mix(in srgb,var(--zigo-blue) 28%,transparent)}.nav-register:hover,.nav-account:hover{background:var(--zigo-blue-dark);color:#fff!important}.mobile-nav-toggle{display:none}
        .quote-box{max-width:1220px;margin:0 auto;padding:34px 24px}.quote-card{width:100%;padding:18px 20px 20px;background:var(--zigo-blue);color:#fff;border-radius:18px;box-shadow:0 18px 42px color-mix(in srgb,var(--zigo-blue) 25%,transparent)}.quote-title{text-align:center;font-size:22px;font-weight:900;margin:0 0 14px;color:#fff}.quote-form{display:grid;grid-template-columns:1.25fr 1.25fr 1.05fr .8fr 1.45fr 1.1fr;gap:16px;align-items:end}.field label{display:block;font-size:15px;margin-bottom:7px;font-weight:800;color:#fff}.field input,.field select{width:100%;height:46px;border-radius:13px;border:1px solid rgba(255,255,255,.25);padding:0 15px;background:#fff;color:#111827;font-size:15px;outline:none}.field input:focus,.field select:focus{border-color:var(--zigo-yellow);box-shadow:0 0 0 3px rgba(250,204,21,.20)}.btn-yellow{height:46px;border:0;border-radius:13px;background:var(--zigo-orange);color:#fff;font-weight:900;cursor:pointer;font-size:15px;box-shadow:0 12px 24px color-mix(in srgb,var(--zigo-orange) 24%,transparent)}.btn-yellow:hover{filter:brightness(.92)}.box-dimensions{display:grid;grid-template-columns:repeat(3,1fr);overflow:hidden;border-radius:13px;background:#fff;height:46px}.box-dimensions input{height:46px!important;border-radius:0!important;border:0!important;border-right:1px solid #d1d5db!important;text-align:center;padding:0 8px!important}.box-dimensions input:last-child{border-right:0!important}.field-dimensions[hidden]{display:none!important}
        .address-details{display:none;grid-column:1/-1;grid-template-columns:1fr 1fr;gap:16px;padding-top:14px;border-top:1px solid rgba(255,255,255,.25)}.address-details.is-visible{display:grid}.address-side{display:grid;grid-template-columns:1fr 1fr;gap:12px}.address-location{grid-column:1/-1;color:#fff;font-size:12px}.landing-alert{grid-column:1/-1;background:#fff7ed;border:1px solid #fdba74;color:#9a3412;padding:14px 18px;border-radius:14px;font-weight:900;text-align:center}.landing-results{margin:25px auto 0;background:#fff;color:#111827;border-radius:20px;padding:24px;box-shadow:0 12px 30px rgba(0,0,0,.12)}.landing-results h2{margin-top:0;text-align:center}.landing-quote-option{display:grid;grid-template-columns:minmax(180px,.9fr) minmax(180px,1fr) minmax(130px,.55fr) auto;gap:18px;align-items:center;border:1px solid #e5e7eb;border-radius:14px;padding:18px;margin-top:12px}.landing-quote-service strong{font-size:18px}.landing-quote-sla{color:#64748b;margin-top:5px}.landing-quote-price{font-size:22px;font-weight:900}.landing-quote-select{background:var(--zigo-orange);color:#fff;border:0;border-radius:10px;padding:12px 22px;font-weight:900;cursor:pointer}
        .hero{max-width:1220px;margin:0 auto;padding:28px 24px 76px;display:grid;grid-template-columns:1fr 1fr;gap:58px;align-items:center;position:relative}.hero::before{content:"";position:absolute;left:24px;right:24px;bottom:0;height:160px;background:linear-gradient(90deg,color-mix(in srgb,var(--zigo-blue) 6%,transparent),color-mix(in srgb,var(--zigo-orange) 4%,transparent));border-radius:32px 32px 0 0}.hero-copy,.hero-visual{position:relative;z-index:1}.hero-kicker{display:flex;align-items:center;gap:10px;color:#08152f;font-size:18px;font-weight:900;margin:0 0 18px}.hero-kicker span{width:28px;height:28px;display:inline-flex;align-items:center;justify-content:center;border:2px solid #08152f;border-radius:999px;color:var(--zigo-blue);font-size:16px}.hero h1{font-size:56px;line-height:1.1;margin:0 0 20px;color:#0f172a;letter-spacing:-1.8px}.hero h1 strong{color:var(--zigo-orange)}.hero p{font-size:19px;line-height:1.75;color:var(--zigo-muted);margin:0 0 28px;max-width:610px}.hero-actions{display:flex;flex-wrap:wrap;gap:14px;align-items:center}.hero-primary,.hero-secondary{display:inline-block;padding:15px 24px;border-radius:14px;font-weight:900}.hero-primary{background:var(--zigo-orange);color:#fff;box-shadow:0 16px 34px color-mix(in srgb,var(--zigo-orange) 28%,transparent)}.hero-secondary{color:var(--zigo-blue);background:#fff;box-shadow:0 12px 28px rgba(17,24,39,.08)}.hero-visual{min-height:390px;display:flex;align-items:center;justify-content:center}.hero-card{width:100%;max-width:520px;min-height:340px;border-radius:32px;background:radial-gradient(circle at 15% 20%,rgba(255,255,255,.95),rgba(255,255,255,.65) 28%,color-mix(in srgb,var(--zigo-blue) 8%,transparent) 62%,color-mix(in srgb,var(--zigo-orange) 8%,transparent));box-shadow:0 30px 70px rgba(15,23,42,.15);border:1px solid #edf0f7;display:flex;align-items:center;justify-content:center;overflow:hidden;position:relative}.hero-image-card{padding:0}.hero-image{width:100%;height:100%;min-height:340px;object-fit:cover;display:block;border-radius:28px}.hero-placeholder{font-size:36px;font-weight:900;color:var(--zigo-blue-dark);padding:30px;text-align:center}
        .business-types{max-width:1120px;margin:88px auto 72px;padding:0 24px}.section-title{text-align:center;margin-bottom:30px}.section-title h2{color:var(--zigo-blue)!important;font-size:40px;font-weight:900;text-transform:uppercase;letter-spacing:4px;margin:0 0 14px}.section-title h3{color:#111827;font-size:38px;font-weight:900;margin:0 0 14px}.section-title p{max-width:760px;margin:0 auto;color:#64748b;font-size:17px;line-height:1.5}.business-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.business-card{background:#fff;border-radius:22px;padding:28px;box-shadow:0 14px 34px rgba(15,23,42,.08);border:1px solid #e5e7eb}.business-card h3{font-size:22px;color:#111827;margin:0 0 10px;font-weight:900}.business-card p{color:#64748b;line-height:1.45;margin:0}.business-step{display:block;color:var(--zigo-blue);font-size:13px;font-weight:900;letter-spacing:2px;margin-bottom:12px}
        .solutions-section{background:#fff;padding:70px 24px}.section-container{max-width:1220px;margin:0 auto}.solutions-section h2{text-align:center;font-size:38px;line-height:1.15;margin:0 0 36px;color:#0f172a;font-weight:900}.solutions-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.solution-card{background:#fff;border:1px solid #e8edf7;border-radius:24px;padding:30px;min-height:210px;box-shadow:0 18px 45px rgba(15,23,42,.06);transition:transform .2s ease,box-shadow .2s ease}.solution-card:hover{transform:translateY(-4px);box-shadow:0 24px 55px rgba(15,23,42,.10)}.solution-card h3{margin:0 0 12px;font-size:22px;color:var(--zigo-blue);font-weight:900}.solution-card p{margin:0 0 18px;color:#334155;line-height:1.45;font-size:16px}.solution-card a,.solution-card span{color:var(--zigo-blue);font-weight:900}
        .faq-section{padding:80px 24px;background:var(--zigo-soft)}.faq-section h2{text-align:center;font-size:38px;font-weight:900;margin:0 0 36px;color:#111827}.faq-grid{max-width:1100px;margin:0 auto;display:grid;grid-template-columns:repeat(2,1fr);gap:20px}.faq-item{background:#fff;border-radius:18px;padding:24px;box-shadow:0 12px 30px rgba(15,23,42,.08)}.faq-item h3{margin:0 0 10px;color:var(--zigo-blue-dark)}.faq-item p{margin:0;color:#475569;line-height:1.6}.cta{background:#fff7d6;padding:55px 24px;text-align:center}.cta h2{font-size:34px;margin:0 0 12px;color:#0f172a}.cta a{display:inline-block;margin-top:22px;padding:14px 26px;background:var(--zigo-orange);color:#fff;border-radius:12px;font-weight:900}.zigo-footer{background:#050a1a;color:#fff;padding:36px 0}.footer-inner{width:min(1180px,calc(100% - 40px));margin:0 auto;display:grid;grid-template-columns:2fr repeat(2,1fr);gap:28px}.zigo-footer h4{margin:0 0 14px;font-size:16px;font-weight:900}.zigo-footer p{margin:0;color:#dbe4ff;line-height:1.5}.zigo-footer a{display:block;color:#dbe4ff;margin-bottom:8px;font-size:15px}.powered{margin-top:18px;color:#8fa1c2;font-size:12px}
        @media(max-width:900px){.hero{grid-template-columns:1fr;gap:30px}.business-grid,.solutions-grid{grid-template-columns:1fr}.section-title h2,.solutions-section h2{font-size:30px}.section-title h3{font-size:28px}.quote-form{grid-template-columns:repeat(2,minmax(0,1fr))}.field-dimensions,.quote-form>.btn-yellow{grid-column:1/-1}.landing-quote-option{grid-template-columns:1fr}.landing-quote-price{text-align:center}}
        @media(max-width:767px){html,body,.page-wrap,.top-header,.nav,.quote-box,.quote-card,.quote-form,.quote-form>*,.field,.field-dimensions,.box-dimensions,.landing-quote-option{width:100%!important;max-width:100%!important;min-width:0!important;box-sizing:border-box!important}html,body{margin:0!important;overflow-x:clip!important}.nav{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;padding:10px 14px!important;gap:8px 12px!important}.brand{min-width:0!important;width:100%!important;overflow:hidden}.brand-logo-frame{width:100%!important;min-height:48px!important}.brand-logo{width:min(250px,72vw)!important;max-width:100%!important;transform:none!important}.brand-name{font-size:23px}.brand-tagline{margin-top:-2px!important;max-width:100%;white-space:normal!important;letter-spacing:1.5px!important}.mobile-nav-toggle{display:inline-flex;width:48px;height:48px;align-items:center;justify-content:center;border:1px solid #dbeafe;border-radius:12px;background:#fff;color:var(--zigo-blue-dark);font-size:24px;cursor:pointer}.main-nav{display:none!important;grid-column:1/-1;width:100%!important;grid-template-columns:minmax(0,1fr)!important;gap:8px!important}.main-nav.is-open{display:grid!important}.main-nav a{display:flex!important;width:100%!important;min-height:44px;align-items:center;justify-content:center;padding:10px 12px!important;white-space:normal!important}.quote-box{padding:16px 12px!important}.quote-card{padding:16px 14px!important}.quote-form{display:grid!important;grid-template-columns:minmax(0,1fr)!important;gap:12px!important}.quote-form>*,.field,.field input,.field select,.btn-yellow{position:static!important;width:100%!important;max-width:100%!important;min-width:0!important}.box-dimensions{height:auto;grid-template-columns:1fr;gap:8px;background:transparent}.box-dimensions input{width:100%!important;border:1px solid #d1d5db!important;border-radius:10px!important}.address-details,.address-side{grid-template-columns:1fr}.btn-yellow{display:flex!important;min-height:46px;align-items:center;justify-content:center}.hero{padding:24px 16px 55px}.hero h1{font-size:40px}.hero-visual{min-height:280px}.hero-card,.hero-image{min-height:280px}.faq-grid,.footer-inner{grid-template-columns:1fr}.business-types{margin:55px auto}.faq-section,.solutions-section{padding:55px 18px}}
    </style>
</head>
<body class="zigo-public-landing">
<div class="page-wrap">
    <header class="top-header">
        <div class="nav">
            <a href="/" class="brand">
                <div class="brand-logo-frame">@if($logoUrl)<img src="{{ $logoUrl }}" alt="{{ $brand }}" class="brand-logo">@else<span class="brand-name">{{ $brand }}</span>@endif</div>
                <div class="brand-tagline">Tecnología • Logística • Conexión</div>
            </a>
            <button type="button" class="mobile-nav-toggle" aria-label="Abrir menú" aria-controls="main-navigation" aria-expanded="false">☰</button>
            <nav class="main-nav" id="main-navigation">
                <a href="/">Inicio</a><a href="{{ route('tenant.b2c.tracking.public',[],false) }}">Rastrear</a><a href="{{ $supportUrl }}">Ayuda</a>
                @auth<a href="{{ route('tenant.customer.app.dashboard',[],false) }}" class="nav-account">Mi cuenta</a>
                @else<a href="{{ route('tenant.customer.login',[],false) }}" class="nav-login">Iniciar sesión</a><a href="{{ route('tenant.customer.register',[],false) }}" class="nav-register">Registro</a>@endauth
            </nav>
        </div>
    </header>

    <section class="quote-box" id="cotizar">
        <div class="quote-card">
            <div class="quote-title">Cotiza gratis tu envío</div>
            @if($errors->any())<div class="landing-alert" role="alert">{{ $errors->first() }}</div>@endif
            <form class="quote-form" method="POST" action="{{ route('tenant.b2c.quote.store',[],false) }}">@csrf
                <div class="field"><label for="cp_origen">Origen</label><input id="cp_origen" name="cp_origen" data-postal="origin" inputmode="numeric" maxlength="5" value="{{ old('cp_origen') }}" placeholder="Código postal origen" required></div>
                <div class="field"><label for="cp_destino">Destino</label><input id="cp_destino" name="cp_destino" data-postal="destination" inputmode="numeric" maxlength="5" value="{{ old('cp_destino') }}" placeholder="Código postal destino" required></div>
                <div class="field"><label for="tipo_envio">Tipo de envío</label><select name="tipo_envio" id="tipo_envio"><option value="caja" @selected(old('tipo_envio')==='caja')>Caja</option><option value="sobre" @selected(old('tipo_envio','sobre')==='sobre')>Sobre</option></select></div>
                <div class="field"><label for="peso">Peso (kg)</label><input type="number" id="peso" name="peso" placeholder="Kg" min="0.1" max="70" step="0.01" value="{{ old('peso',1) }}" required></div>
                <div class="field field-dimensions" data-dimensions hidden><label>Tamaño de caja en (cm)</label><div class="box-dimensions"><input type="number" name="length" placeholder="Largo" min="1" max="300" value="{{ old('length') }}"><input type="number" name="height" placeholder="Alto" min="1" max="300" value="{{ old('height') }}"><input type="number" name="width" placeholder="Ancho" min="1" max="300" value="{{ old('width') }}"></div></div>
                <button class="btn-yellow" type="submit">Cotizar envío</button>
                <div class="address-details" data-addresses>
                    <div class="address-side"><div class="field"><label>Colonia de origen</label><select name="origin_settlement" data-settlement="origin" disabled><option value="">Captura el CP</option></select></div><div class="field"><label>Calle y número</label><input name="origin_address" value="{{ old('origin_address') }}" required></div><small class="address-location" data-location="origin"></small></div>
                    <div class="address-side"><div class="field"><label>Colonia de destino</label><select name="destination_settlement" data-settlement="destination" disabled><option value="">Captura el CP</option></select></div><div class="field"><label>Calle y número</label><input name="destination_address" value="{{ old('destination_address') }}" required></div><small class="address-location" data-location="destination"></small></div>
                </div>
            </form>
            @if($result ?? null)
                <div class="landing-results" id="resultados"><h2>Opciones disponibles</h2>
                    @foreach($result['options'] as $index=>$option)
                        <form method="POST" action="{{ route('tenant.b2c.quote.select',[],false) }}" class="landing-quote-option">@csrf
                            <input type="hidden" name="operation_uuid" value="{{ $result['operation']->uuid }}"><input type="hidden" name="option" value="{{ $index }}">
                            <div class="landing-quote-service"><strong>{{ $option['service'] }}</strong></div><div class="landing-quote-sla">{{ $option['sla'] ?: 'Consulta la opción disponible para tu envío.' }}</div><div class="landing-quote-price">${{ number_format((float)$option['price'],2) }} {{ $option['currency'] }}</div><button class="landing-quote-select">Elegir servicio</button>
                        </form>
                    @endforeach
                </div>
            @endif
        </div>
    </section>

    <section class="hero">
        <div class="hero-copy"><div class="hero-kicker"><span>✓</span> Envíos en sencillos pasos</div><h1>Envía fácil con <strong>{{ $brand }}</strong></h1><p>Cotiza, paga y genera tu guía desde una experiencia simple para enviar y dar seguimiento hasta la entrega.</p><div class="hero-actions"><a href="#cotizar" class="hero-primary">Cotizar ahora</a><a href="{{ route('tenant.b2c.tracking.public',[],false) }}" class="hero-secondary">Rastrear envío</a></div></div>
        <div class="hero-visual"><div class="hero-card hero-image-card">@if($heroUrl)<img src="{{ $heroUrl }}" width="1600" height="900" alt="Soluciones logísticas de {{ $brand }}" class="hero-image">@else<div class="hero-placeholder">{{ $brand }}</div>@endif</div></div>
    </section>

    <section class="business-types"><div class="section-title"><h2>Cómo funciona</h2><h3>Tu envío, de principio a fin</h3><p>Sigue el journey existente para cotizar, elegir y completar tu envío.</p></div><div class="business-grid"><div class="business-card"><span class="business-step">PASOS 1 Y 2</span><h3>Cotiza y elige</h3><p>Captura los datos del paquete y selecciona el servicio disponible.</p></div><div class="business-card"><span class="business-step">PASOS 3 Y 4</span><h3>Ingresa y paga</h3><p>Inicia sesión o crea tu cuenta, completa el envío y revisa el total.</p></div><div class="business-card"><span class="business-step">PASOS 5 Y 6</span><h3>Obtén tu guía y rastrea</h3><p>Descarga la guía y consulta el avance de tu envío.</p></div></div></section>

    <section class="solutions-section"><div class="section-container"><h2>Todo para tus envíos en un solo lugar</h2><div class="solutions-grid"><div class="solution-card"><h3>Cotización clara</h3><p>Consulta opciones y precios disponibles según los datos de tu envío.</p><a href="#cotizar">Cotizar envío →</a></div><div class="solution-card"><h3>Perfil personal</h3><p>Consulta tus envíos, guías y seguimiento desde tu cuenta.</p><a href="{{ route('tenant.customer.register',[],false) }}">Crear cuenta →</a></div><div class="solution-card"><h3>Seguimiento</h3><p>Consulta el estado de una guía desde la superficie pública del tenant.</p><a href="{{ route('tenant.b2c.tracking.public',[],false) }}">Rastrear envío →</a></div></div></div></section>

    <section class="faq-section" id="faq"><h2>Preguntas frecuentes</h2><div class="faq-grid"><div class="faq-item"><h3>¿Puedo cotizar sin registrarme?</h3><p>Sí. Puedes obtener opciones como visitante y tu cotización se conserva al iniciar sesión o crear una cuenta.</p></div><div class="faq-item"><h3>¿Qué tipo de envío puedo cotizar?</h3><p>Puedes seleccionar Sobre o Caja. Las dimensiones se solicitan únicamente para Caja.</p></div><div class="faq-item"><h3>¿Dónde consulto mi guía?</h3><p>Después de completar el pago y generarse el envío podrás descargar la guía desde tu cuenta.</p></div><div class="faq-item"><h3>¿Cómo doy seguimiento?</h3><p>Usa la opción Rastrear e ingresa el número de guía de tu envío.</p></div></div></section>

    <section class="cta"><h2>Comienza a cotizar y generar tus envíos</h2><p>Crea tu cuenta para continuar con tus cotizaciones y consultar tus guías.</p><a href="{{ route('tenant.customer.register',[],false) }}">Crear cuenta</a></section>
    <footer class="zigo-footer"><div class="footer-inner"><div><h4>{{ $brand }}</h4><p>Plataforma para cotizar, generar y dar seguimiento a tus envíos.</p><div class="powered">Powered by ZIGO</div></div><div><h4>Ayuda</h4><a href="{{ route('tenant.b2c.tracking.public',[],false) }}">Rastrear envío</a><a href="{{ route('tenant.customer.login',[],false) }}">Iniciar sesión</a><a href="{{ $supportUrl }}">Soporte</a></div><div><h4>Contacto</h4>@if($branding?->support_email)<a href="mailto:{{ $branding->support_email }}">{{ $branding->support_email }}</a>@endif @if($branding?->support_phone)<a href="tel:{{ preg_replace('/[^0-9+]/','',$branding->support_phone) }}">{{ $branding->support_phone }}</a>@endif</div></div></footer>
</div>
<script>
    (()=>{const type=document.getElementById('tipo_envio'),dimensions=document.querySelector('[data-dimensions]'),addresses=document.querySelector('[data-addresses]');const syncPackage=()=>{const box=type?.value==='caja';dimensions.hidden=!box;dimensions.querySelectorAll('input').forEach(input=>input.required=box)};type?.addEventListener('change',syncPackage);syncPackage();document.querySelectorAll('[data-postal]').forEach(input=>input.addEventListener('change',async()=>{const side=input.dataset.postal,select=document.querySelector(`[data-settlement="${side}"]`),location=document.querySelector(`[data-location="${side}"]`);if(!/^\d{5}$/.test(input.value))return;select.disabled=true;select.innerHTML='<option value="">Consultando catálogo…</option>';try{const response=await fetch(`/codigos-postales/${input.value}`,{headers:{Accept:'application/json'}}),data=await response.json();if(!response.ok)throw new Error(data.message);select.innerHTML='<option value="">Selecciona una colonia</option>'+data.colonias.map(colonia=>`<option>${colonia.nombre}</option>`).join('');select.disabled=false;select.required=true;location.textContent=`${data.municipio}, ${data.estado}`;addresses.classList.add('is-visible')}catch(error){select.innerHTML='<option value="">Catálogo temporalmente no disponible</option>';location.textContent=error.message||'No fue posible consultar el catálogo'}}));if(document.querySelector('.landing-alert')||@json((bool)old('cp_origen')))addresses.classList.add('is-visible');const toggle=document.querySelector('.mobile-nav-toggle'),navigation=document.getElementById('main-navigation');toggle?.addEventListener('click',()=>{const open=navigation.classList.toggle('is-open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});@if($result ?? null)document.getElementById('resultados')?.scrollIntoView({behavior:'smooth'})@endif})();
</script>
</body>
</html>
