@extends('tenant.layout')
@php($brand=$tenant->branding?->brand_name ?: $tenant->name)
@section('title',$brand.' · Envíos fáciles')
@push('head')
<style>
.storefront-hero{display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,.9fr);gap:clamp(1.5rem,4vw,4rem);align-items:center;padding:clamp(1.5rem,5vw,4rem);border-radius:var(--z-radius-xl);background:linear-gradient(135deg,color-mix(in srgb,var(--tenant-primary) 12%,white),#fff 62%);border:1px solid color-mix(in srgb,var(--tenant-primary) 24%,var(--z-border))}.storefront-hero h1{font-size:clamp(2.25rem,5vw,4.3rem);line-height:1.04;margin:.6rem 0 1rem}.quick-quote{padding:clamp(1.2rem,3vw,2rem);box-shadow:0 18px 48px rgba(11,41,72,.12)}.storefront-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;counter-reset:steps}.storefront-step{position:relative;padding:1.25rem 1.25rem 1.25rem 3.6rem;background:#fff;border:1px solid var(--z-border);border-radius:var(--z-radius-lg);font-weight:800}.storefront-step:before{counter-increment:steps;content:counter(steps);position:absolute;left:1rem;top:1rem;width:2rem;height:2rem;display:grid;place-items:center;border-radius:50%;background:var(--tenant-primary);color:#fff}.storefront-footer__content{display:flex;align-items:flex-start;justify-content:space-between;gap:2rem;flex-wrap:wrap}.storefront-contact{display:flex;gap:1rem;flex-wrap:wrap}.storefront-footer a{color:inherit}.powered{opacity:.65;font-size:.78rem}.quick-quote [data-dimensions][hidden]{display:none}@media(max-width:850px){.storefront-hero{grid-template-columns:1fr}.storefront-steps{grid-template-columns:1fr 1fr}}@media(max-width:560px){.storefront-steps{grid-template-columns:1fr}.storefront-hero{padding:1.1rem}.quick-quote{padding:1rem}}
</style>
@endpush
@section('content')
<section class="storefront-hero"><div><div class="z-eyebrow">ENVÍOS LOCALES Y NACIONALES</div><h1>Envía fácil con {{ $brand }}</h1><p class="z-muted" style="font-size:1.12rem;max-width:580px">Cotiza en minutos, elige el servicio ideal y sigue tu envío hasta la entrega.</p></div>
<form method="POST" action="{{ route('tenant.b2c.quote.store',[],false) }}" class="z-card z-stack quick-quote">@csrf<div><div class="z-eyebrow">COTIZADOR RÁPIDO</div><h2 style="margin:.35rem 0">¿A dónde enviamos?</h2></div>
@if($errors->any())<div class="z-alert z-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<div class="z-form-grid"><label class="z-field">Origen<input name="cp_origen" inputmode="numeric" maxlength="5" placeholder="Código postal" value="{{ old('cp_origen') }}" required></label><label class="z-field">Destino<input name="cp_destino" inputmode="numeric" maxlength="5" placeholder="Código postal" value="{{ old('cp_destino') }}" required></label></div>
<div class="z-form-grid"><label class="z-field">Tipo de envío<select name="tipo_envio" data-package-type><option value="sobre" @selected(old('tipo_envio','sobre')==='sobre')>Sobre</option><option value="caja" @selected(old('tipo_envio')==='caja')>Caja</option></select></label><label class="z-field">Peso (kg)<input type="number" name="peso" min="0.1" max="70" step="0.01" value="{{ old('peso',1) }}" required></label></div>
<div class="z-form-grid z-form-grid--3" data-dimensions><label class="z-field">Largo (cm)<input type="number" name="length" min="1" max="300" value="{{ old('length') }}"></label><label class="z-field">Ancho (cm)<input type="number" name="width" min="1" max="300" value="{{ old('width') }}"></label><label class="z-field">Alto (cm)<input type="number" name="height" min="1" max="300" value="{{ old('height') }}"></label></div><button class="z-btn z-btn--block" type="submit">Cotizar envío</button></form></section>
<section class="customer-section"><div class="z-eyebrow">CÓMO FUNCIONA</div><h2>Tu envío, paso a paso</h2><div class="storefront-steps"><div class="storefront-step">Cotiza</div><div class="storefront-step">Elige tu servicio</div><div class="storefront-step">Regístrate o inicia sesión</div><div class="storefront-step">Paga</div><div class="storefront-step">Genera tu envío</div><div class="storefront-step">Rastrea hasta la entrega</div></div></section>
<section class="customer-section"><div class="z-eyebrow">BENEFICIOS</div><h2>Enviar sin complicaciones</h2><div class="z-grid"><article class="z-card"><h3>Cotización clara</h3><p class="z-muted">Compara servicios y conoce el precio antes de continuar.</p></article><article class="z-card"><h3>Seguimiento sencillo</h3><p class="z-muted">Consulta el avance de tu envío cuando lo necesites.</p></article><article class="z-card"><h3>Entrega confiable</h3><p class="z-muted">Elige la alternativa adecuada para cada destino.</p></article></div></section>
@if($preview ?? false)<div class="z-sr-only" aria-hidden="true">@foreach($modules as $module){{ $module->name }} @endforeach</div>@endif
@endsection
@section('footer')<footer class="customer-footer storefront-footer"><div class="z-container storefront-footer__content"><div><strong>{{ $brand }}</strong><div class="storefront-contact z-muted">@if($tenant->branding?->support_email)<a href="mailto:{{ $tenant->branding->support_email }}">{{ $tenant->branding->support_email }}</a>@endif @if($tenant->branding?->support_phone)<a href="tel:{{ preg_replace('/[^0-9+]/','',$tenant->branding->support_phone) }}">{{ $tenant->branding->support_phone }}</a>@endif</div></div><small class="powered">Powered by ZIGO</small></div></footer>@endsection
@push('scripts')<script>(()=>{const type=document.querySelector('[data-package-type]'),dims=document.querySelector('[data-dimensions]');const sync=()=>{const box=type?.value==='caja';dims.hidden=!box;dims.querySelectorAll('input').forEach(input=>input.required=box)};type?.addEventListener('change',sync);sync()})()</script>@endpush
