@php($branding=$tenant->branding)
@php($brand=$branding?->brand_name ?: $tenant->name)
@php($safeColor=fn($value,$fallback)=>is_string($value)&&preg_match('/^#[0-9A-Fa-f]{6}$/',$value)?$value:$fallback)
@php($logoUrl=$branding?->logo_path && Storage::disk('public')->exists($branding->logo_path) ? route('tenant.branding.logo',[],false) : null)
@php($faviconUrl=$branding?->favicon_path && Storage::disk('public')->exists($branding->favicon_path) ? route('tenant.branding.favicon',[],false) : null)
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title',$brand)</title>
@if($faviconUrl)<link rel="icon" href="{{ $faviconUrl }}">@endif
<link rel="stylesheet" href="{{ asset('css/zigo-design-system.css') }}">
<style>
:root{--tenant-primary:{{ $safeColor($branding?->primary_color,'#185FA8') }};--tenant-secondary:{{ $safeColor($branding?->secondary_color,'#0B2948') }};--tenant-accent:{{ $safeColor($branding?->accent_color,'#39A0ED') }};--z-primary:var(--tenant-primary);--z-primary-dark:var(--tenant-secondary);--z-accent:var(--tenant-accent)}
.customer-header{position:sticky;top:0;z-index:30;background:rgba(255,255,255,.96);backdrop-filter:blur(12px);border-bottom:1px solid var(--z-border-subtle);box-shadow:0 1px 8px rgba(7,26,51,.04)}.customer-nav{min-height:68px;display:flex;align-items:center;justify-content:space-between;gap:1rem}.customer-brand{display:flex;align-items:center;gap:.65rem;color:var(--z-text);font-weight:900;text-decoration:none}.customer-brand img{width:auto;max-width:145px;height:38px;object-fit:contain}.customer-brand__avatar{width:36px;height:36px;display:grid;place-items:center;border-radius:10px;background:var(--z-primary);color:#fff}.customer-links{display:flex;align-items:center;gap:.2rem}.customer-links>a{display:inline-flex;align-items:center;gap:.4rem;padding:.58rem .68rem;color:var(--z-text);text-decoration:none;font-weight:700;border-radius:9px}.customer-links>a[aria-current=page]{color:var(--z-primary);background:color-mix(in srgb,var(--z-primary) 9%,#fff)}.customer-main{padding:1.5rem 0 6rem}.customer-footer{padding:2.5rem 0;border-top:1px solid var(--z-border);background:#fff}.customer-bottom{position:fixed;z-index:40;inset:auto 0 0;display:grid;grid-template-columns:repeat(4,1fr);background:#fff;border-top:1px solid var(--z-border);padding:.35rem max(.35rem,env(safe-area-inset-right)) calc(.35rem + env(safe-area-inset-bottom)) max(.35rem,env(safe-area-inset-left))}.customer-bottom a{min-height:52px;display:grid;place-items:center;color:var(--z-muted);text-decoration:none;font-size:.72rem;font-weight:800}.customer-bottom a[aria-current=page]{color:var(--z-primary)}.customer-menu{display:none}.customer-hero{padding:clamp(2rem,7vw,5.5rem);border-radius:var(--z-radius-xl);background:linear-gradient(135deg,color-mix(in srgb,var(--z-primary) 10%,white),#fff 62%);border:1px solid color-mix(in srgb,var(--z-primary) 22%,var(--z-border));overflow:hidden}.customer-hero h1{font-size:clamp(2.1rem,7vw,4.5rem);line-height:1.02;max-width:800px;margin:.5rem 0 1rem}.customer-section{padding:2rem 0}.customer-section h2{font-size:clamp(1.35rem,3vw,1.85rem);margin:.3rem 0 1rem}.customer-tracking{max-width:760px;margin:-1.8rem auto 0;position:relative}.customer-tracking form{display:grid;gap:.75rem}.shipment-card{display:grid;gap:.7rem}.shipment-card__top{display:flex;justify-content:space-between;align-items:start;gap:1rem}.shipment-card a{font-weight:800}.auth-shell{width:min(100% - 2rem,480px);margin:2rem auto}.auth-shell .z-card{padding:clamp(1.25rem,5vw,2rem)}
@media(max-width:767px){.customer-links{display:none;position:absolute;top:60px;left:1rem;right:1rem;padding:.75rem;background:#fff;border:1px solid var(--z-border);border-radius:14px;box-shadow:var(--z-shadow-md);align-items:stretch;flex-direction:column}.customer-links.is-open{display:flex}.customer-links>a,.customer-links form,.customer-links button{width:100%}.customer-menu{display:grid}.customer-nav{min-height:60px}.customer-brand img{height:34px}.customer-main{padding-top:1rem}}
@media(min-width:768px){.customer-main{padding-bottom:2.5rem}.customer-bottom{display:none}.customer-tracking form{grid-template-columns:1fr auto}.customer-tracking button{min-width:150px}.journey-people{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}}
@media(min-width:1024px){body.z-app{padding-left:244px}.customer-header{position:fixed;inset:0 auto 0 0;width:244px;border-right:1px solid var(--z-border-subtle);border-bottom:0;box-shadow:1px 0 8px rgba(7,26,51,.04)}.customer-nav{height:100%;padding:1.25rem;display:flex;flex-direction:column;align-items:stretch;justify-content:flex-start}.customer-brand{min-height:52px;margin-bottom:1rem}.customer-links{display:flex;width:100%;flex:1;flex-direction:column;align-items:stretch;gap:.3rem}.customer-links>a{width:100%;padding:.72rem .8rem}.customer-links form{margin-top:auto}.customer-links form button{width:100%}.customer-main{width:min(1180px,calc(100% - 3rem));margin:0 auto}.customer-footer{margin-left:0}}
</style>@stack('head')</head><body class="z-app">
<header class="customer-header"><nav class="z-container customer-nav" aria-label="Navegación principal"><a class="customer-brand" href="/">@if($logoUrl)<img src="{{ $logoUrl }}" alt="{{ $brand }}">@else<span class="customer-brand__avatar">{{ mb_strtoupper(mb_substr($brand,0,1)) }}</span><span>{{ $brand }}</span>@endif</a><button class="z-icon-btn customer-menu" type="button" aria-label="Abrir menú" aria-expanded="false" aria-controls="customer-links" onclick="const n=document.getElementById('customer-links');n.classList.toggle('is-open');this.setAttribute('aria-expanded',n.classList.contains('is-open'))"><x-zigo.icon name="shipments" /></button><div class="customer-links" id="customer-links">
@auth<a href="{{ request()->routeIs('tenant.customer.landing') ? '/' : route('tenant.customer.app.dashboard',[],false) }}" @if(request()->is('app')||request()->routeIs('tenant.customer.landing')) aria-current="page" @endif><x-zigo.icon name="home" />Inicio</a>@unless(request()->routeIs('tenant.customer.landing'))<a href="{{ route('tenant.customer.app.quote',[],false) }}" @if(request()->is('app/cotizar*')) aria-current="page" @endif><x-zigo.icon name="quote" />Cotizar</a>@endunless<a href="{{ route('tenant.b2c.tracking.public',[],false) }}"><x-zigo.icon name="tracking" />Rastrear</a><a href="{{ route('tenant.customer.app.shipments',[],false) }}" @if(request()->is('app/envios*')) aria-current="page" @endif><x-zigo.icon name="shipments" />Envíos</a><a href="{{ route('tenant.customer.app.addresses.index',[],false) }}" @if(request()->is('app/direcciones*')) aria-current="page" @endif><x-zigo.icon name="location" />Mis direcciones</a><a href="{{ route('tenant.customer.app.support',[],false) }}"><x-zigo.icon name="help" />Ayuda</a><a href="{{ route('tenant.customer.app.profile',[],false) }}"><x-zigo.icon name="user" />Mi cuenta</a>@unless(request()->routeIs('tenant.customer.landing'))<form method="POST" action="{{ route('tenant.customer.logout',[],false) }}">@csrf<button class="z-btn z-btn--ghost" type="submit">Salir</button></form>@endunless
@else<a href="/" aria-current="page"><x-zigo.icon name="home" />Inicio</a><a href="{{ route('tenant.b2c.tracking.public',[],false) }}"><x-zigo.icon name="tracking" />Rastrear</a><a href="{{ $branding?->support_email ? 'mailto:'.$branding->support_email : route('tenant.customer.login',[],false) }}"><x-zigo.icon name="help" />Ayuda</a><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.login',[],false) }}">Iniciar sesión</a><a class="z-btn" href="{{ route('tenant.customer.register',[],false) }}">Crear cuenta</a>@endauth
</div></nav></header>
<main class="z-container customer-main">@if(session('success'))<div class="z-alert z-alert--success" role="status">{{ session('success') }}</div>@endif @if(session('status'))<div class="z-alert" role="status">{{ session('status') }}</div>@endif @yield('content')</main>
@auth @unless(request()->routeIs('tenant.customer.landing'))<nav class="customer-bottom" aria-label="Navegación del portal"><a href="{{ route('tenant.customer.app.dashboard',[],false) }}" @if(request()->is('app')) aria-current="page" @endif><x-zigo.icon name="home" /><span>Inicio</span></a><a href="{{ route('tenant.customer.app.quote',[],false) }}" @if(request()->is('app/cotizar*')) aria-current="page" @endif><x-zigo.icon name="quote" /><span>Cotizar</span></a><a href="{{ route('tenant.customer.app.shipments',[],false) }}" @if(request()->is('app/envios*')) aria-current="page" @endif><x-zigo.icon name="shipments" /><span>Envíos</span></a><a href="{{ route('tenant.customer.app.profile',[],false) }}" @if(request()->is('app/perfil*')) aria-current="page" @endif><x-zigo.icon name="user" /><span>Perfil</span></a></nav>@endunless @endauth
@yield('footer') @stack('scripts')</body></html>
