@php($branding=$tenant->branding)
@php($brand=$branding?->brand_name ?: $tenant->name)
@php($safeColor=fn($value,$fallback)=>is_string($value)&&preg_match('/^#[0-9A-Fa-f]{6}$/',$value)?$value:$fallback)
@php($logoUrl=$branding?->logo_path && Storage::disk('public')->exists($branding->logo_path) ? Storage::disk('public')->url($branding->logo_path) : null)
@php($faviconUrl=$branding?->favicon_path && Storage::disk('public')->exists($branding->favicon_path) ? Storage::disk('public')->url($branding->favicon_path) : null)
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>@yield('title',$brand)</title>
@if($faviconUrl)<link rel="icon" href="{{ $faviconUrl }}">@endif
<link rel="stylesheet" href="{{ asset('css/zigo-design-system.css') }}">
<style>
:root{--tenant-primary:{{ $safeColor($branding?->primary_color,'#185FA8') }};--tenant-secondary:{{ $safeColor($branding?->secondary_color,'#0B2948') }};--tenant-accent:{{ $safeColor($branding?->accent_color,'#39A0ED') }};--z-primary:var(--tenant-primary);--z-primary-dark:var(--tenant-secondary);--z-accent:var(--tenant-accent)}
.customer-header{position:sticky;top:0;z-index:30;background:#fff;border-bottom:1px solid var(--z-border)}.customer-nav{min-height:68px;display:flex;align-items:center;justify-content:space-between;gap:1rem}.customer-brand{display:flex;align-items:center;gap:.7rem;color:var(--z-text);font-weight:900;text-decoration:none}.customer-brand img{width:auto;max-width:150px;height:42px;object-fit:contain}.customer-links{display:flex;align-items:center;gap:.3rem}.customer-links>a{padding:.65rem .75rem;color:var(--z-text);text-decoration:none;font-weight:700;border-radius:10px}.customer-main{padding:1.5rem 0 6rem}.customer-footer{padding:2.5rem 0;border-top:1px solid var(--z-border);background:#fff}.customer-bottom{position:fixed;z-index:40;inset:auto 0 0;display:grid;grid-template-columns:repeat(4,1fr);background:#fff;border-top:1px solid var(--z-border);padding:.35rem max(.35rem,env(safe-area-inset-right)) calc(.35rem + env(safe-area-inset-bottom)) max(.35rem,env(safe-area-inset-left))}.customer-bottom a{min-height:52px;display:grid;place-items:center;color:var(--z-muted);text-decoration:none;font-size:.72rem;font-weight:800}.customer-bottom a[aria-current=page]{color:var(--z-primary)}.customer-hero{padding:clamp(2rem,7vw,5.5rem);border-radius:var(--z-radius-xl);background:linear-gradient(135deg,color-mix(in srgb,var(--z-primary) 10%,white),#fff 62%);border:1px solid color-mix(in srgb,var(--z-primary) 22%,var(--z-border));overflow:hidden}.customer-hero h1{font-size:clamp(2.1rem,7vw,4.5rem);line-height:1.02;max-width:800px;margin:.5rem 0 1rem}.customer-section{padding:clamp(2rem,5vw,4rem) 0}.customer-section h2{font-size:clamp(1.5rem,4vw,2.2rem);margin:.3rem 0 1rem}.customer-tracking{max-width:760px;margin:-1.8rem auto 0;position:relative}.customer-tracking form{display:grid;gap:.75rem}.shipment-card{display:grid;gap:.7rem}.shipment-card__top{display:flex;justify-content:space-between;align-items:start;gap:1rem}.shipment-card a{font-weight:800}.auth-shell{width:min(100% - 2rem,480px);margin:2rem auto}.auth-shell .z-card{padding:clamp(1.25rem,5vw,2rem)}
@media(max-width:767px){.customer-links .desktop-link{display:none}.customer-nav{min-height:60px}.customer-brand img{height:36px}.customer-main{padding-top:1rem}}
@media(min-width:768px){.customer-main{padding-bottom:2.5rem}.customer-bottom{display:none}.customer-tracking form{grid-template-columns:1fr auto}.customer-tracking button{min-width:150px}}
</style>@stack('head')</head><body class="z-app">
<header class="customer-header"><nav class="z-container customer-nav" aria-label="Navegación principal"><a class="customer-brand" href="/">@if($logoUrl)<img src="{{ $logoUrl }}" alt="{{ $brand }}">@else<span>{{ $brand }}</span>@endif</a><div class="customer-links">
@auth<a class="desktop-link" href="{{ route('tenant.customer.app.dashboard',[],false) }}">Inicio</a><a class="desktop-link" href="{{ route('tenant.customer.app.quote',[],false) }}">Cotizar</a><a class="desktop-link" href="{{ route('tenant.customer.app.shipments',[],false) }}">Envíos</a><a class="desktop-link" href="{{ route('tenant.customer.app.support',[],false) }}">Ayuda</a><a class="desktop-link" href="{{ route('tenant.customer.app.profile',[],false) }}">Perfil</a><form method="POST" action="{{ route('tenant.customer.logout',[],false) }}">@csrf<button class="z-btn z-btn--ghost" type="submit">Salir</button></form>
@else<a class="desktop-link" href="{{ route('tenant.b2c.tracking.public',[],false) }}">Rastrear</a><a class="z-btn z-btn--outline" href="{{ route('tenant.customer.login.public',[],false) }}">Iniciar sesión</a><a class="z-btn" href="{{ route('tenant.customer.register',[],false) }}">Crear cuenta</a>@endauth
</div></nav></header>
<main class="z-container customer-main">@if(session('success'))<div class="z-alert z-alert--success" role="status">{{ session('success') }}</div>@endif @if(session('status'))<div class="z-alert" role="status">{{ session('status') }}</div>@endif @yield('content')</main>
@auth<nav class="customer-bottom" aria-label="Navegación del portal"><a href="{{ route('tenant.customer.app.dashboard',[],false) }}" @if(request()->is('app')) aria-current="page" @endif>⌂<span>Inicio</span></a><a href="{{ route('tenant.customer.app.quote',[],false) }}" @if(request()->is('app/cotizar*')) aria-current="page" @endif>＋<span>Cotizar</span></a><a href="{{ route('tenant.customer.app.shipments',[],false) }}" @if(request()->is('app/envios*')) aria-current="page" @endif>▤<span>Envíos</span></a><a href="{{ route('tenant.customer.app.profile',[],false) }}" @if(request()->is('app/perfil*')) aria-current="page" @endif>●<span>Perfil</span></a></nav>@endauth
@yield('footer') @stack('scripts')</body></html>
