@extends('tenant.admin.layout')
@section('title','Crear agente')
@push('styles')<style>.launchpad{max-width:900px}.launchpad fieldset{border:0;padding:0;margin:1.5rem 0}.launchpad label,.launchpad legend{display:block;font-weight:800;margin:.8rem 0 .35rem}.launchpad input,.launchpad textarea,.launchpad select{width:100%;min-height:44px}.choice-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.65rem}.choice{border:1px solid var(--z-border);border-radius:10px;padding:.8rem;background:#fff}.choice label{display:flex;gap:.5rem;margin:0}.choice input{width:auto;min-height:auto}</style>@endpush
@section('content')
<div class="launchpad"><div class="eyebrow">CREAR AGENTE</div><h1>¿Qué necesitas resolver?</h1><p class="muted">Con esta información prepararemos una propuesta inicial configurable para tu negocio.</p>
<form method="POST" action="{{ route('tenant.admin.ai-agents.launchpad.store') }}">@csrf
<label for="problem_description">Describe el problema o la oportunidad</label><textarea id="problem_description" name="problem_description" rows="5" maxlength="2000" required>{{ old('problem_description') }}</textarea>
<fieldset><legend>Objetivo principal</legend><div class="choice-grid">@foreach(['unsure'=>'No estoy seguro','sales'=>'Aumentar ventas','customer_service'=>'Atender clientes','booking'=>'Gestionar citas','quote'=>'Solicitar cotizaciones','custom_operational'=>'Resolver una operación'] as $value=>$label)<div class="choice"><label><input type="radio" name="objective_code" value="{{ $value }}" {{ old('objective_code','unsure')===$value?'checked':'' }}> {{ $label }}</label></div>@endforeach</div></fieldset>
<h2>Información del negocio</h2><label for="business_description">¿A qué se dedica tu negocio?</label><textarea id="business_description" name="business_description" rows="3" maxlength="1500">{{ old('business_description') }}</textarea><label for="customer_description">¿A quién atiendes?</label><textarea id="customer_description" name="customer_description" rows="2" maxlength="1000">{{ old('customer_description') }}</textarea><label for="desired_outcomes">¿Qué resultados esperas?</label><textarea id="desired_outcomes" name="desired_outcomes" rows="2" maxlength="1000">{{ old('desired_outcomes') }}</textarea><label for="desired_agent_name">Nombre preferido (opcional)</label><input id="desired_agent_name" name="desired_agent_name" maxlength="160" value="{{ old('desired_agent_name') }}">
<fieldset><legend>Canales que te interesan</legend><div class="choice-grid">@foreach(['webchat'=>'Chat en tu sitio','whatsapp'=>'WhatsApp','api'=>'API'] as $value=>$label)<div class="choice"><label><input type="checkbox" name="requested_channels[]" value="{{ $value }}" {{ in_array($value,old('requested_channels',[]),true)?'checked':'' }}> {{ $label }}</label></div>@endforeach</div></fieldset>
<fieldset><legend>Conocimiento disponible</legend><div class="choice-grid">@foreach(['website'=>'Sitio web','pdf'=>'PDF','docx'=>'Documentos','faq'=>'Preguntas frecuentes','catalog'=>'Catálogo','csv'=>'Archivos CSV','api'=>'API','manual'=>'Carga manual'] as $value=>$label)<div class="choice"><label><input type="checkbox" name="knowledge_source_types[]" value="{{ $value }}" {{ in_array($value,old('knowledge_source_types',[]),true)?'checked':'' }}> {{ $label }}</label></div>@endforeach</div></fieldset>
<label for="business_hours">Horario de atención</label><input id="business_hours" name="business_hours" maxlength="300" value="{{ old('business_hours') }}"><label for="handoff_preference">¿Cuándo debe intervenir una persona?</label><select id="handoff_preference" name="handoff_preference"><option value="unknown_or_low_confidence" {{ old('handoff_preference','unknown_or_low_confidence')==='unknown_or_low_confidence'?'selected':'' }}>Cuando no sepa o tenga baja confianza</option><option value="when_requested" {{ old('handoff_preference')==='when_requested'?'selected':'' }}>Cuando el cliente lo solicite</option><option value="sensitive_actions" {{ old('handoff_preference')==='sensitive_actions'?'selected':'' }}>Antes de acciones sensibles</option><option value="always_available" {{ old('handoff_preference')==='always_available'?'selected':'' }}>Mantener ayuda humana siempre disponible</option></select><label for="integration_needs">Sistemas que necesitarías conectar</label><textarea id="integration_needs" name="integration_needs" rows="2" maxlength="1000">{{ old('integration_needs') }}</textarea><input type="hidden" name="preferred_language" value="es-MX"><p><button class="z-btn z-btn--primary" type="submit">Generar recomendación</button></p>
</form></div>
@endsection
