@extends('tenant.admin.layout')
@section('title','Propuesta de agente')
@section('content')
<div class="eyebrow">PROPUESTA INICIAL CONFIGURABLE</div><h1>{{ $recommendation->suggestedName }}</h1><p class="muted">{{ str_replace('_',' ',ucfirst($recommendation->recommendedAgentType->value)) }} · Confianza {{ $recommendation->confidence }}</p><article class="card"><h2>Por qué</h2><p>{{ $recommendation->explanation }}</p></article>
@php($sections=['Qué hará'=>$recommendation->allowedCapabilities,'Qué no hará'=>$recommendation->prohibitedCapabilities,'Conocimiento necesario'=>$recommendation->knowledgeRequirements,'Resultados esperados'=>$recommendation->objectives,'Supuestos'=>$recommendation->assumptions,'Información faltante'=>$recommendation->missingInformation,'Riesgos'=>$recommendation->riskFlags,'Alternativas'=>$recommendation->alternatives])
<section class="grid">@foreach($sections as $title=>$items)<article class="card"><h2>{{ $title }}</h2>@if($items)<ul>@foreach($items as $item)<li>{{ $item }}</li>@endforeach</ul>@else<p class="muted">Sin elementos adicionales.</p>@endif</article>@endforeach
<article class="card"><h2>Canales</h2><ul>@foreach($recommendation->channels as $channel)<li>{{ ucfirst($channel) }} — {{ $channel==='webchat'?'disponible':'pendiente' }}</li>@endforeach</ul></article><article class="card"><h2>Handoff</h2><p>{{ ['when_requested'=>'Cuando el cliente lo solicite','unknown_or_low_confidence'=>'Cuando no exista una respuesta confiable','sensitive_actions'=>'Antes de acciones sensibles','always_available'=>'Ayuda humana siempre disponible'][$recommendation->handoffPolicy['code']]??'Ayuda humana disponible' }}</p></article></section>
<article class="card"><strong>Tu agente se creará como borrador.</strong><p>INNOTECH revisará conocimiento, canales, pruebas y publicación contigo.</p>@if($launchpadSession->status->value==='converted')<a class="z-btn z-btn--primary" href="{{ route('tenant.admin.ai-agents.show',$launchpadSession->converted_agent_id) }}">Ver Agent Draft</a>@else<form method="POST" action="{{ route('tenant.admin.ai-agents.launchpad.convert',$launchpadSession) }}">@csrf<button class="z-btn z-btn--primary" type="submit">Crear borrador de agente</button></form>@endif</article>
@endsection
