<?php
namespace App\Http\Controllers\WhatsApp;
use App\Domain\AI\Channels\WhatsApp\Jobs\ProcessWhatsAppInboundJob;use App\Domain\AI\Channels\WhatsApp\Models\WhatsAppInboundReceipt;use App\Domain\AI\Channels\WhatsApp\Services\ResolveWhatsAppChannelService;use App\Http\Controllers\Controller;use Illuminate\Database\QueryException;use Illuminate\Http\{Request,Response};
final class WhatsAppWebhookController extends Controller{
 public function verify(Request$r,string$channelKey,ResolveWhatsAppChannelService$resolver):Response{$c=$resolver->resolve($channelKey,false);$mode=(string)$r->query('hub_mode',$r->query('hub.mode'));$token=(string)$r->query('hub_verify_token',$r->query('hub.verify_token'));$challenge=(string)$r->query('hub_challenge',$r->query('hub.challenge'));if($mode!=='subscribe'||!hash_equals($c->verifyToken(),$token))abort(403,'verification_failed');return response($challenge,200,['Content-Type'=>'text/plain']);}
 public function receive(Request$r,string$channelKey,ResolveWhatsAppChannelService$resolver):Response{
  $c=$resolver->resolve($channelKey,false);$raw=$r->getContent();if(strlen($raw)>262144)abort(413,'payload_too_large');$provided=(string)$r->header('X-Hub-Signature-256');$expected='sha256='.hash_hmac('sha256',$raw,$c->appSecret());if($provided===''||!hash_equals($expected,$provided))abort(403,'signature_invalid');try{$json=json_decode($raw,true,32,JSON_THROW_ON_ERROR);}catch(\JsonException){abort(400,'payload_invalid');}
  foreach($this->events($json,$c->phone_number_id)as$event){try{$x=new WhatsAppInboundReceipt;$x->tenant_id=$c->tenant_id;$x->whatsapp_channel_id=$c->id;$x->provider_message_id=$event['provider_message_id'];$x->event_type=$event['event_type'];$x->status=$c->enabled?'received':'succeeded';$x->payload_encrypted=$event;$x->save();$this->dispatchReceived($c->enabled,$c->tenant_id,$x);}catch(QueryException$e){$x=WhatsAppInboundReceipt::where('whatsapp_channel_id',$c->id)->where('provider_message_id',$event['provider_message_id'])->first();if(!$x)throw$e;$this->dispatchReceived($c->enabled,$c->tenant_id,$x);}}
  return response('',200);
 }
 private function events(array$j,string$phoneId):array{$out=[];foreach($j['entry']??[]as$entry)foreach($entry['changes']??[]as$change){$value=$change['value']??[];if((string)($value['metadata']['phone_number_id']??'')!==$phoneId)continue;$name=$value['contacts'][0]['profile']['name']??null;foreach($value['messages']??[]as$m){$type=(string)($m['type']??'unsupported');$event=['provider_message_id'=>(string)($m['id']??''),'event_type'=>in_array($type,['text','interactive'],true)?$type:'unsupported','from'=>(string)($m['from']??''),'profile_name'=>is_string($name)?mb_substr($name,0,160):null];if($type==='text')$event['text']=(string)($m['text']['body']??'');if($type==='interactive')$event['reply_id']=(string)($m['interactive']['button_reply']['id']??'');if($event['provider_message_id']!==''&&$event['from']!=='')$out[]=$event;}foreach($value['statuses']??[]as$s)if(!empty($s['id']))$out[]=['provider_message_id'=>'status:'.(string)$s['id'].':'.(string)($s['status']??''),'event_type'=>'status','provider_delivery_id'=>(string)$s['id'],'status'=>(string)($s['status']??'')];}return$out;}
 private function dispatchReceived(bool$enabled,int$tenantId,WhatsAppInboundReceipt$r):void{if($enabled&&$r->status==='received')ProcessWhatsAppInboundJob::dispatchAfterResponse($tenantId,$r->id);}
}
