@extends('tenant.driver.layout')
@section('title','Inicio')
@section('content')
<section class="z-page-header" id="perfil"><div><div class="z-eyebrow">Tu jornada</div><h1>Hola, {{ auth()->user()->name }}</h1><p class="z-muted">Todo listo para tu operación de hoy.</p></div><span class="z-badge {{ $profile->isOnline() ? 'z-badge--success' : 'z-badge--muted' }}">{{ $profile->isOnline() ? 'Online' : 'Offline' }}</span></section>
<section class="z-card z-stack" aria-labelledby="availability-title"><div class="driver-status-line"><div><div class="z-eyebrow" id="availability-title">Disponibilidad</div><strong>{{ ['AVAILABLE'=>'Disponible','BUSY'=>'Ocupado','UNAVAILABLE'=>'No disponible'][$profile->availability_status] ?? str_replace('_',' ',$profile->availability_status) }}</strong></div><span class="z-badge {{ $profile->availability_status === 'AVAILABLE' ? 'z-badge--success' : ($profile->availability_status === 'BUSY' ? 'z-badge--warning' : 'z-badge--muted') }}">{{ $profile->availability_status }}</span></div><div class="availability-actions"><form method="POST" action="{{ route('tenant.driver.availability') }}">@csrf<input type="hidden" name="availability_status" value="AVAILABLE"><button class="z-btn">Estoy disponible</button></form><form method="POST" action="{{ route('tenant.driver.availability') }}">@csrf<input type="hidden" name="availability_status" value="UNAVAILABLE"><button class="z-btn z-btn--outline">Pausar jornada</button></form></div></section>
<section class="z-card" aria-labelledby="tenant-context"><div class="z-eyebrow" id="tenant-context">Operando para</div><div class="driver-tenant">@if($tenant->branding?->logo_path)<img class="driver-tenant__logo" src="{{ Storage::disk('public')->url($tenant->branding->logo_path) }}" alt="Logo de {{ $tenant->branding?->brand_name??$tenant->name }}">@else<span class="driver-tenant__logo" aria-hidden="true">{{ mb_strtoupper(mb_substr($tenant->branding?->brand_name??$tenant->name,0,1)) }}</span>@endif<div><strong>{{ $tenant->branding?->brand_name??$tenant->name }}</strong><div class="z-muted">Contexto operacional del tenant</div></div></div></section>
<section id="ganancias" aria-labelledby="today-title"><div class="z-page-header"><div><div class="z-eyebrow">Resumen</div><h2 id="today-title">Métricas del día</h2></div></div><span class="z-sr-only">Entregadas: <strong>{{ $delivered }}</strong> Ganancias generadas: <strong>{{ number_format((float)$earnings,2) }} {{ $policy?->currency ?? 'MXN' }}</strong> Pendientes de liquidación: <strong>{{ number_format((float)$earnings,2) }} {{ $policy?->currency ?? 'MXN' }}</strong></span><div class="z-grid"><article class="z-card z-metric"><small>Entregadas</small><strong>{{ $delivered }}</strong></article><article class="z-card z-metric"><small>Ganancias generadas</small><strong>{{ number_format((float)$earnings,2) }} <small>{{ $policy?->currency ?? 'MXN' }}</small></strong></article><article class="z-card z-metric"><small>Pendiente de liquidación</small><strong>{{ number_format((float)$earnings,2) }} <small>{{ $policy?->currency ?? 'MXN' }}</small></strong></article></div>@if($policy)<p class="z-muted">Esquema: {{ $policy->compensation_type }} · {{ $policy->settlement_frequency }}@if($policy->amount_per_delivery !== null) · {{ number_format((float)$policy->amount_per_delivery,2) }} {{ $policy->currency }} por entrega @endif</p>@endif</section>
<section id="entregas" aria-labelledby="deliveries-title"><div class="z-page-header"><div><div class="z-eyebrow">Operación</div><h2 id="deliveries-title">Próximas entregas</h2></div></div>
@forelse($assignments as $assignment)@php($shipment=$assignment->shipment)<a class="z-card z-card--interactive driver-delivery z-stack" href="{{ route('tenant.driver.shipments.show',$shipment->uuid) }}"><div class="driver-status-line"><span class="z-badge">{{ str_replace('_',' ',$shipment->status) }}</span><span aria-hidden="true">→</span></div><div><strong>{{ $tenant->branding?->brand_name??$tenant->name }}</strong><div class="driver-delivery__tracking">{{ $shipment->tracking_number }}</div></div><div><span class="z-muted">Destino permitido</span><br><strong>CP {{ $shipment->recipient_snapshot['postal_code']??'—' }}</strong></div><div class="z-cluster"><span class="future-value">Distancia: Próximamente</span><span class="future-value">ETA: Próximamente</span></div></a>@empty<div class="z-empty"><div class="z-empty__icon" aria-hidden="true">✓</div><h3>Sin entregas activas</h3><p class="z-muted">Cuando recibas una asignación aparecerá aquí.</p></div>@endforelse</section>
<section class="z-card"><h2>Entregas completadas</h2>@forelse($completedDeliveries as $completed)@php($completedEarning=$completedEarnings->get($completed->local_shipment_id))<p><code>{{ $completed->shipment->tracking_number }}</code> · {{ str_replace('_',' ',$completed->shipment->status) }}@if($completedEarning) · {{ number_format((float)$completedEarning->amount,2) }} {{ $completedEarning->currency }}@endif</p>@empty<p class="z-muted">Aún no hay entregas completadas.</p>@endforelse</section>
<section class="z-card driver-support"><div class="z-eyebrow">Ayuda / soporte</div><h2>¿Necesitas ayuda?</h2><p><strong>Soporte operativo</strong><br><span class="z-muted">Dirección, destinatario, paquete o vehículo: corresponde a {{ $tenant->branding?->brand_name??$tenant->name }}.</span></p><p><strong>Soporte de plataforma</strong><br><span class="z-muted">Problemas con la aplicación o acceso: corresponde a ZIGO.</span></p><span class="z-badge z-badge--muted">Canales disponibles próximamente</span></section>
@endsection
