@extends('tenant.driver.layout')
@section('title','Entrega fallida')
@section('content')
@php($shipment=$assignment->shipment)
<div class="z-eyebrow">Intento {{ $attemptNumber }} de {{ $requirement->max_delivery_attempts }}</div><h1>No pude entregar</h1><p><code>{{ $shipment->tracking_number }}</code></p><h2>¿Qué ocurrió?</h2><p><strong>Intento actual: {{ $attemptNumber }} de {{ $requirement->max_delivery_attempts }}</strong></p>
@if($errors->any())<div class="validation-summary" role="alert"><strong>No fue posible registrar el intento.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="card failure-form" id="failure-form" method="POST" enctype="multipart/form-data" novalidate action="{{ route('driver.shipments.failure.store',$shipment->uuid) }}">@csrf
<label>Razón<select name="reason" id="reason" required><option value="">Seleccionar razón</option>@foreach(\App\Domain\Shipping\LastMile\Models\LocalDeliveryFailedAttempt::REASONS as $reason)<option value="{{ $reason }}" @selected(old('reason') === $reason)>{{ \App\Domain\Shipping\LastMile\Models\LocalDeliveryFailedAttempt::REASON_LABELS[$reason] }}</option>@endforeach</select>@error('reason')<span class="field-error">{{ $message }}</span>@enderror</label>
<label>Notas<textarea name="notes" maxlength="500">{{ old('notes') }}</textarea>@error('notes')<span class="field-error">{{ $message }}</span>@enderror</label>
<label>Foto opcional<input type="file" name="photo" id="photo" accept="image/jpeg,image/png,image/webp" capture="environment"><span id="photo-status">Sin fotografía seleccionada.</span>@error('photo')<span class="field-error">{{ $message }}</span>@enderror</label>
<input type="hidden" name="latitude" id="latitude" value="{{ old('latitude') }}"><input type="hidden" name="longitude" id="longitude" value="{{ old('longitude') }}"><input type="hidden" name="accuracy_meters" id="accuracy" value="{{ old('accuracy_meters') }}">
<p id="location-status" role="status">Ubicación no capturada.</p>@error('latitude')<span class="field-error">{{ $message }}</span>@enderror @error('longitude')<span class="field-error">{{ $message }}</span>@enderror @error('accuracy_meters')<span class="field-error">{{ $message }}</span>@enderror
<button type="button" id="capture-location">Adjuntar ubicación</button><p id="client-errors" class="field-error" role="alert"></p><button class="btn" id="submit-failure">REGISTRAR INTENTO</button></form>
<style>.failure-form{display:grid;gap:14px}.failure-form label{display:grid;gap:6px}.failure-form input,.failure-form select,.failure-form textarea{padding:12px;font-size:16px}.validation-summary,.field-error{color:#991b1b}.validation-summary{background:#fef2f2;border:1px solid #fecaca;border-radius:10px;padding:12px}button[disabled]{cursor:wait;opacity:.7}</style>
<script>(()=>{const form=document.getElementById('failure-form'),status=document.getElementById('location-status'),photo=document.getElementById('photo'),submit=document.getElementById('submit-failure'),latitude=document.getElementById('latitude'),longitude=document.getElementById('longitude'),accuracy=document.getElementById('accuracy');let submitting=false;photo.addEventListener('change',()=>document.getElementById('photo-status').textContent=photo.files.length?'Fotografía lista: '+photo.files[0].name:'Sin fotografía seleccionada.');document.getElementById('capture-location').addEventListener('click',()=>{if(!window.isSecureContext){status.textContent='La ubicación GPS requiere un contexto seguro (HTTPS) o un origen local permitido por el navegador.';return}if(!navigator.geolocation){status.textContent='La ubicación GPS no está disponible en este navegador.';return}status.textContent='Capturando ubicación...';navigator.geolocation.getCurrentPosition(p=>{latitude.value=p.coords.latitude;longitude.value=p.coords.longitude;accuracy.value=p.coords.accuracy;status.textContent='Ubicación capturada (precisión aproximada: ±'+Math.round(p.coords.accuracy)+' m).'},e=>{status.textContent=({1:'Permiso de ubicación denegado.',2:'No fue posible determinar la ubicación GPS.',3:'La captura de ubicación agotó el tiempo de espera. Intenta nuevamente.'})[e.code]||'No fue posible capturar la ubicación GPS.'},{enableHighAccuracy:true,timeout:15000,maximumAge:0})});if(latitude.value&&longitude.value&&accuracy.value)status.textContent='Ubicación capturada (precisión aproximada: ±'+Math.round(Number(accuracy.value))+' m).';form.addEventListener('submit',e=>{if(submitting){e.preventDefault();return}if(!document.getElementById('reason').value){e.preventDefault();document.getElementById('client-errors').textContent='Selecciona la razón del intento fallido.';return}submitting=true;submit.disabled=true;submit.textContent='Registrando intento...'})})();</script>
@endsection
