@extends('tenant.driver.layout')
@section('title','Entrega')
@section('content')
@php($shipment=$assignment->shipment)
@php($pickup=in_array($shipment->status,['READY_FOR_PICKUP'],true))
@php($navigationAddress=$pickup?($shipment->sender_snapshot['address']??null):($shipment->recipient_snapshot['address']??null))
@php($proof=$shipment->deliveryRequirement ?? null)
<nav aria-label="Ruta" class="z-breadcrumbs"><a href="{{ route('tenant.driver.dashboard') }}">Entregas</a><span aria-hidden="true">/</span><span aria-current="page">{{ $shipment->tracking_number }}</span></nav>
<section class="z-page-header"><div><span class="z-badge">{{ str_replace('_',' ',$shipment->status) }}</span><h1>Entrega actual</h1><div class="driver-delivery__tracking">{{ $shipment->tracking_number }}</div></div><div><div class="z-eyebrow">Operando para</div><strong>{{ $tenant->branding?->brand_name??$tenant->name }}</strong></div></section>
<section class="z-card driver-delivery z-stack"><dl class="driver-detail"><div><dt>{{ $pickup ? 'Recolección' : 'Destino' }}</dt><dd>{{ $navigationAddress ?: 'Dirección no disponible' }}</dd></div><div><dt>Persona destinataria</dt><dd>{{ $shipment->recipient_snapshot['name']??'—' }}</dd></div><div><dt>Referencia operativa</dt><dd>{{ $shipment->guide_snapshot['reference']??'Sin referencia' }}</dd></div><div><dt>Distancia</dt><dd class="future-value">Disponible próximamente</dd></div><div><dt>ETA</dt><dd class="future-value">Disponible próximamente</dd></div></dl><div><div class="z-eyebrow">Requisitos POD</div><div class="z-cluster">@if($proof?->require_signature)<span class="z-badge">Firma requerida</span>@endif @if($proof?->require_photo)<span class="z-badge">Fotografía requerida</span>@endif @if($proof?->require_gps)<span class="z-badge">GPS requerido</span>@endif @unless($proof?->require_signature||$proof?->require_photo||$proof?->require_gps)<span class="z-muted">Consulta los requisitos al confirmar la entrega.</span>@endunless</div></div></section>
@if($navigationAddress)<section class="z-card z-stack"><div><div class="z-eyebrow">Navegación</div><h2>{{ $pickup ? 'IR POR EL PAQUETE' : 'IR A ENTREGA' }}</h2><p class="z-muted">Elige tu aplicación de mapas. ZIGO no realiza rastreo continuo.</p></div><div class="driver-actions"><a class="z-btn" rel="noopener noreferrer" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination={{ rawurlencode($navigationAddress) }}">Abrir Google Maps</a><div class="z-cluster"><a class="z-btn z-btn--outline" rel="noopener noreferrer" target="_blank" href="https://waze.com/ul?q={{ rawurlencode($navigationAddress) }}&navigate=yes">Waze</a><a class="z-btn z-btn--outline" rel="noopener noreferrer" target="_blank" href="https://maps.apple.com/?daddr={{ rawurlencode($navigationAddress) }}">Apple Maps</a></div></div></section>@endif
@php($next=['READY_FOR_PICKUP'=>['PICKED_UP'=>'Paquete recolectado'],'PICKED_UP'=>['IN_TRANSIT'=>'Iniciar traslado'],'IN_TRANSIT'=>['OUT_FOR_DELIVERY'=>'Salir a entrega']][$shipment->status]??[])
<section class="driver-actions" aria-label="Acciones de entrega">@foreach($next as $status=>$label)<form method="POST" action="{{ route('tenant.driver.shipments.transition',$shipment->uuid) }}">@csrf<input type="hidden" name="status" value="{{ $status }}"><button class="z-btn z-btn--block">{{ $label }}</button></form>@endforeach
@if($shipment->status==='DELIVERY_FAILED')@if($attemptsRemaining>0)<form method="POST" action="{{ route('tenant.driver.shipments.transition',$shipment->uuid) }}">@csrf<input type="hidden" name="status" value="OUT_FOR_DELIVERY"><button class="z-btn z-btn--block">Iniciar siguiente intento</button></form>@else<div class="z-alert z-alert--danger" role="alert">Límite de intentos alcanzado. La resolución corresponde al Tenant Admin.</div>@endif @endif
@if($shipment->status==='OUT_FOR_DELIVERY')<a class="z-btn z-btn--block" href="{{ route('tenant.driver.shipments.proof',$shipment->uuid) }}">Confirmar entrega</a><a class="z-btn z-btn--outline z-btn--block" href="{{ route('tenant.driver.shipments.failure',$shipment->uuid) }}">Reportar problema</a>@endif</section>
<section class="z-card driver-support"><h2>Ayuda con esta entrega</h2><p class="z-muted">Dirección, destinatario, paquete, vehículo, aplicación u otro. El soporte operativo corresponde a {{ $tenant->branding?->brand_name??$tenant->name }}; el de plataforma, a ZIGO.</p><p class="z-muted"><strong>Contacto futuro:</strong> llamar o enviar mensaje al destinatario sólo durante una asignación activa. Después de completar, sus datos permanecen inaccesibles.</p></section>
@endsection
