@extends('tenant.driver.layout')
@section('title','Entrega')
@section('content')
@php($shipment=$assignment->shipment)
@php($navigation=\App\Support\Presentation\DriverAddressPresenter::forShipment($shipment))
@php($pickup=$navigation['pickup'])
@php($navigationAddress=$navigation['full'])
@php($senderAddress=\App\Support\Presentation\DriverAddressPresenter::fromSnapshot($shipment->sender_snapshot??[])['full'])
@php($proof=$shipment->deliveryRequirement??null)
@php($statusLabels=['READY_FOR_PICKUP'=>'Listo para recolectar','PICKED_UP'=>'Recolectado','IN_TRANSIT'=>'En tránsito','OUT_FOR_DELIVERY'=>'En reparto','DELIVERY_FAILED'=>'Intento fallido'])
<nav aria-label="Ruta" class="z-breadcrumbs"><a href="{{ route('driver.deliveries') }}">Entregas</a><span aria-hidden="true">/</span><span aria-current="page">{{ $shipment->tracking_number }}</span></nav>
<header class="z-page-header"><div><span class="z-badge">{{ $statusLabels[$shipment->status]??str_replace('_',' ',$shipment->status) }}</span><h1>Entrega actual</h1><div class="driver-delivery__tracking">{{ $shipment->tracking_number }}</div></div><div><div class="z-eyebrow">Operando para</div><strong>{{ $tenant->branding?->brand_name??$tenant->name }}</strong></div></header>
<section class="z-card driver-delivery"><h2>{{ $pickup?'Recolección':'Destino' }}</h2><p><strong>{{ $navigationAddress?:'Dirección no disponible' }}</strong></p><p>{{ $navigation['settlement']?:'—' }} · CP {{ $navigation['postal_code']?:'—' }}<br>{{ implode(', ',array_filter([$navigation['municipality'],$navigation['state']])) }}</p>
<p>{{ $pickup?($shipment->sender_snapshot['name']??'Persona remitente'):($shipment->recipient_snapshot['name']??'Persona destinataria') }}</p>
@if(!empty($shipment->guide_snapshot['reference']))<p class="z-muted">Referencia: {{ $shipment->guide_snapshot['reference'] }}</p>@endif</section>
@if($pickup)<section class="z-card"><h2>Remitente</h2><p><strong>{{ $shipment->sender_snapshot['name']??'—' }}</strong><br>{{ $senderAddress }}</p></section>@endif
<section class="z-grid"><article class="z-card"><div class="z-eyebrow">Paquete</div><h2>{{ $shipment->package_snapshot['type']??'Paquete' }}</h2><p class="z-muted">{{ $shipment->package_snapshot['weight']??'—' }} kg</p></article><article class="z-card"><div class="z-eyebrow">Instrucciones</div><p>{{ $shipment->recipient_snapshot['instructions']??$shipment->guide_snapshot['instructions']??'Sin instrucciones adicionales.' }}</p></article></section>
<section class="z-card"><div class="z-eyebrow">Requisitos de esta entrega</div><h2>Prueba de entrega</h2><div class="z-cluster">@if($proof?->require_receiver_name)<span class="z-badge">Nombre receptor</span>@endif @if($proof?->require_receiver_type)<span class="z-badge">Tipo receptor</span>@endif @if($proof?->require_signature)<span class="z-badge">Firma requerida</span>@endif @if($proof?->require_photo)<span class="z-badge">Foto requerida</span>@endif @if($proof?->require_gps)<span class="z-badge">GPS requerido</span>@endif @unless($proof)<span class="z-muted">Los requisitos se mostrarán al confirmar.</span>@endunless</div></section>
@if($navigationAddress)<details class="z-card"><summary class="z-btn z-btn--block">INICIAR NAVEGACIÓN</summary><div class="z-stack" style="margin-top:1rem"><h2>{{ $pickup?'IR POR EL PAQUETE':'IR A ENTREGA' }}</h2><a class="z-btn z-btn--outline" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/dir/?api=1&destination={{ rawurlencode($navigationAddress) }}">Google Maps</a><a class="z-btn z-btn--outline" target="_blank" rel="noopener noreferrer" href="https://waze.com/ul?q={{ rawurlencode($navigationAddress) }}&navigate=yes">Waze</a><a class="z-btn z-btn--outline" target="_blank" rel="noopener noreferrer" href="https://maps.apple.com/?daddr={{ rawurlencode($navigationAddress) }}">Apple Maps</a></div></details>@endif
@php($phone=$shipment->recipient_snapshot['phone']??null)
@if($phone&&in_array($shipment->status,['PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY'],true))<section class="z-card"><div class="z-eyebrow">Contacto durante asignación activa</div><h2>Destinatario</h2><a class="z-btn z-btn--outline z-btn--block" href="tel:{{ preg_replace('/[^+0-9]/','',$phone) }}">Llamar al destinatario</a><p class="z-help">El número no se muestra y dejará de estar disponible al completar la entrega. Number masking: Future.</p></section>@endif
@php($next=['READY_FOR_PICKUP'=>['PICKED_UP'=>'Paquete recolectado'],'PICKED_UP'=>['IN_TRANSIT'=>'Iniciar traslado'],'IN_TRANSIT'=>['OUT_FOR_DELIVERY'=>'Salir a entrega']][$shipment->status]??[])
<section class="driver-actions" aria-label="Acciones de entrega">@foreach($next as $status=>$label)<form method="POST" action="{{ route('driver.shipments.transition',$shipment->uuid) }}">@csrf<input type="hidden" name="status" value="{{ $status }}"><button class="z-btn z-btn--block">{{ $label }}</button></form>@endforeach
@if($shipment->status==='DELIVERY_FAILED')@if($attemptsRemaining>0)<form method="POST" action="{{ route('driver.shipments.transition',$shipment->uuid) }}">@csrf<input type="hidden" name="status" value="OUT_FOR_DELIVERY"><button class="z-btn z-btn--block">Iniciar siguiente intento</button></form>@else<div class="z-alert z-alert--danger" role="alert">Límite de intentos alcanzado. La resolución corresponde al Tenant Admin.</div>@endif @endif
@if($shipment->status==='OUT_FOR_DELIVERY')<a class="z-btn z-btn--block" href="{{ route('driver.shipments.proof',$shipment->uuid) }}">Confirmar entrega</a><a class="z-btn z-btn--outline z-btn--block" href="{{ route('driver.shipments.failure',$shipment->uuid) }}">No pude entregar</a>@endif</section>
<section class="z-card driver-support"><h2>Ayuda con esta entrega</h2><p class="z-muted">El soporte operativo corresponde a {{ $tenant->branding?->brand_name??$tenant->name }}; los errores de plataforma corresponden a ZIGO.</p><a href="{{ route('driver.support') }}">Ir a Ayuda y soporte →</a></section>
@endsection
